### ISSUE TITLE
Introducción al sistema POLUX

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#104]
Asimilar el funcionamiento general del sistema así como de su flujo y actividades necesarias por desarrollar, de acuerdo a las siguientes actividades:
 
- [x] Revisión e instalación de repositorios (Crud, Mid y Cliente).
- [x] Revisión de documentación.
- [x] Análisis de requerimientos.

Criterios de aceptación

1. Registrar el estado actual en el que se recibe el sistema (Formato propio).
2. Registrar inquietudes respecto a los requerimientos analizados.

**Comment by mantnicot** [comment]
Se hizo la descargar de los repositorios de :
POLUX_MID : https://github.com/udistrital/polux_mid
POLUX_CLIENTE : https://github.com/udistrital/polux_cliente
POLUX_CRUD : https://github.com/udistrital/polux_crud
Se descargaron por medio del comando 

"git clone" 

Con ayuda de Juan Camilo se intento realizar la prueba de funcionamiento , pero se denotaron varios errores generados por no haber realizado el 

"Go get"


Después de se noto que no corría a lo cual se corrió con las variables de entorno especificas : 

crud variables del CRUD
AWS_DEFAULT_REGION=us-east-1 POLUX_CRUD__DB_USER=desarrollooas POLUX_CRUD__DB_PASS=W7Sz1lbWFwfE798b PARAMETER_STORE=preprod POLUX_CRUD__DB_NAME=udistrital_core_db POLUX_CRUD__DB_SCHEMA=academica POLUX_CRUD__DB_URL=pgtst.udistritaloas.edu.co POLUX_CRUD__HTTP_PORT=8001 bee run
Mid variables mid
AWS_DEFAULT_REGION=us-east-1 PARAMETER_STORE=preprod POLUX_MID__POLUX_CRUD_NS=/v1 POLUX_MID__POLUX_CRUD_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8108 POLUX_MID__RULER_NS=/v1 POLUX_MID__RULER_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8080/v1/ POLUX_MID_LOG_PATH=/home/developer/go/log/beego/poluxMid.log POLUX_MID__HTTP_PORT=8002 bee run

![Captura de pantalla de 2021-07-22 18-25-52](https://user-images.githubusercontent.com/85162258/126721028-01a855dc-de48-4dac-adbb-34ba4241918f.png)

![Captura de pantalla de 2021-07-22 18-26-50](https://user-images.githubusercontent.com/85162258/126721113-6e057cd1-0eb9-4a87-84c6-3bbe02e4e924.png)


y se ejecuto el mid y crud. Pero corren bien pero al no tener la vpn , no se puede acceder a la información de la universidad y por ende el funcionamiento esta limitado a local.

**Comment by mantnicot** [comment]
Después se intento probar el cliente , pero se siguió lo lineamientos y documentación expuestos en una api parecida para que instale las dependencias.


https://github.com/udistrital/cumplidos_cliente/blob/develop/README.md


Se realizo la instalacion normal de las dependencias y se corrio de manera efectiva


![Captura de pantalla de 2021-07-22 18-36-32](https://user-images.githubusercontent.com/85162258/126721903-b437026c-9d79-4134-8aed-485e22e3f522.png)


Pero los usuarios que fueron entregados en el drive , no funcionarion pues no muestra un menu  


![Captura de pantalla de 2021-07-22 18-42-37](https://user-images.githubusercontent.com/85162258/126722166-4290339b-546e-49ba-b799-0481d72b7f8c.png)



Se solicitara un nuevo grupo de usuarios para realizar las pruebas correspondientes y flujo del programa

**Comment by mantnicot** [comment]
Se estudio toda la documentación dada para el conocimiento y estado de Polux 
![Captura de pantalla de 2021-07-23 21-02-44](https://user-images.githubusercontent.com/85162258/126854478-a7d12aef-a2a3-4925-a378-54d573dfecd1.png)


Se noto varias preguntas y dudas , las cuales fueron colocadas en el documento anexo, el cual esta documentado los resúmenes de los documentos y archivos recibidos


https://1drv.ms/w/s!AkQEWBEvYVTDhV3YehKd4_elXF4h?e=S3Bpes


Para observar las dudas se dejaron los comentarios al costado derecho del documento.


![Captura de pantalla de 2021-07-23 21-06-58](https://user-images.githubusercontent.com/85162258/126854551-6786399c-f649-440a-8e29-f74dbb5a3e2d.png)

**Comment by a52290451** [comment]
Se debe realizar el análisis de los requerimientos solicitados para la optimización de POLUX. Las dudas he inquietudes serán resueltas posteriormente.

**Comment by mantnicot** [comment]
Se charlo con Jhon sobre el requerimiento de usuarios, recomendo volver a probarlos con el siguiente archivo entregado en la documentación  de POLUX_UD

https://drive.google.com/file/d/1ESCHxn4t0WaSe0tRYYOe0idgWSida8MF/view?ts=60febc0b

Se puso evidencia en el documento que usuarios funcionan y cuales no.

No funciono ninguno para las pruebas pues estos no presentan menu de inicio.

**Comment by mantnicot** [comment]
Se actualizo el documento de usuarios para mejor interpretación del mismo y se dejo una nota para aquellos usuarios que no tienen el usuario escrito.


https://docs.google.com/document/d/1ESCHxn4t0WaSe0tRYYOe0idgWSida8MF/edit


Se hablo con el arquitecto Jhon para posible solución y se cree que es por configuracion_crud, la cual es configuracion_api (antes no se diferenciaban entre mid y crud), puede ser que no se encuentre en despliegue:

https://github.com/udistrital/configuracion_api


Se hablara el día 28 de Julio de 2021 para la solución y de pronto depuración para poder ingresar al flujo del proyecto POLUX

**Comment by mantnicot** [comment]
El arquitecto Jhon soluciono el problema de menus de los usuarios, por lo cual ya se puede ingresar a probar el aplicativo
se observo un inconveniente el cual se informo con Jhon 

![Captura de pantalla de 2021-07-28 11-20-48](https://user-images.githubusercontent.com/85162258/127360838-8c1270a2-3103-4ea1-a55d-daf14e0d7f02.png)

Para una mejor descripción del problema, se detallo en el documento de Usuarios

https://docs.google.com/document/d/1ESCHxn4t0WaSe0tRYYOe0idgWSida8MF/edit

**Comment by mantnicot** [comment]
Se obtuvo la VPN correctamente, pero al tener UBUNTU 20.04, se noto que la configuracion de instalación de VPNC no estaba explicita, se pidio ayuda a Juan Camilo el cual brindo una forma de instalacion diferente :+1: 

https://zoomadmin.com/HowToInstall/UbuntuPackage/vpnc

Pero aun así no se mostraba la conexión de CISCO 

Se utilizo el siguiente comando para poder solucionarlo

sudo apt-get install -y network-manager-vpnc-gnome

Lo cual permitio la configuración completa 

![Captura de pantalla de 2021-08-02 15-23-37](https://user-images.githubusercontent.com/85162258/127919190-0ec850cc-137e-48b7-b46f-55d9a04bcf0e.png)


Pero despues hubo un inconveniente con respecto a comenzar el uso de la VPN , una vez que se intenta encender la VPN, aparece el siguiente error 


![Captura de pantalla de 2021-08-02 15-24-33](https://user-images.githubusercontent.com/85162258/127919313-c6581abb-9bfe-4536-859c-450630d8a1b6.png)


Se esta buscando una solucion, para poder solucionar el fallo

**Comment by mantnicot** [comment]
Se intento solucionar por medio de routter , de fallo en el puerto 1134 


Gracias a la info suministrada por Juan Camilo en el siguiente [enlace](https://drive.google.com/drive/folders/1eCH-wknIWfNJoNW1u50pdSij6StwU3dX?usp=sharing) se determino que era por un problema de gestion de constraseñas

Si se intenta crear la conexión con todas las credenciales directas como la siguiente imagen:

![Captura de pantalla de 2021-08-02 15-23-37](https://user-images.githubusercontent.com/85162258/127939341-f31b7f24-71df-48ee-80be-11a43a28ba87.png)

No se asegura la conexión, pero si se genera la conexión sin contraseñas :

![Captura de pantalla de 2021-08-02 19-26-50](https://user-images.githubusercontent.com/85162258/127939399-0d375de4-ec05-4246-aee3-e85695876fe2.png)

y despues se conecta, y se diligencia las contraseñas, funciona así como la conexión a la BD.

![Captura de pantalla de 2021-08-02 19-21-50](https://user-images.githubusercontent.com/85162258/127939080-e58db9de-4dbe-4de4-9523-979d0f57ea37.png)
