### ISSUE TITLE
Propuesta del plan de trabajo

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#105]
Proponer el plan de trabajo para cubrir los requerimientos de optimización solicitados.

**Nota**:
Se debe tomar en consideración la validación del estado actual del sistema y el análisis de requerimientos realizado en [Introducción al sistema POLUX](https://github.com/udistrital/polux_cliente/issues/104).

De igual forma, se debe asignar prioridad y un estimado de tiempo a cada item.

**Criterios de aceptación**

- [x] Documento con la propuesta de trabajo realizada (Formato del documento libre).

**Comment by mantnicot** [comment]
Los requerimientos expuestos en el contrato son los siguientes: 
1-) Optimizar el modulo de parametrización
2-)Agregar o mejorar las nuevas opciones de grado.
3-) Mejorar e integrar el modelo de notificaciones
Los cuales manejaran las siguientes actividades si estas lo necesitan:
a-) Diseñar y desarrollar los componentes de desarrollo (menús, funcionalidades, motor de reglas, servicios, servicios interoperables, etc, que apliquen) 
b-) Diseñar y/o ajustar el modelo de datos 
c-) Desarrollar y/o ajustar la interfaz de usuario 
d-) Realizar las pruebas unitarias 
e-) Validar con el usuario y ajustar las funcionalidades desarrolladas 
f-)  Realizar el despliegue y puesta en producción 
g-) Realizar la entrega y capacitación al usuario, junto con el gerente de proyecto y el líder técnico. 



Conociendo la documentación del sistema sin todavía poder comprobar el funcionamiento por inconvenientes con nuevos usuarios y la VPN. 
Se desarrollaría un plan de trabajo de la siguiente manera: 
No sé como realizar correctamente un plan de trabajo por lo cual adjunto el plan entregado a Diana

[PLAN DE TRABAJO (4)-convertido-firmado (1).pdf](https://github.com/udistrital/polux_cliente/files/6875010/PLAN.DE.TRABAJO.4.-convertido-firmado.1.pdf)

**Comment by a52290451** [comment]
Se proporciona un ISSUE con la [Propuesta de plan de trabajo](https://github.com/udistrital/lineamientos_oas/issues/34) establecida en CORE, como ejemplo para el desarrollo de esta en POLUX.

Se deben describir las actividades específicas para cumplir con cada requerimientos.

**Comment by mantnicot** [comment]
Se debe realizar una reunión para entendimiento en los requerimientos 

Se entiende que los requerimientos están basados en las siguientes actividades a optimizar 
1-) Optimizar el modulo de parametrización
2-)Agregar o mejorar las nuevas opciones de grado.
3-) Mejorar e integrar el modelo de notificaciones

Se tienen la siguientes dudas para resolverlas:


1-) ¿El modulo parametrizacion, hace referencia a el modelo de la base datos expuesto en el archivo https://docs.google.com/spreadsheets/d/1459lPyWxGc4kC2txrbbcdd8AyTN5rso9QNAhfYP5x_E/edit#gid=568063444, si es el caso, generar parametros para que tablas en especifico?
En caso de no, pedir explicacion más a fondo del modulo de parametrizacion.
2-) ¿Cuales son las nuevas modalidades de grado o cuales fueron las ultimas agregadas?
3-) ¿el modelo de cada nueva modalidad debe estar trabajado de igual manera que las anteriores? 
4-) El modulo de reportes y notificaciones , no tengo claro el requerimiento en general 
La unica informacion que tengo presente de notificaciones es la encontrada en 
https://docs.google.com/spreadsheets/d/1ezTNHNJTAgDxOvrqa-437sU8BNHw_g7Y-Kp_qIWKqfE/edit#gid=85110063
y con respecto a reportes se tiene el siguiente documento explicando al final del mismo que no se pudo completar pruebas por la falta de ajustes al sistemas 
https://docs.google.com/document/d/1NnorSPKAtYO9WbD3qS-E4NH0oub0KMxCgd-jTdYYRqA/edit

**Comment by mantnicot** [comment]
El día 28 de Julio de 2021 se hará la reunión para la solución de dudas sobre los requerimientos a entregar

Se creo un formato de PDF para el plan y poder planificar correctamente el plan de trabajo 

[Plan de trabajo ( plantilla ).pdf](https://github.com/udistrital/polux_cliente/files/6889353/Plan.de.trabajo.plantilla.pdf)

Preguntar a realizar al Arquitecto Jhon apartes de las anteriores comentadas en el issue

1-) ¿El modulo de reportes tiene que ver con estos issues https://github.com/udistrital/polux_cliente/issues/73 https://github.com/udistrital/polux_cliente/issues/93 ?

**Comment by mantnicot** [comment]
Se adjunta el plan de trabajo 

[Plan de trabajo ( plantilla ) (1).pdf](https://github.com/udistrital/polux_cliente/files/6896047/Plan.de.trabajo.plantilla.1.pdf)

**Comment by a52290451** [comment]
Plan de trabajo completo.
