### ISSUE TITLE
Creación de Mock-Ups - Módulo de Parametrización

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#107]
Se debe realizar la creación de Mock-ups relacionados con "Optimizar el módulo de parametrización".

**Se debe tener en cuenta**

- Paleta de colores utilizada en POLUX.
- Simulación del flujo de trabajo.
- Otros escenarios en los que se pueden o deben ajustar parámetros.

**Criterios de aceptación**

- [x] Registro de Mock-ups (acorde a los formatos/lineamientos de la OAS) a ser presentado en Mesas de Trabajo con clientes/usuarios, cuya firma de aprobación dará inicio al desarrollo.

**Material de apoyo**

- Se adjunta [link de ISSUE](https://github.com/udistrital/cumplidos_cliente/issues/111) en donde se evidencia el desarrollo de Mock-Ups.
- Se adjunta [link de documento](https://drive.google.com/file/d/1GcWY713ua78gfv8asqnNMETTD9TGFpM2/view?usp=sharing) para utilizarlo como guía en la presentación de Mock-Ups.

**Comment by mantnicot** [comment]
Se creo la primera versión de mockups
Se adjunta el siguiente [LINK](https://app.moqups.com/Z9BKAVEmRi/view/page/aa33141ef) para observación rápido

También se adjunta el siguiente documento , para observar el paso a paso del flujo de Actualizar y Eliminar

[Mockups.pdf](https://github.com/udistrital/polux_cliente/files/6910165/Mockups.pdf)


Se genero una duda al proceso de hacerlo y es:

¿Es posible crear una vista dinámica para poder ingresar cualquier valor a unas tablas ya creadas?

**Comment by a52290451** [comment]
Para cierre del issue, falta la validación de mock-ups por parte del usuario. Se espera agendar reunión prontamente.

**Comment by a52290451** [comment]
Se acuerda reunión con el cliente para validación de mock-ups para el día 18 de Agosto del 2021.

**Comment by mantnicot** [comment]
Se adjunta la segunda versión de los mockups aprobados por el cliente
Se adjunta el [LINK](https://app.moqups.com/Z9BKAVEmRi/view/page/aa33141ef) para tu edición y observación



[Mockups final versión.pdf](https://github.com/udistrital/polux_cliente/files/7017198/Mockups.final.version.pdf)

**Comment by a52290451** [comment]
Pendiente a validación por el usuario. Iniciar con el desarrollo de igual forma.
