### ISSUE TITLE
Desarrollo de la interfaz en el cliente

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#109]
Desarrollar la interfaz grafica necesaria para la interacción del usuario, conforme a lo dispuesto en el [Estudio del módulo de parametrización](https://github.com/udistrital/polux_cliente/issues/108) y lo acordado en reuniones con el cliente.

**Criterio de aceptación**

- [x] Creación de rama Feature de desarrollo en polux_cliente.

**Nota**: tomar como referencia los [Mock-Ups diseñados](https://github.com/udistrital/polux_cliente/issues/107) posterior a su aprobación.

**Comment by mantnicot** [comment]
SE esta generando toda la interfaz en el cliente en cual se ve de la siguiente manera



![Captura de pantalla de 2021-08-23 21-30-29](https://user-images.githubusercontent.com/85162258/130546410-5524974a-53a4-4eac-a2be-0541fe43d2f4.png)
![Captura de pantalla de 2021-08-23 21-30-26](https://user-images.githubusercontent.com/85162258/130546412-102e1c62-a895-4ea3-9c49-17c21d673809.png)
![Captura de pantalla de 2021-08-23 21-30-24](https://user-images.githubusercontent.com/85162258/130546413-296fb3a5-cad9-42ca-bfb1-29ff5988d424.png)

**Comment by mantnicot** [comment]
Se realizo la subido de la rama /MolduloParametrizacion con el desarrollo terminado a la rama develop:

[Commit 1](https://github.com/udistrital/polux_cliente/commit/838c5f9932853f0f92cdfc501db350dc134637cc)

[Commit 2](https://github.com/udistrital/polux_cliente/commit/5c19a6047bb66847838e643d8941fec40861738f)

[Commit 3](https://github.com/udistrital/polux_cliente/commit/fc48ed999f3e07d580bfd785d9b724d83b91ff0e)

Se realizo la subida a la rama de release/0.0.1

[Commit 1](https://github.com/udistrital/polux_cliente/commit/838c5f9932853f0f92cdfc501db350dc134637cc)

[Commit 2](https://github.com/udistrital/polux_cliente/commit/5c19a6047bb66847838e643d8941fec40861738f)

[Commit 3](https://github.com/udistrital/polux_cliente/commit/fc48ed999f3e07d580bfd785d9b724d83b91ff0e)

[Commit 4](https://github.com/udistrital/polux_cliente/commit/49401b16ad9d4e6ba88b5f01b5f9289ea93f7d5c)


Se comienza el proceso de pruebas
