### ISSUE TITLE
Despliegue en producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#110]
Realizar la gestión necesaria para desplegar el módulo de parametrización en producción.

**Criterios de aceptación**

- [x] Polux_cliente.
- [x] Polux_mid.
- [x] Polux_crud

**Comment by mantnicot** [comment]
Se realizo los siguiente commits para agregar el modulo de parametrización y solucionar fallos con sistema de autenticacion de google 


Commits:

[commit a moduloparamerizacion ](https://github.com/udistrital/polux_cliente/commit/cd5bb8235b40efe5400b4154fbe322872428fe1c)

[commit a develop ](https://github.com/udistrital/polux_cliente/commit/bede8c2b2f4f4368b6508f08eafb81747f995de4)


[commit a release ](https://github.com/udistrital/polux_cliente/commit/7559ec32f381593a82dbbb561f001e0bdb280dae)


[commit a develop en solcuion a logs](https://github.com/udistrital/polux_cliente/commit/b39e075f0488444e05853e0102f2124ffe638c9b)

[commit a release todo limpio ](https://github.com/udistrital/polux_cliente/commit/a3f3387b2622da98fa23cb13755869e9fce87c10)

[**commit a master**](https://github.com/udistrital/polux_cliente/commit/0f5b8b6685d1ff96760f732d2167922e4316c7d3)
