### ISSUE TITLE
Despliegue en preproducción

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#111]
Realizar la gestión necesaria para desplegar el módulo de parametrización en Preproducción.

**Criterios de aceptación**

- [x] Polux_cliente.
- [x] Polux_mid.
- [x] Polux_crud.

**Comment by mantnicot** [comment]
Se paso el desarrollo del POLUX_CRUD , en los siguiente commit subidos a develop

[Commit 1](https://github.com/udistrital/polux_crud/commit/1088f10c8b8a689227be972375628f8dd74def17)


[Commit 2](https://github.com/udistrital/polux_crud/commit/32ffbb4251d76ada236d27ed71018d7feafac14d)



[Commit 3](https://github.com/udistrital/polux_crud/commit/21794039719e8222d77cafd01839674196f54712)




[Commit 4](https://github.com/udistrital/polux_crud/commit/c0df4a6934e0b4f837092054813a3f0befb05f41)



[Commit 5](https://github.com/udistrital/polux_crud/commit/f160046e9bcc1972d2352b3f160cd5cb92dc0e68)



[Commit 6](https://github.com/udistrital/polux_crud/commit/87bf800d8cf65ec0bd7e50dabe4a80a70d6d8919)



[Commit 7](https://github.com/udistrital/polux_crud/commit/87019742e51e5ee23ca3e4cb48bb4d27c00accf5)



[Commit 8](https://github.com/udistrital/polux_crud/commit/5be6f72d117278357349991bb47b778769cfc059)

Los siguiente commit para subirlos a la rama de release/0.0.1

[Commit 1](https://github.com/udistrital/polux_crud/commit/1088f10c8b8a689227be972375628f8dd74def17)

[Commit 2](https://github.com/udistrital/polux_crud/commit/32ffbb4251d76ada236d27ed71018d7feafac14d)

[Commit 3](https://github.com/udistrital/polux_crud/commit/21794039719e8222d77cafd01839674196f54712)

[Commit 4](https://github.com/udistrital/polux_crud/commit/c0df4a6934e0b4f837092054813a3f0befb05f41)

[Commit 5](https://github.com/udistrital/polux_crud/commit/f160046e9bcc1972d2352b3f160cd5cb92dc0e68)

[Commit 6](https://github.com/udistrital/polux_crud/commit/87bf800d8cf65ec0bd7e50dabe4a80a70d6d8919)

[Commit 7](https://github.com/udistrital/polux_crud/commit/fc9b00b9a48903820e90490b08548c8235d7815d)

[Commit 8](https://github.com/udistrital/polux_crud/commit/87019742e51e5ee23ca3e4cb48bb4d27c00accf5)

[Commit 9](https://github.com/udistrital/polux_crud/commit/5be6f72d117278357349991bb47b778769cfc059)

[Commit 10](https://github.com/udistrital/polux_crud/commit/e81c75a896391312f2be04b1a84832eef6d66402)



Se realizo la subido de la rama /MolduloParametrizacion de POLUX_CLIENTE con el desarrollo terminado a la rama develop:

[Commit 1](https://github.com/udistrital/polux_cliente/commit/838c5f9932853f0f92cdfc501db350dc134637cc)

[Commit 2](https://github.com/udistrital/polux_cliente/commit/5c19a6047bb66847838e643d8941fec40861738f)

[Commit 3](https://github.com/udistrital/polux_cliente/commit/fc48ed999f3e07d580bfd785d9b724d83b91ff0e)

Se realizo la subida a la rama de release/0.0.1

[Commit 1](https://github.com/udistrital/polux_cliente/commit/838c5f9932853f0f92cdfc501db350dc134637cc)

[Commit 2](https://github.com/udistrital/polux_cliente/commit/5c19a6047bb66847838e643d8941fec40861738f)

[Commit 3](https://github.com/udistrital/polux_cliente/commit/fc48ed999f3e07d580bfd785d9b724d83b91ff0e)

[Commit 4](https://github.com/udistrital/polux_cliente/commit/49401b16ad9d4e6ba88b5f01b5f9289ea93f7d5c)


Ya que no fue necesario el uso de POLUX_MID no se actualizo el repositorio

Se comienza el proceso de pruebas
