### ISSUE TITLE
Pruebas Funcionales y de Usabilidad

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#112]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la optimización del módulo de parametrización.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota**: utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit#gid=481118634) dispuesto para la aplicación de este tipo de pruebas.

**Comment by mantnicot** [comment]
Se realizo las pruebas del modulo de parametrizacion :

[Aplicación pruebas Funcionales y de Usabilidad Parametrizacion.xlsx](https://github.com/udistrital/polux_cliente/files/7096364/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.Parametrizacion.xlsx)


https://docs.google.com/spreadsheets/d/1tL_204ETIPnQV5294-lPKGWbaFYbaL_OOxZ2ZL1q52A/edit?usp=sharing

**Comment by a52290451** [comment]
Se adjunta documento validado.
[Pruebas funcionales y de usabilidad validadas](https://docs.google.com/spreadsheets/d/1KIAn82CGWrD_NhvjnklOOGcU4Kz8bybn/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true)
