### ISSUE TITLE
Despliegue del sistema en ambiente de producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#114]
Se debe realizar el despliegue del sistema en ambiente de producción tomando como referencia los siguientes ISSUES:

1. [Despliegue a producción](https://github.com/udistrital/polux_crud/issues/36).
2. [Despliegue del sistema en ambiente de pruebas](https://github.com/udistrital/polux_cliente/issues/84).

**Comment by mantnicot** [comment]
Se esta realizando todo el desarrollo de las pruebas expuestas en este documento :+1: 
https://docs.google.com/document/d/1AReYFB09zmQ-2lnwjEAolt-Rw-HBVpjqPI7pDw4yxLY/edit#heading=h.46ed997mxdgf

Se observo ciertos inconvenientes con respecto a la conexión de la BD por medio de la VPN, pues no se puede acceder a las tablas.

![Captura de pantalla de 2021-08-03 12-47-03](https://user-images.githubusercontent.com/85162258/128103026-61b53fb4-7a6d-4d20-8029-0c28490aeb75.png)

Los cuales eran generados por problemas de cache y con al localstorage 


![Captura de pantalla de 2021-08-03 19-47-19](https://user-images.githubusercontent.com/85162258/128104237-b73a316b-c604-4974-a0ca-66c4a7040ac6.png)


Las pruebas se estan realizando en dos documentos para evidencia y control :

Excel de evidencia rapido 

https://docs.google.com/spreadsheets/d/1umTmdZALyuhAc9eI6K9L89JIiI2BjqhzIh5w2Jw7Rg4/edit?usp=sharing

Documento de word con las evidencias, pantallazos y paso a paso

https://docs.google.com/document/d/1czPRbLxDy8TJrlZdBL_AAbKcdiG8gtnmoI6LhOupGNM/edit?usp=sharing



Nota: El programa tiene varios fallos, todos vinculados al sistema de auntenticación, por lo cual el programa no funciona correctamente.

Se adjunta un pantallazo de prueba

![Captura de pantalla de 2021-08-03 18-49-00](https://user-images.githubusercontent.com/85162258/128104911-75511456-4b1e-4e26-9361-60374a9706a8.png)


Se espera terminar el diagnostico de la pruebas y poder solucionar el problema para el despliegue.

**Comment by mantnicot** [comment]
Se comenzo a estudiar el problema de los endpoints con respecto a las pruebas

El endpoint de autenticación es el cual genera el conflicto de autenticación es:

https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v1/datos_estudiante/20121102097/2020/1

Se charlo con Brayan y se uso con v2 pero al intentar acceder al servicio, usamos postman : 

![Captura de pantalla de 2021-08-04 11-43-15](https://user-images.githubusercontent.com/85162258/128220791-6f3fccf4-9d28-4842-8d9c-60a55a1f6fd0.png)


Se muestra que el servicio esta abajo o se esta realizando mal la petición.



Se sabe que existe porque existe respuesta.

**Comment by mantnicot** [comment]
Se probaron todos los usuarios en ambiente de pruebas para conocer cuales deben pedirse un cambio

En este documento quedo anexado toda la evidencia y la conclusión es que todos fallaron en realizar incluso peticiones desde el administrador.

[Usuario PreProducción.docx](https://github.com/udistrital/polux_cliente/files/6940433/Usuario.PreProduccion.docx)


https://1drv.ms/w/s!AkQEWBEvYVTDhW14PexsWV9zLXk1?e=Y5cOq1

Se probaron todos los usuarios en ambiente de pruebas para conocer cuales deben pedirse un cambio


[Usuarios Producción.docx](https://github.com/udistrital/polux_cliente/files/6940442/Usuarios.Produccion.docx)


https://1drv.ms/w/s!AkQEWBEvYVTDhW-zrP_evIjIlxGy?e=8COmw6

**Comment by mantnicot** [comment]
Se probo los usuarios y se observo laas acciones que pueden o no hacer para ver el flujo de trabajo

https://1drv.ms/w/s!AkQEWBEvYVTDhXV40GDRiyYUZqM1?e=AiE9BY

**Comment by mantnicot** [comment]
Se esta probando el flujo para realizar el manual correspondiente , pero se notan errores


https://1drv.ms/w/s!AkQEWBEvYVTDhX6aYP_8VenmhPAX?e=EUGsJv

En este link se esta colocando todo el manual para que sea didactico y practico

https://view.genial.ly/6115542359b6100d3535b6a4/interactive-image-imagen-interactiva
