### ISSUE TITLE
Corrección de usuarios para pruebas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#115]
Se requiere registrar el paso a paso de la corrección realizada a los usuarios utilizados, según sus roles, para pruebas en POLUX.

**Criterio de aceptación**

- [x] Documento que registre el paso a paso de las  modificaciones y correcciones realizadas a cada usuario.

**Comment by mantnicot** [comment]
Se adjunta el documento de pasos e inforomacion para la corrección.

[Corrección usuarios.docx](https://github.com/udistrital/polux_cliente/files/6963434/Correccion.usuarios.docx)
