### ISSUE TITLE
Pruebas Unitarias

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#121]
Implementar pruebas unitarias y refactor si es necesario, relacionadas con los desarrollos realizados a la fecha.

**Criterios de aceptación**

- [x] Registro de pruebas unitarias desarrolladas, junto con los resultados obtenidos.

**Material de apoyo**:

Utilizar esta [plantilla](https://docs.google.com/document/d/1Uuk4IQHjhwm-3rQWwsmZQ5uts6X3SCEJ8OpJEsvUHXU/edit) como guía para el desarrollo de pruebas unitarias.

**Comment by mantnicot** [comment]
Se realizo las pruebas del modulo de parametrizacion :

[Aplicación pruebas Funcionales y de Usabilidad Parametrizacion.xlsx](https://github.com/udistrital/polux_cliente/files/7096355/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.Parametrizacion.xlsx)

https://docs.google.com/spreadsheets/d/1tL_204ETIPnQV5294-lPKGWbaFYbaL_OOxZ2ZL1q52A/edit?usp=sharing
