### ISSUE TITLE
Manual, módulo de parametrización.

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#124]
Adjuntar manual de usuarios, relacionado con el módulo de parametrización.

**Comment by mantnicot** [comment]
Se agrega el manual para el modulo de parametrizacion ,se adjunta el manual en texto , vídeo y presentación.


[Modulo de parametrización.docx](https://github.com/udistrital/polux_cliente/files/7108727/Modulo.de.parametrizacion.docx)


https://drive.google.com/drive/folders/1gEo53USzMYP06xWKJl6-t6qvgFBaiOtw?usp=sharing


https://view.genial.ly/61328be6d1912d0d33d7ac63/interactive-image-imagen-interactiva
