### ISSUE TITLE
Creación de Mock-ups - Reportes

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#139]
Realizar la creación de Mock-ups relacionados con el modulo de reportes en donde se muestren los tipos de reportes a generar, la información que estos contienen y la interfaz equivalente en el sistema para generarlos.

**Criterios de aceptación**

- [ ] Mock-ups del módulo de reportes.
- [x] Plantillas de los reportes generados.

**Comment by mantnicot** [comment]
Se tomara como referencia el anterior diseño propuesto, cambiando solo la posición del gráfico circular

![Captura de pantalla de 2021-09-29 22-19-59](https://user-images.githubusercontent.com/85162258/135380694-b040ccfa-ca9c-4c50-84d2-b9a7150d9530.png)

**Comment by a52290451** [comment]
Queda pendiente segundo mock-up para otro tipo de reporte a generar.

**Comment by mantnicot** [comment]
Se crean dos mock ups para la creacion de reportes

![Captura de pantalla de 2021-09-30 13-55-38](https://user-images.githubusercontent.com/85162258/135515330-41a15d8c-54eb-4b00-82c0-1c63d5486fe4.png)


Se toma como base la antigua estructura del anteriores reportes expuestos, pues es de una vista amigable y de la misma manera practica.
 El primer informe es el **informe general de trabajos de grado** el cual contiene la siguiente información : 
 -El nombre del trabajo de grado 
 -La modalidad
 -El estado 
Se agrupa todo en un tabla de información también se muestra la información en un gráfico circular , todo acoplado en un documento para su descarga.


![Captura de pantalla de 2021-09-30 14-47-30](https://user-images.githubusercontent.com/85162258/135520722-f6e2ac79-5ca9-4879-9adc-8b7171c94969.png)

 El segundo informe es el **informe general de trabajos de grado asociados al docente** el cual contiene la siguiente información : 
 -El rol del docente frente al trabajo
 -El nombre del trabajo de grado 
 -La modalidad
 -El estado 
 -El periodo 
Se agrupa todo en un tabla de información y al igual que anterior informe , el documento se podrá descargar

**Comment by a52290451** [comment]
Se validan Mock-ups con cambios menores a realizar

**Comment by mantnicot** [comment]
![Captura de pantalla de 2021-11-05 09-24-36](https://user-images.githubusercontent.com/85162258/140525931-2ae39f66-85e0-4b5a-bd86-97cefe18bdd6.png)


Así quedan los Mock-ups con los cambios ,agregando el periodo del trabajo


![Captura de pantalla de 2021-11-05 09-26-16](https://user-images.githubusercontent.com/85162258/140526193-56d8679f-b568-4867-a4de-90949a4b7710.png)

Se cambia el titulo de la columan de nombre de trabajos de grado
