### ISSUE TITLE
Desarrollo en el cliente para creación de interfaz gráfica asociada a generación de reportes.

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#140]
Desarrollar la interfaz grafica necesaria para el módulo de reportes, conforme a lo dispuesto en la [Apropiación de generalidades - Reportes](https://github.com/udistrital/polux_cliente/issues/138).

**Criterios de aceptación**

- [x] Commit en rama feature para cliente_polux con los cambios realizados.

**NOTA**: tomar como referencia los [Mock-Ups](https://github.com/udistrital/polux_cliente/issues/139) diseñados posterior a su aprobación.

**Comment by mantnicot** [comment]
Commit : [Parte grafica](https://github.com/udistrital/polux_cliente/commit/03404647e44c757295d147539ea9cf3f9112482c)
