### ISSUE TITLE
Desarrollo en API MID y CRUD para generación y almacenamiento de reportes.

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#141]
Se requiere realizar el desarrollo necesario en polux_mid y polux_crud para generación y almacenamiento de reportes. Se debe tener en cuenta la creación o ajuste de EndPoints y las tareas que esto conlleve (acceso a tablas paramétricas, ajuste o creación de controladores, modelo de datos y helpers).

**Criterio de aceptación**

- [x] Commit en rama Feature de desarrollo en polux_mid.
- [x] Commit en rama Feature de desarrollo en polux_crud.

Nota: Tomar en consideración el análisis realizado en "[Apropiación de generalidades](https://github.com/udistrital/polux_cliente/issues/138)".

**Comment by mantnicot** [comment]
Commit de subido del modulo de reportes en parte del cliente , ya que no se requiere desarrollo en mid 


1 -)   [Reportes coordinado y docente ](https://github.com/udistrital/polux_cliente/commit/03404647e44c757295d147539ea9cf3f9112482c)
