### ISSUE TITLE
Adaptación modulo de notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#236]
Realizar la adaptación del módulo de notificaciones al sistema pólux en los espacios en que aplique, de acuerdo al manual de implementación realizado por el equipo CORE.

**Criterios de aceptación**

- [x] Commit con los cambios realizados.
- [x] Pruebas funcionales de lo realizado.

Nota: tener en cuenta [manual de implementación](https://drive.google.com/file/d/1ZlXdKAyooyftamyCZX8Btmd5nhDR5YEX/view?usp=sharing).

**Comment by mantnicot** [comment]
Documentos de notificaciones:


[Documento de explicacion de casos de notificaciones y roles](https://1drv.ms/x/s!AkQEWBEvYVTDiF3Q-0A4QnAZzMiq?e=J4nVRt)


[Documento de mockups ](https://docs.google.com/document/d/1xaABDk-RtKTO119Plh133f6sC4b50rHK0IH35Si4FRI/edit?usp=sharing)

**Comment by mantnicot** [comment]
Se adjunta el checklist por medio de link para su actualización 


[ Checklist notificaciones pruebas ](https://1drv.ms/w/s!AkQEWBEvYVTDiSdL39H7myJQME8x?e=eeqdIw)

**Comment by mantnicot** [comment]
Se adjunta las pruebas realizadas en el modulo de notificaciones , se realizo con el correo del desarrollador para las pruebas


[Pruebas funcionales](https://1drv.ms/x/s!AkQEWBEvYVTDiSoHyXtZed0nBgoq?e=vGekv2)

**Comment by mantnicot** [comment]
Commit del modulo de notificaciones

[Commit rama notificaciones](https://github.com/udistrital/polux_cliente/pull/250)
