### ISSUE TITLE
Despliegue - Módulo de notificaciones en producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_cliente#265]
Realizar despliegue de módulo de notificaciones en ambiente de producción.

**Criterios de aceptación**

- [x] CheckList de despliegue.
- [x] Commit a rama master.

**Comment by mantnicot** [comment]
Se realiza el checklist de notificaciones

[CHECKLIST](https://1drv.ms/w/s!AkQEWBEvYVTDiSdL39H7myJQME8x?e=OAjsBt)

**Comment by a52290451** [comment]
Listado de tareas pendientes para despliegue en prod.
 
 1. Solicitar creación de colas para las notificaciones en producción.
 2. Solicitar permisos para consumo de API de notificaciones en producción.
