### ISSUE TITLE
Diagnosticar estado de pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#293]
Tarea asociada a la adopción del sistema Pólux:

Se debe revisar documentación asociada a Pólux, con el objetivo de conocer sus funcionalidades, flujos de trabajo, roles, componentes, tecnologías y demás elementos relacionados.

Se requiere repasar los manuales de usuario disponibles para comprender el alcance y las funcionalidades que posee cada rol dentro del sistema.

**Criterios de aceptación**

Documento con los hallazgos encontrados, componentes funcionales, no funcionales, tareas aún pendientes para despliegue.

Links de apoyo:

[Diagnóstico final Pólux](https://docs.google.com/document/d/1NoO94ABDCj8wrOa3EUMIPbp__eVpykFX/edit?usp=share_link&ouid=100698401433907561666&rtpof=true&sd=true)
[Documentación](https://drive.google.com/drive/folders/1Mx3ALAPklgKkHMcMISk-NcQKo4trrLht?usp=share_link)
[Manuales de usuario](https://docs.google.com/spreadsheets/d/1q94p70_t46GpJ2eKVlBDFGRDWFxKCGMMclIWWCT-kjc/edit?usp=sharing)

**Comment by diagutierrezro** [comment]
https://docs.google.com/spreadsheets/d/1VoznwoN5GEAtITn05ByDA_tVIioORCS5iYzRMUAYZ4A/edit?usp=sharing
