### ISSUE TITLE
Ajustes relacionados al rol estudiante

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#301]
- [x] Visualización de posibles solicitudes desde estudiante (refrescar cliente).
- [x] Revisión cargue de documento ARL (Pasantía).

**Comment by diagutierrezro** [comment]
Para ajustar la visualización de solicitudes por parte de los estudiantes no se estaba actualizando la variable que almacenaba el tipo de solicitud seleccionado anteriormente, este ajuste se realiza en el siguiente [commit](https://github.com/udistrital/polux_cliente/commit/687466ec850bab018c7764b494ba9c5a0f3ed07d)

**Comment by diagutierrezro** [comment]
Para el cargue de la ARL se debe revisar realizar una busqueda de los tipos de documentos ya que esta información se encuentra vacía en la base de datos
