### ISSUE TITLE
Otros hallazgos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#303]
- [x] Coordinador: Rechazo de solicitud - Se rechaza correctamente pero al director no le aparecen más solicitudes.
- [x] En modalidad de creación - interpretación no se pueden realizar más solicitudes porque no se cumplen con los requisitos.

**Comment by diagutierrezro** [comment]
- Cuando se realizó la corrección del rechazo de transacción en el docente director de este [issue](https://github.com/udistrital/polux_cliente/issues/300) este error no ocurrió mas.
- En cuanto al error de modalidad de creación - interpretación se debe a que esta es una modalidad de grado que solo está relacionada con las carreras de artes y los usuarios que se tienen en el momento son de ingeniería por lo que @milo19980525 realizó una solicitud para obtener un conjunto de usuarios de artes.
