### ISSUE TITLE
Parámetros de pólux en posgrado y materias de profundización

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#305]
- [x] Revisar los menús encontrados en el usuario de administración del sistema (En especial los módulos paramétricos).
- [x] Insertar fechas paramétricas del semestre en las tablas asociadas al api de eventos, con base en la lógica del aplicativo (¿Semestre actual y siguiente?)(Vídeo Fabian).

Material de apoyo: https://drive.google.com/file/d/1MsT9KpfxXbNkEIgDpOW2G99HkTg2b1Um/view (Desde el min 24)

**Comment by diagutierrezro** [comment]
Si bien se tiene el video en el se menciona que no se tiene muy claro el uso de las tablas de sesiones, siendo estas tablas las que se usan en las peticiones del cliente para traer las respectivas fechas, por esta razón se opta por realizar registros manuales de la base de datos creando los siguientes registros necesarios en la tabla **_sesion_** para poder crear solicitudes de estas modalidades
![image](https://user-images.githubusercontent.com/38676533/204065097-532d9062-3454-4645-a805-88564f69877b.png)
Adicional a esto se realizan los respectivos registros en la tabla **_relacion_sesiones_**.
![image](https://user-images.githubusercontent.com/38676533/204065170-aab14921-8ce0-47b3-8d93-bbe6f3ad7930.png)
 Los dos registros anteriores se realizan en la base de datos udistrital_core, en el esquema eventos.

**Comment by diagutierrezro** [comment]
Despues de registrar las sesiones y su respectiva relación entre si se habilitan los modulos de registro de las modalidades pero aún se debe revisar los espacios academicos de cada modalidad.
