### ISSUE TITLE
Pruebas Funcionales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#307]
Se requiere implementar pruebas funcionales asociadas a cada uno de los flujos (modalidades) desde la solicitud de los estudiantes hasta las posibles terminaciones de la misma (rechazo, aprobación y rechazo, aprobación y terminación, etc.)

**Criterio de aceptación**

- [x] Formato de hallazgos con las pruebas realizadas.
- [x] Dejar escrito los requisitos que se tiene por cada una de las modalidades

**Comment by diagutierrezro** [comment]
Se realizan las pruebas y se reunen los requisitos para cada una de las modalidad, se deja registro de estas en el siguiente [documento](https://docs.google.com/spreadsheets/d/1r5fI8gh-hVxYKWWnVegPAZxhCpaNZ8jx5gIR9g8V2qU/edit?usp=sharing)

Es importante dejar claro que los requisitos de las modalidades de materias de profundización, posgrado y creacion - interpretación se realizaron basandose en el siguiente [acuerdo](https://github.com/udistrital/polux_cliente/blob/develop/app/documentos/acuerdo_2015-038.pdf).
