### ISSUE TITLE
Revisar y resolver dependencias

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#312]
Se requiere reresolver las dependencias del dependanbot del cliente de pólux.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama master.

**Sub Tareas**

- [x] Revisar las alertas de dependanbot https://github.com/udistrital/polux_cliente/security/dependabot.
- [x] Corregir aquellas que sean críticas o que estén en alto (high), sin llegar a dañar o comprometer el funcionamiento esperado del cliente.

**Criterios de aceptación**

- [x] Se eliminan las dependencias.
- [x] Se verifica el correcto funcionamiento del sistema con las dependencias eliminadas.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realizan las pruebas en producción de las correcciones de las dependencias, realizando el flujo principal con la modalidad de monografía.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/e2e9fac4-faf2-4eb5-b8d5-aa38af038e0f)

Quedan pendientes varias soluciones a las dependencias, ya que se suben cambios de las librerías y demás, pero el sistema requiere de varias versiones en diferentes secciones.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/a6a6f056-02ac-48c4-87f2-b462402200df)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/e33608e8-de5f-4130-8cbc-e132721fe56b)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/30e0c976-1a7a-45ca-a800-16ea75141eeb)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/1fadc984-9a40-42fe-85cd-8025ef4c48f6)

De las 9 alertas altas y críticas, se solucionan 5.
