### ISSUE TITLE
Diagnosticar el sistema v2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#318]
Teniendo en cuenta que el desarrollo que tuvo que ser suspendido:

1. Verificar cada uno de los tipos de solicitud de trabajo de grado definidos en el sistema.
2. Revisar cada opción de los menús disponibles para los diferentes tipos de usuario.
3. Determinar en un documento con el formato de hallazgos, que fallas se están presentando en este momento.

**Criterios de aceptación**

- [x] Documento con formato de hallazgos con los bugs o errores encontrados.

**Comment by diagutierrezro** [comment]
[Documento de hallazgos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/diagutierrezr_udistrital_edu_co/EfqWYt1TihxFvFPb5faPxPsBhCi7_tbPOw8fSCPoyzSjsA?e=o6RAvN)

Por el momento no se cierra el issue mientras se registran los usuarios faltantes para terminar las pruebas
