### ISSUE TITLE
Hallazgos por corregir 9/02/2023

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#320]
**Correcciones**

- [x] Para el docente evaluador, en trabajo de grado/registarr nota colocar el link del documento del estudiante para que pueda ser descargado.
- [x] Revisar los proyectos curriculares de POSTGRADO en la base de datos o paramterízar de nuevo las fechas.
- [x] Ajustar los estados de solicitudes cuando un docente tiene a cargo más de un estudiante.

**Comment by diagutierrezro** [comment]
Se ajustan las fechas de solicitudes de posgrado para permitir realizar pruebas con esta modalidad de grado
