### ISSUE TITLE
Dudas funcionales del sistema

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#321]
**Dudas**

- [x] ¿Un estudiante debería poder seguir solicitando revisiones una vez haya solicitado una con el documento final?
- [x] Una vez el trabajo haya sido aprobado por parte del coordinador y el director ponga la calificación el estudiante puede realizar solicitudes de tipo, cambio de director, cancelación de modalidad, etc.?
- [x] ¿Después de registrar la nota que sigue en el flujo?
- [x] ¿Los estudiantes deberían visualizar las actas respuesta a sus solicitudes?
- [x] ¿Se pueden seleccionar docentes distintos al proyecto curricular para ser evaluadores o directores?

**Comment by milo19980525** [comment]
Según la reunión con el director del proyecto curricular de Ingeniería de sistemas:

1. No debería poder seguir enviando solicitudes de revisión al documento final (Anteproyecto y proyecto, o en su defecto en informe).
2. No debería poder realizar ese tipo de solicitudes debido a que afectaría el proceso de opción de grado (En dado caso de aprobar). El estudiante inicio el proceso y en el transito de anteproyecto puede cancelar director, cambio de modalidad la cual quedaría como inhabilitada.
3. Dependiente a conexión con otros aplicativos (Se buscan las materias de trabajo de grado y se asignan las notas). Se sugiere generación de paz y salvo para validar la superación del proceso de manera satisfactoria (Director y revisor validan el certificado), una notificación al coordinador, y finalizando con la subida del actas de sustentación y suban la nota de las dos asignaturas.
**Queda pendiente definir actas de materia de grado.**
5. No estaría como tal avalado por el acta si no que se gestionaría a través de la plataforma. No todos los estudiantes hacen la solicitud con un director (en dado caso crear un flujo alterno sin un director inicial). Flujo: Chico se postula con un anteproyecto, envía al coordinador, se asigna revisor y el revisor es quien indica si se acepta, rechaza o es modificable (interacción con estudiante) y continua flujo de modalidad de grado.
6. Deben ser de los mismos del proyecto curricular (De planta, TCO o medio tiempo).

Nota: Se debe revisar tiempo de realización de la monografía o pasantía según el nuevo acuerdo.
Los revisores de anteproyecto y de proyecto pueden variar.

Se debe revisar acuerdo 011 de 2022: https://sgral.udistrital.edu.co/xdata/csu/acu_2002-011.pdf.

**Comment by milo19980525** [comment]
Pendiente conseguir el acuerdo.

**Comment by diagutierrezro** [comment]
Respecto al numeral 3 el flujo actual obliga en algunas modalidades al cargue de un acta de sustentación por parte del director al momento de generar la nota, por otro lado cuando existe un docente evaluador este puede subir la nota sin que haya un acta cargada anteriormente por lo que tocaría revisar este flujo.
