### ISSUE TITLE
Corrección de endpoints JBPM - Académica

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#322]
- [x] Actualizar la consulta de docente por facultad y proytecto curricular por parámetros Académica JBPM

**Comment by milo19980525** [comment]
@diagutierrezro por favor relacionar la consulta que se debría emplear teniendo en cuenta los parámetros de facultad y proyecto curricular.

**Comment by diagutierrezro** [comment]
La consulta para docentes es 
_SELECT DIR_NRO_IDEN id, DIR_NOMBRE || ' ' || DIR_APELLIDO nombre, MNTAC.ACDOCENTEANT.DOC_CRA_COD codigo_carrera, MNTAC.ACCRA.CRA_NOMBRE carrera
FROM MNTAC.ACDIRECTORGRADO 
INNER JOIN ACDOCENTE ON DIR_NRO_IDEN=DOC_NRO_IDEN 
INNER JOIN MNTAC.ACDOCENTEANT ON DIR_NRO_IDEN=MNTAC.ACDOCENTEANT.DOC_NRO_IDEN
INNER JOIN MNTAC.ACCRA ON DOC_CRA_COD=CRA_COD
WHERE DIR_ESTADO='A' 
AND ACDOCENTE.DOC_ESTADO='A' 
AND DOC_ESTADO_REGISTRO='A'
AND DOC_CRA_COD=97
ORDER BY nombre_

El codigo 97 representa el codigo de la carrera en la tabla **MNTAC.ACDOCENTEANT.DOC_CRA_COD**

**Comment by diagutierrezro** [comment]
Otra consulta por la que tambien se puede filtrar es 

SELECT DIR_NRO_IDEN id, DIR_NOMBRE || ' ' || DIR_APELLIDO nombre, MNTAC.ACDOCENTEANT.DOC_CRA_COD codigo_carrera, MNTAC.ACCRA.CRA_NOMBRE carrera
FROM MNTAC.ACDIRECTORGRADO 
INNER JOIN ACDOCENTE ON DIR_NRO_IDEN=DOC_NRO_IDEN 
INNER JOIN MNTAC.ACDOCENTEANT ON DIR_NRO_IDEN=MNTAC.ACDOCENTEANT.DOC_NRO_IDEN
INNER JOIN MNTAC.ACCRA ON DOC_CRA_COD=CRA_COD
INNER JOIN MNTAC.ACTIPCRA tra ON tra.TRA_COD = MNTAC.ACCRA.CRA_TIP_CRA
WHERE DIR_ESTADO='A' 
AND ACDOCENTE.DOC_ESTADO='A' 
AND DOC_ESTADO_REGISTRO='A'
AND DOC_CRA_COD=97
AND tra.TRA_NOMBRE LIKE '%ARTES%';
ORDER BY nombre

Faltaría definir si este ultimo filtro sería un AND o un OR
