### ISSUE TITLE
Probar flujos Artes y Tecnológica

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#323]
Con los usuarios escogidos para las modalidades de grado específicas para Artes y tecnológica, probar los flujos pendientes:

1. [x] Materias de profundización
2. [x] Creación o Interpretación

**Criterios de aceptación**
- [ ] Una vez probados los flujos documentar el archivo de diagnostico v2 del sistema con los hallazgos encontrados.

**Comment by diagutierrezro** [comment]
Se realizan las pruebas del flujo de la modalidad de materias de profundización, surgen varios inconvenientes

1. En el codigo se encuentra quemado el filtro "POSGRADO" pero para esta modalidad el filtro se debe hacer para materias de pregrado por lo que se debe buscar una manera de traer esta información de las consultas realizadas.
2. Surge la pregunta anto para materias de posgrado como de profundización ¿Quién es el encargado de las solicitudes, el coordinador de la carrera del estudiante o el coordinador de la carrera de las materias que solicitó para la modalidad?
