### ISSUE TITLE
Revisar flujo de materias de posgrado

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#324]
Probar la modalidad de materias de posgrado:

**Criterios de aceptación**
- [x] Una vez probado el flujo documentar el archivo de diagnostico v2 del sistema con los hallazgos encontrados.

**Comment by diagutierrezro** [comment]
El flujo de opción de grado con materias de posgrado no se puede realizar por completo ya que una vez que el estudiante envía la solicitud esta no llega al coordinador y debido a que en esta modalidad el estudiante no elige un docente director no se sabe quien es el siguiente responsable en este flujo. Probablemente el flujo deba continuar con el coordinador quien sería el que asigna un docente director al estudiante o aprueba la solicitud..

Se actualiza el [documento de hallazgos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/diagutierrezr_udistrital_edu_co/EfqWYt1TihxFvFPb5faPxPsBhCi7_tbPOw8fSCPoyzSjsA?e=ECGrj8) con este inconveniente.
