### ISSUE TITLE
Documento diagnostico Pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#327]
Teniendo en cuenta la finalización de la contratación realizar un documento dónde se evidencie:

- [x] El estado actual del sistema
- [x] Bugs, errores conocidos y deuda técnica
- [x] Limitaciones
- [x] Actividades realizadas para salir a producción – Equipo de desarrollo
- [x] Actividades requeridas para salir a producción – Equipo de desarrollo
- [x] Actividades requeridas para salir a producción – Terceros
- [x] Usuarios de prueba – WSO2
- [x] Videotutoriales y Manuales de usuario
- [x] Plan de mejoramiento

**Comment by diagutierrezro** [comment]
Se actualiza el[ documento de diagnostico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/cerochac_udistrital_edu_co/Eb4ELQFuRzpFift2UbPy1UEBmexjyWoUZa0qCtxM599ruw?e=ZO2jvA) de polux con el estado actual del sistema, bugs, limitaciones y un plan de mejoramiento
