### ISSUE TITLE
Revisión de documentación Acuerdo 011 de 2022

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#328]
Revisar documentación del acuerdo 011 de 2022 y revisar los flujos definidos.

**[Acuerdo 012](https://sgral.udistrital.edu.co/xdata/ca/acu_2022-012.pdf)**

**Criterios de aceptación**

- [ ] Revisar y anotar las diferencias de los procesos que se definen en el acuerdo y como está en Pólux.

**Comment by diagutierrezro** [comment]
Se revisa el acuerdo 012 y se realiza un [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EYL84Z7jva9AlmSJkiHzliEBm84BaGvf0yAnx3LEtho7IQ?e=DcU8ZQ) con los cambios detectados que afetarían el sistema y que por lo tanto deben de ser ajustados. 

Es importante restaltar que se mencionó que este es un preacuerdo por lo que puede sufrir cambios, por esta razón es recomendable volver a revisar este acuerdo mas adelante.
