### ISSUE TITLE
Revisión de documentación y adaptación a Pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#330]
Revisar documentación asociada a Pólux, con el objetivo de conocer sus funcionalidades, flujos de trabajo, roles, componentes, tecnologías y demás elementos relacionados.

1. Se requiere repasar los manuales de usuario disponibles para comprender el alcance y las funcionalidades que posee cada rol dentro del sistema. 

[Documentación](https://drive.google.com/drive/folders/1Mx3ALAPklgKkHMcMISk-NcQKo4trrLht?usp=share_link)
[Manuales de usuario](https://docs.google.com/spreadsheets/d/1q94p70_t46GpJ2eKVlBDFGRDWFxKCGMMclIWWCT-kjc/edit?usp=sharing)

2. Revisar el documento diagnóstico resultante de la contratación 2022-2023, en el cual se evidencia el estado actual del sistema, limitantes, bugs, credenciales de usuario, entre otros.

[Diagnóstico final Pólux](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/cerochac_udistrital_edu_co/ESLhuvDIGHJGslT78S8engcBtRNqkzuWmke4CE32_ABxpg?e=7Hbt5a)

3. Verificar la grabación de la reunión del 22/03/2023 dónde se muestran algunos flujos del sistema, junto a sus inquietudes.

[Reunión inducción 22/03/2023](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/EYx2C122ttBBpTrLuQD9cTwB-vpBtysLs8vYhzz7w9AO2w)

4. Revisar la siguiente issue dónde se lleva a cabo una reunión con el coordinador de sistemas y se resuelven unas inquietudes relacionadas con los flujos de pólux.

[Issue](https://github.com/udistrital/polux_cliente/issues/321)

[Reunión coordinador sistemas](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/EXAtdnfEw9VKgbFntmJ-JFwBrmgdryG25KBnzZ-x8ArxZA?e=j7xghK)

**Criterios de aceptación**

- [ ] Identificación y definición de las modalidades de grado que soporta Pólux actualmente.

**Comment by cearomeroc** [comment]
De acuerdo a la información y documentos aquí contenidos, se realiza la respectiva revisión, por lo cual se adjunta el respectivo [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/cearomeroc_udistrital_edu_co/EbrtclvKlCZElDzvkIyeEZ4BWq_tEMQT9gNdGkDpwm3_ww?e=PzoJL5) que da soporte a los criterios de aceptación de la presente ISSUE
