### ISSUE TITLE
Revisión de documentación - Acuerdo 012 - 2022

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#331]
Realizar una lectura profunda al acuerdo 012 de 2022, que trata sobre la reglamentación y normatividad de las diferentes modalidades de grado establecidas.

[Acuerdo 012
](https://sgral.udistrital.edu.co/xdata/ca/acu_2022-012.pdf)
Cabe resaltar que previamente el desarrollador a cargo del sistema realizó un análisis el cual puede ser empleado como base del documento.

issue #328 

**Criterio de aceptación**

- [ ] Documento con los principales cambios encontrados en el acuerdo.

**Comment by cearomeroc** [comment]
Se realiza la respectiva revisión documental y se genera el [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/cearomeroc_udistrital_edu_co/EczquTa1XKtPghh0ANKDJnkB7Bfa2fHVI6g4GJm_GzC5vA?e=tbnB11) aquí adjunto.
