### ISSUE TITLE
Diagrama de estados

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#332]
Con base en los artefactos estudiados en el issue #330 realizar:

**Criterios de aceptación**

- [x] Diagrama de estados que emplean las diferentes modalidades de grado.

**Comment by cearomeroc** [comment]
Se adjunta el respectivo diagrama para consulta:
- [Enlace](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/cerochac_udistrital_edu_co/Ebw-4NhlwntEjCtnmrzexKQBKI1sawYK4CiE_kNZBMHrMQ?e=lGdQBx)

**Comment by cearomeroc01** [comment]
De acuerdo al desarrollo de las sesiones y revisión en el sistema POLUX se logró identificar un diagrama general y algunas modificaciones de acuerdo a las modalidades especificas:

Diagrama: [enlace al documento ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Em63IXLDDidKgf0HQVcRdI0BtW34asQgq0n-XX1mQBTbrg?e=Gn5cXB)
