### ISSUE TITLE
Elaboración de HU

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#334]
Con base en los resultados encontrados en #331 realizar las HU asociadas a los diferentes roles que se pueden encontrar en la lógica de negocio (Director, estudiante, revisor, coordinador) dependiente a la modalidad de grado escogida.

**Criterios de aceptación**

- [x] Documento con formato de HU de la OAS.

**Comment by cearomeroc** [comment]
Se realiza la respectiva revisión documental y de procesos generando el siguiente documento de HU en formato OAS.
- [Enlace](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/cerochac_udistrital_edu_co/EoldzAbTRKZHkxwjOfDR2I0Bm4OLrwfPgTW0r84ExUX0BQ?e=NZGOQe)

**Comment by cearomeroc** [comment]
Con base en la sesión con SCRUM MASTER el día 19 de mayo de 2023, se realizará el respectivo refinamiento al documento de HU, detallando minuciosamente cada una de las modalidades y sus requerimientos para dar cumplimiento al acuerdo 012 de 2022, se proyecta una sesión de revisión de avance para el día 25 de mayo.

**Comment by cearomeroc01** [comment]
De acuerdo a las actividades realizadas y al análisis de documentación respectivo se elaboran las siguientes versiones de HU, determinando la versión final la de mayor número.

Historias de usuario, [documentos relacionados](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/El_F1tTfemdGuvGNuqbomCABYarhIME9mQ5QOz3_4e-yMA?e=4z9pNk)
