### ISSUE TITLE
Reunión con un proyecto de posgrado

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#335]
Reunirse con un proyecto curricular de posgrado y levantar requerimientos sobre todas las modalidades de grado existentes.

**Criterio de aceptación**

- [x] Refinar HU elaboradas, en dado caso de ser necesario añadir las que sean pertinentes.

**Comment by cearomeroc** [comment]
Se realiza sesión con dos programas de posgrado el día 28/04/2023, hora 10:00 am:

* Maestría ingeniería civil.
* Maestría ingeniería industrial.

Dentro de los temas que se abordaron fueron las modalidades que les aplican con base al acuerdo 012 de 2022 (pregrado).
- pendiente la generación de acta de reunión.
