### ISSUE TITLE
Reunión con coordinación de un proyecto de Artes

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#336]
Reunirse con un proyecto curricular de la facultad de artes y levantar requerimientos sobre todas las modalidades de grado existentes.

**Criterio de aceptación**

- [x] Refinar HU elaboradas, en dado caso de ser necesario añadir las que sean pertinentes.

**Comment by cearomeroc** [comment]
Se realiza acercamiento telefónico para programar una sesión, tentativamente se proyecta para el día 21 de abril de 2023, jornada mañana. 

Programas interesados en la sesión: 
Artes Escénicas - Yolanda González,  ext 6608- 6609
Arte Danzario - Patricia Ortiz, ext 6630, 6614
Artes Musicales - Francisco Méndez, ext 6612

Pendiente confirmación de los programas para proceder con agendamiento

**Comment by cearomeroc** [comment]
Se confirma reunión presencial con personal administrativo del programa artes musicales para el día viernes 21 de abril de 2023, hora: 10:00am

**Comment by cearomeroc** [comment]
Se lleva a cabo la reunión presencial en la facultad de artes ASAB el día 21 de abril de 2023, 10:00am (pendiente acta de reunión).
