### ISSUE TITLE
Revisión del sistema Pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#341]
Teniendo en cuenta la solicitud de vicerectoría académica y la facultad de ingeniería, bajar cada uno de los repositorios asociados al sistema de pólux (Cliente, mid y crud) y montarlos en un ambiente local, con el proposito de comprender el sistema y verificar que se encuentra funcionando.

**Especificaciones técnicas**

- Clonar los repositorios de pólux en local.
- Tener en cuenta que el cliente se encuentra en Angular JS.
- Se consumen diferentes endpoints de academica a través de JBPM

**Sub Tareas**

- [x] Clonar los repositorios.
- [x] Verificar cada una de las modalidades posibles de grado que maneja pólux.
- [x] Preparar posible demo para lunes/martes.
- [x] Realizar documento técnico.

**Criterios de aceptación**

- [x] Comentario en el issue con ejecución de ambientes en local.
- [x] Comentario del issue que relacione fallas encontradas en las modalidades probadas.
- [x] Comentario en el issue sobre flujo de demo a realizar. 
- [x] Comentario con documento técnico.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Académica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by milo19980525** [comment]
Ejemplo documento técnico.

**Comment by diagutierrezro** [comment]
El demo a realizar unicamente plantea ejemplos basicos de las modalidades de grado que funcionan correctamente (sin materias de posgrado y profundización) incluyendo la modalidad exclusiva de estudiantes de artes, debido a los usuarios limitados se continuará realizando la cancelación de modalidades de grado ya creadas para poder continuar con la presentación de las otras modalidades que se puedan realizar en el sistema.

**Comment by diagutierrezro** [comment]
Las fallas encontradas son:

- Flujo en modalidades de grado de materias de posgrado y profundización.
- En modalidad de pasantía genera error el registro del documento del director externo si este es muy largo, (sucedió con un dato de prueba muy largo) con números de cedula mas reales este error no sucede.
- Para modalidades de grado con varios estudiantes de diferentes proyectos curriculares, no se aprueba por los coordinadores de los diferentes proyectos, este flujo de aprobación solo se dirige hacia el coordinador del proyecto al que pertenezca el estudiante que hace la solicitud.
- El sistema permite que la modalidad de pasantía se pueda realizar por varios estudiantes.

**Comment by diagutierrezro** [comment]
Las dos Apis (crud y mid) y el cliente de polux se ejecutaron de manera local y funcionaron correctamente.

**Comment by Mechaz123** [comment]
Se realiza la puesta en funcionamiento del CRUD, MID y CLIENTE de POLUX
