### ISSUE TITLE
Realización manuales de Pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#342]
Se requiere realizar los manuales de Pólux para los roles que interactuan en el sistema.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release y fue presentado a los programas curriculares de la facultad de ingeniería.

**Sub Tareas**

- [x] Análisis del sistema por rol.
- [x] Redacción de manual de usuario por cada uno de los roles en el sistema detallando el proceso por cada una de las modalidades de grado.

**Criterios de aceptación**

- [x] Manual de usuario para rol de estudiante.
- [x] Manual de usuario para rol de docente.
- [x] Manual de usuario para rol de coordinador

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Junto con @Mechaz123 se crean los [manuales de usuario](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/diagutierrezr_udistrital_edu_co/Eloh6UpgOX1MsOgoNZ8c-CoBAxi66rR4cb4iILHjw-OMGA) para los 3 diferentes usuarios del sistema POLUX (estudiantes, docentes y coordinadores de proyectos curriculares.
