### ISSUE TITLE
Correcciones iniciales para el sistema pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#343]
Se requieren realizar ajustes iniciales sobre el sistema pólux para que se evidencie un incremento en el producto.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release y fue presentado a los programas curriculares de la facultad de ingeniería.

**Sub Tareas**

- [x] Revisión y ajuste de consulta que trae estudiantes con 80% cursado para que quede a 70%.
- [x] Adición de fase para que el director apruebe o rechaze cualquier solicitud realizada por el estudiante (novedades).
- [x] Restricción de novedades una vez registrada la nota por parte de los docentes.
- [x] Ajuste de campo "Docente que avala la propuesta o selección director" por "SELECCIONE EL NOMBRE DEL DOCENTE QUE AVALA SU PROPUESTA DE TRABAJO DE GRADO"
- [x] Ajuste de campo "plan de investigación" por "propuesta de investigación" - Modalidad Investigación-innovación
- [x] Añadir novedad por cambio de objetivos.

**Criterios de aceptación**

- [x] Se evidencia en la consulta de requisitos estudiante que este cumple con un 70% de créditos cursados.
- [x] Se evidencia que se añade novedad de cambio de objetivos y todas las novedades previo su envió requieren aprobación del director.
- [x] Se evidencia el cambio en los campos del formulario indicados.
- [x] Se restringe envió de novedades posteriores a sustetación "calificación de notas"

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realiza el cambio con respecto al requisito de tener el 70% cursado, este cambio se realiza a nivel de BD en pruebas.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/b06ac7c6-09db-494d-9ede-9726ea5a06ab)

Adicional a esto, se realiza la prueba del cambio, la primer imagen se realiza con valor requerido de 80%, con mi perfil personal que posee 79% cursado.

![MicrosoftTeams-image](https://github.com/udistrital/polux_cliente/assets/73924638/d35e38ff-8469-4460-8273-09a2fb1ddf68)

La segunda imagen, se realiza con el mismo perfil, pero ya teniendo el cambio del 70% cursado.

![MicrosoftTeams-image (1)](https://github.com/udistrital/polux_cliente/assets/73924638/4e0e4abd-8e8a-46b9-bc9f-c11943e3db2d)

**Comment by Mechaz123** [comment]
Se desarrolla la funcionalidad asociada a la restricción para la generación de solicitudes de Novedades, una vez registrada la Nota.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/f0d733ce-8282-420c-aaaa-274d4bc5423c)

**Comment by JuanCamiloMartinezLopez** [comment]
### Revisión de novedades por parte de director interno

Se crean los siguiente estados para tener en cuenta al docente director en el flujo de revisión de las solicitudes de novedades sobre el trabajo de grado.
![image](https://github.com/udistrital/polux_cliente/assets/42418412/86c4d128-55cd-4313-a25e-ab7595599341)
quedando inicialmente la solicitud en pendiente por aprobar por director interno
![image](https://github.com/udistrital/polux_cliente/assets/42418412/81845850-ca28-41a2-9e7c-953766e37b51)
Vista del docente interno:
![image](https://github.com/udistrital/polux_cliente/assets/42418412/7b81a5aa-279b-4320-8276-1e9534e11c8c)
En caso de aprobada por el director interno, esta aparece al coordinador con este estado:
![image](https://github.com/udistrital/polux_cliente/assets/42418412/bd9d0cb4-3127-4803-bab1-fcaf51275c4e)
donde este la puede aprobar o rechazar como el flujo anterior.

**Comment by Mechaz123** [comment]
Se realiza el cambio en los nombres del proyecto, asociado a la selección del docente

![image](https://github.com/udistrital/polux_cliente/assets/73924638/c9bc8a65-318d-4e2d-a5ea-e0b0cec29763)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/26ff052d-2248-45bf-826c-8709bfd9f894)

**Comment by Mechaz123** [comment]
Y se desarrolla la funcionalidad por cambio de objetivos, para las diferentes modalidades

![image](https://github.com/udistrital/polux_cliente/assets/73924638/29001d4e-1e00-4206-8251-64475df89a1c)
