### ISSUE TITLE
Ajustes con base en acuerdo 03 Facultad de ingeniería

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#346]
Se requieren realizar los siguientes ajustes sobre el sistema pólux para que se evidencie un incremento en el producto.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama develop, consecuente a los hallazgos corregidos en #343 .

**Sub Tareas**

- [x] Cambiar los nombres de las modalidades de grado de la siguente manera: 

1.  Investigación – Innovación a:  Investigación, Investigación- Creación, Innovación.
2. Creación o interpretación a: Creación, dirección o interpretación.
3. Producción académica a: Producción de artículo académico

- [x] Restringir cambio de modalidad máximo una vez.
- [x] Añadir campo de texto para digitar nombre de la revista.
- [x] Añadir un campo en la modalidad "Producción de artículo académico" que permita digitar el link de la revista de aceptación del artículo para el rol de estudiante.
- [x] Previo al campo de señeccionar la categoría de la revista añadir aviso "label" informativo que mencione: "Seleccione la categoría del artículo aceptado con base en la clasificación dispuesta por Publindex. Revistas nacionales: https://scienti.minciencias.gov.co/publindex/#/revistasPublindex/clasificacion e internacionales: https://scienti.minciencias.gov.co/publindex/#/revistasHomologadas/buscador"
- [x] Añadir un campo seleccionable por el estudiante en la modlidad "Producción de artículo académico" que permita añadir la clasificación de la revista dónde fue aceptado el artículo (A1, A2, B, C) prefereiblemente que sea un desplegable.
- [x] Duplicar la modalidad de grado de pasantía, nombrarlas "Pasantía Interna" y "Pasantía externa".

**Criterios de aceptación**

- [x] Se evidencian los nuevos campos informativos y de contenido en la modalodad "Producción de artículo académico".
- [x] Se restringue la cantidad de cambios de modalidad.
- [x] Se evidencia el cambio de nombres de las modalidades de grado.
- [x] Se evidencias dos modalidades de pasantía "Externa" y "Interna".

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@JuanCamiloMartinezLopez Nos está colaborando técnicamente para comprender el flujo de pólux

**Comment by Mechaz123** [comment]
Se plantea la siguiente tabla para el tema relacionado con la modalidad de producción academica y demás modalidades, con el fin de unificar esos detalles de cada pasantía.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/2de8b7c7-7430-4664-9234-a67260483207)

**Comment by Mechaz123** [comment]
Se realiza el ajuste de almacenar las clasificaciones de la revista en la base de datos de parametros.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/7efe3d4d-74bf-4e9a-9908-457218a6b509)

**Comment by Mechaz123** [comment]
Una vez se registran los datos el sistema realiza el guardado en la nueva tabla creada.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/f46fab98-6c91-4a8a-bc8e-fa9c9147ac05)

**Comment by Mechaz123** [comment]
Para el tema de la restricción de cambio de modalidad solo una vez, el sistema verifica si el usuario tiene una solicitud de cancelación de modalidad y especificamente en el estado aprobado por el consejo de carrera.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/b29a4766-ea35-4394-8608-57e467efb4be)

En caso de tener una solicitud de cancelación de modalidad aprobada, e intenta volver a realizar una cancelación de modalidad el sistema cargará un mensaje el cual no le permitirá crear dicha solicitud.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/d6e56e4a-65b6-4b9e-8369-4fe584321099)

**Comment by Mechaz123** [comment]
Se realiza corrección de ubicación de los campos relacionados a la revista, se encuentran ahora en la sección de solicitud para una revisión de trabajo de grado para la modalidad de articulo academico, así mismo se realiza la corrección de la visualización del parametro asociado a la clasificación de la revista.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/2e3776ee-ff70-4c3b-b2b7-ea61d5896de2)
