### ISSUE TITLE
Verificar modificaciones en modalidad materias de posgrado

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#347]
Verificar el estado de la modalidad "Materias de posgrado" y establecer diferencias con los requerimientos asociados a esta.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama develop, consecuente a los hallazgos corregidos en #343, # 346 y #348 .

**Sub Tareas**

- [x] Analizar el comportamiento del sistema bajo la modalidad de posgrado actualmente, establecer el flujo y compararlo con lo establecido por los requerimientos: [Modalidad de posgrado - Mockup](https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BDAC61FF3-F221-4ED7-962A-1A2E1597A3D6%7D&file=ESPACIOS%20ACAD%C3%89MICOS%20DE%20POSGRADO.docx&action=default&mobileredirect=true&cid=eedbff8d-292c-4820-8e7f-3c5a29a00e58)

**Criterios de aceptación**

- [x] Comentario en el issue con las diferencias encontradas entre la modalidad de trabajo de grado de materias de posgrado actual en el sistema Pólux vs. las propuestas en el documento de requerimientos.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se analiza el flujo establecido en los requerimientos encontrando los siguientes aspectos:

-	La publicación de materias de posgrado se puede realizar correctamente, hay que tener en cuenta los periodos actuales, anterior y siguiente los cuales se deben actualizar por base de datos.
-	Las materias se pueden seleccionar correctamente dependiendo de las que se hayan publicado por parte del coordinador del proyecto de posgrado.
-	Al enviar la solicitud se envía como las otras solicitudes solicitando director de trabajo de grado, pero esta modalidad no tiene director por lo que el flujo se está bloqueando en esa parte, para solucionar esto se deben modificar los id que se envían para que esta sea una solicitud inicial y se pueda revisar por parte del coordinador.
-	El resto del flujo no se puede revisar hasta que no se corrija el punto anterior ya que no se puede aprobar la solicitud.
