### ISSUE TITLE
Ajustes generales del sistema

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#348]
Se requieren realizar los siguientes ajustes sobre el sistema pólux para dejar incrementar el producto hacía el MVP.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama develop, consecuente a los hallazgos corregidos en #343 y #346.

**Sub Tareas**

- [x] Revisar si existe filtro de validación del nivel de formación de estudiantes (que desean cursar una modalidad de grado).
- [x] Revisión de nota mínima aprobatoria (3.0) para proyectos diferentes a posgrado y 3.5 para posgrado.
- [x] Restringir cambio de modalidad máximo una vez.
- [x] Revisar si el endpoint que verifica los requisitos del estudiante, validen si este no se encuentra en estado de pérdida de calidad de estudiante.
- [x] Revisar si la calificación se da de la siguiente manera: 
- Trabajo de grado uno (1) reportada solo por el docente director, trabajo de grado dos (2) será el promedio aritmético de las calificaciones del director y evaluador. 

**Criterios de aceptación**

- [x] Se revisan cada uno de los ítems o subtareas indicando bajo un comentario en el issue que se encuentra en el sistema actualmente e indicar que ha de ser necesario para corregir el comportamiento del sistema.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se revisa si existe filtro por nivel de formación del estudiante y se verifica que si. Existe un endpoin hacia academica_jbpm en el que se indica el codigo del estudiante, año y periodo y este retorna información del estudiante y el tipo de carrera (ingenieria, tecnología, artes, etc)

**Comment by milo19980525** [comment]
Según lo informado por el ingeniero @diagutierrezro en la validación de requisitos se valida el estado del estudiante por lo que cabe aplicar nuevamente ese filtro en cada una de las solicitudes que vaya a realizar el estudiante no solo la inicial.
