### ISSUE TITLE
Corrección diagramas de flujo modalidad de materias de posgrado

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#351]
- [x] Con base en los requisitos funcionales levantados, corregir el mockup relacionado con la modalidad de materias de posgrado.
- [x] Documentar el issue con el link al mockup modificado en formato draw.io, pdf y png

**Comment by cearomeroc01** [comment]
Con base en la información y usuarios funcionales que se logro consultar se han relacionado los documentos que se indican a continuación:
- [Documento soporte en PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Ecl2JDI2wZ5CgA7Q0n8u5RkBw-ANk8z0VfjwLjC3qu2pMw?e=irGPFD)
- [Diagrama en formato de DRAW.IO](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Ee-fzLxlIg9Jm5sgKVDpOe8BfAN4m3qKc140_uHWgowD2Q?e=8wlcDI)
