### ISSUE TITLE
Ajuste HU Pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#353]
- [ ] Ajuste en las HU para el MVP de pólux con base en los ajustes realizados y la realimentación recibida por parte de decanaturas.

**Comment by cearomeroc01** [comment]
De acuerdo a los productos minimos viables que se estima entregar en una primera fase, a continuacion se relacionan las HU especificas a dichos productos:
- [Historias de usuario relacionadas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EY9PgS-vuQdCgMSOBCZBlJgBrTKvF2d7avVlPrFtfiv2RQ?e=jvSJlC)
