### ISSUE TITLE
Fase de revisión de evaluador de todas las solicitudes finales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#356]
Se requiere agregar fase para todas las modalidades que tienen revisor ().

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama develop, consecuente a los hallazgos corregidos en #349 .
- La lógica del negocio requerida para desarrollar el flujo de las pasantías se encuentra en: https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQRLbuudQ5RDsWOuvRObmc4B-F3ouUr6qGYGG64-cdV6yg?e=EpLWRl

1. [Diagrama de flujo](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQRLbuudQ5RDsWOuvRObmc4B-F3ouUr6qGYGG64-cdV6yg?e=EpLWRl)
2. [HU-3](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EY9PgS-vuQdCgMSOBCZBlJgBP8TybLRa7EHdgTV3HiUhlA?e=ZrjL9f)
3. [Mockup](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZgkfbu6uZxJoxKi_g31Y9YBpjUYS1a5eG21f2cC8839Cw?e=A28SMR)

**Sub Tareas**

- [x] Analizar el flujo definido para la evaluación final por parte del revisor.
- [x] Adicionar la evaluación del proyecto final como se hace con el director para que le pueda regresar documentos al estudiante y los pueda corregir.
- [x] Una vez corregidos el estudiante envía solicitud final, pasa por director y luego por evaluador, hasta que ya no existan más comentarios o se registren las notas.
- [x] Tomar como documento final el primer enviado o el último aprobado.

**Criterios de aceptación**

- [x] El usuario con rol docente asignado como revaluador o revisor, debe tener la posibilidad de verificar el documento y devolver con comentarios al estudiante.
- [x] En dado caso de ser rechazada la solicitud, esta debe aparecerle al estudiante para que sea modificada.
- [x] En dado caso de que la solicitud sea aprobada pasa a la fase de .

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Se sugiere modificar estas dos tablas del modelo, para que los comentarios sean los que se asocien a las páginas.
![image](https://github.com/udistrital/polux_cliente/assets/35748918/a9f15d47-05f6-4031-9b02-ffacbeab2f26)

**Comment by ludwinggsanchez** [comment]
- Director no puede registrar nota:

![image](https://github.com/udistrital/polux_cliente/assets/35748918/3c411b7c-0340-4196-a7d1-6a76e9951127)

- Evaluador puede registrar nota o devolver:

![image](https://github.com/udistrital/polux_cliente/assets/35748918/33618753-24d9-470f-859a-9d1b6549aecd)

- Corrección de evaluador puede consultarse en el módulo de revisión

![image](https://github.com/udistrital/polux_cliente/assets/35748918/65444d27-7650-45f2-9eb8-438ff30799f8)

- Director puede registrar nota si el evaluador ya lo hizo

![image](https://github.com/udistrital/polux_cliente/assets/35748918/9646c4a0-e6af-4e3b-a781-e5b5745ccc10)

**Comment by ludwinggsanchez** [comment]
Según [código](https://github.com/udistrital/polux_cliente/blob/ba056f1f08e39daf0bfc192206587c671feada9b/app/scripts/controllers/solicitudes/aprobar_solicitud.js#L1312) queda pendiente incluir la modalidad en el criterio para el flujo de aprobación de solicitud de revisión

**Comment by ludwinggsanchez** [comment]
Se verifican permisos para evaluador y director una vez se aprueba solicitud de revisión:

![image](https://github.com/udistrital/polux_cliente/assets/35748918/19d48a07-950b-4404-91bc-f2060115ff54)

**Comment by ludwinggsanchez** [comment]
Pendiente resolver despliegue polux crud. El log de prueba agregado en udistrital/polux_crud@675182a8d8920fd4ea3b2539017d929fbef20c02 no se ve reflejado.

**Comment by ludwinggsanchez** [comment]
Se confirma despliegue de polux_crud:

![image](https://github.com/udistrital/polux_cliente/assets/35748918/2670c1cd-f04b-4730-9fe3-e1bce5991712)

Se verifica funcionamiento en local y se determina listo para despliegue en ambiente de pruebas

**Comment by milo19980525** [comment]
Se probó el flujo y funciona correctamente!
