### ISSUE TITLE
Mockup revisor

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#360]
- [x] Revisar el flujo de las materias que tienen evaluador.
- [x] Realizar mockup sobre revisión de propuestas.

**Comment by cearomeroc01** [comment]
Se realiza la tarea especifica de revisión del flujo para el rol de REVISOR en las modalidades de TRABAJO DE GRADO que aplica, dado lo anterior se generan los siguientes soportes documentales:
- [Mockup draw.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ERmuOl0yXZdIkNxSfxp0GwABlL29zpEurlafz_mTiyaMKA?e=8i3WST)
- [Mockup PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZgkfbu6uZxJoxKi_g31Y9YBgKwgIWwrN6up_Ig8lPodZg?e=qc9JBa)
