### ISSUE TITLE
Ajustes transversales y parcialmente finales MVP

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#361]
Se requieren realizar los siguientes ajustes sobre el sistema pólux para dejarlo parcialmente listo para su MVP.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la feature manejada por @Mechaz123.

**Sub Tareas**

- [x] Realizar filtro para que personas de un nivel diferente de formación no puedan compartir una modalidad de trabajo de grado, basarse en #348.
- [x] Mostrar un mensaje u observación (nueva columna) en la verificación de solicitud final dónde le muestre al alumno si aprobó o reprobó cada una de las asignaturas (3.0 para pregrado y 3.5 para posgrado). Roles estudiante, docente y coordinador.
- [x] En cada una de las solicitudes realizadas por el estudiante validar su estado (que no sea inactivo o perdida de calidad estudiantil), si no no la puede realizar. Esta consulta es la misma de verificar requisitos por lo que es volver a llamar la petición.
- [x] En pasantía externa adicionar un campo en la solicitud inicial que permita subir documento soporte de persona externa (Persona empresa).

**Criterios de aceptación**

- [x] Se realizan los ajustes pertinentes en el sistema para que se satisfagan cada una de las subtareas.
- [x] Se documenta el issue con las soluciones proporcionadas y la evidencia de su funcionamiento.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se agrega la línea de código asociada a la verificación de requisitos para una solicitud cualquiera por parte del estudiante, con el fin de que esta verifique el estado del mismo.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/3887103e-fe0d-4ec6-a9ad-ed6c6411d6fa)

Queda pendiente la verificación del cambio, ya que no se dispone de un perfil con el cual se pueda probar dicha funcionalidad, para los casos de pérdida de calidad de estudiante y demás.

**Comment by Mechaz123** [comment]
Se desarrolla la funcionalidad asociada a la creación de un campo que muestre si el estudiante aprobó o desaprobó el trabajo de grado en base a su nivel, ya sea de pregrado (3.0) o posgrado (3.5).

![image](https://github.com/udistrital/polux_cliente/assets/73924638/00406ed6-3c41-40c8-887f-b400b41f8d92)

para este caso el estudiante pruebasoaspolux2 es un estudiante de PREGRADO, por lo cual aprueba.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/b91d6e85-d0d5-4868-b698-1ee6ecb4bf7f)

**Comment by Mechaz123** [comment]
Para la solicitud de "En pasantía externa adicionar un campo en la solicitud inicial que permita subir documento soporte de persona externa (Persona empresa).", ya existe un soporte en el cual se carga la carta de la entidad que designa al profesional responsable del acompañamiento, por lo cual no se realiza algún desarrollo con respecto a esta solicitud.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/794fb564-4a02-47b6-9215-46ce0870f41a)

**Comment by Mechaz123** [comment]
Se realiza el cambio asociado al nivel de "PREGRADO" donde la modalidad de "espacios académicos para posgrado" se evaluará bajo 3.5 y el resto de las modalidades se evaluará bajo 3.0.

Y para el nivel de posgrado todas las modalidades se evaluarán bajo 3.5

![image](https://github.com/udistrital/polux_cliente/assets/73924638/3b365734-0fc8-463f-a6e1-45091e8a997d)

**Comment by Mechaz123** [comment]
Se desarrolla la funcionalidad asociada al filtro según el nivel de formación, en caso de no encontrar al estudiante el sistema notificará que no encontró datos del estudiante.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/37233ccc-931b-4928-a6ba-daeebd679383)

En caso de poseer un nivel diferente de información entre los estudiantes, se desplegará un mensaje de alerta notificando este resultado.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/e536c852-1b13-48c9-99aa-610c56e56d11)
 
En caso de pertenecer a un mismo nivel de formación el sistema continuará con el proceso normal como se llevaba anteriormente.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/defdad6c-124f-466b-a067-6895aefcbd6a)

**Comment by Mechaz123** [comment]
Los cambios ya se encuentran subidos en ambiente de pruebas.
