### ISSUE TITLE
Revisión de método de autenticación

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#362]
Se requiere revisar el endpoint de ingreso a polux y cambiarlo a "getinfoByEmail".

**Especificaciones técnicas**

- El último desarrollo estable se encuentra en la rama develop.
- El swagger del API de autenticacion_mid se encuentra en: https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=autenticacion_mid&version=v1&provider=admin&tenant=carbon.super
- El endpoint a utilizar es: http://api.intranetoas.udistrital.edu.co:8110/v1/token/emailToken
- La variable del endpoint es: http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/periodo_academico/consulta_email/
- La consulta del endpoint es: 
SELECT MAX(EST_COD) CODIGO, EST_ESTADO_EST FROM ACEST INNER JOIN ACESTOTR ON EST_COD=EOT_COD INNER JOIN ACCRA ON EST_CRA_COD=CRA_COD INNER JOIN ACTIPCRA ON CRA_TIP_CRA=TRA_COD WHERE TRA_NIVEL='PREGRADO' AND EOT_EMAIL_INS=? AND EST_ESTADO_EST in ('A','E', 'T', 'H','J','B','L','O','V','Q') GROUP BY EST_ESTADO_EST

**Sub Tareas**

- [x] Revisar si el endpoint "getinfoByEmail" retorna la misma información que "userRole" en terminos de obtener proyectos curriculares activos con base en el mismo correo electrónico.
- [x] Identificar que bases de datos, esquemas y tablas consumen cada uno de esos dos endpoints, son los mismos o presentan algunas diferencias.
- [x] Realizar el cambio de método de autenticación en una nueva feature y realizar pruebas.

**Criterios de aceptación**

- [x] Se verifica la validez del endpoint "emailToken" y se documenta el issue.
- [x] Se comparan los endpoints "emailToken" y "userRole" y se documenta el issue.
- [x] Se evidencia el cambio del método de autenticación bajo la documentación del issue.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Las dos consultas realizan otras consultas hacia JBPM las cuales hacen consultas a la base de datos de academica que se encuentra en Oracle, si bien la petición "userRole" trae mas información como el nombre y documento del estudiante la petición "emailToken" trae la información necesaria para Polux.

Se realizaron las respectivas pruebas y el menú se consulta correctamente

**NOTA:** En caso de necesitar información adicional es necesario realizar una solicitud para modificar la consulta que se hace hacia JBPM para traer la otra información necesaria.

**Comment by diagutierrezro** [comment]
Se realiza el respectivo cambio en el codigo, sin embargo se deja comentareado ya que para desarrollo y pruebas se continuará usando "userRol" ya que los usuarios que se usan no tienen correos actualizados.
![image](https://github.com/udistrital/polux_cliente/assets/38676533/8278f254-e76a-465a-a173-087f493b0389)
