### ISSUE TITLE
Despliegue a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#371]
Se requiere realizar la salida a producción de todas las funcionalidades desarrolladas para el MVP de Pólux, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2 
- [x] Revisión y actualización de variables de entorno (D)
- [x] Pruebas funcionales (grupo de soporte) (D - correcciones realizadas por Daniel #397)
- [ ] Pruebas de carga, estrés y seguridad (líder de seguridad) (C)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo) (D)
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción) (C)
- [x] Revisión de estado de bases de datos (ETL) (D)
- [x] Revisión de actualización de APIs consumidas (terceros, transversales) (C, D - Parametros y documentos_crud)
- [x] Revisión de definición de roles y menús (D)
- [x] Definición y/o actualización de manual de usuario/videotutoriales (C, D)
- [x] Documento técnico (D)

**Comment by diagutierrezro** [comment]
Se revisan las variables de entorno del crud y del mid de POLUX:

- El crud unicamente tendría las variables de conexión hacia la base de datos  y las de despliegue del API, para este caso faltaría definir el puerto en el que se ejecutaría el API (parece ser 8108 pero se debe asegurar).
- El mid tendría las variables de conexión hacia el RULER y el crud de POLUX así como las variables para el despliegue del API como el puerto (parece ser 8109 pero se debe asegurar).

**Comment by diagutierrezro** [comment]
Se definen los siguientes menús para los respectivos roles del sistema
**ESTUDIANTE:**
-	Solicitudes
o	Listar solicitudes
o	Crear solicitud
-	Revisión de documentos
o	Revisión estudiante
-	Trabajo de grado
o	Consultar

**DOCENTES (director, codirector, evaluador)**
-	Solicitudes
o	Listar solicitudes
-	Revisión de documentos
o	Revisión docente
-	Trabajo de grado
o	Registrar nota
-	Pasantía
o	Actas de seguimiento

**COORDINADOR PREGRADO**
-	Solicitudes
o	Listar solicitudes
-	Trabajo de grado
o	Consultar

**COORDINADOR POSGRADO**
-	Solicitudes
o	Listar solicitudes
-	Materias de posgrado
o	Publicar asignaturas
o	Registrar Nota

**EXTENSIÓN PASANTIAS**
-	Solicitudes
o	Listar solicitudes

**Comment by milo19980525** [comment]
Se realizaron pruebas en reunión con el usuario sobre la modalidad de grado "Monografía", evidenciando el correcto funcionamiento y por lo tanto será la primera modalidad a probar en el MVP.

**Comment by diagutierrezro** [comment]
Los cambios que se deben realizar en las bases de datos son :

**ACADEMICA**
-	Agregar columna objetivo en la tabla trabajo grado
-	Crear la tabla detalle_trabajo_grado
-	(Agregar registro “Revisión docente evaluador” en tabla estado_trabajo_grado )
-	Actualizar registros de la tabla detalle (migrar datos)
-	Agregar registros del id 17 al 23 de la tabla estado_solicitud
-	Actualizar registros de la tabla modalidad (migrar datos), algunos cambiaron de nombre y se debe - Agregar el registro de pasantía interna
-	Agregar registro de solicitud de cambio de objetivos en la tabla tipo_solicitud
-	Agregar registro Coordinador posgrado en tabla rol_trabajo_grado


**PARAMETROS**

-	Actualizar registro de id 21 en la tabla area_tipo para que sea Polux
-	Agregar seis tipos de parámetros: Tipo Espacios Académicos, Enfoque Espacios Académicos, Clasificación Revista, Detalle Articulo Académico, Detalle Prorroga, Detalle Pasantía Externa.
-	Agregar parámetro “Empresa o razón social”, código abreviación EMPRZ_PLX
-	Agregar parámetro “Código CIIU”, código abreviación CIIU_PLX
-	Agregar parámetro “NIT”, código abreviación NIT_PLX
-	Agregar parámetro “Nombre Revista”, código abreviación NRVS_PLX
-	Agregar parámetro “Link Revista”, código abreviación LRVS_PLX
-	Agregar parámetro “Clasificación Revista”, código abreviación CRVS_PLX
-	Agregar parámetro “A1”, código abreviación A1_PLX
-	Agregar parámetro “A2”, código abreviación A2_PLX
-	Agregar parámetro “B”, código abreviación B_PLX
-	Agregar parámetro “C”, código abreviación C_PLX
-	Agregar parámetro “Justificación Prorroga”, código abreviación JPR_PLX

**Comment by diagutierrezro** [comment]
[Documento tecnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbJ-FyQnHu1IqMFJJg_1SpsBVO193db6c_rNPMBPD-tWkQ?e=g53B8R)

**Comment by Mechaz123** [comment]
Se adjunta el script para los parámetros nuevos, por favor revisar ya que los comentarios actualmente están de la siguiente manera "-- Insercion para parametros.area_tipo"

[Insercion parametros.txt](https://github.com/udistrital/polux_cliente/files/12768229/Insercion.parametros.txt)

Se adjunta en formato txt porque en SQL no permite cargar en github.

**Comment by Mechaz123** [comment]
Ya se encuentran las pruebas unitarias de Polux_mid.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/15f89252-b7b0-4fdd-a679-b5b78e812e93)

**Comment by milo19980525** [comment]
@Mechaz123 por favor revisar los parámetros que registro Juan Camilo asociados a pólux para adicionarlos al script que adjuntaste previamente.

**Comment by milo19980525** [comment]
Para esta tarea "Revisión de sincronización de bases de datos en ambientes (prueba y producción) (C)", @diagutierrezro por favor indicar que tablas no se deben sincronizar.

**Comment by diagutierrezro** [comment]
> Para esta tarea "Revisión de sincronización de bases de datos en ambientes (prueba y producción) (C)", @diagutierrezro por favor indicar que tablas no se deben sincronizar.

No se debe realizar sincronización de las siguientes tablas:
- areas_trabajo_grado
- asignatura_trabajo_grado
- carrera_elegible
- comentario
- correccion
- detalle_pasantia
- detalle_solicitud
- detalle_tipo_solicitud
- detalle_trabajo_grado
- documento_escrito
- documento_solicitud
- documento_trabajo_grado
- espacio_academico_inscrito
- espacios_academicos_elegibles
- estudiante_trabajo_grado
- evaluacion_trabajo_grado
- modalidad_tipo_solicitud
- respuesta_solicitud
- revision_trabajo_grado
- solicitud_trabajo_grado
- trabajo_grado
- usuario_solicitud
- vinculacion_trabajo_grado

**Comment by diagutierrezro** [comment]
Respecto a la tarea "Pruebas funcionales (grupo de soporte) (D - correcciones realizadas por Daniel https://github.com/udistrital/polux_cliente/issues/397)" se revisan los errores encontrados pertinentes a monografía y se encuentra que estos ya fueron solucionados (registro de comentarios en la revisión del proyecto, sección de documentos asociados a la solicitud que no debería de aparecer en algunas modalidades, respuesta a solicitud sin seleccionar ninguna de las opciones) se realiza una revisión de la solicitud de prorroga y se realiza un ajuste menor para que la justificación del rechazo por parte del docente sea obligatorio.

**Comment by diagutierrezro** [comment]
Se realiza la solicitud de actualización del swagger del API polux_crud, el swagger de polux_mid se encuentra actualizado

**Comment by Mechaz123** [comment]
Se realiza la comprobación de parametros usados en Pólux, como primer paso busca en area_tipo la sección de Pólux:

![image](https://github.com/udistrital/polux_cliente/assets/73924638/fac56d5d-4aeb-4ff1-a42b-ebeadf00998f)

Después de esto, se filtra mediante el campo de area_tipo_id para determinar que tipo_parametro esta asociado a Pólux

![image](https://github.com/udistrital/polux_cliente/assets/73924638/0160657b-6251-4640-a4ae-87c0a00fc4d1)

Y por último se realiza el filtro en parametro, para determinar los parametros asociados a Pólux, mediante le tipo parametro.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/dce66eed-b31f-4814-bdb6-16f1e2239c00)

**Comment by milo19980525** [comment]
Se realiza el registro de los parámetros en producción. Fue necesario cambiar los id de area_tipo y tipo_parametro en las relaciones según los id generados a la hora de la inserción en producción.

Por favor revisar @Mechaz123.

**Comment by milo19980525** [comment]
Respecto a la ejecución de migraciones se presenta un comentario sobre la segunda:

Buen día compañero, respecto a las migraciones, se ejecuta la 

[agregar_columna_objetivo_up.sql](https://github.com/udistrital/polux_crud/blob/release/0.0.1/database/scripts/20230615_190847_agregar_columna_objetivo_up.sql)
Se agrega comentario a la columna, por favor recordar que las columnas deben llevar siempre su comentario.
Se ejecuta satisfactoriamente
[crear_tabla_detalle_trabajo_grado_up.sql](https://github.com/udistrital/polux_crud/blob/release/0.0.1/database/scripts/20230712_011240_crear_tabla_detalle_trabajo_grado_up.sql) 
La tabla no cuenta con lineamientos (columnas activo, fecha_creacion, fecha_modificacion)
De no ser necesarios por favor justificar el motivo antes de proceder
[rechazo_sustentacion_up.sql](https://github.com/udistrital/polux_crud/blob/release/0.0.1/database/scripts/20230804_004057_rechazo_sustentacion_up.sql) 
Se ejecuta satisfactoriamente
Por favor revisar la observación de la segunda migración, esta queda pendiente.

@diagutierrezro porfa añadir los campos básicos para la tabla detalle_trabajo_grado

**Comment by diagutierrezro** [comment]
En el API de JBPM se debe ajustar el servicio de docente_tg en producción para que estos no se crucen con resoluciones

**Comment by milo19980525** [comment]
@diagutierrezro y @Mechaz123 se deben habilitar las condiciones relacionadas a:

- [ ] Un cambio de modalidad como máximo.
- [ ] Una vez digitada la nota bloquear solicitud de novedades.

**Comment by milo19980525** [comment]
@diagutierrezro por favor cambiar endpoint de autenticación para producción.

**Comment by diagutierrezro** [comment]
> Respecto a la ejecución de migraciones se presenta un comentario sobre la segunda:
> 
> Buen día compañero, respecto a las migraciones, se ejecuta la
> 
> [agregar_columna_objetivo_up.sql](https://github.com/udistrital/polux_crud/blob/release/0.0.1/database/scripts/20230615_190847_agregar_columna_objetivo_up.sql) Se agrega comentario a la columna, por favor recordar que las columnas deben llevar siempre su comentario. Se ejecuta satisfactoriamente [crear_tabla_detalle_trabajo_grado_up.sql](https://github.com/udistrital/polux_crud/blob/release/0.0.1/database/scripts/20230712_011240_crear_tabla_detalle_trabajo_grado_up.sql) La tabla no cuenta con lineamientos (columnas activo, fecha_creacion, fecha_modificacion) De no ser necesarios por favor justificar el motivo antes de proceder [rechazo_sustentacion_up.sql](https://github.com/udistrital/polux_crud/blob/release/0.0.1/database/scripts/20230804_004057_rechazo_sustentacion_up.sql) Se ejecuta satisfactoriamente Por favor revisar la observación de la segunda migración, esta queda pendiente.
> 
> @diagutierrezro porfa añadir los campos básicos para la tabla detalle_trabajo_grado

Se realiza la migración para agregar los campos requeridos según lineamientos en la tabla detalle_trabajo_grado.

Tambien se agregan estos campos en la tabla asignatura_trabajo_grado ya que son requeridos para los[ reportes solicitados.](https://github.com/udistrital/polux_cliente/issues/411)

**Comment by Mechaz123** [comment]
Se realizan las 250 pruebas unitarias al sistema pólux de manera que el sistema aprobó todas las pruebas realizadas en BASE a las Operaciones Básicas: GETALL, GETONE, POST, PUT y DELETE.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/bfd5de7b-26f7-4f30-bfee-f459f6f56a67)

**Comment by Mechaz123** [comment]
Se revisa que los parametros estén correctamente relacionados para el sistema Pólux.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/0b50d0ad-e95e-4c18-88e5-c7c721b960da)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/5bb433c2-437b-4a8f-ba03-23cf568f5c20)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/36eabd65-a1e7-463b-b08f-f6fb7be4839b)

**Comment by diagutierrezro** [comment]
Se realiza la corrección del listado de tablas que se deben migrar hacia producción, se debe solicitar la migración de las siguientes tablas.
- modalidad_tipo_solicitud
- detalle_tipo_solicitud

**Comment by milo19980525** [comment]
**Videotutoriales para Monografía:**

Codirector: https://youtu.be/V_u6rR17jLc

Coordinador: https://youtu.be/6b6IQe33f60

Docente director: https://youtu.be/bJj3uyiEWgs

Docente evaluador: https://youtu.be/k1ZxJyYR_V0

Estudiante: https://youtu.be/1I3wnUtpoT4

**Comment by milo19980525** [comment]
- [ ] Definir script de borrado de las tablas no paramétricas

**Comment by milo19980525** [comment]
> @diagutierrezro y @Mechaz123 se deben habilitar las condiciones relacionadas a:
> 
> * [ ]  Un cambio de modalidad como máximo.
> * [ ]  Una vez digitada la nota bloquear solicitud de novedades.

Por favor realizar estos cambios solicitados.

**Comment by milo19980525** [comment]
> @diagutierrezro por favor cambiar endpoint de autenticación para producción.

También aplicar este cambio

**Comment by Mechaz123** [comment]
Se realiza la activación de las restricciones para el registro de Nota y también para cambio de modalidad una sola vez, se prueba antes de subir a Master.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/be897528-d82c-4a58-964f-28eb900e05ae)

**Comment by milo19980525** [comment]
Diagramas de flujo generales del aplicativo: https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQRLbuudQ5RDsWOuvRObmc4B-F3ouUr6qGYGG64-cdV6yg?e=ke0rME

**Comment by milo19980525** [comment]
Se determina en la reunión con funcionamiento y gerente de proyectos que se debe:

- [ ] Agregar menú de reportes y enlace a knowage para los reportes.
- [ ] Agregar aviso de restricción de tamaño PDF y guardado del último documento en "Revisión documento"
- [ ] Ajuste documento técnico con matriz de roles.
