### ISSUE TITLE
Pruebas funcionales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#372]
Se requiere realizar pruebas funcionales del MVP de pólux.

Probar todo el flujo por cada una de las modalidades de grados posibles.

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama release/1.0.0, tanto para el cliente como para las APIs mid y crud.

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales de todo el sistema, de acuerdo con el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EWzX9i21lq5FtuB6Q88I0AkBMY3g5tc9WnIH0hawinWo0A?e=ajvzhL) dispuesto.
- [x] Corrección de errores o bugs encontrados, que no requieran gran dedicación para su corrección.
- [x] Listado de bugs o errores encontrados que requieran mayor dedicación para su corrección, con una descripción de su posible solución.

**Criterios de aceptación**

- [x] Todas las funcionalidades del sistema se encuentran probadas.
- [x] Los errores que presenta el sistema se encuentran detectados y listados para su corrección.

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- academica_jbpm
- gestor_documental_mid
- parametros_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas funcionales.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Errores o Bugs encontrados:

- Cuando se intenta aprobar o rechazar una petición, si no se selecciona una respuesta, el sistema directamente elige la opción de rechazar la solicitud.
- En varias modalidades al elegir la novedad de "Solicitud Director Trabajo de Grado", notifica que existe un error, ya que no hay campos con respecto a este tipo de solicitud.

**Comment by milo19980525** [comment]
Se debe tener en cuenta que se están almacenando tipos de documentos que no están siendo relacionados con registros de pólux o de otra API (documentos), por lo que posteriormente se debe llevar a cabo dicha interoperabilidad.
