### ISSUE TITLE
Correcciones salida a producción MVP

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#374]
Se requiere realizar las siguientes correcciones para salir a producción con el MVP de pólux:

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release, consecuente a los hallazgos corregidos en #346, #350, #343 #348, #356, #355 y #351.
- Los ajustes a realizar se basan en los comentarios expuestos en #372 

**Sub Tareas**

- [x] Ajuste de menús de **modalidad de posgrado**, ocultar aquellos que no se están utilizando actualmente en la modalidad.
- [x] En todas las solicitudes que llegan tanto al **director**, **coordinadores** y **evaluadores**, se debe mostrar una **alerta** "Debe seleccionar una opción de respuesta (Aprobar o Rechazar)" cuando **no se seleccione** la opción de **aprobar** o **rechazar**, dado que si no se selecciona ninguna rechaza la solicitud sin informar al usuario que pasó.
- [x] Ocultar de **todas las modalidadades** la solicitud "Solicirtud Director Trabajo de Grado" desde el rol **estudiante**, cuando el estudiante ya tenga en curso una modalidad.
- [x] En la modalidad de **pasantia interna y externa** quitar la sección de "Documentos asociados a la solicitud", dado que se están mostrando en "Detalles de la solicitud". Lo anterior para las fases de revisión de: **Director**, **Coordinador** y **Unidad de Extensión**.
- [x] Como novedades de solicitud una vez se encuentre en curso la modalidad de **espacios académicos de posgrado**, se tiene cancelación de trabajo de grado.
- [x] P**ara el registro de notas** en la **modalidad de Posgrado** se realiza el siguiente proceso: La coordinación de posgrado genera un documento (con las notas) y es pregrado quien sube la nota. Por lo tanto, la solicitud de registro de notas se realiza desde la coordinación de posgrado y se remite a la coordinación de pregrado (El estudiante solo puede cancelar la modalidad).
- [x] Ajustar que llegue la solicitud de revisión al apartado "Revisión de documentos" en el estudiante una vez se solicita una corrección por parte del docente revisor (No está llegando).
- [x] Permitir que aún así el revisor haya solicitado la revisión pueda registrar la nota, dado que puede suceder que un estudiante no corrigió y ya sustentó.
- [x] Las notas de las asignaturas deben ser: 
- Asignatura 1 - Nota de Director
- Asignatura 2 - (Nota de Director+Nota Revisor)/2

**[Correcciones visuales analista de requerimientos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EWzX9i21lq5FtuB6Q88I0AkBMY3g5tc9WnIH0hawinWo0A?e=ajvzhL)**
- [x] En todas las solicitudes relacionadas con **subida de documentos** colocar un aviso informativo sobre cuanto es el tamaño máximo soportado y la extensión (PDF). si el usuario sube un archivo de mayor tamaño o con otro formato debe salir una alerta especificandole "Formato no valido o tamaño máximo excedido".
- [x] En la creación de solicitudes de modalidades de grado desde 0 actualizar los avisos generales y de codirector de la siguiente manera:
Aviso general transversal a todas las modalidades:  Aviso actualizado a la normativa reciente: De acuerdo con lo establecido en el acuerdo N.°012 de 2022, seleccione este campo indicando si desea la inscripción de los espacios académicos correspondientes a Trabajo de Grado I y II en el mismo período académico. Tenga en cuenta que: La decisión sobre dicha inscripción es tomada por su proyecto curricular, examinando el contenido de esta solicitud y su situación académica actual; además, la coordinación de su proyecto curricular será quien se encargue de registrar él(los) espacio(s) académico(s) durante las fechas asignadas en el calendario académico.   

Aviso inferior Seleccione el docente codirector (Si no cuenta con uno por favor no seleccione ninguno)

- [x] #384

 Ingrese el nombre del director interno: 
Ingrese el número de documento del director interno: 
Cargue la carta de la unidad académco administrativa responsable del acompañamiento:

**Criterios de aceptación**

- [x] Las correcciones solicitadas se subsanan y se evidencia su implementación en el ambiente de release.
- [x] Se documenta el issue con las correcciones realizadas.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se verifica y el sistema ya contaba con la validación para subir un tipo diferente de documento.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/fc8f120e-7017-4a13-a702-aff934c938ad)

Se agrega un mensaje relacionado al aviso para la subida de documentos, especificando que sea solo PDF y un tamaño máximo aceptado.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/ba61ae24-2b50-4fae-b298-a760c441b244)

**Comment by Mechaz123** [comment]
Se actualizan los mensajes solicitados en base al nuevo acuerdo.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/eaade4bb-16d7-428e-b5c6-06159cadb95c)

**Comment by ludwinggsanchez** [comment]
Vista de comentarios hechos por el docente revisor

![image](https://github.com/udistrital/polux_cliente/assets/35748918/bbe9a920-a427-4f61-bfa2-c7054d78f6d2)

**Comment by diagutierrezro** [comment]
Para la asignación de notas actualmente se maneja consultando los proyectos de los que se es coordinador, al hacer el cambio hacia el registro de notas por parte de pregrado este coordinador no tendría proyectos de posgrado por lo que no aparecería una lista de proyectos a los que asignarle la nota, por esta razón se decide dejarlo como está actualmente donde el coordinador de posgrado es quien sube la nota de las asignaturas y estas se ven reflejadas en la sección de trabajo de grado del estudiante.

**Comment by diagutierrezro** [comment]
Se desarrolla la novedad de cancelación con el siguiente flujo:
- El estudiante realiza la solicitud describiendo el motivo.
- La solicitud llega directamente al coordinador de pregrado quien decide si aprobar o rechazar, escribe la justificación, carga la respectiva acta.
- Si la solicitud se rechaza el estudiante debe volver a realizar una solicitud inicial y si se aprueba pasa a ser revisada por el coordinador de posgrado.
- El coordinador de posgrada decide si aprobar o rechazar, si se rechaza vuelve al inicio todo el flujo y si se aprueba se asume que se inicia el desarrollo de la modalidad (el paso siguiente en POLUX sería el registro de la nota)

**Comment by diagutierrezro** [comment]
![image](https://github.com/udistrital/polux_cliente/assets/38676533/8bf95693-a30d-44ac-9002-eff8ec6c5a22)
En la materia 1 se pone la nota del director y en la materia 2 el promedio de los diferentes evaluadores que tenga

**Comment by ludwinggsanchez** [comment]
Se ajusta flujo de correcciones y registro de notas para las modalidades de innovación, monografía y emprendimiento

**Comment by Mechaz123** [comment]
Se realiza el cambio de los detalles nuevos para el director interno.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/f0dcb051-e0eb-4749-a9b5-0a06ee72d1ec)

Se deshabilita la sección de Documentos asociados a la solicitud.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/d5a763e5-7158-4ab7-becb-ae206cc2a684)

Se genera la alerta asociada a la selección de una respuesta a una solicitud.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/02c53e25-e11e-44fd-a598-78c445b68429)
