### ISSUE TITLE
Correcciones generales sobre pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#397]
Se requiere realizar las siguientes correcciones con base en la reunión con el usuario:

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release, consecuente a los hallazgos corregidos en #346, #350, #343 #348, #356, #355, #351 y #374.

**Sub Tareas**

- [x] Adicionar una novedad de solicitud de adición de prorrogra inicialmente para la modalidad de monografía. El campo que debe tener esta novedad son justificación, además de un aviso informativo que indique que _la solicitud se puede realizar por un máximo de 6 meses, en dado caso de ser aprobada, contará con ese tiempo para culminar el curso de la modalidad de grado_.
- [x] Adición de sección de aceptación de términos de curso de la modalidad de grado, tomando como base lo encontrado en el apartado en negrilla "Tengo conocimiento que para el presente trámite cumplo con los siguientes ítems:":
- Monografía: https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B04513DEA-D14D-4F57-A651-372B063486F6%7D&file=Monograf%C3%ADa.docx&action=default&mobileredirect=true
- Pasantía(s): https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B5EDB8F57-6D9E-4DAB-BA66-DFC227FE556E%7D&file=Pasant%C3%ADa.docx&action=default&mobileredirect=true
- Emprendimiento: https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B0F5DB3FE-BDFE-4DD8-A3EE-CB795BC8B325%7D&file=Proyecto%20de%20emprendimiento.docx&action=default&mobileredirect=true
- Materias de posgrado: https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BDA58B6A2-8A99-4375-BA6C-E69AEB424022%7D&file=Espacios%20acad%C3%A9micos%20de%20posgrado.docx&action=default&mobileredirect=true
- Investigación-innovación y creación: https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B67B4CC1D-08F6-49A8-AB75-A673AA45E13E%7D&file=Investigaci%C3%B3n-Investigaci%C3%B3n%20creaci%C3%B3n-Innovaci%C3%B3n.docx&action=default&mobileredirect=true
- Producción de artículos académicos: https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B0B7CF9E0-93CA-45A0-B403-F984F1B29364%7D&file=Producci%C3%B3n%20de%20art%C3%ADculos%20acad%C3%A9micos.docx&action=default&mobileredirect=true
- [x] En el cargue de los documentos de revisión y versiones del documento final, colocar un aviso informativo que indique que el sistema no almancena los documentos de las versiones, solo el último documento subido.
- [x] En la modalidad de pasantía externa, adicionar campos para registrar datos básicos de la empresa dónde se realizará la pasantía:
- NIT
- Nombre o razón social
- Código CIIU (código de actividad económica cámara y comercio).

**Criterios de aceptación**

- [x] Las correcciones solicitadas se subsanan y se evidencia su implementación en el ambiente de release.
- [x] Se documenta el issue con las correcciones realizadas.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se habilita la novedad de Prorroga y se desarrolla en el CRUD la lógica, ya que esta solicitud si existía desde antes, pero no guardaba en sí nada, además de esto se hacen los ajustes para que pase por cada uno de los roles especificados.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/8eb45e88-4c3a-4c57-bcc2-020738ca7f00)

Así mismo se realiza un cambio de manera general, que los detalles de la solicitud se muestren si estan activos o no, ya que este campo no tenía ninguna relevancia dentro de la base de datos.

**Comment by Mechaz123** [comment]
Se modifica el mensaje para los documentos subidos al sistema, especificando que el sistema no guarda documentos por versiones.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/1c13e86f-5038-4053-aa07-211816b75f2b)

**Comment by Mechaz123** [comment]
Se adicionan los campos solicitados para la solicitud inicial de la modalidad de pasantía externa.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/9fbe1c96-a9cb-4f3c-bca6-f83caf37cb5b)

Estos datos se almacenarán en la tabla detalle_trabajo_grado.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/5a010945-fcde-43bc-9d08-f6c8de27ff5f)

**Comment by Mechaz123** [comment]
Se agregan los campos de checkbox para cada una de las modalidades listadas en el issue, el mensaje cambiará según la modalidad seleccionada.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/f7b82c40-90ac-46f5-b45b-ae90513df4a4)

![image](https://github.com/udistrital/polux_cliente/assets/73924638/26e87469-d7b5-4a90-9296-6f92cfab0206)

Adicional a esto se agrega la validación para estos campos al momento de enviar la solicitud.

![image](https://github.com/udistrital/polux_cliente/assets/73924638/0891434c-7d36-45e4-82d2-568654ce7870)
