### ISSUE TITLE
Correccion de carga de notas por parte del codirector

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#406]
Se requiere realizar la siguiente corrección en todas las modalidades que pueden tener codirector.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release, consecuente a los hallazgos corregidos en #346, #350, #343 #348, #356, #355, #351 y #374.

**Sub Tareas**

- [x] Deshabilitar el ingreso de notas del codirector.
- [x] En el cliente al momento de resumir el estado total de la modalidad eliminar el apartado de nota reportada por el codirector o colocar un mensaje "No registra nota".

**Criterios de aceptación**

- [x] El codirector no puede registrar notas.
- [x] Se evidencia el aviso informativo en las tablas de registro de notas que indica que el codirector no registra notas.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Ya no se muestra el botón para que el docente codirector pueda entrar al modulo de registro de notas 
![image](https://github.com/udistrital/polux_cliente/assets/38676533/5ac1bfe5-effb-4667-ada2-b0c309457b88)

En el sistema ya se encuentra el mensaje indicando que el docente codirector no puede registrar notas 
![image](https://github.com/udistrital/polux_cliente/assets/38676533/2e1e84b6-2ab7-4d0d-8760-5ad8158ee9e6)
