### ISSUE TITLE
Reportes MVP pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#411]
Se requieren realizar los siguientes reportes en la herramienta Knowage para el sistema pólux con el propósito de terminar el desarrollo del MVP.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release, consecuente a los hallazgos corregidos en #371.

**Sub Tareas**

- [x] Aprendizaje de la herramienta de inteligencia institucional de la OATI (Knowage) de la mano del ingeniero Ludwing.
- [x] Análisis de los reportes requeridos por decanatura, definidos en: [Reportes Pólux](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/El3k9hTnnXRDghd4rTm0t6oBF3RzjerdXm-iRSZWeTS_mA?e=eBXsoa)
- [x] Creación de datasets requeridos para las consultas a utilizar por los reportes.
- [x] Creación del reporte: Reporte solicitudes iniciales
- [x] Creación del reporte: Reporte solicitudes aprobadas por coordinación y con revisor asignado
- [x] Creación del reporte: MODALIDAD DE PASANTÍA

**Criterios de aceptación**

- [x] Se evidencia conocimiento sobre la herramienta de Knowage.
- [x] Se crean los datasets requeridos para realizar los reportes (evidencia en el issue).
- [x] Se realizan comentarios asociados a dudas o aclaraciones frente a los reportes (opcional).
- [x] Los 3 reportes requeridos se desarrollan en la herramienta knowage.

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Despliegue en Knowage
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se realiza reunión junto con @ludwinggsanchez donde me realiza una explicación de la herramienta para realizar los reportes
![image](https://github.com/udistrital/polux_cliente/assets/38676533/a9b30683-2352-4611-b39e-2b7e992c2a5f)

**Comment by diagutierrezro** [comment]
Se realizan los reportes de solicitudes iniciales y solicitudes aprobadas por coordinación y con revisor asignado, los reportes se encuentran en la siguiente [carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/diagutierrezr_udistrital_edu_co/Ev--N-exgb9NlV5TNqcxv_wBHoJpv_C0MCjO3iP1Jx7GdA?e=tDvH0r).

**Comment by milo19980525** [comment]
@diagutierrezro Incluir documentación en el issue de los reportes funcionando en Knowage.

**Comment by diagutierrezro** [comment]
Reporte de solicitudes iniciales en Knowage
![image](https://github.com/udistrital/polux_cliente/assets/38676533/ebc5e9b7-34a5-4936-82bf-866c7e05ad43)

 Reporte solicitudes aprobadas por coordinación y con revisor asignado
![image](https://github.com/udistrital/polux_cliente/assets/38676533/ceb18e44-3a62-42a8-8d93-add766443cdb)
Se deja pdf generado por el sistema para una mejor visualización
[report.pdf](https://github.com/udistrital/polux_cliente/files/12930777/report.pdf)
