### ISSUE TITLE
Correcciones MVP

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#423]
Se requiere realizar los siguientes ajustes sobre producción para el MVP de pólux.

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama master, tanto para el cliente como para las APIs mid y crud.
- Las pruebas realizadas se encuentran en #416.

**Sub Tareas**
- [x] Ajuste de endpoint de consumo de Nuxeo directo para utilizar el gestor documental.

**Criterios de aceptación**
- [x] Ajustes realizados para garantizar que las correcciones fueron completadas.

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- academica_jbpm
- gestor_documental_mid
- parametros_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas funcionales.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se realiza el ajuste para detener el uso directo de nuxeo y mostrar los documentos asociados en el trabajo de grado.
![image](https://github.com/udistrital/polux_cliente/assets/38676533/76f33c20-4113-4444-893f-fcd324dfab61)
