### ISSUE TITLE
Mockups gestión de tiempos en pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#424]
Se requiere realizar los mockups de Pólux para la gestión de tiempos de solicitudes en el flujo de cualquier modalidad de grado.

- [x] Analizar cuales son los procesos que requieren una gestión de tiempos y quienes serían los responsables.
- [x] Diseñar una interfaz que permita al administrador de Pólux la gestión de tiempos en cada una de las solicitudes.
- [x] Diseñar una interfaz o mockup que evidencie la idea de notificaciones que le llegarían al usuario (Se sugiere sean por correo electrónico).

**Comment by milo19980525** [comment]
@cearomeroc01 por favor remitir avances de los mockups, gracias.

**Comment by cearomeroc01** [comment]
De acuerdo a la tarea asignada a continuación se relaciona el documento con los avances:
— [Tiempos modalidades](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Elifqe0wbKJIvN54d-19z04B1J8MPiWa7qeVsD64gf_cww?e=xEQPqM)
(en la respectiva carpeta se ubican documento en word con plantillas para correos, y mockup en formato draw.io)

**Comment by milo19980525** [comment]
Buen avance, queda pendiente el diseño de la interfaz para cambiar datos paramétricos.

**Comment by milo19980525** [comment]
Se relacionan las sugerencias sobre las plantillas de los correos.

**Comment by cearomeroc01** [comment]
De acuerdo a las observaciones realizadas y tareas, a continuación se relacionan:
— [Plantillas para correos v3](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ee0ilEE84p5Lls61G9dikFQBeXLItEw0BmS7jKLGX2m-yw?e=nvPpnA)
— [Mockup en formato draw.io del componente para la configuración y gestión de tiempos.](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EVVAIx_xvHVAvyk6ne5r8z8BE7nZCsUjHjANtogzR_FrQw?e=8VHfEq)
