### ISSUE TITLE
Documento Diagnóstico Final

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#450]
Se requiere realizar el documento final "Diagnóstico" para todos las funcionalidades desarrolladas y por desarrollar en Pólux.

**Especificaciones técnicas**

- El formato del informe diagnóstico se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcEzaU-TYfNMpdLTB7j9u5IB-pa9uKfFzPSdI-ANpHqThA?e=1l6H4s.

**Sub Tareas**

- [x] Con base en el formatos propuesto desarrollar el informe.

**Criterios de aceptación**

- [x] Se genera un diagnóstico final sobre los proyectos llevados a cabo en Pólux.

**Requerimientos**

- [X] Formato para desarrollar.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@diagutierrezro y @Mechaz123  por favor colocar el documento diagnóstico desarrollado en este issue

**Comment by Mechaz123** [comment]
Se adjunta el link del archivo para la revisión del documento:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbR36V7P2MtDjPHCJFV-ynUBM2Eao2V5gyXMTjAclBOOwg?e=r7nLla

**Comment by milo19980525** [comment]
@Mechaz123 y @diagutierrezro buen trabajo.
