### ISSUE TITLE
Preparación inducción a nuevos contratistas CPS de la OATI - Backend

### ISSUE THREAD

**Issue by milo19980525** [udistrital/polux_cliente#476]
Se requiere realizar una o las presentaciones que considere pertinente para la su socialización con el nuevo personal de desarrollo a ser contratado por la oficina.

**Especificaciones técnicas**

- El formato de las presentaciones se requiere en power point (mayor accesibildad desde one drive).
- Lineamientos de la OATI: https://github.com/udistrital/lineamientos_oas.

**Sub Tareas**

- [x] Desarrollar las presentaciones necesarias para abordar las siguientes temáticas: 
- Tecnologías usualmente utilizadas por la OATI (frameworks, lenguajes, versiones, dependencias)
- Líneamientos de manejo de versiones (manejo de comandos básicos de github)
- Generalidades de la infraestructura y arquitectura de la OATI (Comunicación entre APIs a través del protocolo HTTP, manejo de APIs MID, CRUD, su propósito, gestión de variables de entorno, inventario de Apis, Api store, entre otros)
- Generalidades de Golang y beego (componentes, conectores a BDs, manejo de peticiones HTTP, ventajas, desventajas, características principales e instalación).
- Ejemplo básico de API CRUD (controladores, helpers, manejo de conexión BD, manejo de variables de entorno, componentes).
- Ejemplo de clonación de un API CRUD con [base en la plantilla generada por brayan con Hygen](https://github.com/udistrital/plantilla_api_crud) o en dado caso de con un repositorio base (cumplidos_dve_v2, resoluciones_v2).
- Ejemplo básico de API MID (controladores, helpers, manejo de conexión BD, manejo de variables de entorno, componentes).
- Ejemplo de clonación de un API MID con [base en la plantilla generada por brayan con Hygen](https://github.com/udistrital/plantilla_api_mid) o en dado caso de con un repositorio base (cumplidos_dve_v2, resoluciones_v2).

**Criterios de aceptación**

- [x] Se generan las presentaciones requeridas y se domina el tema a presetnar.

**Requerimientos**

- [X] Formato para desarrollar (Libre elección, página de portada, agenda, colores pastel y con alto contraste).

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
- Se crea una [presentación ](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/diagutierrezr_udistrital_edu_co/EQeA5Y2VljhEmfupYlJVTCkBwicVa0rYg0Ozp1vse5I4zA) donde se indican las generalidades las APIs, Golang y Beego 
- Se crea una [presentación ](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/diagutierrezr_udistrital_edu_co/EXmDB1RCsndOpNib2Bxo21EBhihOlz6upO6bXR0u8Rti0w)en la que se explica el paso a paso para crear un API con los lineamientos de la OATI.

Se decide que la generalidades de infraestructura y arquitectura se explicarán mostrando en pantalla los diferentes puntos que componen estas generalidades (Store, gestión de variables de entorno, inventario de APIs, etc)

**Comment by milo19980525** [comment]
@diagutierrezro por favor realizar enunciado del ejercicio a realizar en word.

**Comment by diagutierrezro** [comment]
Se realiza el [enunciado ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/Ebno1uD4OthPpRA40XW2F9QB3MhF56Sj16KFtOtr18hPTA?e=bRz3SY)del ejercicio
