### ISSUE TITLE
Revisión de registro de nota por parte del docente evaluador.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#488]
Se requiere realizar la revisión al momento en el que el docente evaluador desea registrar una nota del trabajo de grado ya que actualmente cuando se presiona el botón este no realiza ninguna acción.

Hay que tener en cuenta que las transacciones que manejen deben apuntar hacia el api de parametros

**Sub Tareas**

- [x] Clonar los repositorios de Pólux 
- [x] Entender la lógica del sistema en ese punto del flujo.
- [x] Revisar por que razón el botón no realiza nada al presionarlo.
- [x] Probar el desarrollo que ya se encuentra realizado.

**Criterios de aceptación**

- [x] Evidencias de que se realizaron pruebas del desarrollo que ya se encontraba realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se clonaron los 3 repositorios del proyecto y se crearon las ramas feature en cada una

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/947157a5-46e5-4d73-b02a-788da06097ec)

**Comment by JuanDHernandezA** [comment]
Probando el desarrollo del servicio de registrar la nota por parte del Docente Evaluador, da como resultado el siguiente análisis:
- Al momento de registrar la nota a una monografía se hace una correcta petición al API mid de Polux, y se registra la nota en la base de datos 
![Captura de pantalla 2024-05-03 133413](https://github.com/udistrital/polux_cliente/assets/129443402/05523734-5347-4929-9987-572260813043)
![Captura de pantalla 2024-05-03 133425](https://github.com/udistrital/polux_cliente/assets/129443402/adb9ab87-af2b-45d1-a494-e357c2882287)
![Captura de pantalla 2024-05-03 140905](https://github.com/udistrital/polux_cliente/assets/129443402/9228772b-d3a6-41a0-bed1-e68a63f42de0)

- Cuando se da clic al botón de "Registrar Calificaciones" muestra la siguiente ventana de alerta, donde no se confirma si se ha registrado o no la nota. Además de no mostrar de forma correcta la información de "Modalidad" y "Estado"
![Captura de pantalla (84)](https://github.com/udistrital/polux_cliente/assets/129443402/f5dfc865-7c60-4096-b5e8-01ab0a697bec)

- De igual forma, al momento de seleccionar la opción para registrar la nota de la monografía, en la ventana no se puede visualizar  la información de "Modalidad" y "Estado". Pero ya aparece la nota registrada y no permite enviar una nueva calificación
![Captura de pantalla (86)](https://github.com/udistrital/polux_cliente/assets/129443402/59ca70c5-80b7-4bef-a7f8-102f059bbbec)

- Desde el perfil del Estudiante, ya se puede visualizar la nota registrada por el Docente Director
![Captura de pantalla 2024-05-03 133620](https://github.com/udistrital/polux_cliente/assets/129443402/df6b4ea4-d227-4c06-91f4-003a686a3165)

- Desde el perfil de Docente Director no se puede registrar una nota, esto se debe a que no ha cambiado el estado "revisión docente evaluador" al momento de subir la nota por parte del rol de Docente Evaluador
![Captura de pantalla 2024-05-03 141958](https://github.com/udistrital/polux_cliente/assets/129443402/62c2c586-e571-4081-8e78-f04fccdc5b23)
