### ISSUE TITLE
Revisión de comentario en docente evaluador.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#489]
Se requiere realizar el ajuste cuando el docente evaluador desea hacer comentarios ya que esta función aún apunta hacia el crud por lo que debe ser migrada hacia la transacción desarrollada en el mid.

**Sub Tareas**

- [x] Clonar los repositorios de Pólux.
- [x] Entender la lógica del sistema en este punto del flujo.
- [x] Modificar y ajustar el endpoint del cliente para que apunte hacia el mid.
- [x] Probar que la transacción que ya se encuentra desarrollada funcione correctamente y si no funciona dejar evidencias del error.

**Criterios de aceptación**

- [x] Endpoint modificado para que apunte hacie el mid
- [x] Evidencias de lo encontrado posterior al cambio del endpoint

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Clonar los Repositorios de Polux y Crear Rama de Feature

Polux_CRUD:
![Image](https://github.com/udistrital/polux_cliente/assets/65032868/4754960f-2e37-4942-903c-d924f10c2118)

Polux_MID:
![Image](https://github.com/udistrital/polux_cliente/assets/65032868/8ad914a2-cac2-466e-b733-2c4a92a39e90)

Polux_CLIENTE:
![Image](https://github.com/udistrital/polux_cliente/assets/65032868/41b558a8-77d9-4cfb-8266-a737898235ac)

**Comment by CrisEs2506** [comment]
SubTarea N°2: Entender la lógica del sistema en este punto del flujo.
1. Cuando se da al botón "Solicitar correcciones" devuelve el siguiente error:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/d2bb13ef-5c8d-4432-a511-66a0ccb98cef)

2. El error es el siguiente:

<img width="366" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/19118ae8-3177-4971-b342-6ee4aad94444">

Por lo que la consulta no se está realizando en el servidor de apioas - polux_crud

Nota: Esto solo ocurre para el Docente Evaluador con usuario 'pruebasoaspoluxadm'.

3. Al momento de ingresar un comentario para la corrección del trabajado de grado, el mensaje es el siguiente:

<img width="532" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/bee8d861-68ea-42b0-8b0b-66f7efe6c386">

4. Observando más a fondo vemos que la petición que se realiza es al polux_crud, pero dado que es una transacción (tr), esto no debería estar allí, si no por el contrario debería solicitarse al polux_mid:

<img width="302" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/25fc01dc-acbf-41ab-8232-d995d6ce06a7">

**Comment by CrisEs2506** [comment]
SubTarea N°3: Modificar y ajustar el endpoint del cliente para que apunte hacia el mid.

1. Apuntando hacía el MID a nivel local:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/6b3d48e3-ea6c-4e5e-8894-238134828334)

2. Apuntando hacía el MID del apioas/polux_mid:

<img width="365" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/177672a8-7795-442d-80dd-3a40c9976892">

**Comment by CrisEs2506** [comment]
SubTarea N°4: Probar que la transacción que ya se encuentra desarrollada funcione correctamente y si no funciona dejar evidencias del error.

El error que se encuentra es a nivel de polux_mid dado que aunque se logra hacer la petición, en su proceso arroja error, el cuál es el siguiente:

<img width="713" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/be0f90cb-a892-4bdf-905b-5eb5420727b7">

Dirigiendonos a los controladores del polux_mid, específicamente al archivo "tr_registrar_revision_tg.go" observamos que en la línea 28 al intentar decodificar (Unmarshal) el JSON, no se está consiguiendo convertir a la estructura esperada de Go. Este error se busca solucionar en el siguiente ISSUE.

<img width="632" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/012ad61b-b006-4382-bb01-f14e5896694e">
