### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión exploratoria con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#491]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado la reunión con el usuario el día 26/04/2024 

Con las siguientes personas :

                - Diego Gutierrez
                - Kevin López Cardenas
                - Cristian Antonio Escorcia Blanco


Todo el compilado y resumen de la reunión se encuentra en la siguiente acta.


[Acta](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWYJNKIXPZ1BootWO6lPuJUBw_a6k9nPzT2Bot6bAqytAg?e=IDzkMK)

**Comment by jcmurilloa** [comment]
Por favor adjuntar firmas al acta

**Comment by mantnicot** [comment]
Se adjunta el archivo de firma de la ACTA

[FIRMAS](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EYdFJkw-r8VCpmhObEaOV4IBZdDHJYY2_pNgmLtSdIuiQQ?e=rYUhTq)

**Comment by jcmurilloa** [comment]
Excelente trabajo
