### ISSUE TITLE
Construir diagrama de flujo según requerimientos del cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#492]
Se requiere realizar el 

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha actualizado el diagrama de flujo.

Se agrego el apartado de acta en aprobación con el usuario de coordinación y se agrega la solicitud de prorroga.


![Flujo de las modalidades polux 2024 ](https://github.com/udistrital/polux_cliente/assets/85162258/5085bff8-1a73-447a-b82b-5ce8a3dff7d3)


[LINK MODELO](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZnmSu6Qp_dCvEGj9wKCI-cBXCInuj-StjhftbrKgrDeUg?e=tvsIOG)

**Comment by jcmurilloa** [comment]
Definir flujo como anexo al plan piloto de pruebas que se comparte con el cliente

**Comment by mantnicot** [comment]
Se ha adjuntado el flujo a la carpeta de plan de pruebas piloto para el cliente.

[LINK DIRECTO DE LA CARPETA](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et2iUxCVkoJAtpjfX-ZbF3YBzIBQvtOL3xaWvvjjpLXM_w?e=P9VKuL)

**Comment by jcmurilloa** [comment]
El diagrama de flujo cumple con lo solicitado
