### ISSUE TITLE
Corrección del flujo para registro de comentarios del docente evaluador.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#494]
Se requiere realizar la corrección cuando el docente evaluador desea realizar un comentario al momento de registrar la nota según lo comentado en el issue  #489  .

**Especificaciones tecnicas**
- El último desarrollo estable del cliente, mid y crud se encuentra en la rama develop.
- En el API de [polux_mid](https://github.com/udistrital/polux_mid/tree/develop) se encuentra un desarrollo actual de la transacción que usa la funcionalidad de realizar un comentario por parte del docente evaluador.

**Sub Tareas**

- [x] Identificar el motivo por el cual se está generando error en el flujo actual.
- [x] Realizar los ajustes necesarios para que el docente evaluador pueda registrar una nota.
- [x] Continuar con la revisión del flujo una vez el docente evaluador pueda registrar un comentario.

**Criterios de aceptación**

- [x] Se realizan las correcciones necesarias para que el docente evaluador pueda realizar un comentario.
- [x] Se realiza la respectiva documentación tanto de los ajustes realizados como de la revisión del flujo que continúa posterior a la realización del comentario.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Identificar el motivo por el cual se está generando error en el flujo actual.

1. Al realizar click en "Enviar correciones" la petición se realiza a "polux_mid" pero este devuelve un error 400.
<img width="959" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4f357abd-2e42-464b-8399-e4fef95306cd">

2. Se observa que el error arrojado por parte de "polux_mid" es porque no se puede convertir el JSON suministrado a la estructura del modelo de Go. Viendo más a fondo en el código, se aprecia que en el modelo "VinculacionTrabajoGrado" especificamente en el campo "RolTrabajoGrado" se encuentra declarado como un entero, cuando en realidad debería ser un objeto del modelo "RolTrabajoGrado".
<img width="733" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/34341e38-a810-48a2-8807-22fc6e520921">
