### ISSUE TITLE
Corrección del registro de nota por parte del docente evaluador.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#495]
Se requiere realizar las correcciones necesarioas para realizar el correcto registro de nota por parte del docente evaluador, si bien según los comentado en el issue #488 ya permite el registro de nota, el estado del trabajo de grado y alguna información sobre el trabajo de grado no se modifica de manera correcta.

**Especificaciones tecnicas**

- El último desarrollo estable del cliente y crud se encuentra en la rama develop.
- Existe un desarrollo de la transacción utilizada en la rama [feature/cambios_parametros_registrar_nota](https://github.com/udistrital/polux_mid/tree/feature/cambios_parametros_registrar_nota) donde ya se encuentra una implmentación parcial de la transacción a corregir.

**Sub Tareas**

- [x] Identificar el motivo por el cual no se realizan todas las modificaciones necesarias al momento de realizar el registro de nota por parte del docente evaluador.
- [x] Realizar los ajustes necesarios para que la transacción del registro de nota por parte del docente evaluador se realice de manera correcta incluyendo los cambios de estado y la visualización correcta de la información del trabajo de grado.
- [x] Una vez corregidos los errores mencionados anteriormente probar el flujo posterior (registro de nota por parte del docente director)

**Criterios de aceptación**

- [x]  Se realizan las correcciones necesarias para que una vez el docente director registre nota se realicen todos los ajustes necesarios que permitan continuar con el flujo normal (cambio de estado y visualización de información)
- [x] Se realiza la respectiva documentación tanto de los ajustes realizados como de la revisión del flujo que continúa posterior al registro de nota del docente evaluador.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Revisando el desarrollo de la rama feature/cambios_parametros_registrar_nota se encontró que no está implementada la funcionalidad de 'actualizar el estado del trabajo de grado', por lo que una vez registrada la nota por el Docente Evaluador sigue con el estado de "Revisión docente evaluador" y no pasa a estado "Sustentado" para que el Docente Director pueda registrar la nota.

Adicional a esto, se encontraron errores forzados para verificar el flujo y que siempre registre las 2 notas sin necesidad de cambiar el estado del trabajo de grado y que el Docente Director registrara la nota. 

Se hicieron las respectivas correcciones de los errores encontrados y ya se puede proceder a desarrollar la funcionalidad de cambio de estado de trabajo de grado.

**Comment by JuanDHernandezA** [comment]
Evidencia de la corrección al error que al momento de registrar la nota por parte del Docente Director, no mostraba la información de  "Modalidad" y "Estado", en el cual se puede observar que no se actualiza el estado.

![image](https://github.com/udistrital/polux_cliente/assets/129443402/959355b7-1dba-41c5-9b9f-fe795bef9011)
