### ISSUE TITLE
Definir lista áreas de conocimiento con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#497]
Se requiere realizar el 

**Sub Tareas**

- [x] Establecer contacto con el cliente
- [x] Recepcionar lista de áreas de conocimiento
- [x] Revisión y definición de áreas de conocimiento

**Criterios de aceptación**

- [x] Lista de áreas de conocimiento

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha hablado con el cliente y ya se genero el correo de petición a las facultades


También se adjunta el oficio de rectoría en el cual se demuestra que el cliente ha sido designado como representante

[OFICIO](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehy6P1zym2ZEl8mcFDcDpNIB06fBoYK-rOVXjiMDOKLlZg?e=wczHA3)

**Comment by mantnicot** [comment]
Se ha dado entrega de las areas de conocimiento de parte del usuario.


Solo falta la entrega de parte de ingeniería Eléctrica


![image](https://github.com/udistrital/polux_cliente/assets/85162258/758c3c48-471a-4ebd-a0c7-9acbbd143d47)


[Listado Areas de conocimiento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EaCAK4ZIoR5EqgbrVjLAUZ4BGVDqCGXi4N0ajDvBveDWzw?e=akQjKF)

**Comment by jcmurilloa** [comment]
Pendiente áreas de conocmiento ing. eléctrica

**Comment by mantnicot** [comment]
Se ha comunicado con el cliente que el área de ingeniera eléctrica no ha podido realizar la gestión, el cliente comenta que insistirá

**Comment by mantnicot** [comment]
Se ha reunido con el cliente y todavía no ha recibido respuesta de ingeniería eléctrica

**Comment by mantnicot** [comment]
Se han recibido las areas de conocimiento de parte de ingeniería eléctrica


[Documento de areas de conocimiento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EaCAK4ZIoR5EqgbrVjLAUZ4BGVDqCGXi4N0ajDvBveDWzw?e=60asSm)

**Comment by jcmurilloa** [comment]
Muy buena gestión para con el cliente Cristian!
