### ISSUE TITLE
Definición y actualización manuales e instructivos Monografías

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#498]
Se requiere realizar el 

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [x] Generar el requerimiento de actualización de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se agrega los últimos manuales e instructivos que se realizaron por el equipo.

Videotutoriales y Manuales de usuario  

Video tutorial de Codirector para Monografía.  
Tipo: Video.  
Enlace: [https://youtu.be/V_u6rR17jLc](https://youtu.be/V_u6rR17jLc)

Video tutorial de Coordinador para Monografía.  
Tipo: Video.  
Enlace: [https://youtu.be/6b6IQe33f60](https://youtu.be/6b6IQe33f60 )

Video tutorial de Docente director para Monografía.  
Tipo: Video.  
Enlace: [https://youtu.be/bJj3uyiEWgs](https://youtu.be/bJj3uyiEWgs ) 

 

Video tutorial de Docente evaluador para Monografía.  
Tipo: Video.  
Enlace: [https://youtu.be/k1ZxJyYR_V0](https://youtu.be/k1ZxJyYR_V0 ) 

 

Video tutorial de Estudiante para Monografía.  
Tipo: Video.  
Enlace: [https://youtu.be/1I3wnUtpoT4](https://youtu.be/1I3wnUtpoT4 ) 

 

Carpeta de manuales de usuario 

Tipo: Documento.  

Enlace: [MANUALES DE USUARIO](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/diagutierrezr_udistrital_edu_co/Eloh6UpgOX1MsOgoNZ8c-CoBLNYd2TBRBfR-OyTYgGBw0A?e=OrEN5F)

**Comment by mantnicot** [comment]
Se ha revisado el instructivo del rol de estudiante y los demás roles , y se considera que funcionan para las pruebas piloto.

Es decir , que faltaría el realizar un manual más especializado en MONOGRAFIAS.

**Comment by mantnicot** [comment]
Se hablo con la persona encargada de rectoría con respecto a los manuales e instructivo y ella respondió que si se desea actualizar los manuales , lo ideal sería que ella debe actualizarlo.


Se realizará el proceso con ella para poder actualizar un MANUAL PARA MONOGRAFIAS.

**Comment by jcmurilloa** [comment]
Pendiente recepción y revisión de Manuales el 15 de mayo

**Comment by mantnicot** [comment]
Se agrega la actualización de carpeta con los manuales antiguos para generar trazabilidad de los cambios.

[CARPETA MANUALES ANTIGUOS](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErUpwg9xGAJJkyZhW14PmwABVq2uTWLLNyBm-TJvJwuJTA?e=2Fmdjz)

**Comment by mantnicot** [comment]
Se ha enviado el primer manual con respecto a los estudiantes, queda a espera de actualizar los pantallazos del sistema, pero se dejara así en pro de agilizar las pruebas piloto.


[Manual estudiante ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EodVHY13f2VBv-jP24Tbki4BnSMnPquvUyK1nNrauE9KSQ?e=jlz2e1)

Se queda a espera del manual de coordinador y docentes

**Comment by mantnicot** [comment]
Se ha dado entre de los manuales de docente y coordinador , se dejo a revisión los pantallazos de resto , aprobados

[carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EodVHY13f2VBv-jP24Tbki4BnSMnPquvUyK1nNrauE9KSQ?e=u68mzD)

**Comment by jcmurilloa** [comment]
Por favor Cristian alinear los nombres de los archivos para los tres manuales de usuario, que solo cambie del nombre según rol.

**Comment by jcmurilloa** [comment]
Pendiente actualización de imágenes de los instructivos.
