### ISSUE TITLE
Actualización y socialización plan de pruebas piloto

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#499]
Se requiere realizar el 

**Sub Tareas**

- [x] Actualizar plan de pruebas piloto
- [x] Enviar al equipo para aprobación
- [x] Socialización del plan piloto con el cliente

**Criterios de aceptación**

- [x] Plan de pruebas definivito 
- [x] Plan de pruebas piloto enviado al cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación 
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se esta realizando un revisión de las fechas de pruebas piloto puestas en la carpeta de las pruebas

[CARPETA DE PRUEBAS PILOTO](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Esmpoa92z2tCjemvacCNPWEBdFJN20v9L0lFN6uPk0SWiw?e=2zcUXq)

**Comment by mantnicot** [comment]
Se ha generado una carpeta nueva de pruebas piloto y se han actualizado las fechas y los links para los formatos de pruebas.


[Carpeta pruebas piloto ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EunCbncLh5ZGqYDgfd5DShgB3PM3iIWal_ZM71RE3A1a7g?e=bh99zk)

**Comment by jcmurilloa** [comment]
Ajustar el formato de pruebas hallazgos según obervaciones
Ajustar plan piloto de pruebas según observaciones

**Comment by mantnicot** [comment]
Se ha realizado la actualización de los formatos y documentos del plan de pruebas piloto.

[Documento plan de pruebas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ef1UHJTMsuZHql2De1AEkUsBiDAzbhkBHdgQreO3Gue1zw?e=fXeyZx)

[Pruebas de hallazgo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbzfO4XM9K5CgnVVO11m6gsB5GBxoQc28yrSBNIJuh1cTg?e=9xnfdk)

**Comment by jcmurilloa** [comment]
Muy buen trabajo Crsitian, esta pendiente por definir el canal de envío para la socialización del plan con el cliente

**Comment by mantnicot** [comment]
Por cuestiones de problemas con el sistema de IRIS, se ha enviado el primer comunicado con el cliente por Hotmail , se espera poder realizar los procesos a futuro por el sistema , después de la reunión creada para el día 23/05/2024

**Comment by mantnicot** [comment]
Se ha definido con el cliente con base a lo problemas en IRIS el envió de los comunicados serán por medio de correo , atravez del correo de computo

**Comment by jcmurilloa** [comment]
Muy bien trabajo Cristian, oportuna comunicación!
