### ISSUE TITLE
Diseñar el Mockup del apartado comentario en el momento de rechazar la monografía

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#500]
Se requiere diseñar el mockup para la vista del apartado comentario en el momento de rechazar la monografía. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo el mock definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Primera versión del mockup , a espera de muestra al equipo de desarrollo 

![Modulo de mejora en solicitud trabajo de grado drawio](https://github.com/udistrital/polux_cliente/assets/85162258/e8db4862-5172-4db5-8a66-d80b95925d50)

**Comment by jcmurilloa** [comment]
Refinar según observaciones realizadas por el equipo

**Comment by mantnicot** [comment]
Se han realizado los cambios propuestos por el equipo : 

1. Se a quitado el comentario predeterminado del campo
2. Se ha agregado un comentario para informar que el campo debe estar siempre sin importar si aprueba o rechaza

![Modulo de mejora en solicitud trabajo de grado v2  drawio](https://github.com/udistrital/polux_cliente/assets/85162258/944ee830-ac76-43d4-bf04-3dd199b9b141)

[Carpeta del mockup](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ev3NXnlbFT1Gn05J7YtcajkBoz3EVrGC4kZUdKAeQ1jdVg?e=6uGXak)

**Comment by jcmurilloa** [comment]
Excelente trabajo!
