### ISSUE TITLE
Corrección del cargue del documento por parte del docente director al registrar nota.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#502]
Se requiere realizar la corrección del cargue del documento al momento en el que el docente director desea registrar la nota del trabajo de grado y postreior a esta corrección realizar las siguientes pruebas del flujo del registro de nota para evaluar si el flujo siguiente funciona de manera correcta. 

**Sub Tareas**
- [x] Realizar la corrección del cargue del documento por parte del docente director al momento de registrar la nota según lo encontrado en el issue #504 .
- [x] Realizar las pruebas del flujo posterior al cargue del documento cuando el docente director va a registrar las notas.

**Criterios de aceptación**

- [x] Se realiza la corrección del cargue del documento por parte del docente director.
- [x] Se realizan las pruebas del flujo posterior al cargue del documento y se realiza la respectiva documentación en el issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
1. Se realizaron las correcciones a los errores encontrados en el issue #504, en donde la variable utilizada para enviar los IDs del documento y el trabajo de grado para insertar en la tabla documento_trabajo_grado aparecía como vacía.

- Se inicializa la variable con una referencia hacia el modelo de DocumentoTrabajoGrado, esto con el fin de que no fuera un elemento vacío y corregir la advertencia que no permitía el correcto flujo de la transacción.

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/fa9ede55-8a63-4dff-964a-9b1ef24390b2)

- Al momento de realizar la petición, podemos observar en la base de datos que ya almacenó el acta de sustentación:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/3d214fce-1e18-463b-ab0e-0c540a7bc34e)


- Y de igual manera, también se observa que el acta y el trabajo de grado están asociados en la tabla documento_trabajo_grado:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/9a69ea98-e985-43cc-83c4-379f0b9e1956)


2. Revisando el flujo de la transacción, al momento de registrar la nota por parte del Docente Director aún genera errores, esto debido a que no está desarrollada la funcionalidad para cambiar el estado de "Sustentado" a "Notificado a coordinación con calificación" 


![Image](https://github.com/udistrital/polux_cliente/assets/129443402/159cc5df-f1ae-410b-8d3e-e40128b7b2cf)
