### ISSUE TITLE
Analizar comentario de docente director al momento de responder una solicitud

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#503]
Se requiere realizar el analisis de las tareas a realizar para hacer el cambio al momento en el que el docente responde una solicitud este pueda agregar un comentario (tanto para aprobaciones como rechazos), esto teniendo en cuenta tambien la sección en la que el estudiante pueda visualizar este comentario.

**Sub Tareas**
- [x] Analizar tareas a realizar para que el docente realice comentarios al momento de dar respuestas y que estas respuestas se puedan visualizar.

**Criterios de aceptación**
- [x] Analisis y documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N° 1: Analizar tareas a realizar para que el docente realice comentarios al momento de dar respuestas y que estas respuestas se puedan visualizar.


1. Para que el docente director pueda responder a una solicitud debe dirigirse al menu "Solicitudes" del navbar y al submenú de "Listar Solicitudes", lo cuál lo lleva a la siguiente interfaz grafica:


<img width="549" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/b80760d6-a849-46a8-8c38-169a982c1598">


2. Al momento de dar responder solicitud (icono de check) nos redirige a la siguiente interfaz donde se puede observar la información de la solicitud, los detalles de la solicitud con su causa (comentario que realizó el estudiante) y el formulario de aprobación que es el apartado donde debemos enfocarnos para realizar la nueva feature, en este último encontramos un campo respuesta para seleccionar la opción de sí aprobar la solicitud o rechazarla.


<img width="549" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/2fd678fc-932c-4b4c-af3e-82a7dfb5ea04">


3. Analizando un poco la estructura de "polux_cliente" se ve que en la carpeta "app" dentro del archivo "app.js" encontramos el endpoint o url a la que apunta dicha interfaz grafica que es la siguiente "/solicitudes/aprobar_solicitud/:idSolicitud":


<img width="616" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f593f3b6-0d89-483f-a258-f04f07224bf8">


4. Vemos que la templateUrl se encuentra en la carpeta "views", subcarpeta "solcitudes" en el archivo "aprobar_solicitud.html" e inspeccionando un poco el frontend lo corroboramos:


<img width="959" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/5f35e9c1-d527-43e2-b634-530f471ed24b">
<img width="699" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/63a4535f-220c-4a1a-b75d-697b39b5c135">


5. Inicialmente se debería añadir el input para que el docente director pudiera realizar un comentario sobre la solicitud.

**Comment by diagutierrezro** [comment]
Muy buen analisis Cristian, gracias.
