### ISSUE TITLE
Proyectar comunicado lanzamiento de piloto en producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#506]
Se requiere realizar la proyección del comunicados de lanzamiento de piloto en producción

**Sub Tareas**

- [x] Proyección de los comunicados
- [x] Revisión por parte del líder del proyecto
- [x] Documentación de los comunicados

**Criterios de aceptación**

- [x] Comunicado de lanzamiento aprobado
- [x] Comunicado de punto proyectado
- [x] Comunicado final proyectado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada líder de proyecto.

**Comment by mantnicot** [comment]
Se ha realizado una consulta con Diana sobre como funcionaría el envió de los comunicados y se informo que se puede por el correo de computo.

Realizar un contacto con computo para planear el envió de la información.

**Comment by mantnicot** [comment]
Se ha realizado un total de 4 plantillas de comunicados por correo para las pruebas.

[Plantilla comunicados](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EXQzlbODYi5MovKvDnlfnDoBWoaTZGWXt5RA2sKNqMuw8w?e=4PiuUr)

**Comment by mantnicot** [comment]
Se ha generado el oficio correspondiente al primer envio de información sobre las pruebas piloto

![image](https://github.com/udistrital/polux_cliente/assets/85162258/da51e5e5-0ba3-437d-9e30-af6a6ea3cff8)


[OFICIO](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EUran_JT051Kp4ShSrMlEv8BOEhQ2ycm949hDIafd2RTmw?e=KFrNdO)

**Comment by jcmurilloa** [comment]
Se genera revisión y VoBo del comunicado de lanzamiento, para ser enviado por cómputo.
