### ISSUE TITLE
Analizar que está fallando en el flujo posterior al registro de solicitudes de corrección por parte del evaluador

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#507]
Se requiere realizar el analisis para encontrar el error en el flujo posterior cuando un docente evaluador realiza una solicitud de corrección dado que posterior a la corrección realizada en #494 el flujo no respondía de la manera esperada.

**Sub Tareas**
- [x] Realizar analisis del flujo posterior para encontrar error.
- [x] Documentar en este issue los errores encontrados.

**Criterios de aceptación**
- [x] Pruebas del flujo realizadas.
- [x] Errores documentados.

**Dependencias**
Se requiere que el API ruler_api se despliegue de manera correcta ya que actualmente se encuentra caida.

**Requerimientos**
No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Realizar analisis del flujo posterior para encontrar error.**

1. Al registrar un comentario sobre el trabajo de grado por parte del docente evaluador, la petición se realiza correctamente, como se evidencia en la siguiente imagen:


![image](https://github.com/udistrital/polux_cliente/assets/65032868/0fa2d7e7-3278-41aa-ab3b-295f6f68a55b)

2. Sin embargo, se observa que por alguna razón al momento de volver a listar los trabajos de grado por parte del docente evaluador, el trabajo al que se le realizó el comentario pierde el contenido de "nombre" y "modalidad": 


<img width="512" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/dd747d75-6597-4902-846b-6b986249d64b">  


<img width="518" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/abce7f3f-a182-4e8f-9573-7e576dbc947a">

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Documentar en este issue los errores encontrados.**
1. Dentro del helper "tr_registrar_revision_tg" en su función " AddTransaccionRegistrarRevisionTg" el cuál recibe como parametro el objeto "transaccionRechazo" que se envía desde el cliente, observamos que las líneas encargadas de realizar el "PUT" o actualización a la base de datos busca enviar todo el objeto "TrabajoGrado", no obstante el objeto "transaccionRechazo" solo está enviando el "Id" por lo que falta agregar los campos faltantes.


<img width="725" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/eff71477-73bd-4e01-a8a3-01dcfcc9ad43">  


<img width="677" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e76fbbde-43a9-450d-a045-98851e6e9aa3">
