### ISSUE TITLE
Finalizar desarrollo de la transacción para registro de nota por parte del docente director

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#509]
Se requiere realizar la finalización del desarrollo de la transacción para que el docente director pueda realizar el respectivo registro de la nota y el trabajo de grado cambie de estado correctamente, una vez realizados estos cambios realizar las respectivas pruebas de manera local.

**Sub Tareas**
- [x] Finalización del desarrollo de la transacción para registro de nota por parte del docente director.
- [x] Desarrollo para cambio de estado correcto una vez el docente director registra nota.
- [x] Pruebas realizadas (probar flujo completo con registro de nota por parte de los dos docentes)

**Criterios de aceptación**
- [x] Desarrollos finalizados.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Revisando el código desarrollado, al momento de registrar la nota por parte del docente director se tiene que se actualizan las notas de las asignaturas del trabajo de grado, pero se encontraron los siguientes errores:

1. La consulta para hacer el cambio de estado de "Cursando" a "Cursado" en las asignaturas no es correcta:

![image](https://github.com/udistrital/polux_cliente/assets/129443402/be513739-daa9-4fc4-ace9-4bb1ffa111e1)

- Se hace la corrección de la consulta y ya cambia el estado de las asignaturas como se observa en la imagen del siguiente error

2. Al momento de poner las notas en las asignaturas, en la materia 1 no registra la nota del docente, lo que provoca que aparezca la asignatura como reprobada

![image](https://github.com/udistrital/polux_cliente/assets/129443402/30c9f321-db3b-406a-ae51-498c7dd3af46)

- Revisando el código, al momento de buscar el tipo de vinculación al trabajo de grado por parte de los docentes para identificar al Docente Directo, no lo encuentra porque solo recibe el id de la vinculación.
- Se corrige haciendo una consulta a la tabla vinculacion_trabajo_grado filtrando por el id que ya se tenía, y se obtiene el tipo de vinculación del docente director para agregar la nota de forma correcta
![image](https://github.com/udistrital/polux_cliente/assets/129443402/65c6d9d3-ea78-43e9-8d2a-e057987bc491)

Con estos errores corregidos, se puede continuar con el desarrollo del cambio de estado del trabajo de grado

**Comment by JuanDHernandezA** [comment]
Se agrega la funcionalidad para cambiar el estado del trabajo de grado una vez el docente director ingresa la nota, en la siguiente imagen se puede observar que ya queda registrado el nuevo estado de "Notificado a Coordinación con calificación"
![Captura de pantalla 2024-05-16 115417](https://github.com/udistrital/polux_cliente/assets/129443402/9d2f7068-d601-4dd7-b90f-551f64491030)

**Comment by JuanDHernandezA** [comment]
- Realizando las pruebas, al momento de probar los rollback de la transacción, se observa que hay un error cuando se intenta eliminar el registro de documento_escrito:
![Captura de pantalla 2024-05-16 123355](https://github.com/udistrital/polux_cliente/assets/129443402/49f0f443-5a0f-4717-b089-fea369c28b02)

Este error se genera debido a que al momento de enviar la petición DELETE del registro en la tabla documento_escrito, el ID del registro se usa como llave foranea en la tabla documento_trabajo_grado, por lo que se arregla el error llamando primero a la función rollback de documentoTrabajoGrado para que no exista conflicto al momento de eliminar el documento escrito

- Se agrega el rollback para devolver el estado inicial de las asignaturas antes de realizar la transacción, por lo que se almacena el estado y la fecha de modificación de las asignaturas en unas variables, las cuales se llamarán en la función del rollback de las asignaturas y se envirán al crud para volver a actualizar a su estado inicial:
![Captura de pantalla 2024-05-17 132456](https://github.com/udistrital/polux_cliente/assets/129443402/fa83499f-8c42-4662-a73b-6fd90f66e924)

Se prueban la funciones y se observa que las asignaturas vuelven a su estado inicial y los registros del acta de sustentación son eliminados de forma correcta.

**Comment by JuanDHernandezA** [comment]
Probando el flujo de la solicitud de revisión trabajo de grado:

- Una vez el estudiante haya solicitado la revisión y esta haya sido aprobada por el docente director y la coordinación, el docente evaluador procede a subir la nota:

![image](https://github.com/udistrital/polux_cliente/assets/129443402/0cbade6a-f64c-402b-851e-4112fa9a85a5)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/0acd447b-2755-4b80-8bdd-a7f5f3498c28)

Se puede observar que la nota se registra de manera correcta y el estado del trabajo de grado pasa a "Sustentado"

- Ahora el Docente Director puede calificar la monografía:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/5a91410f-fc35-450c-ba0a-11325fcd4047)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/287c805f-33ff-48c1-9123-f7bf95f12acb)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/26d18e72-6802-47c2-9a11-c271ef2d799d)

De igual manera, se puede observar que el estado del trabajo de grado cambió a "Notificado a coordinación con calificación" una vez registrada la nota

- Desde el perfil del estudiante podemos observar el resumen de las calificaciones:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/722bbebc-067e-4f2b-b905-03d945619506)

En este resumen podemos observar las notas ingresadas por los docentes vinculados, las asignaturas con el estado "Cursado", la asignatura 1 con la nota del Docente Director, la asignatura 2 con el promedio de las 2 notas y ambas con la anotación de aprobado.
