### ISSUE TITLE
Corrección al momento de solicitar correcciones por parte del docente evaluador

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#510]
Se requiere realizar la corrección del flujo cuando el docente evaluador realiza un comentario según lo encontrado en #507 para que no desaparezca la información del trabajo de grado una vez se realiza el comentario.

**Sub Tareas**
- [x] Realizar corrección del flujo al solicitar las correcciones por parte del docente evaluador.
- [x] Probar el flujo posterior a la solicitud de correcciones para comprobar que el sistema funciona correctamente.
- [x] Documentar las pruebas realizadas y los errores en caso de encontrarlos

**Criterios de aceptación**
- [x] Corrección realizada.
- [x] Pruebas realizadas y documentadas en el issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N° 1:  Realizar corrección del flujo al solicitar las correcciones por parte del docente evaluador.**
1. Ubicandonos en "polux_cliente", en el archivo "registrar_nota.js" de la carpeta "controllers", especificamente en la función de "ctrl.registrarCorreciones" vemos que se realiza una copia del objeto "VinculacionTrabajoGrado" y se observa que el objeto "DocumentoTrabajoGrado" posee como subobjeto a "TrabajoGrado" con todos los atributos correctos, por lo que se asigna este subobjeto a la copia del objeto inicial que se llama "vinculacionModificada" en el campo "TrabajoGrado" con el fin de que este espacio no se rellene únicamente con el "Id" si no con todos los atributos faltantes y que de esta manera se solucione el error comentado.
<img width="513" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4d7968a8-2c7c-44e9-bff7-6f2bbc64986b">

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Probar el flujo posterior a la solicitud de correcciones para comprobar que el sistema funciona correctamente.**
1. Se crea una nueva revisión y el docente evaluador puede hacer los comentarios correctamente:
<img width="919" alt="Pasted image 20240515092311" src="https://github.com/udistrital/polux_cliente/assets/65032868/9bad6e3d-130e-4ec9-b65a-bbf2ba118cdc">


2. Luego de la corrección, observamos que el objeto "transaccionRechazo" se está enviando de manera correcta con todos los campos necesarios para guardarse en la base de datos:
<img width="921" alt="Pasted image 20240515092956" src="https://github.com/udistrital/polux_cliente/assets/65032868/d96f0931-2867-47a9-8c12-8fa53df7f007">


3. Finalmente al momento de listar los campos que antiguamente faltaban, ahora se realiza de manera correcta, como se evidencia en las siguientes imagenes:
<img width="498" alt="Pasted image 20240515014607" src="https://github.com/udistrital/polux_cliente/assets/65032868/27075276-4419-4a19-a891-01531f12584c">
<img width="504" alt="Pasted image 20240515014705" src="https://github.com/udistrital/polux_cliente/assets/65032868/b24e01c7-d4f8-4a14-9368-bb5038f6a09d">

**Comment by CrisEs2506** [comment]
**SubTarea N°3: Documentar las pruebas realizadas y los errores en caso de encontrarlos.**
1. Se observa que la actualización en la base de datos "udistrital_core_db" especificamente en la tabla "trabajo_grado" se está realizando correctamente como se muestra en la siguiente imagen:
<img width="797" alt="Pasted image 20240515094513" src="https://github.com/udistrital/polux_cliente/assets/65032868/c725af20-5e2f-47bc-9b43-4fa277e04a10">

2. En el apartado de revisión deocumentos del estudiante, observamos que se está listando de manera efectiva, lo que garantiza que el estudiante sí puede revisar los comentarios que se realizaron por parte del docente evaluador para que de está manera sepa que debe corregir:
<img width="499" alt="Pasted image 20240515094812" src="https://github.com/udistrital/polux_cliente/assets/65032868/df9a2e93-98e8-44c4-9354-4856bb79db98">
