### ISSUE TITLE
Ajuste de registro de objetivos al momento de crear el trabajo de grado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#512]
Se requiere realizar la revisión y ajuste para registrar los objetivos del trabajo de grado ya que actualmente estos objetivos no se registran una vez el coordinador del proyecto curricular aprueba el trabajo de grado.

**Sub Tareas**

- [x] Revisar y realizar los respectivos ajustes para que se registren los objetivos una vez el coordinador apruebe la solicitud inicial.
- [x] Realizar pruebas de solicitud de cambio de objetivos para confirmar que el error encontrado en #496 se corrige agregando los objetivos.
- [x] Documentar los cambios y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajustes que permitan el registro de objetivos.
- [x] Pruebas de solicitud de cambio de objetivos realizadas.
- [x] Documentación al issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Revisando el código de la transacción de Solicitud, en el modelo de TrabajoGrado se observa que no se tiene el atributo de Objetivo, por lo que se añade para revisar el comportamiento del flujo con este cambio


![Image](https://github.com/udistrital/polux_cliente/assets/129443402/baa50db9-a561-4e20-8407-4aa547d63b61)


El flujo ya permite registrar la solicitud de "Cambio de objetivos" por parte del estudiante, donde se puede observar que ya se envían los dos objetivos al momento de enviar la solicitud

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/0962e517-8d09-4a57-ac05-00a13d65912f)

Al momento de listar las solicitudes del Docente Director no aparece dicha solicitud. Se revisa el código y en el arreglo de tiposSolictud del cliente no está agregada la abreviación de la solicitud de "Cambio de objetivos" (SCO_PLX), por lo que se agrega para que pueda listar este tipo de solicitud.

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/cf6b130e-5edf-43fc-b9a6-e01914352519)

Se vuelve a probar listar las solicitudes y ya aparece la solicitud del cambio de objetivos. Se continua con el flujo hasta llegar a aprobar dicha solicitud por el coordinador del proyecto curricular, en donde se observa que el cambio se hace de manera correcta:



![Image](https://github.com/udistrital/polux_cliente/assets/129443402/f669ab96-b6c3-44ef-943e-0b847efb1dd7)
