### ISSUE TITLE
Desarrollo de funcionalidad para que el docente evaluador pueda registrar comentarios al responder una solicitud.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#513]
Se requiere realizar el desarrollo de la funcionalidad analizada en # para que el docente evaluador pueda registrar comentarios justificando su respuesta cuando responde alguna solicitud, una vez se realice la implementación realizar las respectivas pruebas. Tener presente la visualización de dicha respuesta que da el docente director.

**Sub Tareas**

- [x] Desarrollo de funcionalidad para poder registrar comentarios.
- [x] Pruebas del desarrollo de la funcionalidad (tener en cuenta la visualización de la respuesta).
- [x] Documentación del desarrollo y pruebas realizadas.

**Criterios de aceptación**

- [x] Desarrollo de funcionalidad realizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Desarrollo de funcionalidad para poder registrar comentarios.
1. Se agrega funcionalidad al formulario de aprobación para que independientemente de si se elige la opción de "Aprobar solicitud" o "Rechazar solicitud" aparezca el "text-area" para que el docente director redacte su justificación de la respuesta o decisión tomada.


<img width="781" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/505a0c16-38f1-4638-82c9-3163493614b6">

![image](https://github.com/udistrital/polux_cliente/assets/65032868/b48fd396-e493-494e-9cf1-98a91fd7885b)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/403702f1-dcdf-4508-8236-81a205619118)

2. Se agrega la funcionalidad para que cuando haya contenido en el espacio de la justificación, se habilite el respectivo botón para enviar el formulario:


<img width="793" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/737f578b-b3a0-4246-883c-b8ec021e4a2e">

![image](https://github.com/udistrital/polux_cliente/assets/65032868/6c39e0e6-2bbd-4582-b962-e39deb563b34)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/e5869b02-f30c-4cd2-9d73-b3069015ba34)


3. Se modifica el código del controllador "aprobarSolicitud" en su función "RespuestaDocente" para registrar la justificación que se coloca en el "text-area" y que se arme de manera correcta el payload para enviarlo con la petición Put, cuando se "Aprueba solicitud":

<img width="736" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4f6a14d5-458a-46fa-8081-fa5c5f9dd9f4">


4. Se modifica el código del controllador "aprobarSolicitud" en su función "RespuestaDocente" para registrar la justificación que se coloca en el "text-area" y que se arme de manera correcta el payload para enviarlo con la petición Put, cuando se "Rechaza solicitud":


<img width="618" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f65f7e9a-802a-4c99-9f53-12766a82d3ac">

**Comment by CrisEs2506** [comment]
SubTarea N°2: Pruebas del desarrollo de la funcionalidad (tener en cuenta la visualización de la respuesta) y SubTarea N°3: Documentación de las pruebas realizadas.

Aprobar Solicitud:

1. Se crea la solicitud de Monografía por parte del Estudiante:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/36f96851-096d-4f2c-868a-e7cd02afa14f)

<img width="598" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/6e984a1a-1b8d-4509-b539-36d3ef6701d5">

2. Aprobar la Solicitud por parte del Docente Director:

<img width="636" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/ba902e8a-0606-4297-b89c-780cab47054e">

<img width="959" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/8958a7fd-b3c4-40f7-a660-5f35509b2900">

3. Listar solicitudes por parte del Estudiante y ver los detalles de la solicitud de Monografía que fue aprobada:

<img width="330" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/9f921990-941c-49da-967c-482b6bb65c5a">

4. Listar solicitudes por parte del Coordinador y ver los detalles de la solicitud de Monografía que fue aprobada por el Docente Director:

<img width="499" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/26dee3c6-aa09-4309-98e4-aeedfb8bf6d6">


Rechazar Solicitud:

1. Se crea la solicitud de Monografía por parte del Estudiante:

<img width="596" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/11bf137f-1a33-48b1-a438-8295463b20ca">

<img width="598" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/6ca28774-087f-4147-803f-8185cdf0f195">

2. Rechazar la Solicitud por parte del Docente Director:

<img width="627" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/5c9c67d5-a116-474c-b39f-5fccecc8306f">

<img width="959" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4bff88a3-e837-456b-8e02-d60559a6de0b">

3. Listar solicitudes por parte del Estudiante y ver los detalles de la solicitud de Monografía que fue rechazada:

<img width="403" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/85f6431d-a5ea-46a3-8bfa-a6ca3f8d3082">

**Comment by diagutierrezro** [comment]
Falta por aprobar el PR, buen trabajo Cristian.
