### ISSUE TITLE
Analizar implementación para guardar documento de solicitud inicial 

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#514]
Se requiere realizar el análisis de la implementación para guardar el documento inicial que se envía al momento de realizar la solicitud inicial ya que se requiere que este documento se guarde como anteproyecto, para esto se debe analizar principalmente la parte tecnica iniciando en el manejo hacia bases de datos y continuando el flujo hacia el mid y cliente.

**Sub Tareas**
- [x] Análisis sobre tareas a realizar para llevar a cabo la implementación.
- [x] Documentación sobre este análisis realizada.

**Criterios de aceptación**
- [x] Análisis realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se obtuvieron los siguiente resultados del análisis:

1. Revisando en la base de datos la tabla en donde se almacenan todos los documentos asociados a los proyectos de grado, se encontró una columna llamada *tipo_documento_escrito*. 
 
![image](https://github.com/udistrital/polux_cliente/assets/129443402/5da31ebb-5896-44e2-91d4-649921fff161)

- Se buscaron los tipos de documentos en los parámetros y se clasificaron por dominios. Se buscaron aquellos asociados con Polux, obteniendo los siguientes resultados:

![image](https://github.com/udistrital/polux_cliente/assets/129443402/d230b8e0-7ffc-498a-bf47-14e813230ba7)

![image](https://github.com/udistrital/polux_cliente/assets/129443402/61f17161-d1d7-409c-b0bf-fe08fa6de94c)


- En el resultado se observa que no existe un tipo de documento para el anteproyecto de un proyecto de grado.

Se propone agregar un nuevo tipo de documento para identificar los anteproyectos de las modalidades de grado.

2. Revisando el código en donde se asocia el tipo de documento de grado con el documento cargado por el estudiante, se encontró que esto se realiza desde el cliente.

![image](https://github.com/udistrital/polux_cliente/assets/129443402/16c85c49-63e5-4aa1-9b27-47c64a29516b)

- Adicionalmente, se encontró que en los controladores de revisión de documentos, para traer el documento a revisar se usa el tipo 'DTR_PLX', lo que podría causar conflictos si se almacena el documento de la solicitud inicial con el tipo Anteproyecto.

![image](https://github.com/udistrital/polux_cliente/assets/129443402/2aa7dac1-d53b-4db3-b7aa-928d984807a0)


Se propone implementar en la transacción *tr_respuesta_solicitud* la funcionalidad de guardar dos copias del documento adjuntado por el estudiante: una como Anteproyecto y otra para realizar las revisiones por parte del Docente Director.

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego, el desarrollo se realiza en otro issue.
