### ISSUE TITLE
Revisar para actualización documento técnico Pólux junto a casos de soporte

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#515]
Se requiere realizar el 

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [x] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
[Documento tecnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/Ea_cHccVI5JCuq6SAlA6tq4BvH0HKc8ay1nnUw2MbfpMzA?e=TOeCg4)

**Comment by jcmurilloa** [comment]
Muy buen trabajo!
