### ISSUE TITLE
Asignar los roles a usuarios del plan piloto de pruebas

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#516]
Se requiere realizar la asignación de los roles a usuarios que desarrollarán el plan piloto de pruebas

**Sub Tareas**

- [x] Revisión de ingreso de usuarios mediante portal de ingreso único
- [x] Generar la solicitud de asignación de roles a usuarios
- [x] Realizar seguimiento a solicitud

**Criterios de aceptación**

- [x] Usuarios con asignación de roles

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada líder de proyecto.

**Comment by diagutierrezro** [comment]
En reunión se definió que no es necesario realizar esta asignación ya que en ambiente de producción los usuarios ya deberían de tener los respectivos roles definidos para poder utilizar el sistema de manera correcta.

**Comment by jcmurilloa** [comment]
Buen trabajo Diego, pendiente generar el seguimiento a los usuarios en el piloto en producción.
