### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión exploratoria con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#518]
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión exploratoria con cliente para modalidad artículo académico pasantía.

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión para el día 23/05/2024 a las 11:00 am en la sede paiba

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NWJjNzYzYWQtOTRiZi00YjQ2LWE0YTctNTM4ZWE3ZDZiYThi%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha creado la el acta de la reunión , a espera de la firma del cliente : 


[Acta sin firma](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EUYN31er87FOnwmzJFkKJI0BH2YAgpJn8q-CX8Q9Ug4yyA?e=XSUOBQ)

**Comment by jcmurilloa** [comment]
Se genera revisión, pendiente firmas.

**Comment by mantnicot** [comment]
Se agrega el documento con las firmas correspondientes

[Acta con firmas](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Eb5HPJxVMeZAuRJIWWb4e7QBKsdWXGSkVpEbKXGd7ZL60w?e=o5vbA5)

**Comment by jcmurilloa** [comment]
Excelente trabajo Cristian!
