### ISSUE TITLE
Revisar scripts de creación de parametros para hacer la sincronización en ambiente de producción.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#522]
Se requiere realizar la revisión de los [scripts creados](https://github.com/udistrital/polux_cliente/issues/437#issuecomment-1813373090), realizar las modificaciones o adiciones necesarias para que los parametros registrados actualmente para Pólux en la base de datos de parametros se vean reflejados en el script.

**Sub Tareas**

- [x] Modificar los tipo_parametro para que el area_tipo_id sea **25**.
- [x] Realizar la revisión del script para asegurar que todos los parametros de pólux se encuentran en dicho script.
- [x] Realizar las modificaciones o adiciones en caso de ser necesario.

**Criterios de aceptación**
- [x] Modificación de los tipo_parametro a codigo 25.
- [x] Revisión del script realizada.
- [x] Modificaciones ya adiciones realizadas en caso de ser necesario.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Modificar los tipo_parametro para que el area_tipo_id sea 25.

1. En Producción dentro del schema "parametros", en la tabla "tipo_parametro" ya se encontraban los registros con "id" = 69, 70, 71 y 72.
2. Por tanto se añaden los registros faltantes con "id" = 73, 74, 75, 76, 77, 78, 79, 80, 81, 82 y 83, con "area_tipo_id" = 25 que es la llave foranea que hace referencia al área "Polux".

[Inserts-parametros.tipo_parametro-Produccion.txt](https://github.com/udistrital/polux_cliente/files/15428752/Inserts-parametros.tipo_parametro-Produccion.txt)

Nota: Recordar cambiar la extensión del archivo ".txt" por ".sql".

**Comment by CrisEs2506** [comment]
**SubTarea N°2:**  Realizar la revisión del script para asegurar que todos los parametros de pólux se encuentran en dicho script.

1. En los Inserts para el schema "parametros", en la tabla "parametros" con "tipo_parametro_id" = 76, existe una variación en el campo "descripcion" de "Pasantia Interna"; en el script aparece: 'Modalidad que realiza el estudiante en una entidad nacional o internacional, asumiento el cáracter de práctica o de introducción a su quehacer profesional'. Mientras que en el registro que hay en Desarrollo aparece: 'Modalidad que realiza el estudiante en una entidad nacional o internacional, asumiento el cáracter de práctica'.
2. El archivo SQL o script se organizo de manera en qué aparecían las consultas SQL ('ORDER BY id ASC') en el schema de Desarrollo, en cascada, para evitar el mínimo error por un cambio en el "id" autoincremental.

[Inserts-parametros.parametros-Produccion.txt](https://github.com/udistrital/polux_cliente/files/15430989/Inserts-parametros.parametros-Produccion.txt)

**Nota:** Recordar cambiar la extensión del archivo ".txt" por ".sql".

**Comment by CrisEs2506** [comment]
Dado que al momento de generar los inserts faltantes en Producción en el schema "parametros", en la tabla "parametros", se obtuvieron ID's diferentes a los encontradas en Desarrollo por el tema del autoincremental, es necesario actualizar el script con dichos nuevos ID's:

[Inserts-parametros.parametros-Produccion.txt](https://github.com/udistrital/polux_cliente/files/15436932/Inserts-parametros.parametros-Produccion.txt)

**Comment by diagutierrezro** [comment]
Buen trabajo Cristian
