### ISSUE TITLE
Realizar ajustes al sistema para piloto en producción

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#523]
Se requiere realizar los cambios solicitados desde el despliegue piloto a producción según vayan surgiendo los requerimientos para mantener el sistema estable en ambiente de producción

**Sub Tareas**
- [x] Realizar ajustes según requerimientos que vayan surgiendo en el sprint.
- [x] Documentar cambios realizados.

**Criterios de aceptación**
- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
Se genera traslado de issue a siguiente sprint, debido a que a la fecha, no se ha generado la necesidad de ajustes al sistema en el piloto en producción-

**Comment by JuanDHernandezA** [comment]
Se realiza corrección en el Cliente al momento de realizar la solicitud inicial por parte del estudiante debido a que no se estaba enviando la información del tipo de modalidad de grado de forma correcta.

**Comment by diagutierrezro** [comment]
Se corrigieron varios datos de las modalidades que tienen que ver con la parametrización, posteriormente dos usuarios reportaron problemas al momento de crear la solicitud inicial, tomó bastante tiempo esta revisión ya que en ambiente de pruebas la funcionalidad se ejecutaba de manera correcta, finalmente despues de una reunión con uno de los estudiantes que presentó el error se pudo revisar la consola de AWS donde despues de una revisión mas detallada se descubrió que la variable de entorno que apunta hacia el crud de pólux estaba incorrecta por lo que se solicita la actualización de esta variable de entorno en el [kb](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?tracker=528&aid=61480).

**Comment by jcmurilloa** [comment]
Se traslada a Sprint 10, con el fin de dar continuidad al piloto en producción.

**Comment by jcmurilloa** [comment]
Al culimnar el piloto en producción, se sugiere cerrar la issue si cuenta con los requerimientos necesarios @diagutierrezro

**Comment by diagutierrezro** [comment]
Se creará un issue para actualizar el documento de hallazgos, una vez se realice el documento se cerrará el issue.

**Comment by diagutierrezro** [comment]
Se da por finalizado el piloto en producción, se genera un documento con los hallazgos encontrados por los usuarios durante el piloto que se puede encontrar en #607
