### ISSUE TITLE
Actualización diagrama de flujo de la modalidad artículo académico

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#525]
Se requiere realizar la construcción diagrama de flujo de la modalidad artículo académico

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo de la modalidad de producción académica , el cual es el nombre oficial de articulo académico

[Flujo en draw.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ESx6_RRKG7ZMugXC-zTlJG4BCJSKHSPRqRwR6fmAMKuzUQ?e=3tSDhV)

[Carpeta ubicación](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehy6P1zym2ZEl8mcFDcDpNIB06fBoYK-rOVXjiMDOKLlZg?e=nKnr1S) 


![Flujo de las modalidades polux 2024-Producción Academica drawio](https://github.com/udistrital/polux_cliente/assets/85162258/266bb336-9b46-452a-ad4b-eaa41e64fdec)


Se espera confirmar el flujo a futuro con la facultad , pues se construyo con base a lo encontrado en el [Acuerdo 02. 2023](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ERg8L2I-c-NHg5sjQ3Ur4O4BrMe7tP6RIPnmW7eNejOhYg?e=PfpW6j)


[Flujos construidos del sigud](https://sigud.udistrital.edu.co/vision/filesSIGUD/SIGUD%202018/Gestion%20de%20Docencia/GD-PR-017/#diagram/1766c20b-ffc5-46cf-bce7-75c1365d17b2)

**Comment by mantnicot** [comment]
Se ha hechos los cambios hablados en el Daily en el flujo para seguir manteniendo mejor cohesión con el acuerdo 02.2023


![Flujo de las modalidades polux 2024 producción academica-Producción Academica drawio v2](https://github.com/udistrital/polux_cliente/assets/85162258/1651d98d-9c2d-4a31-b44c-754d34759873)


[Flujo en Draw.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EQ4sUhmHweJJpeZelTSjZj8BFLeXyhrnKUUbYOEv71beTg?e=5zeSAf)

[Carpeta ubicación](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehy6P1zym2ZEl8mcFDcDpNIB06fBoYK-rOVXjiMDOKLlZg?e=nKnr1S)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot Solo resta socializar con el cliente!
