### ISSUE TITLE
Generar el envío del comunicado de lanzamiento de piloto en producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#526]
Se requiere generar el envío del comunicado de lanzamiento de piloto en producción

**Sub Tareas**

- [x] Refinar el comunicado
- [x] Enviar información a cómputo
- [x] Revisión de envío de comunicado

**Criterios de aceptación**

- [x] Comunicado de lanzamiento enviado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación 
- [X] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha generado el envio de parte de computo para el comienzo del piloto en producción


[Correo_ Cristian Antonio Escorcia Blanco - Outlook.pdf](https://github.com/udistrital/polux_cliente/files/15458328/Correo_.Cristian.Antonio.Escorcia.Blanco.-.Outlook.pdf)


[Captura de correo](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQ881k8zz-1Ghp1pbfbjc_YB9S3VGOKeE-Os_VMM18HhwA?e=N7bZ87)

**Comment by jcmurilloa** [comment]
Cada vez mejoramos esos comunicados Cristian! Buen trabajo!
