### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión con cliente para flujo articulo académico y pasantía

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#527]
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión con cliente para flujo articulo académico y pasantía

**Sub Tareas**

- [x] Concertar reunión con el cliente
- [x] Desarrollar la reunión con el cliente
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido hablar con clemencia para organizar la reunión y comento que se encuentra lunes , martes y miércoles , por lo cual se cuadrara con Kevin para reunión presencial.

**Comment by mantnicot** [comment]
Se ha creado el acta de la reunión , queda a espera del revisión del diagrama con el equipo para el envió de firmas.

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZkFg8DGSh9JsXSH00pJ-C4B_ctHRiQncBxNu3NQzabiZg?e=hUaNJ2)

**Comment by mantnicot** [comment]
Se ha subido el acta con las firmas correspondientes

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EYdIwPSdkq1JtAwp9097rLUBZ96TMQDZ1cQdqAc9dx8s7w?e=N2AKh4)
