### ISSUE TITLE
Presentación ante Planestic del módulo de monografías

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#528]
Se requiere realizar la presentación ante Planestic del módulo de monografías

**Sub Tareas**

- [x] Concertar reunión exploratoria con Planestic
- [x] Desarrollar la reunión Planestic
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se creo la reunión para el día 29/05/2024 a las 2:30 pm


[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTgyMTg0ZjQtN2VjMS00NTYxLTg2ZTItMTNmNzIxZWM2MWUy%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%2200dbf53d-1724-496d-b55c-da224db8208e%22%7d)

**Comment by mantnicot** [comment]
Se ha creado el acta de presentación a planestic

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZILyd3xXdpPgDj8wNjXah4B0OZi03KM4e8CmrED3Plesg?e=ScOH9l)

**Comment by mantnicot** [comment]
se ha juntado todas las firmas 

[Acta con firmas](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ESJLBfCHU01Hjtnn0SyX0AoBhtfQhW2qsGfA0izjXCY-mg?e=CMZrIU)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
