### ISSUE TITLE
Proyectar y enviar comunicado punto medio piloto en producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#532]
Se requiere realizar la proyección y envío del comunicado de punto medio del piloto en producción del sistema

**Sub Tareas**

- [x] Proyección del comunicado
- [x] Revisión por parte del líder del proyecto
- [x] Documentación del comunicado

**Criterios de aceptación**

- [x] Comunicado de punto medio aprobado
- [x] Comunicado de punto medio enviado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada líder de proyecto.

**Comment by mantnicot** [comment]
Se ha realizado el envio del comunicado a computo para el envio al resto de usuarios del Piloto de Pólux

![Image](https://github.com/udistrital/polux_cliente/assets/85162258/717f76e4-07a1-48b8-a466-caf5d04030ad)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, pendiente evidencia de envío por parte de cómputo.

**Comment by mantnicot** [comment]
Se ha realizado el envió de parte de computo a los usuarios


![Image](https://github.com/udistrital/polux_cliente/assets/85162258/d1e6824e-403e-4fc7-9714-47d505fa5c7d)
