### ISSUE TITLE
Apropiación del sistema

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#535]
Se requiere realizar la apropiación del sistema pólux para entender el funcionamiento del mismo y sus diferentes Apis, para esto se requiere revisar la [documentación disponible](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20POLUX) y clonar los diferentes repositorios de pólux: [Cliente](https://github.com/udistrital/polux_cliente), [mid](https://github.com/udistrital/polux_mid) y [crud](https://github.com/udistrital/polux_crud)

**Sub Tareas**

- [x] Clonar repositorios de pólux.
- [ ] Leer la documentación disponible.

**Criterios de aceptación**

- [x] Repositorios clonados.
- [ ] Documentación leida.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
@Astaroth-Andres-Molano Recuerda generar el respectivo commit y la documentación del avance acá en la issue

**Comment by Astaroth-Andres-Molano** [comment]
Se clonan los repositorios, se instalan dependencias y se procede a poner en marcha a cada uno en ambiente local, inicialmente hubo compliaciones con la librería Beego, se realizan maniobras para poder solucionarlo:

https://udistritaleduco-my.sharepoint.com/:v:/g/personal/afmolanos_udistrital_edu_co/ESySSUN5Ss5FvRCrmGtq6SMBWET0czYizITUpjpzhIPuSQ?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view

Despues de solucionado se ponen en marcha en ambiente local:

- Polux_cliente




![Pólux cliente](https://github.com/udistrital/polux_cliente/assets/69996417/7f243676-4619-441c-ba3f-3091f55743fe)

![Interfaz Pólux](https://github.com/udistrital/polux_cliente/assets/69996417/36fa1638-6ef6-42a1-85b6-d156c88ba6da)

- Polux_MID

![Clonar Polux_MID](https://github.com/udistrital/polux_cliente/assets/69996417/145e9191-bbb2-40de-a1ab-b0edb3bd9f5a)

- Polux_CRUD
![Clonar Polux_CRUD](https://github.com/udistrital/polux_cliente/assets/69996417/4bf5bb87-2a74-4d14-b15c-5d1553a1d14e)
