### ISSUE TITLE
Revisión del estado actual de modalidad producción articulos academicos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#536]
Se requiere realizar la revisión del estado actual para la modalidad de articulos académicos para conocer el comportamiento del sistema en esta modalidad y realizar los respectivos ajustes en caso de ser necesario. 

**Sub Tareas**
- [x] Realizar revisión del estado actual en ambiente de pruebas, se puede usar como guía el flujo creado en #525 (tener presente que ese no es el flujo que debería tener el sistema como tal, es un flujo según el acuerdo).
- [x] Documentar hallazgos encontrados.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Link de la primera sesión de la tarea: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/afmolanos_udistrital_edu_co/ESySSUN5Ss5FvRCrmGtq6SMBWET0czYizITUpjpzhIPuSQ?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Realizar revisión del estado actual en ambiente de pruebas.**

1. Creación de Producción de Artículo Académico:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/3a875a3c-5855-49c0-8168-fe7b9df26b08)

<img width="562" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/97bc201b-3694-4a94-b32f-d11b54caecb1">

**Resultado:**

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/686449d9-8048-40d7-a9a6-4fbf30fcbbcb">

**Peticiones (Network):**

<img width="506" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/070c8717-4a92-48ea-b40f-2b3e1dea946b">

<img width="665" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/9f71970b-290e-4a2d-81ef-4b7bcb068fb8">

**Observaciones:** Todos los datos del formulario son añadidos correctamente, sin embargo, al momento de darle al botón "Enviar Solicitud" esta no se crea.

2. Listar Solicitudes por parte del Estudiante:

<img width="631" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/d0b1ef72-9321-493c-843e-b9543ba36b89">

**Observaciones:** Se corroborá que la solicitud realizada anteriormente no se crea y por ende no se puede continuar con el flujo.

3. Listar Solicitudes por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/da4a41f6-ea5a-4044-8943-99abdede09ce)

**Observaciones:** No se crea la solicitud tampoco para el Docente Director.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Realizar revisión del estado actual en ambiente de pruebas.**

1. Creación de Producción de Artículo Académico (en ambiente local):

![image](https://github.com/udistrital/polux_cliente/assets/65032868/3a875a3c-5855-49c0-8168-fe7b9df26b08)

<img width="562" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/97bc201b-3694-4a94-b32f-d11b54caecb1">

**Resultado:**

<img width="632" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/566a8850-038c-483f-b967-e6d2f3c951f6">

2. Listar Solicitudes por parte del Estudiante:

<img width="629" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/0cc9ae47-4936-4c3c-b78f-2cba09d6e3b2">

3. Listar Solicitudes por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/2763a5e9-41bf-4188-b7b7-2422875103e0)

4. Aprobar Solicitud por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/f9fa6463-8507-418c-a80a-52248adeaefd)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/3646049c-38e9-4f33-bda5-dba63762cd30)

**Resultado:**

![image](https://github.com/udistrital/polux_cliente/assets/65032868/28a1bdab-ded2-44af-9f61-75a539f1931f)

**Observaciones:** Al momento de aprobar la solicitud, no aparecía un campo para agregar comentarios, cómo en el caso de Monografía.

5. Listar Solicitudes por parte del Coordinador:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/9bc2e9f1-ca04-4278-bcce-e2a122c6488d)

6. Aprobar Solicitud por parte del Coordinador: 

![image](https://github.com/udistrital/polux_cliente/assets/65032868/4302ba54-2f7a-4353-81bf-15fdb0bdcd1a)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/8b2bc551-b382-4444-a789-f8dd136ddfe0)

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Realizar revisión del estado actual en ambiente de pruebas.**

1. Solicitud de Revisión de Trabajo de Grado por parte del Estudiante:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/afdf35c1-de03-422f-b864-ed5848e1381b)

**Resultado:**

![image](https://github.com/udistrital/polux_cliente/assets/65032868/1eba8008-0462-4a03-886d-b75aea6ddf2c)

2. Listar Solicitudes por parte del Estudiante:

<img width="418" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/716f8242-b6bb-4722-a075-4018853ff8a6">

3. Listar Solicitud por parte del Docente Director:

<img width="418" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/7b31d94b-3cfa-4068-a42f-30714969b5e0">

4. Aprobar Solicitud por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/66c4ed43-e716-4a41-a50b-d81dbb795d40)

**Peticiones:**

![Imagen de WhatsApp 2024-06-06 a las 00 15 57_5fd456f8](https://github.com/udistrital/polux_cliente/assets/65032868/577dc792-29d1-4563-a8a2-809f35fd3ec8)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/67ac188c-9a2d-4694-8719-78ddd046b602)

**Consola:**

![image](https://github.com/udistrital/polux_cliente/assets/65032868/a7d52fcc-a2cd-4eb8-b6fb-f255872d6209)

**Observaciones:** Al momento de darle al botón que se lleva al formulario para Aprobar o Rechazar la Solicitud, se genera un error, sin embargo se desconocen las razones y en el inspector se observa que se realiza una petición POST la cuál creemos no tiene mucho sentido y es lo que puede estar causando el error.

**Comment by Astaroth-Andres-Molano** [comment]
Nota: Al momento de realizar una aprobación de solicitud de Revisión de trabajo de grado en esta modalidad por parte del Docente Director, ocurre el error anteriormente documentado, en este caso no se puede dar continuidad al flujo ya que no se puede cancelar la solicitud creada ni desde el estudiante ni desde el docente director.

**Comment by Astaroth-Andres-Molano** [comment]
Link de la segunda sesión de la tarea: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/afmolanos_udistrital_edu_co/EW91jKTSsU9DhGyzKTuyf54BbHdjPVC4OU6l1Y-fNMpWeg?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view
