### ISSUE TITLE
Revisión del estado actual de la modalidad de pasantía interna.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#537]
Se requiere realizar la revisión del estado actual de la modalidad de pasantía interna para ver el comportamiento actual del sistema en esta modalidad.

**Sub Tareas**

- [x] Realizar la revisión de la modalidad de pasantía interna en ambiente de pruebas teniendo en cuenta el flujo que se encuentra en el siguiente [enlace](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EncJQTPes-pNhWUY5P3rdjABYQKUw5wrhI0BHuDVb5V8RQ).
- [x] Realizar la documentación de los hallazgos encontrados.

**Criterios de aceptación**

- [x] Revisión de la modalidad de pasantía interna realizada.
- [x] Documentación de los hallazgos encontrados realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Realizando la revisión junto con @Astaroth-Andres-Molano se encontró el siguiente error:

- Al momento de enviar la solicitud para la modalidad de grado Pasantía Interna, se genera un error al momento de enviar un POST a la tabla Solicitud_trabajo_grado. Revisando el Payload  podemos observar que en el objeto Solicitud hace falta el atributo modalidad_tipo_solicitud, el cual determina la modalidad de grado y el tipo de la solicitud. Este valor no puede ser nulo por lo que la base de datos retorna un error:


![Image](https://github.com/udistrital/polux_cliente/assets/129443402/f83743e2-b3ef-4e9b-81ff-b9895c08e600)

- Se debe revisar en el Cliente al momento de preparar la solicitud por qué no se está enviando el tipo de modalidad de Pasantía Interna

Por lo anterior no se puede continuar probando el flujo de la modalidad de Pasantía Interna.

**Comment by JuanDHernandezA** [comment]
Continuando con el flujo, la solicitud se puede visualizar y aprobar de forma correcta por parte del Docente Director:
![Captura de pantalla 2024-06-07 181642](https://github.com/udistrital/polux_cliente/assets/129443402/feb7d943-f02e-4513-8623-8c924d28fd57)
![Captura de pantalla 2024-06-07 181748](https://github.com/udistrital/polux_cliente/assets/129443402/89f6c0f9-be15-4845-a6cc-667047a8974b)

Desde el perfil del Coordinador se encontraron los siguientes errores:

- Al momento de aprobar la solicitud inicial, sale el siguiente aviso que indica un error de tipo de variable en el RolTrabajoGrado:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/5c76a9c2-1432-4f01-a053-ebd41ab9d250)

Revisando el cliente, en donde se prepara el JSON podemos observar que para el atributo RolTrabajoGrado se está almacenando todo el registro y no solo el ID, se realiza el cambio:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/56c50f42-7b01-4347-bd2c-52f52af1ca75)

- Continuando con el flujo, al momento de aprobar la solicitud por parte del Coordinador, sale un error al momento de realizar un POST en la tabla Detalle_Pasantia. Revisando el objeto enviado, nos damos cuenta que falta agregar el id del Trabajo de Grado. Se realiza el cambio y la transacción se completa de forma correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/2d4d273c-0aa7-4299-b39e-dccbf23b5e33)
![Captura de pantalla 2024-06-07 194829](https://github.com/udistrital/polux_cliente/assets/129443402/a92c26a3-8dce-4d15-8fe1-2ee65059db0b)

- Revisando en el perfil del estudiante, en el menú de Consulta Trabajo Grado, podemos observar que la modalidad se registró de forma correcta:
![Captura de pantalla 2024-06-07 194919](https://github.com/udistrital/polux_cliente/assets/129443402/fcc34c93-e798-4815-ae63-cafddfb5d8eb)

**Comment by JuanDHernandezA** [comment]
Continuando con el flujo, desde el perfil del Estudiante en el menú de Revisión Documento, sale el siguiente mensaje:

![image](https://github.com/udistrital/polux_cliente/assets/129443402/d997f1cd-d742-4941-ac0a-dc065e6df179)

Revisando la base de datos, pudimos observar que solo se están almacenando 2 documentos para esta modalidad: el Anteproyecto y el Trabajo de Grado.

Concluimos que no está desarrollada la lógica encargada de manejar los documentos asociados a la modalidad de pasantía interna. Adicional a esto, no se muestra la opción de cargar la ARL y las Actas de Seguimiento de la pasantía.

Por lo cual, el flujo no puede continuar.
