### ISSUE TITLE
Revisión del estado actual de modalidad  de pasantia externa

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#538]
Se requiere realizar la revisión del estado actual de la modalidad de pasantía externa para ver el comportamiento actual del sistema en esta modalidad. Importante tener en cuenta cualquier diferencia con la modalidad de pasantía interna y documentar dichas diferencias.

**Sub Tareas**

- [x] Realizar la revisión de la modalidad de pasantía externa en ambiente de pruebas.
- [x] Realizar la documentación de los hallazgos encontrados.

**Criterios de aceptación**

- [x] Revisión de la modalidad de pasantía externa realizada.
- [x] Documentación de los hallazgos encontrados realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se continúa el flujo correctamente hasta llegar a la aprobación por parte del Coordinador donde arroja error en el dato RolTrabajoGrado desde el MID, al remitirse y revisar el objeto enviado desde el cliente donde se prepara el JSON para el atributo RolTrabajoGrado está enviando todo el registro pero se necesita solo el id, se realiza corrección:


![Corrección 2](https://github.com/udistrital/polux_cliente/assets/69996417/aa3e245a-0f92-42a5-aa1f-4487c2521fda)

Al volver a probar la aprobación por parte del Coordinador se encuentra otro error al generar el POST, revisando el objeto enviado al igual que en las pruebas de Pasantía Interna se observa que falta agregar el id del Trabajo de Grado:




![DetallePasantíaExterna](https://github.com/udistrital/polux_cliente/assets/69996417/f811746f-8c4a-4f89-a5fb-65caa2bc3fd4)

Al tratar de agregar el dato se observa que el objeto DetallesPasantiaExterna está para metrizado con DetalleTrabajoGrado:


![DetallePasantíaExterna](https://github.com/udistrital/polux_cliente/assets/69996417/a3fb6861-9bd6-417a-86f3-571069015eb4)

Se procede a consultar para saber si el modelo es correcto o hay que corregir.

**Comment by Astaroth-Andres-Molano** [comment]
Con el lider del equipo se define que ya no se va a utilizar más la modalidad de pasantía externa por ende ya no se reaqlizarán más correcciones a esta modalidad.
