### ISSUE TITLE
Actualización diagrama de flujo de pasantia externas e internas

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#540]
Se requiere realizar la actualización del diagrama de flujo de la modalidad pasantía interna y externa

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente

**Criterios de aceptación**

- [ ] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha generado el diagrama de flujo de pasantías , a espera de hacer el acta y firmas 

[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EncJQTPes-pNhWUY5P3rdjABYQKUw5wrhI0BHuDVb5V8RQ?e=eujQi6)

**Comment by mantnicot** [comment]
Tambien se agrega la pagina de pasantias de ingenieria 

[https://ingenieria.udistrital.edu.co/pasantias](https://ingenieria.udistrital.edu.co/pasantias)

**Comment by jcmurilloa** [comment]
Se genera revisión del flujo po parte del equipo SOS y se proyectan unos cambios con el fin de extenderlos al sistema pendiente nuevo diagrama

**Comment by mantnicot** [comment]
Se ha realizado el cambio de flujo con la anotaciones dadas por el equipo



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/e1f7a363-b901-4d25-993f-cd83a4391d64)


[Carpeta de flujos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EncJQTPes-pNhWUY5P3rdjABYQKUw5wrhI0BHuDVb5V8RQ?e=2bfnwK)

**Comment by jcmurilloa** [comment]
Sugerencias acogidas por parte del equipo de trabajo SOS, con esta información definidia, se procede a establecer flujo en el sistema para esta modalidad de grado.
