### ISSUE TITLE
Desarrollo para guardar anteproyecto.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#541]
Se requiere realizar el desarrollo para guardar el documento que se envía para la solicitud inicial como un anteproyecto según lo analizado en #514 

**Sub Tareas**

- [x] Realizar el desarrollo para almacenar el documento inicial para que se guarde como un anteproyecto.
- [x] Realizar pruebas de funcionamiento.
- [x] Realizar documentación de desarrollo y pruebas realizadas.

**Criterios de aceptación**

- [x] Desarrollo realizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Teniendo en cuenta el análisis planteado en el issue #514, se realizó el siguiente desarrollo:

- Se creó y se insertó en la base de datos el nuevo tipo de documento para identificar los anteproyectos de los trabajos de grado:

```shell
   #Script SQL para la inserción del nuevo tipo, se debe crear un workspace para el documento
   INSERT INTO documento.tipo_documento (nombre,descripcion,codigo_abreviacion,activo,numero_orden,tamano,extension,workspace,tipo_documento_nuxeo,fecha_creacion,fecha_modificacion,dominio_tipo_documento) VALUES ('Anteproyecto','Anteproyecto del trabajo de grado','ANP_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9);
```

![image](https://github.com/udistrital/polux_cliente/assets/129443402/a04cc0be-a019-4af5-b19c-7127075b6430)

- Se integró la funcionalidad en el mid para que al momento de aprobar la solicitud inicial por parte del Coordinador se almacenen 2 documentos: El Anteproyecto y El Trabajo de Grado para revisión. Debido a que desde el API mid no se consume el servicio de Documentos de la oficina, se agregó una nueva variable de entorno encargada del consumo de dicho servicio

```shell
  # app.conf
   UrlDocumentos = ${POLUX_MID__DOCUMENTOS_URL}
```
- Se crearon los modelos de Tipo de Documento y Dominio Tipo Documento para manejar los datos del servicio de Documentos:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/b7e508d0-441c-4524-8912-166d89878e60)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/155fe06d-3418-440f-a1f4-645fd94398c2)

- Se realizaron las pruebas y se puede observar desde la base de datos que en la transacción se almacenan los 2 documentos con distinto tipo de documento:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/34a98170-14c6-458c-a021-149280ad6187)

- Se realizó la prueba de actualizar el documento en la sección de Revisión de Documento, esto con el fin de observar si el documento del Anteproyecto no se actualizaba en la base de datos. Como se puede observar, el documento de revisión fue actualizado y el anteproyecto se mantiene igual:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/f0f0c8fd-1ce8-4f23-af62-5720be05b9e0)

**Comment by diagutierrezro** [comment]
Queda pendiente por aprobar el PR, buen trabajo Juan Diego
