### ISSUE TITLE
Visualización del documento de anteproyecto

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#542]
Se requiere realizar la finalización del desarrollo para visualizar el documento que se envía en la solicitud inicial como el anteproyecto. Este se debe visualizar desde el usuario de estudiante y desde el usuario del coordinador del proyecto.

**Sub Tareas**

- [x] Terminar desarrollo para visualizar documento con los dos roles especificados.
- [x] Realizar pruebas de funcionamiento.
- [x] Documentar desarrollo y pruebas realizadas.

**Criterios de aceptación**

- [x] Desarrollo finalizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realiza la lógica necesaria dentro del controlador de la etiqueta versiones-documentos-tg para que consulte y muestre el documento del anteproyecto del trabajo de grado.

Desde el menú de Consultar Trabajo Grado desde el perfil del estudiante se puede observar que ya muestra el botón para visualizar el anteproyecto:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/c9e1b30e-f0f4-40d9-88ea-6a95f071bdf0)


Se verificó que el documento del anteproyecto corresponda al primer documento cargado en la solicitud inicial y que el documento de Trabajo de Grado corresponda al documento actualizado en la sección de Revisión Documento; todos los documentos visualizados fueron correctos.

También desde el perfil del Coordinador se verificó que la nueva funcionalidad funcionara de forma correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/23360b62-c65c-4996-91d3-dc548f0d9fe3)
