### ISSUE TITLE
Corrección de errores modalidad de producción de artículos académicos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#544]
Se requiere realizar la corrección de los errores encontrados en #536 iniciando por la visualización de la solictud de revisión por parte del docente director.

**Sub Tareas**

- [x] Realizar ajustes necesarios para que el docente director pueda visualizar la solicitud de revisión y dar la respuesta pertinente.
- [x] Probar funcionamiento correcto de la visualización de la solicitud de revisión.
- [x] Realizar documentación de cambios y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Revisión en ambiente de pruebas realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
Nota: Dada la estimación de 5 puntos (2-3d) y teniendo en cuenta que la Issue fue asignada el día jueves, considero que me es necesario ocupar el tercer día (hoy martes) para terminar de ajustar el código, ya que aunque en un principio parecía ser algo trivial, he encontrado que es mucho más complejo de lo que parecía. Mil gracias por su comprensión.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar ajustes necesarios para que el docente director pueda visualizar la solicitud de revisión y dar la respuesta pertinente. y SubTarea N°2: Realizar documentación de cambios.

1. Inicialmente se encerro el contenido de la función 'getParametros()' en una promesa que será resuelta después de haber ejecutado todo el código, con el fin de que no se haga nada adicional y evitar los fallos en el flujo. Adicionalmente, no existía un condicional que garantizará la entrada del código de abreviación "SRTG_PLX". Se realizaron estos ajustes y quedó de la siguiente manera:

<img width="695" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/70624c05-e5ac-4bbf-80bf-f3c66d5b9ee7">

2. Se cambio el uso de promesas por async/await en todas las consultas de la función 'getParametros()', lo cuál garantiza una mayor legibilidad y mantenibilidad del código:

<img width="569" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e1f41771-c1d9-46b8-b6ab-442ce8332d77">

3. Dado que al momento de darle al botón de aprobar solicitud en el menú del listado de solicitudes, se ejecuta la función 'getDetallesSolicitud()' en primera instancia, está al ingresar en la línea 686 no esperaba a que se ejecutará la función 'getParametros()' y por tanto la asignación de la variable 'ctrl.parametro_revista' era indefinida, lo que no permitía recorrer el array y motivo por el cual fallaba el sistema en ese punto del flujo. Para dar solución a este inconveniente lo que se realizo fue convertir la función a asincrona y agregar código al inicio de la función para indicarle que debe ejecutar primero las funciones 'getParametros()' y 'asignarParametros()'. Garantizando de este modo que ninguna variable quede sin definirse:

<img width="428" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/480fbfd7-8c61-47ec-88b6-35b0a10b6018">

<img width="442" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/3400b242-83d3-4992-a25c-11ca7c4caafb">

**Comment by CrisEs2506** [comment]
SubTarea N°2: Probar funcionamiento correcto de la visualización de la solicitud de revisión y SubTarea N°3: Realizar documentación de pruebas realizadas.

Nota: A partir de cierta el sistema dejo de funcionar por lo que no se pudo realizar la documentación a tiempo, sin embargo, es cuestión de que ese aspecto se solucione y documentar que todo funciona correctamente (ya se comprobó, solo que no sé tomaron evidencias en su momento), adjunto evidencias del inconveniente presentado en su momento:

<img width="959" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/6fd876de-b5fd-4e3e-8457-8cb34adf1abb">

**Comment by CrisEs2506** [comment]
SubTarea N°2: Probar funcionamiento correcto de la visualización de la solicitud de revisión y SubTarea N°3: Realizar documentación de pruebas realizadas.

1. Solicitud de Revisión de Trabajo de Grado por parte del Estudiante:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/2b186e85-fc25-4862-8575-43b0f773ec2a">

Resultado:

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/550d14ef-ff41-45ea-a663-b23d733ec8d5">

2. Listar Solicitudes por parte del Estudiante:

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/cde2d5df-7fb4-4090-bfef-eb719ba6d6be">


3. Listar Solicitud por parte del Docente Director:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/c3ae166d-2d63-4050-bef8-df537a45867f">

4. Rechazar Solicitud por parte del Docente Director:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/43b65b43-bb7a-4fc2-ba60-c76ab51827ca">

Resultado:

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a5613ff1-08d9-480d-98ff-8442525dace4">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e279b4db-d3b2-4128-a861-346560d6e4d4">

5. Aprobar Solicitud por parte del Docente Director:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f9d557af-ea67-4f30-92ff-91ba9749e7e9">

Resultado:

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/0cb3aca1-7eec-4cfb-8bb3-5be37727b7a6">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/346bdc8e-c175-444c-b6d4-afa2e86c0d9a">

6. Listar Solicitud por parte del Coordinador:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/578fbd7b-045f-45ba-a1d6-d3a5f4fd3d5f">

6. Rechazar Solicitud por parte del Coordinador:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e0b1057b-86b9-4da5-99e2-d848fa9c2dd0">

Resultado: 

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/ac73305e-8815-40e2-baf9-7cda19de9639">

<img width="348" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/3513cc87-99ab-4c07-877f-c320b6a46ace">

8. Aprobar Solicitud por parte del Coordinador:

<img width="525" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/8364c8fe-afb3-47e6-a7d7-92b3a99505ec">

Resultado: 

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/2707dae2-d829-416f-8d29-099d2d396256">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/cb507cab-5ab1-4d86-b597-6462b79efe45">

**Comment by diagutierrezro** [comment]
Buen trabajo Cristian.
