### ISSUE TITLE
Desarrollar reunión de control del equipo del proyecto piloto producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#545]
Se requiere desarrollar reunión de control del equipo del proyecto piloto producción

**Sub Tareas**

- [x] Concertar reunión con el equipo del proyecto
- [x] Desarrollar la reunión con el equipo del proyecto
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by diagutierrezro** [comment]
Se realiza [reunión de contról](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/P%C3%B3lux%20-%20Primera%20reuni%C3%B3n%20de%20control%20del%20equipo%20del%20proyecto-20240613_150345-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=ipezzk) con Kevin (usuario designado por la facultad de ingenieria) y @mantnicot

**Comment by mantnicot** [comment]
Se ha levantado el acta 

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Eb1AAlkaNbtKvgyITWwZIQYBM8PZm-oZmexV-sso6DXIPg?e=sogxHY)

**Comment by jcmurilloa** [comment]
Se genera la respectiva revisión y comentarios para posteriormente, recolectar las firmas correspondientes.

**Comment by mantnicot** [comment]
se agrega el acta  firmada 

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXRjqPygT29Evwi3zb-zowQBcWBtlm_FKzp3_SYmhSwMpg?e=R7rzX8)
