### ISSUE TITLE
Revisar finalización del flujo posterior a aprobación de revisión por parte del docente director.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#547]
Se requiere realizar la revisión del flujo que continúa despues de que el docente director aprueba la solicitud de revisión para finalizar con la revisión del estado actual de la modalidad de producción de articulos academicos.

**Sub Tareas**

- [x] Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director.
- [x] Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

**Criterios de aceptación**

- [x] Flujo revisado.
- [x] Pruebas realizadas.

**Requerimientos**

- [x] Es necesario que el issue #544 esté finalizado.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director y SubTarea N°2: Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

1. Solicitud de Revisión de Trabajo de Grado por parte del Estudiante:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/2b186e85-fc25-4862-8575-43b0f773ec2a">

Resultado:

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/550d14ef-ff41-45ea-a663-b23d733ec8d5">

2. Listar Solicitudes por parte del Estudiante:

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/cde2d5df-7fb4-4090-bfef-eb719ba6d6be">


3. Listar Solicitud por parte del Docente Director:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/c3ae166d-2d63-4050-bef8-df537a45867f">

4. Rechazar Solicitud por parte del Docente Director:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/43b65b43-bb7a-4fc2-ba60-c76ab51827ca">

Resultado:

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a5613ff1-08d9-480d-98ff-8442525dace4">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e279b4db-d3b2-4128-a861-346560d6e4d4">

5. Aprobar Solicitud por parte del Docente Director:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f9d557af-ea67-4f30-92ff-91ba9749e7e9">

Resultado:

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/0cb3aca1-7eec-4cfb-8bb3-5be37727b7a6">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/346bdc8e-c175-444c-b6d4-afa2e86c0d9a">

6. Listar Solicitud por parte del Coordinador:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/578fbd7b-045f-45ba-a1d6-d3a5f4fd3d5f">

6. Rechazar Solicitud por parte del Coordinador:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e0b1057b-86b9-4da5-99e2-d848fa9c2dd0">

Resultado: 

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/ac73305e-8815-40e2-baf9-7cda19de9639">

<img width="348" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/3513cc87-99ab-4c07-877f-c320b6a46ace">

8. Aprobar Solicitud por parte del Coordinador:

<img width="525" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/8364c8fe-afb3-47e6-a7d7-92b3a99505ec">

Resultado: 

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/2707dae2-d829-416f-8d29-099d2d396256">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/cb507cab-5ab1-4d86-b597-6462b79efe45">

**Comment by CrisEs2506** [comment]
SubTarea N°1: Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director y SubTarea N°2: Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

1. Solicitud de Cancelación de Modalidad por parte del Estudiante:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a4514974-b3d6-4e82-9fbd-48ae73513c99">

Resultado:
<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/719411f1-68a3-4319-a79f-9e127a8beb91">
<img width="348" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/1f8d0e19-61e7-42e8-b7b6-8d0b0de1266f">

2. Listar Solicitud de Cancelación de Trabajo de Grado por parte del Docente Director:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/df13be10-8850-47bc-8cf4-0407aaf9ec47">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/5e3d4e29-0456-4f12-b82f-0a6747546c6b">

3. Aprobar Solicitud de Cancelación de Trabajo de Grado por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/1b6fe87f-9340-460a-97e3-18dc4c42a753)

Resultado:

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f0c3c6e4-5ece-4ded-811b-5a3ccfb0c2b2">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a6537f81-848a-4895-9827-ae600af8a407">

4. Listar Solicitud de Cancelación de Trabajo de Grado por parte del Coordinador:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/d840dd29-5ec6-4f3c-a700-3cf24963d737">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4e4785a0-84ff-4a77-9241-1c4b7b70d803">

5. Rechazar Solicitud de Cancelación de Trabajo de Grado por parte del Coordinador:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/bfcf1316-d4f5-498a-8a40-e2369d736121">

Resultado:

<img width="254" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/80bbae63-519e-4f22-b534-439f079d749a">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/d5cdf1aa-3dab-4a04-aa22-23700568bcdb">

**Comment by CrisEs2506** [comment]
SubTarea N°1: Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director y SubTarea N°2: Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

**Solicitud Cambio Título de Trabajo de Grado - Artículo Académico**

1. Crear Solicitud de Cambio de Título de Trabajo de Grado por parte del Estudiante:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/1d553e11-6bb4-414a-880c-ba9b285649d7">

Resultado:

<img width="254" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/7319c602-95da-4e40-935d-cf353679a408">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/58af9e28-03ba-40c4-9728-99d7b46620d2">

2, Listar Solicitud de Cambio de Título de Trabajo de Grado por parte del Docente Director:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/572b0eef-18e1-4851-ba36-5a477a191ae7">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/75e9f8de-801c-4652-9cd6-1043cac5388b">

3. Rechazar Solicitud de Cambio de Título de Trabajo de Grado por parte del Docente Director:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/7d24c923-f440-4fec-bd89-90fa2963dd17">

Resultado:

<img width="254" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f3f9c590-6f7a-4294-a610-13254bf76823">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/295f023a-30ab-43d4-b855-969c682e581a">

4. Aprobar Solicitud de Cambio de Título de Trabajo de Grado por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/1332dc72-66f5-4761-9a70-2ffcaba4a22a)

Resultado: 

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/d9833690-b034-4b2a-bc36-0ce0cdb68a36">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/d3ee94d1-4430-459d-afde-122585c9b91b">

5. Listar Solicitud de Cambio de Título de Trabajo de Grado por parte del Coordinador:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/c615e29a-ef98-41c3-aa67-b498577f1cfd">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/97de11c3-0a1d-4f1a-988c-1c292a2f9e6d">

5. Rechazar Solicitud de Cambio de Título de Trabajo de Grado por parte del Coordinador:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/6d50bd78-62e1-4094-93ad-1021c3b887e5">

Resultado:

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/913ca011-3efd-4aba-8a7d-9a77e808c7ae">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/87edcc78-f695-441f-9ee4-6002f1c87df6">

6. Aprobar Solicitud de Cambio de Título de Trabajo de Grado por parte del Coordinador:

<img width="527" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/73dcc653-1480-46c7-a431-78a8edf56ea0">

Resultado: 

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/24db7837-80c6-4e95-8c3c-8a5afd0be25b">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/c736b294-5001-4deb-86d2-534da58a3bbb">

**Comment by CrisEs2506** [comment]
SubTarea N°1: Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director y SubTarea N°2: Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

**Solicitud Cambio de Director Interno - Artículo Académico**

1. Crear Solicitud Cambio de Director Interno por parte del Estudiante:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/aa1f2188-91b1-4a40-a2fc-9811a2f8dc3c">

Resultado:

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/78e454e7-1020-44a2-965e-69c96c8cd27a">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/9f637c38-a28e-467f-ba55-ebfd0cb5c737">

2. Listar Solicitudes Cambio de Director Interno por parte del Docente Director:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/312d2a6f-f928-4351-aba4-30139b908712">

<img width="348" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/6cfb23db-50e1-4c0f-97ae-8a5290a0fe14">

3. Rechazar Solicitud Cambio de Director Interno por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/eaeb5e0a-6e21-4c4a-b21f-54b45a6f869e)

Resultado:

<img width="251" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/ce4656d7-6b82-493b-9b24-2c1728182bc9">

<img width="348" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/64c006b0-6791-4822-87c8-2fb7ebd6f61b">

4. Aprobar Solicitud Cambio de Director Interno por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/28d3bc6f-b34e-48d5-9f41-53df342fc072)

Resultado:

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/23bda282-1e3e-40ee-bd8c-dcb308a1fee7">

<img width="350" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/9495924c-c103-40de-9526-20beb5e7d13f">

5. Listar Solicitudes Cambio de Director Interno por parte del Coordinador:

<img width="529" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/1aeb8c09-f07c-4ed6-8ad6-7ececa4807be">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a219f11f-7332-4ea0-9600-eb6deb0ef058">

6. Rechazar Solicitud Cambio de Director Interno por parte del Coordinador:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/6d478799-d1d9-4325-937c-9cb7fc2712f7">

Resultado: 

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/779c548b-04eb-4877-ad3b-5c9630ad6fc6">

<img width="349" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/2a4fead6-feda-4fd9-9471-c4b7629c3ccc">

7. Aprobar Solicitud Cambio de Director Interno por parte del Coordinador:

<img width="528" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a00b21be-e064-4749-9a6e-921b58fdad43">

Resultado: 

![image](https://github.com/udistrital/polux_cliente/assets/65032868/2af145ca-109e-4b4e-94bf-9a8a7ef20b44)

Observación:

La única petición que se realiza es un POST a 'polux_mid':

<img width="517" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/845649b0-c883-42ff-be94-2fa1b90c94a3">

El payload que se envía por medio de la petición es el siguiente:

<img width="734" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/d0664f34-3c1e-42a2-b588-04f95557c9ba">

Y a nivel de consola no arroja ningún error.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director y SubTarea N°2: Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

**Solicitud de Prórroga - Artículo Académico**

1. Crear Solicitud de Prórroga por parte del Estudiante:

<img width="560" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/06a14676-c0a2-4362-bd29-91f74f2e1a4b">

Resultado: 

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/5a913d0a-861e-4094-9380-80f5e6e2b886">

<img width="371" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/06b50ee6-4d25-4ca5-a6e0-1edbb63e9364">

2. Listar Solicitud de Prórroga por parte del Docente Director:

<img width="560" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/5fb001df-59bb-4c69-8d37-701d930b2220">

<img width="371" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/c53fe709-b6a1-4dc5-b6ed-bbb3fbf97b54">

3. Rechazar Solicitud de Prórroga por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/4cd176f7-47c7-4320-a54c-4f445b38ee9e)

Resultado:

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/1d00f4a2-cedb-47d5-ae58-3672dbe7987a">

<img width="373" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/9f6dcf8a-b38b-495f-8816-56940ac8540f">

4. Aprobar Solicitud de Prórroga por parte del Docente Director:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/be2fe0b7-fba1-4986-bc4c-fdb372f7ba7d)

Resultado:

<img width="253" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/07511b84-0c55-4860-ad90-b79488546a98">

5. Listar Solicitud de Prórroga por parte del Coordinador:

<img width="562" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/faeac9e6-cd00-4ebc-9e97-f9b0e2093171">

<img width="371" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/bd6fed5d-59b6-43d9-b467-4635540c424f">

6. Rechazar Solicitud de Prórroga por parte del Coordinador:

<img width="561" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f59779fd-4de8-49ab-a748-c8d2c0a6bfa2">

Resultado:

<img width="250" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/948eb769-3003-4a36-91ff-fdfff2183b5b">

<img width="371" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/134b9438-9702-40f4-be4f-77c892df4571">

7. Aprobar Solicitud de Prórroga por parte del Coordinador:

<img width="561" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/85c3e7b1-1dff-4790-8076-1d0707eda905">

Resultado:

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/a5799616-dc5e-4194-a188-74b0ea447fc4">

<img width="371" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4127f202-b6a0-4031-87ca-ac1b8032c235">

**Comment by CrisEs2506** [comment]
SubTarea N°1: Revisar flujo posterior a la aprobación de la solicitud de revisión por parte del docente director y SubTarea N°2: Documentar pruebas realizadas y errores encontrados (en caso de hacerlo).

**Registrar Nota - Artículo Académico:**

1. Registrar Nota por parte del Docente Director:

<img width="364" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/361c786d-7257-4fcd-adf4-008e44060be2">

Resultado:

<img width="252" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/eba5b7f3-4de4-466f-8d09-0e1b9f5e7c6d">

2. Aprobar Calificación por parte del Coordinador:

Nota: Se encuentra bloqueado la aprobación de solicitudes por parte del coordinador por lo que no es posible continuar con el flujo, se adjunta evidencia:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/1daaf5ff-54e0-47e9-ba3e-186fa5a2a6a3)

**Comment by diagutierrezro** [comment]
Se crearán nuevos issues para corregir los errores encontrados. Buen trabajo Cristian.
