### ISSUE TITLE
Corrección de vista "revisión de documentos" para modalidad de pasantía interna

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#548]
Se requiere realizar la revisión de lo que está fallando y posteriormente realizar las correcciones para poder visualizar de manera correcta la sección de "revisión de documentos" con el rol de estudiante teniendo en cuenta lo que se encontró en #537.

**Sub Tareas**

- [x] Realizar revisión para detectar por que está fallando la visualización de la sección "revisión de documentos".
- [x] Según lo encontrado en la revisión anterior realizar las correcciones necesarias para poder visualizar dicha sección.
- [x] Realizar pruebas de correcto funcionamiento de visualización de la sección "revisión de documenos"
- [x] Documentar el issue con las correcciones y pruebas realizadas.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Correcciones realizadas.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se revisa el código de la transacción para aprobar la solicitud inicial y esta no guarda los documentos adjuntados para la pasantía.

Desde el cliente se prepara el JSON con los 2 documentos: "Acuerdo de Voluntad, Convenio o Contrato" y "Carta de la Unidad Académica":

- Se agregan los tipos de detalles recibidos en el formulario correspondientes a los documentos:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/d2d54efd-441d-4019-8562-4f39e5aeefe5)

- Se adjuntan los datos correspondientes para que cumpla con el struct de DocumentoEscrito y se guardan con el TipoDocumento de "Documentos adicionales asociados a las pasantias":
![image](https://github.com/udistrital/polux_cliente/assets/129443402/b0c6e552-eaf2-4fd5-aeec-1f59d9fd4b2e)

Desde el MID, se modifica el struct de DetallePasantia para recibir los documentos:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/36f60d07-bfbd-496c-ae79-2332addb0324)

Se crea la funcionalidad para almacenar los documentos tanto en la tabla DocumentoEscrito como en la tabla DocumentoTrabajoEscrito.

Se prueba la funcionalidad y se verifica que en la base de datos se encuentren todos los documentos asociados:
- En la tabla Documento_Escrito
![image](https://github.com/udistrital/polux_cliente/assets/129443402/a177ed58-921b-4712-92df-04033d6118a2)

- En la tabla Documento_Trabajo_Grado
![image](https://github.com/udistrital/polux_cliente/assets/129443402/7bb8e21f-c413-4e8b-890c-f66ddf92c837)

Se procede a realizar la funcionalidad para la visualización de los documentos en la plataforma

**Comment by JuanDHernandezA** [comment]
Revisando la funcionalidad que muestra los documentos asociados al trabajo de grado, detecta a los documentos con el tipo "Documentos adicionales asociados a las pasantías" como la ARL del estudiante, por lo que se propone crear 2 nuevos tipos de documentos, uno para el Acuerdo de Voluntad, Convenio o Contrato y otro para la Carta de la Unidad Académica. Se crean e insertan los nuevos tipos en la base de datos

``` bash
#script para la inserción de los 2 nuevos tipos de documentos, se debe crear un workspace nuevo para cada tipo
INSERT INTO documento.tipo_documento 
	(nombre,descripcion,codigo_abreviacion,activo,numero_orden,tamano,extension,workspace,tipo_documento_nuxeo,fecha_creacion,fecha_modificacion,dominio_tipo_documento) 
	VALUES 	('Contrato Pasantia','Acuerdo de Voluntad, Convenio o Contrato para la modalidad de Pasantia','AVCC_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
			('Carta Aval Pasantia','Carta de la Unidad Académica Responsable para la modalidad de Pasantia','CUA_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9);
```
![image](https://github.com/udistrital/polux_cliente/assets/129443402/8773492d-4e0c-4fd5-882a-02d448b1afc7)

Se corrige la lógica ya desarrollada para almacenar los documentos con los nuevos tipos de documento:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/a2fa6039-f177-4fc1-9f06-420df5966967)

Se verifica que los documentos se almacenen con los nuevos tipos en la base de datos:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/2dd1963c-17a2-41cf-9efe-852238d49652)

Se desarrolla la lógica para visualizar los nuevos tipos de documentos en el menú de Consultar Trabajo de Grado. Se prueba la funcionalidad, verificando que coincidan los documentos que se cargaron en la solicitud inicial:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/bd2d95ca-2cd9-46b3-b27d-6c719f8d7320)

**Comment by JuanDHernandezA** [comment]
Se verifica si la funcionalidad anterior solucionó el error de mostrar los documentos en el menú de Revisión de Documentos, lo cual no fue correcto:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/167bc5ce-34ee-417a-bbc7-86db86e1cbb4)

Se revisa la lógica encargada de este menú. Se encuentra que el Estado del Trabajo de Grado de "Aprobada pasantía, en espera de cargar ARL" no se encuentra entre los tipos permitidos para mostrar este menú. Se agrega y queda solucionado el error en la vista Revisión de Documentos para la pasantía interna:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/ed6dc6d3-2a84-483b-96db-b2c2009b94f4)

**Comment by diagutierrezro** [comment]
El cargue de ARL se maneja en otra issue, buen trabajo Juan Diego
