### ISSUE TITLE
Corrección de cargue de ARL para pasantía interna.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#549]
Se requiere realizar la revisión y corrección del cargue de la ARL para la modalidad de pasantía interna, esta revisión incluye las peticiones que hace el cliente, en caso de ser una transacción se debe revisar que estas apunten hacia el mid de Pólux, en caso de que no lo haga, se debe verificar que exista la transacción y cambiar el endpoint o crear la respectiva transacción en el mid.

**Sub Tareas**

- [x] Revisar estado de cargue de ARL.
- [x] Realizar correcciones necesarias para el cargue de ARL.
- [x] Pruebas de funcionamiento del cargue de ARL.
- [x] Documentación de correcciones y pruebas realizadas.

**Criterios de aceptación**

- [x] Revisión del estado de cargue de ARL realizada.
- [x] Correcciones realizadas.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se prueba el flujo de cargar la ARL para continuar con la modalidad de Pasantía. Se sube el documento y sale el mensaje de aprobado, pero está apuntando al CRUD, específicamente a la transacción tr_actualizar_documento_tg
![image](https://github.com/udistrital/polux_cliente/assets/129443402/7d7ea3e0-3ac3-4e85-b07f-a10698f89976)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/bf153ea5-3b77-46b5-9c44-be58175fdf33)

A pesar de esto, la página sigue con la opción de cargar ARL y en el menú de Consultar Trabajo Grado no cambia el estado y solicita el cargue de la ARL
![image](https://github.com/udistrital/polux_cliente/assets/129443402/e88d2afc-7fb7-47aa-ba8c-5c24b0223ba3)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/c53db21b-fdbf-44ab-8fa6-75a9277b4681)

Por lo que se debe realizar la migración de la transacción del CRUD llamada tr_subir_arl al API MID y realizar la funcionalidad encargada de realizar los cambios de Estado de Trabajo de Grado de "Pasantía aprobada, en espera de ARL" al estado "Pasantía en curso, en espera de primera versión"

**Comment by JuanDHernandezA** [comment]
Al revisar el flujo que debe tomar la pasantía una vez el estudiante carga la ARL se debe tener un Estado de Trabajo Grado que establezca que se debe esperar a la aprobación de la ARL por parte de la Oficina de Extensión de Pasantía. Por lo que se propone el siguiente Estado

``` bash
INSERT INTO parametros.parametro(
	nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion, tipo_parametro_id)
	VALUES ('ARL Cargada, en espera de aprobación', 'El estudiante cargó el certificado de afiliación de ARL y es necesaria la aprobación por parte de la Oficina de Extención de Pasantías', 'ACEA_PLX', true, 0.00, NOW(),NOW(), 73);
```
![image](https://github.com/udistrital/polux_cliente/assets/129443402/da346667-cc21-48a1-9179-1aeff279c6b6)

Una vez realizado esto, se desarrolla la transacción tr_subir_arl, preparando el documento desde el Cliente y en el MID se almacena en las tablas Documento_Escrito con el tipo de documento "Documentos adicionales asociados a las pasantias"; también se guarda en Documento_Trabajo_Grado, además de cambiar el estado del trabajo de grado al propuesto anteriormente.

Se prueba la funcionalidad desarrollada:
- Se carga la ARL
![Captura de pantalla 2024-06-20 173601](https://github.com/udistrital/polux_cliente/assets/129443402/05b75e17-41f0-41f1-a293-b674d8940926)

- Se verifica en la base de datos si se almacenó de forma correcta:
  - Tabla Documento_Escrito, en donde se observa que se guardó con el tipo indicado
![image](https://github.com/udistrital/polux_cliente/assets/129443402/17e65c8e-6337-43cf-9d23-e0c2e3bc2e8b)

  - Tabla Documento_Trabajo_Grado:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/b325c40e-6640-4116-9163-99774ee37eb1)
  - Tabla Trabajo_Grado, en donde se visualiza el cambio de estado al nuevo propuesto anteriormente:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/da8781b8-b7a4-4e3f-936f-eb4f2e8353a3)

Desde el menú de Consultar Trabajo Grado, ya está habilitada la opción de visualizar la ARL cargada. Se verifica y si corresponde al documento cargado:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/d551b8a8-cfc7-4654-8c57-287c08a86591)

**Comment by JuanDHernandezA** [comment]
Se agregan los rollback en la transacción tr_subir_arl y se verifican que funcionen de forma correcta.

Se verifica que en el menú de Revisión de Documentos ya no permita subir el documento de la ARL. Inicialmente no mostraba nada, pero esto se debía a que se debía agregar el nuevo Estado de Trabajo de Grado a la lista de estados que pueden acceder a este menú. Con esto se corrige el error y la vista se ve correctamente con respecto al estado en el que se encuentra actualmente el trabajo de grado:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/269ac2cc-aa7b-442e-bbab-e680500ea7c2)
