### ISSUE TITLE
Ajuste flujo solicitud inicial para modalidad de pasantía interna.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#550]
Se requiere realizar el ajuste al flujo de aprobación de la solicitud inicial para la modalidad de pasantía interna teniendo en cuenta el [diagrama de flujo](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20POLUX%2F2024%2FEJECUCION%2FAnalista%20de%20requerimientos%2FFlujos%2FFlujo%20pasantias%20%2Edrawio%2Epng&parent=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20POLUX%2F2024%2FEJECUCION%2FAnalista%20de%20requerimientos%2FFlujos) para que este flujo de aprobación no requiera de la aprobación del docente director sino que en su lugar pase directamente al usuario de la oficina de pasantía y posteriormente al coordinador del proyecto curricular.

**Sub Tareas**

- [x] Realizar ajustes necesarios al flujo de aprobación de solicitud inicial para pasantía interna.
- [x] Realizar pruebas del funcionamiento correcto del flujo de aprobación.
- [x] Documentar los ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Inicialmente se busca en la tabla de parámetros de la base de datos si existe un Estado de Solicitud específico para las pasantías. Se encuentran los siguientes registros que servirán para manejar el flujo de la Pasantía Interna:

![image](https://github.com/udistrital/polux_cliente/assets/129443402/12a89e8b-f347-4465-bad3-3bbb85363646)

Partiendo desde el perfil del Estudiante para crear la solicitud de la modalidad, se desarrolla la lógica necesaria para establecer el Estado de Solicitud en "Pendiente revisión por extensión pasantía" para que el siguiente actor del flujo sea el encargado de la Oficina de Extensión de Pasantía y no el Docente Director:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/00afad4b-38f3-49b5-b11b-fd943ada967d)

El formulario se envía de forma correcta y se procede a verificar que la solicitud aparezca en el perfil de Extensión Pasantías.

**Comment by JuanDHernandezA** [comment]
Revisando desde el perfil de la Oficina de Extensión de Pasantías, no aparece la solicitud realizada por el estudiante. Se revisa el código y la lógica para listar las solicitudes tenía un error al momento de consultar el estado de las solicitudes. 
![image](https://github.com/udistrital/polux_cliente/assets/129443402/50be4c54-a5bc-4db3-858a-47c5d1077d24)


Se corrige el error y ya se puede visualizar la solicitud con el estado "Pendiente revisión por extensión pasantía":
![image](https://github.com/udistrital/polux_cliente/assets/129443402/4a087d80-d36a-49d5-ac60-ddab891ef943)

Al momento de aprobar la solicitud muestra el mensaje de "Rechazado" y rechaza la solicitud. Se revisa el código y se encontraron los siguiente errores:

- En el archivo aprobar_solicitud.html, en la etiqueta que controla la respuesta de la solicitud estaba incompleta. Revisando la lógica, se elimina el condicional debido a que no se usa para el nuevo flujo:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/8d7c8a99-d20c-4528-8880-acd577773a42)

- Desde la lógica que prepara el JSON al momento de aprobar la solicitud, no está implementado para las solicitudes con estado "Pendiente revisión por extensión pasantía", por lo que se desarrolla la siguiente lógica para aprobar la solicitud
  - Se crea un condicional que se encarga de verificar el estado de la solicitud mencionada
  - Se implementa la funcionalidad para cambiar el estado a "Aprobado por la oficina de Pasantía" en la tabla respuesta_solicitud
  - Se implementa la funcionalidad para cambiar el tipo de solicitud a "Solicitud Inicial" en la tabla solicitud_trabajo_grado

Una vez realizados los cambios, se prueba la funcionalidad al momento de Aprobar la Solicitud por parte de la Oficina de Extensión de Pasantías. Como se pude observar, funciona de forma correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/6bf0184b-967c-4a65-8f5b-a0f922155f28)

![image](https://github.com/udistrital/polux_cliente/assets/129443402/c4fba70c-358e-4068-8df9-eb60fd2d4560)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/5a6eb7cb-52a3-4aea-b299-ce77e021daf1)

Ahora, desde el perfil del Coordinador se prueba si se lista la solicitud aprobada por la Extensión Pasantía; la cual falla debido a que no se visualiza las solicitudes con estado "Aprobado por la oficina de Pasantía"

Se agrega la funcionalidad y ya se puede visualizar la solicitud:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/784ff0fa-f712-4360-ba81-05bb2f72888b)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/1ae38529-03d7-4560-9ad5-8aa65c289705)

**Comment by JuanDHernandezA** [comment]
Ahora, se prueba rechazar la solicitud por parte de Extensión Pasantía, pero este genera un error. Se revisa el código y el error consiste en que el formato enviado del JSON no corresponde a la modelo de la base de datos. Se corrige el elemento que genera el error:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/491cef38-0c1f-49cb-a0b2-afcad3e9cf96)

Se vuelve a probar Rechazar Solicitud por parte de Extensión Pasantía, el cual se ejecuta de manera correcta
![image](https://github.com/udistrital/polux_cliente/assets/129443402/b668601d-7146-4ae1-97fa-214333ebeae7)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/8ea1c3c7-34a1-43d9-a2d6-810088cd1428)

Ahora, se prueba el flujo con el perfil del Coordinador:

- Se prueba en rechazar la solicitud por parte de la Coordinación. El flujo se hace de manera correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/49578b0c-d92c-42df-a8c8-2e60285c2165)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/86f26304-dd33-4cd0-ba34-7f223a9f1f14)

- Se prueba en Aprobar la solicitud. El flujo se hace de manera correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/c28fb30e-ff19-4dbd-aa0f-1069a0e506b5)
![image](https://github.com/udistrital/polux_cliente/assets/129443402/f7aaa5f8-1331-4261-8725-8b69748cfc08)

Con lo cual se finaliza el flujo de la solicitud inicial con la modalidad de grado de Pasantía Interna.

**Comment by diagutierrezro** [comment]
Buen trabajo Juan Diego
