### ISSUE TITLE
Proyectar un informe técnico ejecutivo del proyecto para el periodo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#553]
Se requiere proyectar un informe técnico ejecutivo sobre cada línea de acción del proyecto para socialización con el patrocinador del proyecto, alimentando el informe del mes anterior: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ERC_-j07j4lMmdAmNCB0ZRABSRGo1EOGVmBf2AboeC0ADg?e=bVL3Uz

**Sub Tareas**

- [x] Establecer avances por cada línea de acción del proyecto en el periodo
- [x] Mencionar las limitantes encontradas en el proyecto en el periodo
- [x] Registrar nuevas líneas de acción del proyecto en el periodo

**Criterios de aceptación**

- [x] Informe ejectivo proyectado y enviado a líder de proyecto

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por líder de proyecto.

**Comment by mantnicot** [comment]
Se ha realizado comentarios de avances con respecto al documentos de avances 

[avances ](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/jcmurilloa_udistrital_edu_co/EbIzkwLpTl1JpboUM1Ex_wABF-dgzIV6EMuNHU3eZj6tqg?e=HsuvFo)

**Comment by diagutierrezro** [comment]
Se actualiza el [documento de insumos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/jcmurilloa_udistrital_edu_co/EbIzkwLpTl1JpboUM1Ex_wABKJaEbThzHlDLZXUlyfE4Ug?e=hIo9To) para el informe técnico.

Se actualizó según los avances de las últimas semanas.

**Comment by jcmurilloa** [comment]
Muy buena información @diagutierrezro y @mantnicot. El informe definitivo y presentación se dispondrán en la respectiva carpeta:  https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EhDMY7HVPXhHjubEgwiKyjQBu3nxmcWcMA89IOXY3G4YOQ?e=E0w08S
