### ISSUE TITLE
Ajustar petición de respuesta solicitud para restringir creación de solicitudes

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#558]
Se requiere realizar el ajuste de la petición respuesta_solicitud la cual verifica que el estudiante tiene alguna solicitd en curso bien sea pendiente por revisar por el docente director o el coordinador, actualmente una vez el docente director da respuesta de aprobado el estudiante tiene permitido crear nuevamente una solicitud debido a que el estado de pendiente por revisar por el coordinador no se está tomando en cuenta para que restrinja la creación de nuevas solicitudes.

**Sub Tareas**

- [x] Modificar la petición de respuesta solicitud para restringir correctamente la creación de solicitudes.
- [x] Realizar pruebas del funcionamiento correcto posterior a la modificación.
- [x] Documentar el issue con modificación y pruebas realizadas.

**Criterios de aceptación**

- [x] Modificación realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Modificar la petición de respuesta solicitud para restringir correctamente la creación de solicitudes y SubTarea N°2: Documentar el issue con modificación.

1. Se modificó el archivo "crear_solicitud.js" en su método "verificarSolicitudes" para que cuando el código de abreviación del estado de la solicitud sea igual a "ADD_PLX" (Solicitud Aprobada por Docente Director) se bloqueé la creación de solicitudes por parte del estudiante:

<img width="783" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/8df373ab-e306-4775-b212-9c5739c2db6d">

**Comment by CrisEs2506** [comment]
SubTarea N°2: Realizar pruebas del funcionamiento correcto posterior a la modificación y SubTarea N°3: Documentar el issue con pruebas realizadas.

1. Se observa que al momento de crear una solicitud por parte del estudiante y esta es aprobada por el docente director, se bloquea automaticamente el sistema para que el estudiante no pueda crear más solicitudes, hasta que la actual en curso se apruebe por el coordinador. 

2. Notese que la query a la base de datos, analiza si el código del estado de la solicitud es 4610 (Radicada), 4628 (Pendiente por revisar por director intero) o el código de la funcionalidad nueva desarrollada 4626 (Aprobada por docente director); y en dado caso de que tenga alguno de estos códigos, bloqueé el sistema para la creación de nuevas solicitudes por parte del estudiante.

![image](https://github.com/udistrital/polux_cliente/assets/65032868/439cfb83-0fed-4842-b854-a79596d9b562)
