### ISSUE TITLE
Ajuste de modalidad pasantia interna para que coincida con la externa

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#559]
Se requiere realizar el ajuste de la interfaz al momento de realizar una solicitud inicial con la modalidad de pasantía interna agregando el NIT y el CIIU debido a que solo se dejará una modalidad de pasantía y en esta se registrará la información necesaria para las dos modalidades. Para esto se deben ajustar los diferentes items solicitados para la actual modalidad de pasantía interna.

**Sub Tareas**

- [x] Agregar registros necesarios a la base de datos para asignar estos "detalles" a la solicitd inicial de la pasantía interna.
- [x] Realizar pruebas del correcto funcionamiento para la pasantía interna verificando que se muestren los campos agregados, NIT y CIIU de una manera similar a como se hace en la modalidad actual de pasantía externa.
- [x] Documentar el issue con los registros agregados y/o modificados en la base de datos y las pruebas realizadas.

**Criterios de aceptación**

- [x] Registros agregados y/o modificados en la db.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan los registros en modalidad_tipo_solicitud para incluir los campos "Ingrese el NIT de la empresa" y "Ingrese el código CIIU (código de actividad económica cámara y comercio)" en el formulario de Pasantía Interna:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/31af14ed-c3f1-40b3-b228-b0f60a6ab093)

Se revisa que los campos queden incluidos y en que orden:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/cb9cba34-9fc4-44a9-b7ed-ccbe1d3a1809)

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza prueba de solicitud inicial en modalidad Pasantía Interna, rol alumno realiza el registro correctamente:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/24da32b4-d169-425c-9acb-ae8fb5799ced)

se revisa en rol Docente director y lista correctamente y se pueden ver los datos de los campos que se incluyeron en la modalidad:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/896bf971-5761-4b5f-9768-57e68158a505)

Se realiza la aprobación correctamente:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/66f6c8de-50a6-4b12-8200-127f2a12f9dd)

**Comment by diagutierrezro** [comment]
Por favor en la base de datos dejar el campo "requerido" del CIIU en false

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza ajuste requerido en BD:


![Image](https://github.com/udistrital/polux_cliente/assets/69996417/001c3320-b412-47d1-85dd-a6bf807e0e33)
