### ISSUE TITLE
Cambio de textos en pasantía interna para que quede solo "pasantía".

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#560]
Se requiere realizar los cambios de los textos en la modalida de pasantía, esto teniendo en cuenta que se defnió que se manejaría una sola modalidad tanto para la interna como externa por lo que se requiere que los textos en esta modalidad hagan referencia unicamente a "pasantía".

**Sub Tareas**

- [x] Cambios de textos realizados para que hagan referencia unicamente hacia pasantía.
- [ ] Documentar issue con los cambios realizados.

**Criterios de aceptación**

- [ ] Textos modificados.
- [ ] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan los cambios de los textos en el código del cliente y en la base de datos respectivamente:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/ef75b0e1-55ff-411b-8f69-d28d4d4741f5)



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/a64cc009-83fa-4786-9b6e-b2772e836d5c)

Se realizan pruebas y en el formulario ya no sale la palabra "interna" o "interno", en la información del docente director en el resumen de la petición inicial la modalidad sale como "pasantía":



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/765a9843-3564-44d9-8db6-e35d19e09d4e)

Al seguir el flujo también se comprueba en el rol de coordinador:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/b2c0d5a5-9d63-46d4-b035-7df6bf594b9d)

Se realiza pruebas terminando el flujo y la modalidad queda llamada "Pasantía".
