### ISSUE TITLE
Realizar presentación de articulos academicos al equipo y al usuario

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#561]
Se requiere realizar las presentaciones al equipo de inversión y al usuario donde se muestre el funcionamiento del sistema en la modalidad de articulos academicos.

**Sub Tareas**

- [x] Presentaciones realizadas al equipo de inversión y al usuario.

**Criterios de aceptación**

- [x] Presentaciones realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Presentaciones realizadas al equipo de inversión y al usuario.

**Presentación al Equipo de Desarrollo**

https://udistritaleduco-my.sharepoint.com/:v:/g/personal/jcmurilloa_udistrital_edu_co/EWn23GeWQRNPkDM8z-oV9gABgfYXWbQ22QMPYM3Gr_gKdQ

**Presentación al Cliente**

https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/P%C3%B3lux%20-%20muestra%20de%20flujo%20de%20producci%C3%B3n%20acad%C3%A9mica-20240620_140459-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=aXhXIG&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D
