### ISSUE TITLE
Actualizar imagenes de los manuales creados para monografía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#562]
Se requiere realizar la actualización de las imagenes  en los [manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ElMcenqrBDVEhPa6hT3AHtUBTBWF4oOQv6ptLSFYDZ1EWw?e=RWHqfE) creados para el piloto en producción de la modalidad de monografía según los acuerdos a los que se habían llegado con Viviana

**Sub Tareas**

- [x] Realizar la actualización de las imagenes en los manuales para modalidad de monografía.

**Criterios de aceptación**

- [x] Imagenes actualizadas en manuales.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Por temas personales del desarrollador se mueve el issue para el siguiente sprint

**Comment by jcmurilloa** [comment]
No se evidencia avance alguno según lo repasado en la presente issue, las tareas se asignaron hace dos sprints.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza actualización de imagenes en los 3 manuales según observaciones en los mismos, adjunto link de Sharepoint donde están ubicados:
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ElMcenqrBDVEhPa6hT3AHtUBTBWF4oOQv6ptLSFYDZ1EWw?e=RWHqfE

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres.
