### ISSUE TITLE
Creación de historias de usuario para artículo académico y pasantía

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#563]
Se requiere realizar la Creación de formatos de historias de usuario para artículo académico y pasantía

**Sub Tareas**

- [x] Creación del formato historias de usuario para artículo académico 
- [x] Creación del formato historias de usuario para pasantía
- [x] Socialización del formatos historias de usuario para artículo académico y pasantía 
- [x] Aprobación del formato de historias de usuario

**Criterios de aceptación**

- [x] Formatos historias de usuario para artículo académico y pasantía
- [x] Docuenmentación de formatos historias de usuario para artículo académico y pasantía

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado la primera versión de las historias de usuario de articulo académico

[Historias de usuario v1](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EVngl0XttU9Kisx5TjqvfJQB_xAEX8P4-arU_E2wpFXyhg?e=RYPmR4)

**Comment by mantnicot** [comment]
Se ha agregado la primera versión de las historias de usuario de pasantías
