### ISSUE TITLE
concertar, desarrollar y levantar el acta de sesión de refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#566]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente respecto a modalidad de artículo académico.

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se realizo la reunión el día 20/06/2024 a las 3 pm

**Comment by mantnicot** [comment]
Se ha realizado el acta 

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ERg8L2I-c-NHg5sjQ3Ur4O4BrMe7tP6RIPnmW7eNejOhYg?e=FdbDkP)

**Comment by mantnicot** [comment]
Se ha recolectado las firmas 

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfKhJqescGtBv5JSQBxwDCUBnQnkQbNUDLei-dp90LVDqg?e=bfpX7L)

**Comment by jcmurilloa** [comment]
Excelente @mantnicot
