### ISSUE TITLE
Realizar correcciones de los errores encontrados en la modalidad de articulos academicos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#567]
Se requiere realizar la corrección de los errores encontrados en #547 iniciando con el error que dejó bloqueado el usuario del coordinador y posteriormente realizar la revisión del erorr que se muestra en el cliente al momento que el coordinador aprueba el cambio de director interno.

**Sub Tareas**

- [x] Realizar ajustes necesarios para desbloquear usuario de coordinador del proyecto curricular.
- [x] Revisar y corregir error al momento de aprobar solicitud de cambio de director interno.
- [x] Realizar pruebas de correcto funcionamiento despues de corregir los errores.
- [x] Realizar documentación de ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Errores corregidos.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar ajustes necesarios para desbloquear usuario de coordinador del proyecto curricular.

1. El coordinador fue desbloqueado satisfactoriamente actualizando un registro en la base de datos con los códigos correspondientes ya que se encontraban en 0.

![image](https://github.com/udistrital/polux_cliente/assets/65032868/4e8dd6ec-ba37-4d66-8e5c-12569f8fc612)

**Comment by CrisEs2506** [comment]
SubTarea N°2:  Revisar y corregir error al momento de aprobar solicitud de cambio de director interno.

1. Se corrió el MID de manera local y se logró apreciar el siguiente error:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/5b2def25-ee4f-4749-b0ed-a92566c292d2)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/56cbd714-756a-4a6c-a17e-9357b907ec75)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/3367616b-7f6f-4fad-bdc7-a21d7a8a612f)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/feae52ab-9f1c-4077-8d99-04eb56954a4e)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/b7115ea5-0016-4249-990d-d7fa98d1ff06)

**Comment by CrisEs2506** [comment]
Será que es posible aumentar los puntos de historia del ISSUE? Es que siento que en un tiempo de 5 puntos no era suficiente para arreglar este error, muchas gracias :(

**Comment by CrisEs2506** [comment]
SubTarea N°3:  Realizar pruebas de correcto funcionamiento despues de corregir los errores y SubTarea N°4: Realizar documentación de pruebas realizadas.

1. El MID ya responde de la manera correcta, sin ningún tipo de error:

<img width="743" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f9e149cb-3dc8-4101-a368-a08995d6f440">

2. El cliente responde con el cuadro de dialogo de forma correcta:

**Comment by CrisEs2506** [comment]
SubTarea N°2: Corregir el error al momento de aprobar solicitud de cambio de director interno y SubTarea N°4: Realizar documentación de ajustes:

1. El código de "AddTransaccionRespuestaSolicitud" está tratando de actualizar una revisión de trabajo de grado aunque la consulta no encontró ninguna revisión pendiente. Esto es lo que causa que "revisionTrabajoGrado" contenga un objeto con valores por defecto (con campos nulos), lo que posteriormente lleva a un comportamiento incorrecto cuando se realiza el PUT.
2. La solución fue sencilla, añadiendole una verificación adicional para asegurar que la revisión encontrada es válida:

<img width="712" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/b5cd1205-6b35-4b51-b3f1-fbbab8fdc8e5">
