### ISSUE TITLE
Ajustes solicitados

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#571]
Se requiere realizar ajustes solicitados en la reunión que se realizó en #561 para modificar aspectos visualies del sistema.

**Sub Tareas**

- [x] Realizar modificación del texto donde se carga el documento para la solicitud de revisión, indicando todos los documentos que se deben subir y unir en un único PDF.
- [x] Redactar de mejor manera el texto donde se elige la clasificación de la revista, para que exista una mejor experiencia de usuario.
- [x] Modificar para que el link de la revista se vea como un hipervinculo y redirija al link suministrado.
- [x] Realizar pruebas de funcionamiento correcto de las tareas realizadas.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Modificaciones realizadas.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar modificación del texto donde se carga el documento para la solicitud de revisión, indicando todos los documentos que se deben subir y unir en un único PDF.

**Comment by CrisEs2506** [comment]
SubTarea N°2: Redactar de mejor manera el texto donde se elige la clasificación de la revista, para que exista una mejor experiencia de usuario.

**Comment by CrisEs2506** [comment]
SubTarea N°3: Modificar para que el link de la revista se vea como un hipervinculo y redirija al link suministrado.

**Comment by CrisEs2506** [comment]
SubTarea N°4: Realizar pruebas de funcionamiento correcto de las tareas realizadas.
