### ISSUE TITLE
Creación de vista para aprobación de ARL

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#575]
Se requiere realizar la vista para realizar la aprobación de la ARL por parte del usuario de pasantias, inicialmente se abordará la creación inicial de la tabla donde el usuario de EXTENSION_PASANTIAS pueda ver las ARL que se han aprobado o las pendientes por aprobar que inicialmente deben contener el nombre del estudiante, estado y acciones a realizar (queda pendiente realización de mockups por parte de @mantnicot para definirlo mejor).

En la columna de acciones se manejaran dos botones, uno solo para visualizar la información y otro donde se muestra la información y se puede dar una respuesta de la solicitud, en los dos se debe ver la información que se defina (según mockups) sobre el trabajo de grado y la ARL.

El alcance del issue llegará hasta la aprobación de la ARL donde se define que el estado del trabajo de grado cambiará a "Pasantía en curso, en espera de primera versión" donde ya se podría iniciar como tal el trabajo de grado en la modalidad de pasantía.

**Sub Tareas**

- [x] Creación de tabla de visualización general de ARL (aprobadas y pendientes por aprobar).
- [x] SOLO visualización de la solicitud de aprobación de ARL.
- [x] Vista de aprobación o rechazo de solicitudes de aprobación.
- [x] Aprobación de la solicitud.
- [x] Pruebas de funcionamiento en ambiente local.

**Criterios de aceptación**

- [x] Creación de tabla inicial realizada.
- [x] Solo visualización realizada.
- [x] Vista de acciones (Aprobar o rechazar) realizada.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se crean los archivos necesarios para el desarrollo de la nueva vista: un archivo .html y su respectivo controlador .js ambos con el nombre de revision_arl.

En el archivo app.js se agrega la nueva ruta para acceder a la nueva ventana, indicando la vista y el controlador:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/41e50118-ef81-48c3-a0c6-0bc1a5030907)

Se desarrolla la lógica para recuperar los trabajos de grado con el estado de "Acta Cargada, en espera de aprobación", y mostrarlos en una tabla siguiendo las indicaciones:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/273355f9-a15e-4529-9af0-374058d84a26)

**Comment by JuanDHernandezA** [comment]
Para los modals de los botones de acciones se realizó un cambio en la transacción de la solicitud inicial para poder almacenar en la tabla detalle_trabajo_grado el nombre de la empresa, el NIT y el CIIU de la empresa donde se realizará la pasantía:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/60d81b08-2565-4d53-bbfa-b0c2a01ef608)

Una vez realizados estos cambios, se realiza la funcionalidad para recuperar los datos asociados al trabajo de grado que se requieren para la vista de "Ver Detalles" y "Revisar ARL".

Se muestra la información en ambas vistas:
- Ver Detalles:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/2603cf0a-7620-4241-a5fc-f5a7450c59be)

- Revisar ARL:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/4af1451a-a8bd-4f73-b3c0-44b395165d29)

**Comment by JuanDHernandezA** [comment]
Se desarrolla la funcionalidad para aprobar la ARL cargada por el estudiante:

- Cuando el usuario de Extensión Pasantía aprueba la ARL aparece el siguiente mensaje:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/3c4099c9-e4ab-43cd-9cb2-4b3dcfe6b4fa)

- Y posterior se puede observar que el estado del trabajo de grado cambió a "Pasantía en curso, en espera de primera versión" y en este estado el usuario no puede enviar una respuesta:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/094e77f9-0621-4d8b-891a-76c84bf3c7b7)
