### ISSUE TITLE
Revisión de estado modalidad de emprendimiento

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#576]
Se requiere realizar la revisión del estado actual para la modalidad de emprendimiento para conocer el comportamiento del sistema en esta modalidad y realizar los respectivos ajustes en caso de ser necesario.

**Sub Tareas**

- [x] Realizar revisión del estado actual en ambiente de pruebas.
- [x] Documentar hallazgos encontrados.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza revisión del estado y funcionamiento de la modalidad de emprendimiento.

Solicitud Inicial estudiante:

![Image](https://github.com/udistrital/polux_cliente/assets/69996417/42ad5dc6-168c-4045-94a5-d6a139ff4b46)

se realiza exitosamente:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/eb2fa958-673f-418e-8f34-6b3b919bb6a9)

Siguiendo el flujo se revisa desde el rol de docente director la solicitud y se aprueba exitosamente:



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/8bc9d447-8a64-4b36-944d-f06c800436fa)

Ahora desde el rol de coordinador igualmente se aprueba exitosamente.

El siguiente paso desde el rol estudiante se sube versión del documento del proyecto y se solicita revisión 

![Image](https://github.com/udistrital/polux_cliente/assets/69996417/e561111e-5f29-4236-9e4f-75136d20e9b3)

El docente director revisa y hace comentarios


![Image](https://github.com/udistrital/polux_cliente/assets/69996417/8e9354f7-e6e3-46f3-a78b-072b3cd8285a)

Se viaualizan desde rol estudiante



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/388fdb27-c198-44a5-8fc2-35be62a5fe5c)

Ahora se realiza solicitud de revisión de proyecto de grado por parte del estudiante



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/1731cbab-64ff-4e84-ba1d-87de5d71a2ed)



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/171af984-b024-4334-9319-e548c8974d35)

Se realiza prueba desde docente director realizando rechazo exitosamente 

![Image](https://github.com/udistrital/polux_cliente/assets/69996417/69686b76-2ba5-4534-a877-c6e69e7bcf3a)

se repite el flujo de solicitud de revisión de proyecto de grado para realizar prueba con aprobación del docente director exitosamente 

![Image](https://github.com/udistrital/polux_cliente/assets/69996417/03f372f7-7542-4ff5-bc0e-6b95cfc14de6)

**Comment by Astaroth-Andres-Molano** [comment]
Ahora se rechaza por parte del coordinador para realizar más pruebas y seguir el flujo



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/c67e08a7-9b8c-4eb9-8139-698b7fc6b2d8)

Por parte del estudiante se genera solicitud de cambio de título de proyecto



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/4d723c9a-29f6-4f52-aa09-fceac3dd97d5)

Se revisa solicitud y se aprueba por parte del docente director



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/285a3492-b53c-4e39-93ac-f7e14b08a0d3)



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/200fcef3-8fcb-4dc0-ad1e-881e5c913b03)

Se revisa y aprueba por parte del coordinador la solicitud



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/c1915a16-fd16-4089-8d86-a775fe79e584)



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/37108609-587e-42c8-9ab7-9f1341b811ab)

Ahora se prueba la solicitud de cancelación de modalidad flujo que inicia desde el estudiante



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/0c99c8cc-5887-4d1b-8b6e-4c4ae021d7ad)

Aprobación de la cancelación por parte del docente director



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/a15f7586-42fa-4c09-aa58-a970b524f356)

Ahora aprobación por parte del coordinador
![Image](https://github.com/udistrital/polux_cliente/assets/69996417/bc41da3b-a2c5-4095-a6c5-3613242fbbef)
Nuevamente se inicia el flujo desde cero, se llega al punto donde el estudiante solicita revisión del proyecto de grado



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/82ec8b82-8598-4c68-b678-d0123489a287)

Se aprueba por docente docente director

![Image](https://github.com/udistrital/polux_cliente/assets/69996417/29d75915-26bc-4eb6-90a7-b83120ec2bd3)

se aprueba por coordinador, el siguiente paso será la calificación por parte del evaluador


![Image](https://github.com/udistrital/polux_cliente/assets/69996417/fc59ab3e-b0c0-47dc-88ac-1cdcda0afcd7)



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/db8ed8ac-43e8-4b09-8817-c170d3021b26)

Siguiente paso será la calificación por parte del docente director



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/95e39f9a-79ed-4041-90ca-3feb45d9b627)



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/4bfcee87-f90e-44e5-8ae8-59fac1fb4476)

y por último la consulta de las calificaciones por parte del estudiante



![Image](https://github.com/udistrital/polux_cliente/assets/69996417/33ed090f-6090-4936-b480-c59c7899e242)

**Hallazgos:**

No se encuentran errores en el funcionamiento de la Modalidad de Proyecto de Emprendimiento.
