### ISSUE TITLE
Analizar cambio de flujo para estudiante de diferentes proyectos curriculares.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#577]
Se requiere realizar el analisis de los cambios a realizar para la modificación del flujo inicial que incluye la aprobación por los diferentes proyectos curriculares cuando los estudiantes son de diferente proyecto curricular y cada proyecto curricular define su docente evaluador.

Tener presente que si bien el analisis es para el flujo inicial se deben realizar cambios a futuro relacionados especialmente con el registro de la nota de los docentes evaluadores.

**Sub Tareas**

- [x] Analisis realizado.
- [x] Documento con cambios a realizar según el analisis.

**Criterios de aceptación**

- [x] Analisis finalizado.
- [x] Documento realizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Analisis realizado y SubTarea N°2: Documento con cambios a realizar según el analisis.

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/cdespitiav_udistrital_edu_co/EWdL9Ip52AJGlRP74Kz0e30Br01B-DQcfotGT40oCS6iQw?e=PfVMLg
