### ISSUE TITLE
Actualización diagrama de flujo de monografia para dos estudiantes de diferentes proyectos curriculares

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#578]
Se requiere realizar la actualización del diagrama de flujo de la modalidad de monografia según requerimientos recientes de cliente para dos estudiantes de diferentes proyectos curriculares

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente
- [x] Presentar al equipos SoS diagrama actualizado
- [x] -Aprobar con el cliente diagrama actualizado

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo de monografía para dos estudiantes de distintos proyectos curriculares 



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/d4a951c4-89c7-4136-aaa5-87927615986c)
[Carpeta flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Em6Cq_pJnLFCuNG-izuXrgIB7JOw3aAUfr3WWJVqnb3b7w?e=6ugyY6)

**Comment by jcmurilloa** [comment]
Buen diseño @mantnicot, etner en cuenta las recomendaciones generadas por el equipo SoS por favor.

**Comment by mantnicot** [comment]
Se ha realizado los cambios dados por el equipo al flujo



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/b5340f3f-a99c-41c4-ac37-ea83d8728a14)

[Carpeta flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpAbyBvIv7tIg6kYaQMHoCsBjx3dz8009kXfl-5Mru892w?e=WU5dBl)

**Comment by mantnicot** [comment]
Se ha podido hablar con el cliente con respecto al flujo y se hizo cambios en el flujo 




![Image](https://github.com/udistrital/polux_cliente/assets/85162258/f556cb9d-851b-4ba5-9847-a96a9d039388)



[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnVzi326BaxLt35NF85ryKEBerfYjxZ49iA4Lskt5dEbpQ?e=Mr7fvP)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, en la proxima sesión SoS nos actualizas los cambios generados por el cliente por favor.

**Comment by jcmurilloa** [comment]
Tener en cuenta las reomendaciones brindadas en la sesión SoS y volver a cargar.

**Comment by mantnicot** [comment]
Se ha realizado los cambios hablados en la reunión con el equipo de desarrollo



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/aa122bad-2e7a-4e3a-b7f8-d42f153b6e9a)

[Carpeta del flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Evzflk7SwxJIlpClmEO5xr8BNo1Mox2aa_Kc5vbfCDBfuQ?e=T3k8m8)

**Comment by jcmurilloa** [comment]
Excelentre trabajo @mantnicot, ten en cuenta para los siguientes flujos, graficar los diferentes estados del objeto, en este caso, identificar los estados de la monografía desde el inicio hasta el final.
