### ISSUE TITLE
Pruebas de funcionamiento para modalidad de producción articulos académicos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#580]
Se requiere realizar la revisión del flujo completo en la modalidad de producción de articulos academicos. Estas pruebas incluyen la aplicación de las diferentes novedades que se pueden aplicar tanto si el trabajo de grado es realizado por un estudiante o dos, registrar las pruebas realizadas de acuerdo al [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/cdespitiav_udistrital_edu_co/EeKlZCOxnvRMkFSBVuCC8CwBf94lazr7R6PDwb4swSMBxw?e=LiTgvL).

**Especificaciones tecnicas**
- El último desarrollo estable debe encontrarse desplegado en ambiente de pruebas.

**Sub Tareas**
- [x] Realizar pruebas donde un trabajo de grado en la modalidad de producción de articulos académicos se realice por uno o dos estudiantes al tiempo, estas pruebas incluyen las diferentes novedades que se puedan aplicar al trabajo de grado. 

**Criterios de aceptación**

- [x] Pruebas funcionales realizadas.
- [x] Documentación de las pruebas realizadas y los errores presentados (en caso de que existan).

**Requerimientos**
No aplica

**Dependencias**
- Actualmente el CRUD de Pólux no se encuentra desplegado correctamente por errores con la conexión hacia base de datos, por lo que es necesario que este error se encuentre corregido al momento de realizar las pruebas.
- Los dos usuarios con los que se cuenta actualmente en Pólux no deben contar con trabajos de grado activos para poder desarrollar las pruebas.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar pruebas donde un trabajo de grado en la modalidad de producción de articulos académicos se realice por uno o dos estudiantes al tiempo, estas pruebas incluyen las diferentes novedades que se puedan aplicar al trabajo de grado:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/cdespitiav_udistrital_edu_co/EaXFWegLMclBt5PUfIC0F7cBgsRnknSVamXsJ0_mSGv_EA?e=DKoM0r

**Comment by diagutierrezro** [comment]
Muy buen trabajo Cristian.
