### ISSUE TITLE
Definir los requerimientos respecto a módulo de reportes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#581]
Se requiere realizar la definición de los requerimientos con el cliente respecto a módulo de reportes

**Sub Tareas**

- [x] Concertar reunión.
- [x] Desarrollar la reunión.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado la primera propuesta de reportes para el cliente

[Propuesta reportes](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmuIaFmIHx5Curp_DOskg40BT9tITVB8QkCrNUZqq8wwFw?e=65juer)

**Comment by jcmurilloa** [comment]
Se expondra en la mesa de seguimiento a proyectos la necesidad de definición del manejo de reportes

**Comment by mantnicot** [comment]
Se ha establecido en la reunión de seguimiento , que el manejo de reportes se puede proponer desde el equipo de desarrollo y así mismo se dará prioridad a reportes estáticos , formato tabla , como primer alcance

**Comment by jcmurilloa** [comment]
Pendiente continuar con el refinamiento de este requerimiento con los responsables, según comentarios realizados en sesión de seguimiento de proyecto.
