### ISSUE TITLE
Diseñar el mockup para la vista de aprobación de ARL

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#582]
Se requiere diseñar el mockup para la vista de aprobación de ARL. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo el mock definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado los mockups de aprobación en arl para el rol de oficina de extensión de pasantia

![Image](https://github.com/udistrital/polux_cliente/assets/85162258/aade5edf-16f5-4895-a674-8cb3102bc06a)
![Image](https://github.com/udistrital/polux_cliente/assets/85162258/d0dcc99e-172c-4903-a06c-5073544ac350)
![Image](https://github.com/udistrital/polux_cliente/assets/85162258/c6580e86-8169-4c8b-83d9-69256c1bbb51)

[Carpeta de los mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkvUrNolhihIq0T7-aBiGL4B5U_U0nvtnbth_crdQLHJyQ?e=F2CiKR)

**Comment by jcmurilloa** [comment]
Pendiente generar modificaciones según el refinamiento de los estados en el sistema por medio de documento de parametrización, y compartir nuevamente.

**Comment by mantnicot** [comment]
Se ha realizado los cambios de parte del equipo



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/00d52641-d9cd-4e19-984b-011d3ca9ef5e)
![Image](https://github.com/udistrital/polux_cliente/assets/85162258/56332bc6-bd02-4d27-a19e-6deac69be1cd)
![Image](https://github.com/udistrital/polux_cliente/assets/85162258/7c855b2a-1001-457e-920f-ec95bf764f0b)

[Carpeta mockup](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EooVcnt7ZBdDqh3LsW9k8w8B49GcxLOP45vGlau4ddhIig?e=p6Cewp)

**Comment by jcmurilloa** [comment]
Excelente diseño @mantnicot!
