### ISSUE TITLE
Continuar flujo de aprobación de ARL para modalidad de pasantía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#585]
Se requiere realizar la continuación del desarrollo del flujo de aprobación de la ARL de la modalidad de pasantía que se viene desarrollando en #575, se continua con el flujo al momento de rechazar la ARL que se ha cargado

**Sub Tareas**

- [x] Flujo para rechazo de ARL desarrollado.
- [x] Pruebas de funcionamiento en ambiente local.

**Criterios de aceptación**

- [x] Flujo de rechazo realizado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se crea el nuevo Estado de Trabajo de Grado para cuando se rechace la ARL:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/25b7c95e-91a5-42ac-b5a2-9f4af612403c)

Se rechaza la ARL desde el perfil de Extensión Pasantías:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/9750e984-816d-427f-b755-d930771d5222)

Se verifica el nuevo estado del trabajo de grado, en donde se visualiza el estado creado:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/3276f849-e1f8-45fe-9104-c581024d1aa2)

Se verifica que el estudiante pueda cargar la ARL en el menú de Revisión de Documentos, pero como se puede observar no permite la carga de la ARL:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/4edc1001-4f27-40a4-afc3-a241ec4b161f)

**Comment by JuanDHernandezA** [comment]
Desde el cliente, se modifica la vista para que los trabajos de grado con el estado de "ARL Rechazada" puedan visualizar el menú de Cargar ARL:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/4a44b9a8-2aa8-4431-87d1-88462acc8810)

Debido a que ya hay un documento de tipo "Documentos de pasantías", el cual es usado para identificar la ARL de la pasantía, al momento de cargar la nueva ARL se debe actualizar el id del documento en el registro de documento_trabajo_grado donde se asocia la anterior pasantía con el trabajo de grado.

Se realiza dicho cambio en la transacción tr_subir_arl y se verifica que el trabajo de grado solo tenga un documento de tipo Documentos de pasantías (Id 78):

![image](https://github.com/udistrital/polux_cliente/assets/129443402/7339ba72-ec32-4424-9eba-0111d47e00c2)

Se verifica también que el estado del trabajo de grado sea "ARL Cargada, en espera de aprobación" y se verifica que se visualice de forma correcta el documento de la ARL:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/a5efd353-a8d0-459d-a561-d418bf2e8e8f)

Desde este punto el flujo continua como si fuera la primera vez que el estudiante carga la ARL.

Adicional a esto, se corrige la vista de Revisión ARL cuando no hay pasantías activas o ARL pendientes por revisar:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/068eb9cb-a198-4869-868a-3ab9baa3a721)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego.
