### ISSUE TITLE
Revisión del estado posterior a la aprobación de la ARL por parte de la oficina de pasantía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#586]
Se requiere realizar la revisión del estado de la modalidad de pasantía una vez la ARL ha sido aprobada. Documentar errores encontrados

**Sub Tareas**

- [x] Revisión del estado posterior a aprobación de ARL.
- [x] Documentación de errores encontrados.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Una vez la oficina de extensión de pasantía aprobó la ARL, el trabajo de grado queda en estado: "Pasantía en curso, en espera de primera versión". Se entra al menú de Revisión Documentos para cargar la primera versión, pero sale la siguiente advertencia:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/16a9cf00-b6f9-4690-8dc0-4616dc268870)

Revisando las peticiones, se puede observar que no busca los trabajos de grado con el estado mencionado, cuyo ID es 4590:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/28743d89-9b8f-4b7b-bf6a-7594522bf59a)


Por lo que se debe agregar el código de abreviación a los estados permitidos en esta vista

**Comment by diagutierrezro** [comment]
Se asumirá la corrección del error en otro issue, buen trabajo.
