### ISSUE TITLE
Actualización diagrama de flujo general y de sistema para modalidad de emprendimiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#588]
Se requiere realizar la actualización del diagrama de flujo general y de sistema para modalidad de emprendimiento

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente
- [x] Presentar al equipos SoS diagramas actualizados
- [x] Refinar diagramas según revisión de equipo SoS
- [x] Aprobar con el cliente diagramas actualizados

**Criterios de aceptación**

- [x] Diagrama de flujo del sistema actualizado
- [x] Diagrama de flujo general actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo de emprendimiento tanto general como de sistemas



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/3c73b023-33a7-4013-9846-c53f0011008e)
![Image](https://github.com/udistrital/polux_cliente/assets/85162258/f8bf0e8a-2fe1-41e1-9888-0261e8c5a1f4)


[Carpeta de flujos v1](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtlifY2Gy_1Gmux6-nvGoNIBGUhyEu6GiiMFgE3gkw_KyA?e=5tV8jL)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, lo revisamos en la prócima sesión SoS!

**Comment by jcmurilloa** [comment]
Por favor @mantnicot, actualizar al nuevo modelo de flujo.
