### ISSUE TITLE
Desarrollar reunión de control del equipo del proyecto piloto producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#589]
Se requiere desarrollar reunión de control del equipo del proyecto piloto producción

**Sub Tareas**

- [x] Concertar reunión con el equipo del proyecto
- [x] Desarrollar la reunión con el equipo del proyecto
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se adjunta el acta sin firmas

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ea1k3DUCjHBIiRWJCp1DfOEB0jQiQQ9DC9RyKe27v5VJtw?e=qaLCDe)

**Comment by jcmurilloa** [comment]
@mantnicot el acta es clara, recuerda que aquí en la issue podemos comentar de manera más completa, desde la concertación de la reunión mencionando la fecha y hora, hasta adjuntar el enlace de la grabación. Todo esto se menciona en el acta, sin embargo, con el fin de diminuir os tiempos de revisión de los criterios de aceptación por parte del equipo de la OATI, podríamos comentar estos aspectos de manera cronológica.

**Comment by mantnicot** [comment]
Se sube el acta firmada por todos los asistentes

[ACTA FIRMADA](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETEBEZvCsNdDjxfq7FDwP5EBrutp0Hqy_i7bODoPAPOqfQ?e=r72esT)

**Comment by jcmurilloa** [comment]
Gracias @mantnicot, ten en cuenta las recomendaciones brindadas en esta issue.
