### ISSUE TITLE
Corregir visualización de documento en vista de consultar trabajo de grado

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#591]
Se requiere realizar la corrección de la visualización de documentos ya que solamente aparece el UID de nuxeo pero no permite la visualización, se recomienda usar como guía la visualización que se da en el listado de solicitudes, especialmente en las solicitudes iniciales o solicitudes de revisión.

**Sub Tareas**

- [x] Corrección de visualización de documentos.
- [x] Pruebas de funcionamiento en ambiente local.

**Criterios de aceptación**

- [x] Corrección realizada.
- [x] Pruebas de funcionamiento en ambiente local realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Corrección de visualización de documentos.

1. En el archivo 'listar_solicitudes.html' dentro de la carpeta de 'directives' se actualizó los 'ng-if' para que tengan en cuenta los códigos de abreviación de las peticiones realizadas y no de los nombres como se encontraba anteriormente:

<img width="834" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/95988e07-997d-4a43-8ecb-73627f32afdb">

2. En el archivo 'listar_solicitudes.js' se añadió al método 'cargarDetalles' una consulta GET que trae los detalles de la solicitud y que es fundamental para conocer los códigos de abreviación de la base de datos, con el fin de que funcione correctamente los 'ng-if' mostrados anteriormente: 

<img width="667" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/7bd753d0-0bfe-45ee-9561-c9b49e1cbcd2">

3. En el archivo 'listar_solicitudes.js' se actualizó el método 'getDocumento' y se importaron las librerias faltantes para que traiga el documento que antes no estaba:

<img width="842" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/aed45fa8-fda4-40a4-bf59-ef44fea1db31">

<img width="829" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f4826217-d919-46cb-9ebd-a44137fc10a9">

**Comment by CrisEs2506** [comment]
SubTarea N°2: Pruebas de funcionamiento en ambiente local.

1. Se observa que al momento de ver los detalles de una solicitud desde el apartado de Consultar Trabajo de Grado, está genera el link al documento y traduce el id de la revista a su respectiva descripción de manera correcta:

<img width="626" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/cb5073ae-bd55-43d8-a850-b68a88dc4168">
