### ISSUE TITLE
Analisis y cambio a estructura de base de datos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#592]
Se requiere realizar el analisis y posteriormente los cambios en la base de datos para poder asociar un docente evaluador  bien sea con un proyecto curricular o con un estudiante, esto para preveer el registro de notas en el flujo final de la modalidad.

**Sub Tareas**

- [x] Realizar analisis de cambios a realizar en la base de datos.
- [ ] Realizar cambios definidos en la base de datos.
- [ ] Realizar pruebas de funcionamiento, importante verificar que el flujo anterior sigue funcionando correctamente.

**Criterios de aceptación**

- [x] Analisis realizado.
- [ ] Cambios en la base de datos realizados.
- [ ] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Moficaciones a bases de datos.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar analisis de cambios a realizar en la base de datos.

1. Al momento de crear la solicitud inicial de un Trabajo de Grado se ejecuta una petición llamada 'Registrar' la cual se encarga de verificar los requisitos del estudiante actual y ver sí es posible que realice dicha modalidad de grado:

![image](https://github.com/udistrital/polux_cliente/assets/65032868/04b01561-3f5d-4d75-83f1-38402dd50fa2)

![image](https://github.com/udistrital/polux_cliente/assets/65032868/6f9dfc8a-0a11-4f45-a133-5558f981bd3a)

Allí se puede observar como el response trae un campo llamado 'Carrera' con el respectivo código del proyecto curricular del estudiante, allí haremos enfasis para que cuando se agregue el segundo estudiante se compare dichos códigos y en caso de ser diferentes se realice una lógica diferente para el momento de enviar las solicitudes a los dos coordinadores de los dos proyectos curriculares.

PD: Lo anterior comentado es equivalente a la solicitud '3' que se ejecuta al agregar el código del segundo estudiante en el formulario de solicitud inicial:

<img width="761" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/af14415c-9691-4a9f-b63b-f28217f93af1">

**Comment by diagutierrezro** [comment]
Aún no se realizará implementación ya que se debe realizar reunión con el usuario para confirmar que se continúa con el cambio, se mantiene issue abierta y según lo acordado con el usuario se implementa o se cierra el issue.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar analisis de cambios a realizar en la base de datos.

Para el tema de que un Docente Evaluador pueda calificar a su Estudiante de Proyecto Curricular únicamente, propongo que se duplique el trabajo de grado para que se califique por aparte pero que se trabaje en conjunto, en este orden de ideas:

1. Crear duplicado de datos para la tabla 'detalle_solicitud' con diferente id de llave foranea 'solicitud_trabajo_grado':

<img width="678" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/4e06abf0-13c0-44f1-88fa-edb6eadf08a3">

Se crearían dos solicitudes de trabajo de grado en la tabla 'solicitud_trabajo_grado' con el fin de que se pueda asociar ambas llaves fóraneas en la tabla 'solicitud_trabajo_grado' y dos llaves foraneas de 'trabajo_grado':

<img width="569" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/bd6e80be-437f-4fc1-bd85-365453bbc66e">

2. En la tabla de 'usuario_solicitud' un estudiante se asociaría con la otra llave foranea que se creo en la tabla 'solicitud_trabajo_grado':

<img width="680" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/f8c780f5-b449-4bd0-b491-bf7a6ce4ce31">

3. De igual manera en la tabla 'respuesta_solicitud' se duplicaría la solicitud de "Radicada" con diferente 'solicitud_trabajo_grado' y adicional cada respuesta del ente responsable (sea Docente Director o Coordinadores) iría a su correspondiente solicitud.

<img width="683" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/aff74a29-cb90-44f5-a9e9-526a2ed0db1c">

4. En el momento en que se apruebe la solicitud inicial se crearan dos trabajos de grados pero con los mismos documentos y la misma información:

<img width="680" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/16dc9924-8d06-40e2-b46f-277c8d4c52ec">

5. La vinculación de los entes en la tabla 'vinculacion_trabajo_grado' se haría un duplicado para el caso del docente director tan solo que a la diferente llave foranea de 'trabajo_grado' y para los coordinadores sí simplemente se asignaría al trabajo de grado de su estudiante de proyecto curricular:

<img width="680" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/3fb8564b-b0af-4414-b096-687879326ae3">

6. Los registros de la tabla 'estudiante_trabajo_grado' se encontraría cada estudiante asociado a su respectivo 'trabajo_grado', muy similar al registro de la tabla 'solicitud_trabajo_grado' (#2 de este comentario):

<img width="463" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/e008507e-ad80-4c49-ade2-f53142cbad8a">

7. Finalmente para el tema de la 'evaluacion_trabajo_grado' solo es cuestión de asociar todas las llaves foraneas de la tabla 'vinculacion_trabajo_grado' y colocar su respectiva nota, con la particularidad de que el Docente Director colocará la misma nota para sus dos registros:

<img width="548" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/1a24d855-75f7-4447-b2fd-10c27bb0b14e">

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar analisis de cambios a realizar en la base de datos.

**Opción 2**

1. Todo el flujo se realiza como se comentó al comienzo, sin embargo, al momento de que se aprueba la Solicitud Inicial, en la tabla 'vinculacion_trabajo_grado' se añadirá un nuevo registro con el docente evaluador adicional y se creará una nueva columna llamada 'estudiante' donde solo para este caso (estudiantes de diferentes proyectos curriculares) se agregue el código del respectivo estudiante, logrando coincidir la 'Carrera' del estudiante y del docente evaluador.
Esto con el fin de que en la tabla 'evaluacion_trabajo_grado' se asocien los 3 campos de 'vinculacion_trabajo_grado' y que cada docente evaluador pueda calificar a su respectivo estudiante:

![Imagen de WhatsApp 2024-07-08 a las 13 28 15_c66c25d3](https://github.com/udistrital/polux_cliente/assets/65032868/e234ce83-896f-4e34-b3dd-fa60a6072f12)

**Comment by diagutierrezro** [comment]
Despues de hablar con el usuario se define que los trabajos de grado que tengan estudiantes de diferentes proyectos curriculares realizarán la solicitud por separado por lo que este cambio ya no es necesario, se cierra el issue.
