### ISSUE TITLE
Revisión de cambios realizados por X-Ray

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#593]
Se requiere realizar la prueba de que todo funciona correctamente en la rama de X-Ray por los cambios realizados en la instrumentalización, en caso de haber errores por favor documentarlo en el issue.

**Sub Tareas**

- [x] Pruebas realizadas.
- [x] Errores documentados (en caso de que existan)

**Criterios de aceptación**

- [x] Pruebas finalizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Para realizar las pruebas de la funcionalidad de X-Ray se optó por usar la modalidad de grado de monografía.

Las funcionalidades que funcionaron de forma correcta fueron:
- Listar Solicitudes por Estudiante
- Listar Solicitudes por Docente
- Listar Solicitudes por Coordinador
- Ver detalles de solicitud
- Aprobar solicitud por Docente
- Consultar Trabajo Grado
- Aprobar solicitudes por Docente
- Solicitar revisión de documento
- Subir nueva versión del documento: Correcto
- Publicar comentario en Revisión

Las funcionalidades donde se encontraron errores fueron:
- Solicitud Inicial: Error al momento de enviar la solicitud:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/b0584c20-e0bb-414f-a61b-9836b8e7db75)
- Aprobar solicitud por Coordinador: Error al momento de enviar la respuesta:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/697d42c3-7d62-4855-80b4-9b061553d98c)

  - A pesar del error, el estado de la solicitud cambió:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/966a0a9c-f28a-4f67-bfb4-944209ddf326)

  - Pero no quedó registrado el trabajo de grado:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/c3fbf274-f552-46c6-83f6-f9af58808c44)

- Crear cualquier solicitud: Error al momento de enviar la solicitud:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/a7ec64ff-a3d9-484f-9cc9-250a11516d5f)

  - A pesar de que sale el error, las solicitudes quedan registradas:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/fa76293c-d5a4-484b-aa38-2d7f0ea7cc90)

- Registrar revisión por Docente: Error al momento de Guardar Revisión:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/0f49dbd3-def8-4087-bc68-4bdc25b0a803)

- Registrar nota por Docente Director y Evaluador: 
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/2c508c3f-c075-4be1-bdcc-6025405d3796)

- Registrar revisión por Docente Evaluador: Error al momento de enviar los comentarios:
![Image](https://github.com/udistrital/polux_cliente/assets/129443402/d915b74f-3080-4266-aef6-692564dcb126)

En resumen, las transacciones que presentan error son:
- tr_solicitud
- tr_respuesta_solicitud
- tr_registrar_revision_tg
- tr_vinculado_registrar_nota

**Comment by JuanDHernandezA** [comment]
Revisando el error que sale por consola, se imprime los datos que llegan a la transacción tr_solicitud y la respuesta de la primera petición que se hace. Se puede observar que los datos llegan de forma correcta, pero la respuesta de la solicitud POST llega vacía, por lo que genera el error y no se puede continuar con el flujo de manera correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/233cf6ab-8545-445b-8390-d92c979e40ac)

**Comment by diagutierrezro** [comment]
Se realizan cambios en la instrumentalización, se realizan pruebas de funcionamiento correcto.
