### ISSUE TITLE
Revisión de estado modalidad de investigación, investigación - creación, Innovación.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#595]
Se requiere realizar la revisión del estado actual para la modalidad deinvestigación, investigación - creación, Innovación para conocer el comportamiento del sistema en esta modalidad y realizar los respectivos ajustes en caso de ser necesario. Por favor dejar bien documentado los datos y documentos que se piden al momento de hacer una solicitud, especialmente solicitd inicial y de revisión.

**Sub Tareas**

- [x] Realizar revisión del estado actual en ambiente de pruebas.
- [x] Documentar hallazgos encontrados.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan las pruebas de funcionamiento en el flujo de la modalidad de investigación, investigación - creación, Innovación.

Se hace el recuento de datos solicitados para la modalidad en los 3 roles involucrados:

A continuación, los datos solicitados en el formulario solicitud inicial estudiante:
•	Ingrese el nombre de la propuesta
•	Ingrese los objetivos de la propuesta
•	Escriba un resumen de su propuesta
•	Seleccione las áreas del conocimiento de su proyecto
•	Cargue la propuesta de investigación (cargar archivo)
•	Ingrese la Estructura de investigación que avala la propuesta
•	Seleccione el Docente director designado por la estructura de investigación
•	De acuerdo con lo establecido en el acuerdo N.°012 de 2022… ¿sí o no?
•	Digite el código de los otros estudiantes que participan en el proyecto
•	Tengo conocimiento que para el presente trámite cumplo con… ¿sí o no?
A continuación, los datos solicitados en el formulario aprobación de la solicitud inicial docente director:
•	Respuesta
•	Escriba la justificación de la respuesta

A continuación, los datos solicitados en el formulario aprobación de la solicitud inicial coordinador:
•	Respuesta
•	Escriba la justificación de la respuesta
•	Seleccione el acta de la respuesta dada por el consejo de carrera
•	Seleccione el docente director del proyecto
•	Seleccione el docente revisor del proyecto

Se inicia el flujo con la solicitud inicial por parte del estudiante

![1-Propuesta inicial estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/790eb991-4a44-4643-be5d-000182d1e481)

Desde el rol de docente director se revisa la propuesta inicial y se acepta
![2-radicada en docente director](https://github.com/udistrital/polux_cliente/assets/69996417/c1a788c2-d5f6-45ec-bca9-f1860aeb054f)

![3-aceptada docente director](https://github.com/udistrital/polux_cliente/assets/69996417/ef00323e-58bb-4824-8135-8b4ae3c17ac0)

Posteriormente desde el coordinador se realiza la aprobación de manera exitosa 

![4-aceptada coordinador](https://github.com/udistrital/polux_cliente/assets/69996417/b02332e3-55d7-4dce-9287-9f646f07273d)

Ahora se realiza prueba actualizando versión del documento del proyecto y solicitando revisión por parte del docente director

![5-actualizar documento de trabajo de grado estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/b3dc801e-e61d-43ac-905b-ef9fe20e6498)
![6-solicitar revisión estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/af3eab53-6ea4-494d-9f53-32c2a3bd856b)

Por parte del docente director se realiza la revisión y registro de comentario al documento

![7-revisión documentos docente director](https://github.com/udistrital/polux_cliente/assets/69996417/4afdf7ab-7545-4399-bb4f-804418b32453)

![8-registrar revisión](https://github.com/udistrital/polux_cliente/assets/69996417/5bb82e71-a52e-4afd-bc5e-091d638e985e)
![9-registro revisión exitosa docente director](https://github.com/udistrital/polux_cliente/assets/69996417/0a37a97c-c332-4a98-90b3-03d2bb183be1)

Desde rol estudiante se hace consulta de la revisión y comentarios al documento del proyecto

![10-revisiones estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/a5d1db11-df21-4e9a-9682-e93c38129cfd)
![11-revisiones estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/fe386fbc-357b-4d75-9a4c-540d59165ede)

La siguiente prueba realizada fue solicitud de cambio de objetivos del proyecto, se genera la solicitud desde el rol estudiante



![12-solicitud cambio de objetivos estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/db329356-c621-4e04-838b-53b92b00e0cb)
![13-solicitud cambio de objetivos exitosa estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/c159af3d-296b-426e-a105-f574dd50e917)

Por parte del docente director se revisa la solicitud y se aprueba
![14-solicitud cambio objetivos docente director](https://github.com/udistrital/polux_cliente/assets/69996417/fa7d740e-cb4d-4271-8cd7-6529ee3f27e5)

![15-aprobada solicitud cambio objetivos docente director](https://github.com/udistrital/polux_cliente/assets/69996417/ed998f72-d508-4451-9f7e-5bdf5731d5f9)

Por parte del coordinador se aprueba la solicitud

![16-aprobado coordinador](https://github.com/udistrital/polux_cliente/assets/69996417/3f2e56ec-9752-41e5-bb12-dc058a4ef545)

Siguiente prueba realizada es la cancelación de la modalidad, se genera la solicitud desde el rol de estudiante



![17-solicitud cancelación de modalidad estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/a7033d23-20ed-4c39-8623-ccadf2d7b1e1)
![18-solicitud cancelación exitosa estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/71ad1165-94c1-4539-a5dd-771e4ea480b1)

Se revisa y aprueba desde el docente director 

![19-solicitud cancelación docente director](https://github.com/udistrital/polux_cliente/assets/69996417/734de7ad-0120-474f-bf59-d937d3e743de)
![20-respuesta exitosa cancelación docente director](https://github.com/udistrital/polux_cliente/assets/69996417/061a8a1d-cf6c-4300-a19d-9a25a3156f34)
Se aprueba desde rol coordinador

![21-aprobado cancelación coordinador](https://github.com/udistrital/polux_cliente/assets/69996417/804190bc-31a0-4f44-b2b2-efe22dc232c1)

Se repite todo el flujo y por último se prueba la calificación del proyecto iniciando por la solicitud de revisión por parte del estudiante

![22-solicitud revisión def estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/8c356c8e-1ca3-44f3-8e69-1f272e0984c5)

Desde docente director se revisa la solicitud y se aprueba


![23-solicitud revisión def docente director](https://github.com/udistrital/polux_cliente/assets/69996417/3cac4771-98f7-467e-a950-e76037fe9f65)

Ahora se aprueba desde el rol coordinador

![24-solicitud revisión def coordinador](https://github.com/udistrital/polux_cliente/assets/69996417/59169da1-f029-46ef-a529-579ec3a8329c)
![25-aprobado revisión def coordinador](https://github.com/udistrital/polux_cliente/assets/69996417/daf81c7d-bfe5-4fb0-91f4-5b5339285347)

Ingreso al rol de evaludor y encuentro la solicitud de calificación para el proyecto y registro la calificación 



![26-solicitud calificación proyecto evaluador](https://github.com/udistrital/polux_cliente/assets/69996417/1eaebca4-85cb-4908-9f48-5ee482b7da16)
![27-registro de la calificación evaluador](https://github.com/udistrital/polux_cliente/assets/69996417/e67d177a-ddc4-43cb-a481-fb24384884e4)
![28-registro calificación proyecto evaluador exitoso](https://github.com/udistrital/polux_cliente/assets/69996417/f044ab54-a0d0-438b-9ec5-b1744ee55a8f)

Ahora por parte del docente director se registra la calificación

![29-registro calificación docente director](https://github.com/udistrital/polux_cliente/assets/69996417/0498099f-17eb-47d9-a202-54e21903babf)
![30-registro calificación exitoso docente director](https://github.com/udistrital/polux_cliente/assets/69996417/8f49c517-390a-4cb0-9158-16a68272a27d)

y desde el rol estudiante se consultan las calificaciones 

![31-consulta notas estudiante](https://github.com/udistrital/polux_cliente/assets/69996417/9e83e0c8-8912-48f4-86f7-fd6c926d90d8)


Hallazgos:

La aplicación funcionó correctamente en todas las pruebas realizadas.

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres, gracias.

**Comment by Astaroth-Andres-Molano** [comment]
En reunión con Kevin López Cardenas Representante de decanatura de ingeniería, Diego Gutierrez Rojas Líder técnico OATI y Cristian Escorcia Blanco Analista OATI, se realiza presentación de los flujos de las modalidades de emprendimiento e investigación:

https://udistritaleduco-my.sharepoint.com/:v:/r/personal/computo_udistrital_edu_co/Documents/Grabaciones/Polux%20-%20muestra%20de%20investigaci%C3%B3n%20y%20emprendimiento-20240708_150555-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=97I3JW
