### ISSUE TITLE
Corrección en visualización de revisión de documentos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#598]
Se requiere realizar la corrección del error encontrado en #586, si bien allí se encontró que es por un estado faltante es mejor primero revisar en otra modalidad como se maneja el aviso cuando no se ha realizado una primera revisión, dependiendo de lo encontrado allí se definira si es mejor agregar a la lista el estado faltante o modificar el estado definido despues de aprobar la ARL

**Sub Tareas**

- [x] Realizar revisión del manejo dado a la alerta de la primera revisión.
- [x] Realizar corrección de la manera definida con @diagutierrezro posterior a la revisión anterior.
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Corrección realizada.
- [x] Prueba de funcionamiento realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Para realizar el análisis se realiza con la modalidad de Monografía. Al momento de aprobar la solicitud inicial, el trabajo de grado queda en estado "En Curso":

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/effcc01f-7341-4921-b893-17f43bb2a847)

En este estado, entrando a la vista de Revisión de Documentos, salen los siguiente mensajes y vistas: Para solicitar una revisión, se selecciona al docente director y se envía la revisión. A partir de ahí comienza el flujo para la revisión de documentos, agregando comentarios, enviando documentos y subiendo nuevas versiones del trabajo de grado.

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/8845112e-fd83-4e43-8460-28b78e981ce6)

Ahora, si se continua con el estado de "Pasantía en curso, en espera de primera versión" y agregando el estado al trabajo de grado, se obtiene la siguiente vista:

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/5acd3d6b-c85b-4df8-afb1-d14a6425d10d)

En este flujo, el estudiante debe subir un documento como primera versión del trabajo de grado. Al momento de enviar el documento, se llama a la transacción tr_actualizar_documento, la cual se encuentra en el API CRUD de Polux, por lo que no está actualizada con los nuevos parámetros y no realiza ningún cambio en el trabajo de grado.

![Image](https://github.com/udistrital/polux_cliente/assets/129443402/ee50cd82-3319-4c20-818a-7bff8918ce47)

**Comment by JuanDHernandezA** [comment]
Mostrando los resultados del análisis a @diagutierrezro, se decidió que al momento que la Oficina de Extensión de Pasantías apruebe la ARL del estudiante, el trabajo de grado pase al estado de "En Curso" en vez del estado "Pasantía en curso, en espera de primera versión".

Se realiza el cambio en la funcionalidad para actualizar el estado al momento de aprobar la ARL, verificando que el trabajo de grado quede en el estado "En Curso":
![image](https://github.com/udistrital/polux_cliente/assets/129443402/cc65bbfc-556c-4a63-b201-7102db502009)

Desde la vista de Revisión de Documento se verifica que pueda visualizar el menú de cargar nuevo documento y solicitar revisión:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/cc5eed38-8584-432a-9bbf-c4499060a499)

Se verifica la funcionalidad de Subir nueva versión del documento, el cual responde de manera correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/c26ac54a-58a2-4dd6-a151-8fea9729b12f)

Ahora, se verifica la funcionalidad de Solicitar revisión:

- Desde el usuario del Estudiante la solicitud sale de manera correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/69fd818b-2b61-433e-abea-09a9e8c0902f)

- Desde el usuario de Director Interno se puede visualizar de manera correcta la vista de la Revisión del Documento:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/27762959-a33b-4c47-b2e4-e93eaf6f50f5)

- Se agrega un comentario y un documento para verificar la funcionalidad de la revisión, la cual fue de manera correcta:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/9efff1b7-d21f-4c00-9beb-0f22d5ff3519)

- Se verifica que el estudiante pueda visualizar los comentarios y documentos cargados por el Director Interno y que pueda agregar comentarios a la revisión, nuevamente, todo fue correcto:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/ec6bcc4f-06c7-4fbb-8056-a33d05ab07ff)

Como comentario adicional, se visualiza que en la modalidad de pasantía se están registrando 2 Directores Externos, esto se debe al cambio que se realizó al unir el flujo de la solicitud inicial de Pasantía Interna con Pasantía Externa

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego, se cierra issue.
