### ISSUE TITLE
Actualización diagrama de flujo general y de sistema para modalidad de investigación

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#599]
Se requiere realizar la actualización del diagrama de flujo general y de sistema para modalidad de investigación

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente
- [x] Presentar al equipos SoS diagramas actualizados
- [x] Refinar diagramas según revisión de equipo SoS
- [x] Aprobar con el cliente diagramas actualizados

**Criterios de aceptación**

- [x] Diagrama de flujo del sistema actualizado
- [x] Diagrama de flujo general actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo de investigación , con base a los criterios dados por el equipo


![Image](https://github.com/udistrital/polux_cliente/assets/85162258/576b42ea-6557-4089-b789-2201493411e8)

[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsEWQZB-oj9DsxXBZGf_xIkBjSkDGc_v0fZ_1QBF5AOkKQ?e=HCesXc)

**Comment by mantnicot** [comment]
Se arregla el flujo con los estados de rechazo de director y coordinación



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/981ab677-ea8e-4c89-a2b1-77e13901579d)

[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EhGW1qsaqTVLicmF6qFGqdABMFaBN0WmSeLDvoVDOit4nw?e=JCJ1nW)

**Comment by jcmurilloa** [comment]
Gracias por atender las recomendaciones @mantnicot, revisaremos con detalle el flujo en el próximo review.

**Comment by jcmurilloa** [comment]
Por favor @mantnicot atender las sugerencias sobre el flujo y los estados coincidentes con Pólux.

**Comment by mantnicot** [comment]
Se ha realizado los cambios comentados y así mismo agregado los cambios de estados de la solicitud



![Image](https://github.com/user-attachments/assets/fd72428e-3ec3-4e5d-8289-2c342050f6ad)



[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Es5We1oWz8hEkcDETB32sUUB5m4Hz0TKlfKbk9S5lA3U3Q?e=IJo5o7)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot.
