### ISSUE TITLE
Actualización diagrama de flujo general y de sistema para modalidad de Espacios académicos de posgrado

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#600]
Se requiere realizar la actualización del diagrama de flujo general y de sistema para modalidad de Espacios académicos de posgrado

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente
- [x] Presentar al equipos SoS diagramas actualizados
- [x] Refinar diagramas según revisión de equipo SoS
- [x] Aprobar con el cliente diagramas actualizados

**Criterios de aceptación**

- [x] Diagrama de flujo del sistema actualizado
- [x] Diagrama de flujo general actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo de espacios academicos de posgrado




![Image](https://github.com/udistrital/polux_cliente/assets/85162258/4a7e3bfd-8416-43d3-92f4-9fb45e79f663)

[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EikpHw5TO1hBqd6lqqVI4Z8ByvTq4bGjrbKtU9hrvo8KWw?e=jCaaUe)

**Comment by mantnicot** [comment]
Se ha arreglado el flujo con lo estados de rechazado



![Image](https://github.com/udistrital/polux_cliente/assets/85162258/c9c2dd5a-272c-4743-b016-46a45d0dfca0)

[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ev4BokdeRk1Ihe82mz2HuqMBf9qY5TreuAaAVbfIfHmp1w?e=8BzUT4)

**Comment by jcmurilloa** [comment]
Gracias por atender las recomendaciones @mantnicot, revisaremos con detalle el flujo en el próximo review.

**Comment by jcmurilloa** [comment]
Según lo repasado en la sesión review, por favor atender las recomendaciones brindadas por el equipo, y tener en cuenta el acuerdo @mantnicot.

**Comment by mantnicot** [comment]
Se ha realizado la actualización de los flujos con base a los comentario del equipo y sus estados 




![Image](https://github.com/user-attachments/assets/46dd53ae-aa7b-4f35-961e-e90d4f65369a)



[CArpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eqh7DxT-9g5Fn2IShkPFFhMBdWUa9nVIOdcJHjcw1t9C_Q?e=QrxJSS)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot.

**Comment by mantnicot** [comment]
Se ha actualizado el flujo , quitando el listado de materias



![Image](https://github.com/user-attachments/assets/ab480a9c-e222-437a-90d9-a95f4d601d6e)



[Carpeta de flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Euf1lV5EFulAn9SuHDoLrLQBasSk29hacyPdncFojW6G5w?e=An4tjq)
