### ISSUE TITLE
Presentación de modalidades emprendimiento e investigación hacia el usuario.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#601]
Se requiere realizar la presentación de emprendimiento e investigación al usuario designado por la facultad de ingeniería para definir si las modalidades requieren cambios o no..

**Sub Tareas**

- [x] Presentación de modalidades realizada con el usuario.

**Criterios de aceptación**

- [x] Presentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se hace entrega de la respectiva acta firmada por los asistentes

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EbfIEE3LUmdHlXl1ZqZee4QBOUcgIMzW1I_txOAtEV5uwA?e=DOYtGM)

**Comment by Astaroth-Andres-Molano** [comment]
En reunión con Kevin López Cardenas Representante de decanatura de ingeniería, Diego Gutierrez Rojas Líder técnico OATI y Cristian Escorcia Blanco Analista OATI, se realiza presentación de los flujos de las modalidades de emprendimiento e investigación:

https://udistritaleduco-my.sharepoint.com/:v:/r/personal/computo_udistrital_edu_co/Documents/Grabaciones/Polux%20-%20muestra%20de%20investigaci%C3%B3n%20y%20emprendimiento-20240708_150555-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=97I3JW
