### ISSUE TITLE
Proyectar y enviar comunicado final de piloto en producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#603]
Se requiere realizar la proyección y envío del comunicado final del piloto en producción del sistema

**Sub Tareas**

- [x] Proyección del comunicado
- [x] Revisión por parte del líder del proyecto
- [x] Documentación del comunicado

**Criterios de aceptación**

- [x] Comunicado de punto medio aprobado
- [x] Comunicado de punto medio enviado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada líder de proyecto.

**Comment by mantnicot** [comment]
Se ha creado el documento de correo final del piloto

[Documento correo final](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXRjqPygT29Evwi3zb-zowQBcWBtlm_FKzp3_SYmhSwMpg?e=5Xw0Vb)

**Comment by jcmurilloa** [comment]
Documento aprobado según recomendaciones, pendiente evidencia de comunidado enviado desde cómputo. Buen trabajo @mantnicot

**Comment by jcmurilloa** [comment]
Gracias @mantnicot, de esta manera vamos cerrando piloto en producción de monografías.
