### ISSUE TITLE
Actualizar documento de hallazgos del piloto de monografias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#607]
Se requiere realizar la actualización del [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbzfO4XM9K5CgnVVO11m6gsBk2Y9P8D_PjRoR5wIiaguWQ?e=wEvFoy) de hallazgos del piloto realizado para la modalidad de monograría.

Se deben agregar **todas** las situaciones que indicaron los usuarios en el grupo que se había definido, esto con el fin de llevar un mejor registro de lo realizado en dicho piloto.

**Sub Tareas**

- [x] Documento de hallazgos actualizado.

**Criterios de aceptación**

- [x] Documento actualizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Documento de hallazgos actualizado.

https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/doc2.aspx?sourcedoc=%7B853BDFBC-F4CC-42AE-8275-553B5D66EA0B%7D&file=Pruebas-hallazgos-Polux-2024-MONOGRAFIAS.xlsx&fromShare=true&action=default&mobileredirect=true

Nota: En las filas 3 y 4 del Excel en la columna correspondiente a colocar el Identificador del Plan de Pruebas, no está la opción de 'POV1_2' por lo que se colocó 'POV1_3' ni tampoco 'POV1_1' por lo que se colocó 'POV1_10'.

**Comment by diagutierrezro** [comment]
Se solicita al analista @mantnicot que de aprobación del documento, se aprueba el documento por lo que se cierra el issue.
