### ISSUE TITLE
Revisar estado de carga de actas de seguimiento por parte del docente director.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#608]
Se requiere realizar la revisión del estado actual del cargue de actas de seguimiento por parte del docente director. Revisar las peticiones http que se realizan especialmente las transacciones y verificar que estas apunten hacia el MID.

**Sub Tareas**

- [x] Revisar estado actual del cargue de actas de seguimiento.
- [x] Documentar hallazgos encontrados en el issue.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Para realizar el análisis se usa la pasantía en estado "En Curso"

Al momento de ingresar con el usuario del Director Interno a la vista de Actas de Seguimiento, aparece el siguiente mensaje:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/52b8530b-d3e7-44a8-bd15-15271f420ca7)

Se revisa la petición que se hace para traer los trabajos de grado, y se observa que no están actualizadas las consultas con la migración a la base de datos de parámetros, por lo que se debe actualizar todas las peticiones para que funcionen con los parámetros de Polux:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/5424efc1-d05d-4e5f-aca7-58b35aa92150)

Se revisa la lógica de la vista y se observa que se hace uso de un tipo de documento asociado a las Actas de Seguimiento; actualmente no existe un tipo de documento en la base de datos para las actas, **por lo que se debe crear un nuevo tipo de documento en la base de datos de parámetros**.

En la funcionalidad de cargar las actas de sustentación se llama a la transacción tr_actualizar_documento_tg en la API CRUD. Esta transacción se encarga de crear el registro del documento en las tablas documento_escrito y documento_trabajo_grado. Adicional a esto, en la API CRUD existe otra transacción con el nombre tr_registrar_acta_seguimiento la cual se encarga de realizar el mismo procedimiento que la otra transacción mencionada. **Por lo que se debe crear una nueva transacción en la API MID encargada de cargar los registros en las tablas de documento_escrito y documento_trabajo_grado**.

Desde el perfil del estudiante, en la vista Consultar Trabajo Grado, se revisa la lógica que muestra el siguiente mensaje:
![image](https://github.com/udistrital/polux_cliente/assets/129443402/61b4c024-6e48-4cd9-b91f-4e1cef3da0d0)

En la lógica se observa que se valida si existen documentos asociados al trabajo de grado con el tipo de documento "ACT_PLX"; revisando la base de datos, este tipo corresponde a las actas del consejo académico y no a las actas de seguimiento de la pasantía, **por lo que se debe actualizar al momento de crear el nuevo tipo de documento**.

**Comment by diagutierrezro** [comment]
La corrección se manejará en otro issue.
