### ISSUE TITLE
Corregir registro de nota con docentes directores y evaluadores.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#609]
Se requiere realizar la revisión y corrección del registro de nota ya que en algunas modalidades que tienen evaluador la nota del evaluador queda en la materia 1 pero ahí debería ir la nota del docente director. Por favor revisar en artículos académicos, emprendimiento e investigación.

**Sub Tareas**

- [x] Realizar revisión del registro de notas correcto en las modalidades indicadas.
- [x] Realizar corrección del registro de nota para que este se haga de manera correcta.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Corrección realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar revisión del registro de notas correcto en las modalidades indicadas.

**Artículos Académicos**

1. El registro de la nota por parte del Docente Director ya queda registrada en la materia 1 como se observa en la siguiente imagen de la base de datos:

<img width="679" alt="image" src="https://github.com/udistrital/polux_cliente/assets/65032868/0f33aaf9-799f-4cbe-a25d-5a0b389df282">

**Emprendimiento**



**Investigación**

**Comment by diagutierrezro** [comment]
Se tiene presente el error para revisarlo en el siguiente sprint, se cierra issue ya que en estas pruebas no se pudo replicar el error encontrado.
