### ISSUE TITLE
Analizar cargue de archivos .zip o .rar para poder enviar documentación adicional

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#610]
Se requiere realizar el análisis para cargar un documento .zip o .rar en la solicitud de revisión final que realiza el estudiante, esto con el fin de poder enviar documentación extra.

**Sub Tareas**

- [x] Analizar como enviar estos documentos en la solicitud de revisión teniendo en cuenta cambios a realizar en el cliente y en transacción del mid.

**Criterios de aceptación**

- [x] Analisis realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza analisis para implementar el cargue de archivos anexos para la revisión final de proyectos de grado, se encuentra que hay que realizar las siguientes modificaciones:

- Crear el registro en la bd "udistrital_core_db" esquema "academica" tabla "detalle" con nombre "Documentos anexos para revisión" y tipo_detalle 4665 que hace referencia en tabla parametros como documento pólux.
- Hacer los inserts en la bd "udistrital_core_db" esquema "academica" tabla "detalle_tipo_solicitud" con tipo_solicitud=4645 que hace referencia a solicitud de revisión de trabajo de grado con cada tipo de modalidad de trabajo de grado.
- Hacer los inserts en bd  "udistrital_core_db" esquema "academica"  tabla "modalidad_tipo_solicitud" para ingresar el detalle o input en el formulario de solicitud de revisión final de trabajo de grado.
- Realizar ajustes en la función  cargarDocumentos y agregar la funcionalidad de cargar archivos .rar y .zip.
- Ajustar la descripción y el tipo de archivo en los metadatos.
- Incorporar lógica para manejar el tamaño máximo permitido para los archivos .rar y . zip.
