### ISSUE TITLE
Actualización de Manual de monografía (dos estudiantes de diferentes proyectos curriculares)

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#612]
Se requiere realizar la actualización del manual de monografías teniendo en cuenta el aspecto relacionado con la realización de esta modalidad por parte de dos estudiantes de diferentes proyectos curriculares. 

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [x] Generar el requerimiento de actualización de Manuales
- [ ] Revisión de manuales generados

**Criterios de aceptación**

- [ ] Solicitud de creación o actualización de Manuales con responsable
- [ ] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado el comentario a Viviana la encargada de los manuales y ella ya colocara junto a otro comentario en el manual , cuando se haga la modalidad con estudiantes de diferentes proyectos curriculares

**Comment by jcmurilloa** [comment]
Gracias por la gestión @mantnicot, estamos pendientes entonces de documentar esta issue cuando estén listos.

**Comment by mantnicot** [comment]
Se ha realizado la gestión de actualización del manual de parte de Viviana con los cambios acordados tanto de dos estudiantes como las notas para limpieza de cache

[Carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EulMJXiqVp5BpfMw_i3buJcBT1oBoZPTgyxKF4msSQxSGw?e=BYUOkG)

**Comment by jcmurilloa** [comment]
Muy buena gestión @mantnicot.
