### ISSUE TITLE
Realización manuales modalidades articulo académico, emprendimiento e investigación

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#613]
Se requiere realizar los manuales de usuario para las modalidades articulo académico, emprendimiento e investigación.

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [x] Generar el requerimiento de actualización de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado la reunión con Viviana para 17/07/2024 a las 12 pm junto con el lider tecnico

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, quedamos a la espera de la respectiva revisión de los manuales actualizados y su respectiva documentación en la issue.

**Comment by mantnicot** [comment]
Se ha hablado con Viviana con respecto a los manuales y comento la idea de que al tener tantos flujos parecidos que se hiciera un solo manual , y que esta faltante unir la parte de investigación , por que en el sistema no le aparece la opción , y por eso la demora.

Se espera la entrega hoy cuando se de solución a eso

**Comment by mantnicot** [comment]
Se ha recibido y se ha revisado los manuales

El de estudiantes

[Manual editable comunicaciones de estudiantes](https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B169599BE-D6E4-47A4-A2EC-52A0907674BA%7D&file=MDU%20Monograf%C3%ADa%20(estudiantes).docx&action=default&mobileredirect=true)

 Director y codirector
[Manual editable comunicaciones de director y codirector](https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B89404C71-AB06-41EA-845E-DD5D57D11A2A%7D&file=MDU%20Trabajos%20de%20grado%20-%20Director%20y%20codirector.docx&action=default&mobileredirect=true)

Coordinador
[Manual editable comunicaciones de coordinador]( https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA8DC183A-F1C4-4256-A289-231092A77368%7D&file=MDU%20Coordinadores%20-%20Polux.docx&action=default&mobileredirect=true)


[Carpeta de los manuales POLUX](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqJRIsOhnfVHvg54aqPh43IB865TwQiYRqxKQCUJpUn7jQ?e=BcPWhM)

**Comment by jcmurilloa** [comment]
Los manuales se ven bien, gracias por la gestión @mantnicot.
