### ISSUE TITLE
Reunión cliente para definición de modalidades de espacios académicos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#614]
Se requiere desarrollar reunión con el cliente para la definición de modalidades de espacios académicos en el sistema pólux

**Sub Tareas**

- [x] Concertar reunión con el equipo del proyecto
- [x] Desarrollar la reunión con el equipo del proyecto
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se asigno la reunión para el día 15/07/2024 a las 2:00 pm 

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGU0YjcwOGUtMDg3MC00ODAwLTk3ODEtOThmNWVjMjIzZWNk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se agrega el acta sin firmas, se espera aprobación del gerente


[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQMmfhso_X5Dj9t4HkP3LlIB1fpupboaVYTSXKVop7A1OQ?e=WOXqjm)

**Comment by jcmurilloa** [comment]
Gracias @mantnicot por la proyección del acta, por favor mencionar en el acta que el flujo iniciaría desde la generación de la solicitud sin tener en cuenta la selección de materias, pues esto hace parte de SGA, asimismo, que las calificaciones tendrán que realizarse tanto en Pólux como en SGA por parte de los evaluadores, siendo la de SGA la valida para el trámite del proceso de grado. Quedo atentos a estos cambios para revisión.

**Comment by mantnicot** [comment]
Se ha hecho los cambios de parte del acta y se ha recolectado la firma con el cliente , se ha cambiado el flujo y así mismo en el acta no se toca el tema de flujo desde listado materias

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETYraDPuOo5GohS77z73jHUBZ4IkmA7BA_rh66iHWb6YIA?e=duKGCO)
