### ISSUE TITLE
Iniciar ajustes para cargue de actas de seguimiento

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#615]
Se requiere realizar los ajustes iniciales para poder visualizar la vista inicial del cargue de acts se seguimiento según lo que se encontró en #608 

**Sub Tareas**

- [x] Realizar ajuste de petición para que se haga el llamado correcto con los parametros que se usan actualmente.
- [x] Crear transacción en el mid para cargar actas de seguimiento.
- [x] Crear tipo de documento para acta de seguimiento. Recordar dejar el registro de esto en 
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Ajustes realizados
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se crea el nuevo tipo de documento para las Actas de Seguimiento en la base de datos de parámetros:

```bash
INSERT INTO documento.tipo_documento 
(nombre,descripcion,codigo_abreviacion,activo,numero_orden,tamano,extension,workspace,tipo_documento_nuxeo,fecha_creacion,fecha_modificacion,dominio_tipo_documento) 
	VALUES 	('Actas de Seguimiento','Actas de Seguimiento de la modalidad de Pasantia','ASP_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9)
```

Se arreglan todas las peticiones del cliente con los nuevos parámetros establecidos para traer los trabajos de grado y poder visualizar la tabla de trabajos de grado:
![image](https://github.com/user-attachments/assets/fe871df7-2548-41fe-8581-1bd3b8d92139)

**Comment by JuanDHernandezA** [comment]
Se crea la transacción tr_registrar_acta_seguimiento en el API MID de Polux.

Se realiza el cambio en el cliente para que al momento de cargar un acta, esta llame a la transacción del MID y no del CRUD. Adicional a esto, se cambia el JSON que se enviaba a la transacción para que corresponda al modelo creado en el API MID, insertando el nuevo tipo de documento al acta cargada por el docente director.

Se prueba la funcionalidad de la transacción para guardar el acta en la tabla documento_escrito y documento_trabajo_grado. La funcionalidad se ejecuta de forma correcta:

![Image](https://github.com/user-attachments/assets/e637b347-6f8b-4f70-a82d-f88ea8ceba5b)

![Image](https://github.com/user-attachments/assets/58c5c3ed-44c0-44dd-a64a-1a21d2b7edcf)

![Image](https://github.com/user-attachments/assets/379b6a09-f97c-4a94-a5ac-2bee1c1d1ad8)

Adicional a esto, se prueban los rollback y también se ejecutan de manera correcta.

Al momento de cargar 3 actas de seguimiento, el sistema no permite cargar más:

![Image](https://github.com/user-attachments/assets/57d15b12-43b7-470f-95c5-f4e3705d5cef)

**Comment by JuanDHernandezA** [comment]
Se corrige en la vista de Consultar Trabajo Grado el tipo de documento de las actas para poder visualizarlas en este menú por parte del estudiante:


![Image](https://github.com/user-attachments/assets/1927d2e6-f8dc-4efc-925a-ac053ec15692)

**Comment by diagutierrezro** [comment]
Se cierra el issue, buen trabajo Juan Diego
