### ISSUE TITLE
Implementar cargue de documentos adicionales en solicitudes de reivisón final - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#616]
Se requiere realizar la implementación inicial del cargue de documentos adicionales (en formato no PDF) según lo analizado en #610, tener en cuenta que se podrían aceptar archivos en formato .zip o .rar 

**Sub Tareas**

- [x] Implementación inicial realizada.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza la primera parte de la implementación de cargue de documentos anexos, estos son los precedimientos realizados:

1- se realiza la creación del detalle "Documentos anexos para revisión" en la bd  "udistrital_core_db" esquema "academica" tabla "detalle"


![Image](https://github.com/user-attachments/assets/584a70b9-67c5-4530-817b-d06019d09032)



![Image](https://github.com/user-attachments/assets/aa7b99b0-ebf2-4f0f-a700-ad467e0d5f88)

2-Se revisa el tipo de solicitud 4645 que corresponde a "Revisión de proyecto de grado" en la tabla "modalidad_tipo_solicitud" para identificar los códigos de las modalidades y los ids



![Image](https://github.com/user-attachments/assets/19094995-453d-4cea-b6b4-4968bd25fc4b)

3-Se realizan los insert del detalle id 82 correspondiente a carga de docuentos anexos en  la bd "udistrital_core_db" esquema "academica" tabla "detalle_tipo_solicitud"

-Modalidad "Creación, dirección o interpretación"



![Image](https://github.com/user-attachments/assets/0b6a0379-648b-4f13-bf0a-3c03826f61d9)

-Modalidad "Proyecto de emprendimiento"


![Image](https://github.com/user-attachments/assets/be8326ec-af22-4090-90fc-1273355c97f3)

-Modalidad "Pasantía", se debe realizar un update al registro 302 de la tabla "modalidad_tipo_solicitud" para cambiarle el orden y que se visualice en el orden adecuado

![Image](https://github.com/user-attachments/assets/66c1eb5e-6308-409b-99bd-75cd989ef632)

y se realiza el respectivo insert


![Image](https://github.com/user-attachments/assets/16822455-aaf1-4abe-8ae7-5965d4ece107)

-Modalidad "Monografía"


![Image](https://github.com/user-attachments/assets/c35791a4-ab38-4cad-b50b-e0ae8e4d2133)

-Modalidad "Investigación, Investigación-Creación, Innovación"


![Image](https://github.com/user-attachments/assets/3e32d624-c146-4c1f-a773-9de6ce8fb1be)

-Modalidad "Producción de artículo académico", se deben realizar updates a los registros 298, 299 y 300 para cambiar el orden y visualización adecuada a los detalles


![Image](https://github.com/user-attachments/assets/eb83223c-4f5d-4e6f-9ce5-c4950ea0ada3)



![Image](https://github.com/user-attachments/assets/ad71ebe0-67a5-4bed-a705-c51a4fd0e6d1)



![Image](https://github.com/user-attachments/assets/3fd9b305-ea6e-498b-bf6e-ad2191647a89)

se realiza el respectivo insert


![Image](https://github.com/user-attachments/assets/f9e9a7c0-fde9-4115-9b62-d66fb941d7ed)



![Image](https://github.com/user-attachments/assets/d86d7223-e04f-4058-8049-f75fa051e347)

4- se inserta la propiedad SELECCIONE_DOCUMENTOS_PARA_REVISION_PROYECTO en el archivo translate del polux_cliente



![Image](https://github.com/user-attachments/assets/c4356edd-3d78-4ae3-88cb-9e6bbd5b9255)

5-Se visualiza el detalle o botón para cargue de anexos en el formulario de solicitud de revisión de trabajo de grado


![Image](https://github.com/user-attachments/assets/040edb15-0179-4e88-bfed-2e4a476ac80c)

**Comment by diagutierrezro** [comment]
Se continua el desarrollo en #622
