### ISSUE TITLE
Realizar análisis para agregar el código del estudiante a la tabla de registro de nota

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#617]
Se requiere realizar el análisis de como se puede implementar la adición del código del estudiante en la tabla que ve el docente cuando entra al componente de registrar nota, plantear principalmente los cambios a realizar a nivel de Mid teniendo en cuenta que el código del estudiante solo se guarda en la tabla estudiante_trabajo_grado y cuando se realiza la consulta para entrar al componente trabajo_grado es complejo llegar al código del estudiante a nivel de bd.

**Sub Tareas**

- [x] Análisis realizado.
- [x] Documentación de issue realizado con propuestas.

**Criterios de aceptación**

- [x] Análisis realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Análisis realizado y SubTarea N°2: Documentación de issue realizado con propuestas.

1. En el apartado de registrar nota de los docentes (ya sea director o evaluador) se lista las vinculaciones de trabajo grado que posean y a su vez se trae el trabajo de grado al que está asociado como se observa en la siguiente petición:

<img width="664" alt="image" src="https://github.com/user-attachments/assets/0fd1060f-c514-4544-8e92-937b355c82fb">

<img width="665" alt="image" src="https://github.com/user-attachments/assets/d81067c3-867a-499f-97d9-42e95fab8935">

2. Tomando de referencia el subobjeto llamado 'TrabajoGrado' en su campo 'Id' podemos implementar una consulta a la tabla 'estudiante_trabajo_grado' que traiga los datos de la columna 'estudiante' en donde el 'trabajo_grado' sea igual al 'Id' de la consulta anteriormente realizada.

<img width="461" alt="image" src="https://github.com/user-attachments/assets/5b25657b-f57a-4fdf-b7b0-a94699419939">

Esto nos retornará todos los códigos de los estudiantes que estén asociados a dicho trabajo de grado.

3. Finalmente en el archivo 'registrar_nota.html' y 'registrar_nota.js' se modificaría y agregaría el código para que la tabla liste los códigos previamente consultados.
