### ISSUE TITLE
Realizar pruebas de funcionamiento de la modalidad de pasantía posterior al cargue de actas de seguimiento.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#619]
Se requiere realizar pruebas para comprobar el funcionamiento correcto del sistema para la modalidad de pasantía una vez que el docente director carga las actas de seguimiento, esto incluye realizar pruebas de las diferentes solicitudes terminando con la solicitud de revisión final..

**Sub Tareas**

- [x] Revisar diferentes funcionalidades posteriores al cargue de actas de seguimiento.
- [x] Documentar en el issue errores encontrados (en caso de hacerlo).

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realiza la revisión de las siguientes solicitudes:
- **Cambio de director interno:** Funciona de forma correcta
- **Cambio de objetivos:** Funciona de forma correcta
- **Cancelar la modalidad:** Funciona de forma correcta
- **Cambio de director externo:** Se muestra el siguiente formulario para ingresar los datos del nuevo director, incluida la hoja de vida, documento que no se pide en la solicitud inicial:
![Image](https://github.com/user-attachments/assets/d03e720c-335f-49a0-8dbe-f407f407264e)

Al momento de aprobar la solicitud por parte del coordinador, sale error en la transacción tr_respuesta_solicitud:
![Image](https://github.com/user-attachments/assets/2251e001-3948-4445-aa2b-e7b70d9cf217)

Este error se debe a que los datos enviados en la petición no corresponde al modelo de DetallePasantia; este modelo fue modificado para almacenar los documentos de Contrato y Carta de aprobación

- **Solicitud de prórroga:** Al seleccionar el tipo de solicitud muestra el siguiente mensaje:
![Image](https://github.com/user-attachments/assets/3b0fdaa1-4bd0-48cf-8e3a-694ddd4faedb)
Esto se debe a que no existe un registro en la tabla detalle_tipo_solicitud en el cual cumpla con la modalidad de Pasantía y el tipo de solicitud de Prórroga:
![Image](https://github.com/user-attachments/assets/1cbec9c3-ebf9-487e-ac37-3fa25a178689)

- **Cambio de título de trabajo de grado:** Actualmente, se muestra el siguiente formulario:
![Image](https://github.com/user-attachments/assets/50497a45-7db4-419c-a992-4321e5c1faf6)

Se discute con @diagutierrezro y @mantnicot y se establece que este formulario debe quedar igual a la demás modalidades, en donde solo se ingresa el nuevo título del trabajo y la justificación.

- **Revisión de trabajo de grado:** Funciona de forma correcta, después de todo el flujo las notas se registran de forma correcta
![Image](https://github.com/user-attachments/assets/e80be0cb-36c8-40f1-91b8-8d8e89be3b04)

**Comment by diagutierrezro** [comment]
Los cambios se abordan en el issue #625, buen trabajo Juan Diego
