### ISSUE TITLE
Ajustar códigos de abreviación para pasantias.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#620]
Se requiere realizar el ajuste de los códigos de abreviación, esto teniendo en cuenta que ahora solo se usará una única modalidad de pasantía (para internas y externas) se debe eliminar de la base de datos el código **PASEX_PLX** y modificar el código **PASIN_PLX** para que solo se use **PAS_PLX**, estos cambios se deben hacer en la base de datos y  tambien en el cliente y mid donde sea necesario para que la lógica no se vea modificada.

**Sub Tareas**

- [x] Realizar eliminación y ajuste de códigos de abreviación en la base de datos.
- [x] Realizar ajustes de códigos de abreviación en el cliente.
- [x] Realizar ajustes de códigos de abreviación en el mid.
- [x] Comprobar funcionamiento correcto posterior a los cambios anteriores.

**Criterios de aceptación**

- [x] Cambios de códigos de abreviación realizados.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Primero se realiza la búsqueda de cuáles funcionalidades hace uso del código de abreviación PASEX_PLX para verificar si también hacen uso del código de abreviación de PASIN_PLX, en caso de que no, se debe agregar o cambiar la lógica si es necesario el uso de dicha funcionalidad

Se realiza la búsqueda en el cliente y en el MID, se reemplazaron y/o eliminaron los códigos PASEX_PLX. Al no usarse, ya se puede eliminar el registro de la base de datos:

```
DELETE FROM parametros.parametro WHERE codigo_abreviacion = 'PASEX_PLX';
```

Revisando la base de datos de Académica, las siguientes tablas contienen registros que dependían o contenían el ID de la modalidad de Pasantía Externa:
- modalidad_tipo_solicitud
- detalle_tipo_solicitud
- detalle_solicitud
- solicitud_trabajo_grado
- documento_solicitud
- respuesta_solicitud
- usuario_solicitud

Por lo que se crearon los Scripts necesarios para eliminar dichos registros:

```bash
DELETE FROM academica.modalidad_tipo_solicitud
	WHERE modalidad = 4601;
	
DELETE FROM academica.detalle_tipo_solicitud
	WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4601);
	
DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud IN (SELECT id FROM academica.detalle_tipo_solicitud WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4601));
	
DELETE FROM academica.solicitud_trabajo_grado
	WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4601);

DELETE FROM academica.documento_solicitud
	WHERE solicitud_trabajo_grado IN (SELECT id FROM academica.solicitud_trabajo_grado WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4601));

DELETE FROM academica.respuesta_solicitud
	WHERE solicitud_trabajo_grado IN (SELECT id FROM academica.solicitud_trabajo_grado WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4601));
	
DELETE FROM academica.usuario_solicitud
	WHERE solicitud_trabajo_grado IN (SELECT id FROM academica.solicitud_trabajo_grado WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4601));
```

Ya con eso el registro de la modalidad de Pasantía Externa y asociados quedan eliminados del sistema de Polux

**Comment by JuanDHernandezA** [comment]
Ahora, se reemplaza el código de abreviación de PASIN_PLX en las API. Se busca que las funcionalidades no queden duplicadas, esto debido a que anteriormente para almacenar los detalles de la pasantía se reemplazó el código PASEX_PLX por PASIN_PLX, por lo que hay funcionalidades repetidas, como el almacenar 2 veces el Director Externo.

Se revisa el código y se han eliminado funcionalidades duplicadas y se ha escrito el nuevo código de abreviación para la pasantía, además de hacer el cambio en la base de datos:

```
UPDATE parametros.parametro
	SET codigo_abreviacion='PAS_PLX'
	WHERE codigo_abreviacion='PASIN_PLX';
```

Se prueba todo el flujo de la modalidad de pasantía para verificar que todo funciones correctamente. Al finalizar las pruebas, se pudo probar todo el flujo inicial, cargar la arl y las actas de seguimiento y todas las solicitudes a excepción de "Solicitud de Revisión de Trabajo de Grado" debido a que se está modificando este formulario en otro issue. Todos los resultados de las pruebas fueron los esperados.

**Comment by diagutierrezro** [comment]
Se debe tener en cuenta los cambios de códigos cuando se vaya a subir a producción.
