### ISSUE TITLE
Realizar presentación de modalidad de pasantía al usuario

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#621]
Se requiere realizar una presentación de la modalidad de pasantía al usuario para mostrar el funcionamiento actual del sistema en dicha modalidad.

**Sub Tareas**

- [x] Realizar presentación al usuario.

**Criterios de aceptación**

- [x] Presentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realizó la presentación de la funcionalidad del sistema Polux para la modalidad de grado de Pasantía al usuario. En esta reunión se mostró el flujo completo de la modalidad y se recibieron comentarios para realizar correcciones al sistema.

Se adjunta link de la grabación:

[Link grabación de la presentación](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/computo_udistrital_edu_co/Documents/Grabaciones/Polux%20-%20muestra%20modalidad%20pasant%C3%ADas-20240801_140937-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=EEJyEu&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
