### ISSUE TITLE
Implementar cargue de documentos adicionales en solicitudes de reivisón final - Parte 2

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#622]
Se requiere realizar la continuación del desarrollo para cargue de documentos adicionales en solicitudes de revisión final según lo que se inició en #616 

**Sub Tareas**

- [x] Crear nuevo tipo de detalle en parametros.
- [x] Actualizar el detalle creado en #616 
- [x] Realizar ajustes en el cliente para convertir estos archivos a base64 y enviar a nuxeo.

**Criterios de aceptación**

- [x] Cambios a base de datos
- [x] Ajustes a cliente realizados.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza la creación de nuevo parámetro para separar el objeto html que carga archivos comprimidos:

```bash
INSERT INTO parametros.parametro(
	nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion, tipo_parametro_id, parametro_padre_id)
	VALUES ('ArchivoComprimido', 'Detalle de tipo archivo comprimido', 'ACOM_PLX', true, 0.00, now(), now(), 83, null);
```


![Image](https://github.com/user-attachments/assets/6e483a90-e728-4a60-920c-2dc7d905cb1e)


y se actualiza el detalle anteriormente creado en la issue #616:

```bash
UPDATE academica.detalle
	SET tipo_detalle=6686
	WHERE id=82;
```


![Image](https://github.com/user-attachments/assets/60838c17-cad8-4507-9222-ec00ec8bdba5)

se realiza prueba y se visualizan los detalles de carga de pdf y archivos comprimidos



![Image](https://github.com/user-attachments/assets/892435b8-baac-4ed3-9fcd-a60f20f39e1d)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan pruebas de carga:



![Image](https://github.com/user-attachments/assets/5970a94d-6f4c-4615-a0b8-c363c9513384)
