### ISSUE TITLE
Realizar ajustes en visualización de solicitudes de revisión

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#623]
Se requiere realizar ajustes en la visualización de las solicitudes de revisión para que los documentos cargados que no son PDF según lo desarrollado en los issue #616 y #622 se puedan descargar directamente ya que estos no pueden tener una visualización al ser un formato .zip o .rar

**Sub Tareas**

- [x] Realizar cambios en el cliente para poder descargar la documentación.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Cambios al cliente realizados.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se reliza la inserción en el HTML para visualizar el elemento de archivos anexos:



![Image](https://github.com/user-attachments/assets/6f5cada3-9166-4351-868a-a04b14e55174)



![Image](https://github.com/user-attachments/assets/cd9d286d-f5c4-4f4a-b7c9-ae5fe5cb7a82)


Se verifica el funcionamiento de este elemento con la función getDocumento, teniendo en cuenta que su extensión es .zip y no .pdf



![Image](https://github.com/user-attachments/assets/ebd254b0-0e5a-42d0-ae26-07b071ec0575)

La función trae el archivo de Nuxeo, pero no lo puede abrir ya que trata de visualizarlo y en este caso se necesita descargar solamente.

Se procede a desarrollar la descarga de este archivo.

**Comment by diagutierrezro** [comment]
Se comprueba funcionamiento, buen trabajo Andres.
