### ISSUE TITLE
Iniciar implementación para mostrar código de estudiante en tabla de registro de nota

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#624]
Se requiere realizar la implementación para mostrar el código del estudiante en la tabla del registro de nota por parte de los docentes según lo analizado en #617 

**Sub Tareas**

- [x] Realizar implementación usando el ORM de beego en el CRUD.
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Implementación realizada.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar implementación usando el ORM de beego en el CRUD.

1. Se crea un nuevo Controlador llamado 'estudiante_vinculacion_trabajo_grado.go' y se agrega al archivo 'router.go':

<img width="494" alt="image" src="https://github.com/user-attachments/assets/4bf84f03-b42b-406f-9756-e04ba4554cb7">

**Primer Método**

2. En el Controlador se crea una función llamada 'GetByTrabajoGrado' donde se recibe el campo 'Active' y el 'Usuario' por parte del cliente:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/4fef6598-5645-4cc2-8f5c-cda55d4d863e">

<img width="638" alt="image" src="https://github.com/user-attachments/assets/53dcc6aa-4b17-40b3-9d27-e66bbe29623c">

<img width="623" alt="image" src="https://github.com/user-attachments/assets/1a0e2e0c-eeb2-4601-b678-240708fc2ac5">

Como se puede observar en el código en primer lugar se arma la query para realizar en el Modelo de 'VinculacionTrabajoGrado', luego si todo sale bien, se extraen los IDs de los trabajos de grado asociados a cada una de las Vinculaciones anteriormente retornadas y con ello se arma la siguiente query para realizar en el Modelo 'EstudianteTrabajoGrado'. Finalmente se crea la respuesta y se envía al Cliente.

3. Por parte del Cliente el funcionamiento de la función 'cargarTrabajos' en el archivo 'registrar_nota.js' es prácticamente el mismo, con la diferencia de que se llama al nuevo endpoint del controlador 'estudiante_vinculacion_trabajo_grado':

<img width="637" alt="image" src="https://github.com/user-attachments/assets/fd5e84a1-6032-49fc-ad93-9a4a56c5d12b">

**Segundo Método**

**Comment by CrisEs2506** [comment]
SubTarea N°2: Probar funcionamiento correcto.

1. En el apartado de 'registrar_nota' se observa como la tabla refleja el código del estudiante del trabajo de grado al que está asociado:

<img width="947" alt="image" src="https://github.com/user-attachments/assets/08d594f2-2e8d-4648-b2f1-1c22841437e3">
