### ISSUE TITLE
Ajustas solicitud de cambio de director externo

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#629]
Se requiere realizar la corrección en la solicitud de cambio de director externo según el error encontrado en #619 donde se debe cargar una nueva hoja de vida que hace referencia al director externo entrante, es necesario corregir el error que se genera en la transacción.

**Sub Tareas**

- [x] Realizar correcciones necesarias en cliente y mid de polux para la solicitud de cambio de director externo.
- [x] Pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Correcciones para solicitud de cambio de director externo realizadas.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se modifica el formato de la información que se envía desde el cliente, con el fin de que responda con el modelo establecido en la API MID, enviando los datos del nuevo director externo y su hoja de vida:

![image](https://github.com/user-attachments/assets/038712d1-8076-4622-938f-248d5d4e10f3)

Se corrige la transacción tr_respuesta_solicitud, para que actualice de forma correcta la información del nuevo director externo y almacene la nueva hoja de vida
![image](https://github.com/user-attachments/assets/859d6921-448c-4db4-8729-37c486cd74aa)

Se verifica el cambio de la hoja de vida desde la base de datos:
![image](https://github.com/user-attachments/assets/cd8e2923-1aa2-412d-a557-98bdbe992fcf)
![image](https://github.com/user-attachments/assets/b7d9b8b4-7512-488b-8abc-32ed2f039e75)

Y se verifica los nuevos datos desde la vista de Consulta Trabajo Grado:
![image](https://github.com/user-attachments/assets/e588e9ff-df64-44b1-bd94-5d39f43c756e)

**Comment by JuanDHernandezA** [comment]
Se crean los rollbacks necesarios para la nueva funcionalidad de almacenar la hoja de vida del Director Externo. Revisando los demás rollback, se observa que están incompletos o que no están ajustados para la modalidad de pasantía, específicamente para controlar los rollback de los Directores Externos.

Se corrigen y acomodan los rollback; se prueba su funcionalidad y funciona correctamente.

**Comment by diagutierrezro** [comment]
Gran trabajo Juan Diego, gracias.
