### ISSUE TITLE
Creación piloto en producción modalidad pasantía

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#630]
Se requiere realizar la documentación para la construcción del piloto en producción para la modalidad pasantía

**Sub Tareas**

- [x] Generar contacto con cliente
- [x] Levantar requerimientos de programación
- [x] Proyectar el plan piloto en producción
- [x] Presentar el plan piloto a equipos SoS

**Criterios de aceptación**

- [x] Plan piloto aprobado equipos SoS y cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha hablado con el equipo sobre la posibilidad de las fechas para el piloto del 12 de agosto al 30 de agosto , haciendo semanalmente una reunión de equipo

[Formato de piloto pasantias](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ed6x97QtdH9CvIocwM3kU20B-Plulm5x7Ku-zLSsYyRFZQ?e=8yHEPA)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, repasaremos el documento final en la próxima sesión Review SoS, con el fin de su respectiva aprobación.

**Comment by mantnicot** [comment]
Se ha termina los documentos , se espera la presentación al cliente para poder colocar los casos de las pruebas , pues para esto se necesita saber como funciona el sistema directamente.

**Comment by jcmurilloa** [comment]
Teniendo en cuenta lo sustentado, se generará contacto con el patrocinador del proyecto para lograr generar la interacción requerida con el responsable.

**Comment by jcmurilloa** [comment]
Pendiente las recomendaciones generadas por el equipo SOS, entre estas la definición de los roles para el inicio del piloto.

**Comment by mantnicot** [comment]
Se ha podido terminar la planeación del plan piloto de pasantía , se espera solo la entrega de los usuarios para poder realizar envió de la información , se han cambiado los 3 documentos , adaptándose al caso de pasantías.


[Carpeta de los 3 documentos ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpmxBLIl27BKvDk_LAwVkzcBJ3su0gUzdvYfbIdRBJug1A?e=ZkopJv)

**Comment by mantnicot** [comment]
Ya se ha refinado el plan piloto y se ha comunicado con la respectiva decanatura 

[Documento piloto refinado](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ed6x97QtdH9CvIocwM3kU20B-Plulm5x7Ku-zLSsYyRFZQ?e=8gRYD3)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, bienvenido el inicio del piloto!
