### ISSUE TITLE
Ajustar tabla de registro de nota

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#632]
Se requiere realizar la corrección de lo encontrado en #624 donde se muestran dos registros separados para estudiantes en el mismo trabajo de grado, en este caso se requiere modificar la función en el crud donde se verifique si los estudiantes son del mismo trabajo de grado y en caso de que si lo sean separar los códigos de los estudiantes por ,(coma) pero en un solo registro

**Sub Tareas**

- [x] Ajuste de función en el CRUD para que solo se muestre un registro cuando un trabajo de grado tiene mas de un estudiante.
- [x] Prueba de funcionamiento correcto.

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Ajuste de función en el CRUD para que solo se muestre un registro cuando un trabajo de grado tiene mas de un estudiante.

**Corrección de Merge Branch**

1. Los decoradores de la función 'GetAll()' por alguna razón se cambiaron al momento de realizar el Merge y el Pull a la rama lo local, por lo que se tuvo que volver a corregir o de lo contrario no se ejecutaría la función:

<img width="707" alt="image" src="https://github.com/user-attachments/assets/b12e11ef-0c22-4219-bc01-7e02a3113627">

<img width="463" alt="image" src="https://github.com/user-attachments/assets/8d579d80-aa30-4eea-8361-c64970f43480">

2. Al realizar los anteriores cambios, se modifica el archivo 'commentsRouter_controllers.go', donde se quita que el parametro sea recibido mediante la URL, quedando de la siguiente manera:

<img width="709" alt="image" src="https://github.com/user-attachments/assets/44ccb266-dfbe-42ca-b7f8-d996fcd01443">

<img width="350" alt="image" src="https://github.com/user-attachments/assets/83e2e4cf-3d95-40df-8810-d9fde7f92891">

3. De este modo también se tuvo que corregir la línea 27 puesto que ya no se recibe el parametro a través de la URL, si no como un objeto y a partir de allí se extrae el documento:

<img width="455" alt="image" src="https://github.com/user-attachments/assets/a4295c4d-923d-4398-ad86-84f68c0555be">

**Feature - Trabajo de Grado con Dos Estudiantes**

1.

**Comment by CrisEs2506** [comment]
SubTarea N°2: Prueba de funcionamiento correcto.

<img width="947" alt="image" src="https://github.com/user-attachments/assets/b2a3f94e-3c9f-4604-8c1e-1525dd394184">

**Comment by diagutierrezro** [comment]
Se solicita actualización del swagger a Jhon y se comprueba funcionamiento correcto en ambiente de pruebas, gracias Cristian.
