### ISSUE TITLE
Agregar el país de la revista en artículo académico

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#633]
Se requiere realizar la adición del detalle del país para la solicitud de revisión en la modalidad de articulos académicos, este campo será digitable y obligatorio para esta solicitud por lo que es necesario agregar este detalle en la base de datos y su posterior adición a las otras tablas para que se muestre en esta solicitud.

**Sub Tareas**

- [x] Adicionar detalle para registrar país de la revista.
- [x] Probar funcionamiento correcto.
- [x] Documentar issue #584  con los cambios realizados en la base de datos.

**Criterios de aceptación**

- [x] Adición de detalle realizada.
- [x] Pruebas de correcto funcionamiento realizadas.
- [x] Documentación de issue de cambios en bases de datos realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza el previo análisis de la bd para creación del nuevo detalle, se realiza consulta en academica.detalle para revisar que el código de abreviación 'PR' del detalle a crear no exista aún


![Image](https://github.com/user-attachments/assets/2a9d1fb9-dea8-4ce1-a693-55821c423403)

Se hace el insert en academica.detalle para la creación del nuevo detalle



![Image](https://github.com/user-attachments/assets/6ceccbee-887a-4955-b20f-3435cddeccb0)

visualización del detalle creado


![Image](https://github.com/user-attachments/assets/875f69ca-5ef1-4f3f-9bed-e207b6bbc733)

En academica.detalle_tipo_solicitud se actualizan los registros de los detalles 300 y 299 cambiando el número de orden para abrir campo al nuevo detalle


![Image](https://github.com/user-attachments/assets/ba8fa2a8-cd98-4de3-b850-399eea722802)



![Image](https://github.com/user-attachments/assets/caaeec7d-9dba-47bd-b8da-9bf89a7b79e6)

Ahora en esta misma tabla academica.detalle_tipo_solicitud se hace el insert del nuevo detalle



![Image](https://github.com/user-attachments/assets/8bdde365-9fcb-4d3a-a5b0-e8754baaef02)

Visualización de academica.detalle_tipo_solicitud con el insert y actualizaciones para la modalidad de articulos académicos 


![Image](https://github.com/user-attachments/assets/929996ab-90b8-4e07-a54e-a924d74f8d09)

En polux cliente en el archivo translate se realiza modificación para incluir enunciado de código país de la revista



![Image](https://github.com/user-attachments/assets/5bc7d890-34a1-4a92-a576-1bfad70e7921)

Visualización del nuevo detalle 


![Image](https://github.com/user-attachments/assets/df96b573-37e4-4f3e-9921-da4f3dda9c18)

Prueba de funcionamiento



![Image](https://github.com/user-attachments/assets/c8fccc41-cb36-4e2a-84e5-09d58cc7db87)

Visaualización desde docente director del nuevo detalle



![Image](https://github.com/user-attachments/assets/fe1fd003-b215-437a-a9e5-44b326956552)

Visaualización desde coordinador del nuevo detalle



![Image](https://github.com/user-attachments/assets/c1cef42f-d9aa-49bb-8450-8384bd66564e)

Funcionamiento correcto

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza ajuste en el detalle para que se ingrese el nombre del país y no el código, se hace actualización del detalle
![13-update ajuste país revista](https://github.com/user-attachments/assets/592f5e28-6ce9-4fa5-aea5-64214887febe)
visualización del detalle actualizado a detalle de tipo texto

![14-registro del detalle actualizado](https://github.com/user-attachments/assets/29238119-9b51-480e-8318-80095e80ecd4)
Se realiza modificación en polux cliente archivo translate para la visualización del label
![15-modificación en translate](https://github.com/user-attachments/assets/5dff0872-65f7-41f0-9647-783eb857cb84)
visualización del detalle actualizado en la interfaz
![16-visualización del ajuste](https://github.com/user-attachments/assets/7b6c2b8e-0757-4107-b76a-2be682aefe1d)
se realiza prueba de funcionamiento
![17-prueba funcionamiento](https://github.com/user-attachments/assets/3054a4a5-5175-44fa-af8f-6a7dcdf2edbf)
visualización por parte del docente director
![18-visualización docente director](https://github.com/user-attachments/assets/f1adb2f9-52eb-4142-b689-625f44a5409e)
visualización por parte del coordinador
![19-visualización coordinador](https://github.com/user-attachments/assets/d1d93171-2ca8-419a-ac29-0f92bb7aed71)
funcionamiento correcto

**Comment by diagutierrezro** [comment]
Buen trabajo Andres
