### ISSUE TITLE
Realizar apropiación de la herramienta excelize

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#635]
Se requiere realizar la apropiación de la herramienta excelize la cual se implementa en GO y con la que se buscan realizar los reportes requeridos por el usuario.

**Sub Tareas**

- [x] Apropiación de la herramienta excelize

**Criterios de aceptación**

- [x] Apropiación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1:  Apropiación de la herramienta excelize.

**Repositorio Oficial**

https://github.com/qax-os/excelize?tab=readme-ov-file

**Fuentes de Referencia**

- Documentación: https://xuri.me/excelize/es/base/installation.html
- Minitutorial: https://youtu.be/ZJA9CAQReSM?t=2205

**Comment by diagutierrezro** [comment]
Se realiza implementación inicial de excelize en otro issue.
