### ISSUE TITLE
Implementar alcance inicial de reportes - parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#637]
Se requiere realizar una implementación inicial (a modo de prueba) para comprobar como funcionaría la implementación de reportes con excelize en el sistema de Pólux, para esto replicar el [reporte](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQs9ZTlTGu9BqNMI7mufliYBHrvTOCsR8W-1oRSgyy4kow?e=uBCYcf) de la pestaña "reporte general"

**Sub Tareas**

- [x] Realizar implementación inicial.
- [x] Documentar hallazgos que se vayan encontrando a medida que se realiza la implementación inicial.

**Criterios de aceptación**

- [x] Implementación inicial realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Realizar implementación inicial.

**polux_crud**

1. Se creo un nuevo Modelo llamado 'reporte_general' con la estructura correspondiente para almacenar todos los datos traidos de la base de datos:

<img width="710" alt="image" src="https://github.com/user-attachments/assets/81993297-bf5b-47e3-a08c-832b273d5c97">

2. Se crea una función en el Modelo llamada 'GetReporteGeneral()' encargada de realizar la consulta SQL y crear un slice asignandole todos los datos recogidos a la estructura:

<img width="708" alt="image" src="https://github.com/user-attachments/assets/49084577-a76b-4fe5-823c-fbc8fb7ff82e">

<img width="705" alt="image" src="https://github.com/user-attachments/assets/9c2911ba-cf1b-4722-993f-2d695ecc8e87">

<img width="708" alt="image" src="https://github.com/user-attachments/assets/bb8605ab-b824-48ae-925d-1fbcf2a470ec">

<img width="706" alt="image" src="https://github.com/user-attachments/assets/09aab7be-3d5a-41e2-8967-97eb16438066">

<img width="707" alt="image" src="https://github.com/user-attachments/assets/ac7d00f4-f93c-4ef3-8551-40935fb312b3">

<img width="706" alt="image" src="https://github.com/user-attachments/assets/8acb34b7-c59e-4ec9-8b22-2cba13f5af74">

3. Como se observa en la línea 191 de la imagen anterior, se llama a la función 'BuildExcel()' la cuál tiene la tarea de construir el excel, añadir los headers (títulos de las columnas) y colocar cada uno de los datos del slice de ReporteGeneral en cada celda de la hoja de cálculo, además de indicar la ruta en donde se quiere guardar el Excel:

<img width="707" alt="image" src="https://github.com/user-attachments/assets/bf899a8d-7733-430b-b1b3-1fd04ab69cd7">

<img width="707" alt="image" src="https://github.com/user-attachments/assets/86c1d8fc-5c47-4103-97b9-f9102a42d7a6">

4. En la línea 225 se llama a la función 'appendRow' encargada de colocar en cada fila y cada columna del Excel los datos del slice de ReporteGeneral:

<img width="706" alt="image" src="https://github.com/user-attachments/assets/04ffdc03-77b9-4e69-9c45-e0e985c6210d">

5. Se crea un Controlador llamado 'reporte_general' con un método Post (pensando que en el futuro se le pasarán parametros como los filtros por los cuales se quiere crear el reporte) el cuál es el encargado de ejecutar la función 'GetReporteGeneral()' y dar la respuesta del servidor ya sea en caso éxitoso o del error presentado:

<img width="711" alt="image" src="https://github.com/user-attachments/assets/51243b34-030f-4f0c-8025-831fc5a9ee1d">

6. Finalmente, se añade manualmente el controlador al archivo 'Router.go':

<img width="708" alt="image" src="https://github.com/user-attachments/assets/4bc2515d-9eb0-45a7-9831-295c62b70a5f">

**Comment by diagutierrezro** [comment]
Se continuará implementación en otro issue, gracias Cristian.
