### ISSUE TITLE
Ajustar detalles no requeridos.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#638]
Se requiere realizar el ajuste para no obligar al usuario a enviar detalles no requeridos en las solicitudes, para esto, usar el campo de requerido que llega desde la base de datos, una vez se haga este ajuste verificar si el campo requerido es false y la respuesta está vacia y en dado caso de que esto se cumpla quitar este detalle del arreglo de detalles general.

**Sub Tareas**

- [x] Realizar ajuste para usar campo requerido y no obligar a llenar detalles que no se usan.
- [x] Ajustar lógica en el cliente para eliminar del arreglo general los detalles no obligatorios que no tienen una respuesta.
- [x] Probar funcionamiento correcto del sistema.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza analisis del detalle de anexos para identificar como condicionar para que no sea incluido en el objeto de detalles con documento cuando no lleva carga util


![Image](https://github.com/user-attachments/assets/93b1534a-a0dc-4737-bce8-46db283a8d76)



![Image](https://github.com/user-attachments/assets/ba27bc1b-a240-4c64-9026-03e5bee131f6)

Se realizan cambios en la función validarFormulario para tales efectos



![Image](https://github.com/user-attachments/assets/4aac6159-ac9d-4dd7-93ba-58efe6973d91)

Se realizan pruebas de solicitud de revisión de proyecto de grado sin incluir documentos anexos 


![Image](https://github.com/user-attachments/assets/a6b57b91-9e3b-460c-8224-c8fd75a6bb0c)



![Image](https://github.com/user-attachments/assets/df2616b9-29ef-4fe7-b6f2-1f254bb19083)




![Image](https://github.com/user-attachments/assets/11056fec-d8d8-40b1-82fc-7180501f73d0)

Se realizan pruebas de funcionamiento de solicitud de revisión de proeyecto de grado incluyendo anexos

![Image](https://github.com/user-attachments/assets/a9ec03c3-ae13-4044-b2b2-59f3402162ca)



![Image](https://github.com/user-attachments/assets/81692c3a-239c-42fc-a3b2-02dd20671488)



![Image](https://github.com/user-attachments/assets/60637a91-9993-4d00-837b-64a9abc2dbfe)

Al revisar la visualización de la solicitud sin anexos con el rol de docente director aún aparece el detalle de documentos anexos



![Image](https://github.com/user-attachments/assets/304d39ed-bf13-41af-ac59-8835f498bd65)

Se realizan cambios en la función cargarSolicitudes para que cuando el objeto de documentos anexos no traiga carga util no lo incluya en el objeto a registar en bd



![Image](https://github.com/user-attachments/assets/0c5cc399-d20c-41e2-819e-26541da3ef9a)

Se realizan pruebas de funcionamiento nuevamente en la visualización de docente director


![Image](https://github.com/user-attachments/assets/12e96cb2-14ed-4b8e-929f-3f2e3fd40fd6)



![Image](https://github.com/user-attachments/assets/c3af7497-893d-4081-bb32-f4dcd11e3407)

La prueba es existosa en este caso no aparece el detalle de anexos cuando no son cargados

Se realizan pruebas de fucionamiento cargando anexos para validar correcto funcionamiento



![Image](https://github.com/user-attachments/assets/f0077313-a997-401f-81d4-514cc512de52)



![Image](https://github.com/user-attachments/assets/feca323d-9cae-4ad8-8072-f43865d1a581)

Se realizan pruebas de funcionamiento con anexos en rol coordinador



![Image](https://github.com/user-attachments/assets/5bff9204-69eb-41d5-b62f-add9af594dc0)

Se realizan pruebas sin anexos en rol coordinador



![Image](https://github.com/user-attachments/assets/14b0bb13-6016-417e-9f67-3b80cd75f77c)

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza cambio en la función cargarSolicitudes para descartar detalles no requeridos que no traigan carga util


![Image](https://github.com/user-attachments/assets/71d65dc5-099e-4c50-b732-a76997f3c2c0)

Se realiza prueba donde se ve que no incluye los detalles no requeridos que no tienen respuesta en el Payload



![Image](https://github.com/user-attachments/assets/b8e04e83-fab8-4944-8f63-1ad33c351467)
