### ISSUE TITLE
Ajustar cargue de anexos para recibir otro tipo de documentos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#642]
Se requiere realizar ajuste a lo realizado en #622 donde se permitan recibir documentos de formatos que se deben definir como son .doc, docx, xls, xlsx, ppt, pdf, etc  donde tambien se debe definir el tipo de archivo que tiene cada una de estas extensiones. Se recomienda manejar en un arreglo donde se listen las extensiones validas (probar inicialmente con archivos word, excel y power point) 

**Sub Tareas**

- [x] Realizar ajustes para recibir archivos de las extensiones definidas.
- [x] Probar funcionamiento con diferentes archivos (incluidos pdf)

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
Buen día. Por favor realizar los respectivos commits de avance en la issue, el día de hoy cumplimos 3 días del sprint y no se evidencia avance de la tarea.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza git pull en develop, luego se crea nueva rama feature/carga_anexos_v, se realizan cambios en html para no cargar archivos comprimidos



![Image](https://github.com/user-attachments/assets/8f9a885b-55e7-4ef7-a327-408e6b7e798d)

Se realizan cambios en el controlador crear_solicitud.js para aceptar otro tipo de archivos y se corrige cambio pendiente de la tarea #638 (condicional que comparaba los id de los tipos de detalle)


![Image](https://github.com/user-attachments/assets/cd1c68ba-405a-4b22-9656-3f0b4689f8e7)

Se realiza la primera prueba cargando un documento de word .docx



![Image](https://github.com/user-attachments/assets/f250abbb-c7c3-4bd5-9825-698796e437df)

se evidencia en los prints en consola el tipo de documento y la subida del documento en el network que por el momento aún los sigue guardando como un tipo pdf



![Image](https://github.com/user-attachments/assets/51d75ace-f88b-4ce6-a059-9f10821db5ac)

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza modificación en la función cargarDocumentos al endpoint de Nuxeo, cambia de "upload" a "uploadAnyFormat" para cambiar de gestor documental



![Image](https://github.com/user-attachments/assets/99b77c6a-212f-444e-82a6-c104e9a3c642)

se realiza prueba de carga con archivo excel



![Image](https://github.com/user-attachments/assets/fa0b1bb7-3714-4e99-9c5f-3f01c38f8bde)

la solicitud carga exitosamente



![Image](https://github.com/user-attachments/assets/00335bff-3e8f-4279-9469-79679762befb)

se revisa la carga en el payload y los print en la consola



![Image](https://github.com/user-attachments/assets/898633ad-e9a8-49d5-b5dd-978577dd743d)

Se realiza carga con archivo power point .pptx, solicitud exitosa, se revisa el payload para verificar la subida del archivo con su respectiva extensión en el nombre 

![Image](https://github.com/user-attachments/assets/83248671-5bdc-4695-a200-8dec8fc8464d)



se revisan los print en consola

![Image](https://github.com/user-attachments/assets/bcb32575-5072-4e14-a595-8565bd72e66f)

se verifica el status 200 en la petición GET



![Image](https://github.com/user-attachments/assets/7af2cffa-37c3-40fe-bb66-7e75644972a6)

se realizan cambios en translate para cambio en el label del formulario



![Image](https://github.com/user-attachments/assets/b2a9e944-c64c-48ae-a59b-5bb96a84a26e)

se realizan ajustes en translate para aviso warning, advertir que no se deben usar archivos comprimidos


![Image](https://github.com/user-attachments/assets/ab86330c-eb20-4e66-9686-3f85c900258d)

Se verifican los cambios en la interfaz



![Image](https://github.com/user-attachments/assets/a44db383-d0aa-4f76-b20c-60b789102c08)

**Comment by diagutierrezro** [comment]
Se comprueba el cargue de anexos de otros anexos en nuxeo de manera correcta, gracias Andres.
