### ISSUE TITLE
Realizar el contacto y adelantar reunión con cliente de Facultad de Artes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#643]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente de Facultad de Artes

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [ ] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [ ] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto.
- [ ] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [ ] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido hablar con la persona restantes de artes y comenta que esta semana tiene problemas para poder concretar una reunión pues están en adiciones , por lo cual se pregunto si tiene otra persona que pueda apoyarnos , pero no ha dado respuesta aun.

Mañana se volverá a escribir para pedir un nuevo contacto

**Comment by mantnicot** [comment]
Se han podido brindar contactos de todas las coordinaciones de artes , se ha enviado un correo en el cual se pide que especifiquen los flujos de los trabajos de grado , para poder saber que diferencias 




![Image](https://github.com/user-attachments/assets/3305af77-ff78-464c-8351-8585f84add2b)

Se queda a espera de respuesta de parte de los coordinadores

**Comment by jcmurilloa** [comment]
Muy bien @mantnicot, esperemos pronta respuesta y concertar una reunión.

**Comment by mantnicot** [comment]
Se ha podido obtener información sobre la facultad y se plantea poder tener una reunión al otra semana con el equipo de arte danzario a cargo de Wilson , quien ya se ha comunicado con conmigo por llamada y me ha explicado cosas del proceso via llamada telefonica

**Comment by jcmurilloa** [comment]
Se genera contacto y se asigna reunión en nueva issue.
