### ISSUE TITLE
Definir el flujo del acuerdo junto con el utilizado por la Facultad de artes en las modalidades de grado

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#644]
Se requiere realizar la definición del flujo del acuerdo junto con el utilizado por la Facultad de artes en las modalidades de grado 

**Sub Tareas**

- [x] Generar contacto con responsable
- [x] Recopilar la información actual
- [x] Definir los diagramas de flujo
- [x] Exponer al equipos SoS

**Criterios de aceptación**

- [x] Diagramas de flujo definidos para las diferentes modalidades de la facultad de artes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido hacer una revisión exhausta de todo los flujo de las modalidades de la facultad de artes y con base a los dos documentos brindados de forma oficial de parte de coordinación , se observa que :

- La facultad de artes se mantiene bajo el acuerdo de 012 de 2022 el cual también tiene base para la facultad de ingeniera ( _se genera la duda por que no se usa el acuerdo 02 - 2023_ )

- La facultad tiene su propio formato de guía para las modalidades pero esta mal detallado y especifica son procesos más amplio , pero no especifica , clausulas o artículos a seguir.


![Image](https://github.com/user-attachments/assets/6265d14c-858b-445b-a26c-bc8cfd7b8e60)



- Con base a la documentación , se concluye que los flujos con la facultad de ingeniera son iguales y la única diferencia son los énfasis de los proyectos , pero esto no afecta en el flujo de Pólux



Se espera poder tener una reunión presencial para entender como manejan los procesos internamente en la facultad

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, ni comparación con nuestros flujos!
