### ISSUE TITLE
Pruebas funcionamiento completo modalidad de pasantía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#645]
Se requiere realizar las pruebas del funcionamiento completo de la modalidad de pasantía para comprobar funcionamiento correcto de la modalidad completa. Se deben manejar las pruebas realizadas en el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EWzX9i21lq5FtuB6Q88I0AkB84n8yfJlc5Bmjy3-kZ5abg).

**Sub Tareas**

- [x] Realizar pruebas de funcionamiento de modalidad de pasantias.

**Criterios de aceptación**

- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación realizado.

**Dependencias**

Para realizar la solicitud de revisión se requiere que se encuentre en ambiente de pruebas los cambios realizados en #638 ya que es un desarrollo bloqueante.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realizan las pruebas del funcionamiento del sistema Polux para la modalidad de grado de Pasantía. Los resultados son registrados y detallados en el siguiente formato:

[Pruebas Funcionales Modalidad Pasantía](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/ajuanh_udistrital_edu_co/EQsAuCwbh79HpuI4LgdVJxIBSLPzpb3mk0b9i_9-9dr4rQ?e=zQA8GR)

**Comment by diagutierrezro** [comment]
Se revisan las pruebas, todo funciona correctamente. Gracias Juan Diego
