### ISSUE TITLE
Concertar, desarrollar y levantar del acta de sesión de requerimientos y/o refinamiento con funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#646]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con funcionamiento y cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente y funcionamiento.
- [x] Desarrollar la reunión con el cliente y funcionamiento.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se va a realizar la reunión con el cliente el 01/08/2024 a las 2:00 pm , están invitados tanto el líder como el desarrollador a cargo 

[Enlace Reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2M3OTA2ZDUtZmUwYi00N2QyLTg3YTMtM2I2NTE1MjFmNjEy%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha creado el acta , se espera aprobación del gerente para enviar a firmar

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ET9AngdRvJ5Gu9dKrlTy0x0BetJXiBI7SUZ0EUeENjC4_g?e=j3yfvh)

**Comment by jcmurilloa** [comment]
Acta revisada y aprobada, por favor iniciar con la recolección de firmas.

**Comment by mantnicot** [comment]
Se adjunta el acta firmada

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ET-zQ2iSP-9JpMfhc8t0jK4BLd5BD66DaqgrDqHo1DNWqA?e=2rChEz)

**Comment by jcmurilloa** [comment]
Muy buen trabajo!
