### ISSUE TITLE
Crear los siguientes anexos para las solicitudes de revisión

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#648]
Se requiere realizar la creación de dos detalles mas de anexos similares a los creados anteriormente tambien a nivel de bases de datos.

**NOTA: Por ahora crearlas unicamente para modalidad monografía.**

**Sub Tareas**

- [x] Creación de anexos adicionales realizada.
- [x] Probar correcta creación y funcionamiento de anexos.

**Criterios de aceptación**

- [x] Creación de anexos finalizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
Buen día. Por favor realizar los respectivos commits de avance en la issue, el día de hoy cumplimos 3 días del sprint y no se evidencia avance de la tarea.

**Comment by Astaroth-Andres-Molano** [comment]
Se ejecuta script para adicionar detalles de anexos en academica.detalle_tipo_solicitud pero no es posible repetir detalle para la misma modalidad_tipo_solicitud



![Image](https://github.com/user-attachments/assets/786cb3d3-3b8f-41ca-a2ec-2e79adde7fb3)

Debido a esto lo más pertinente fue crear dos detalles más en academica.detalle, pero antes había que modificar el parámetro creado anteriormente para archivos comprimidos para los anexos



![Image](https://github.com/user-attachments/assets/c3671482-bc78-4d7f-8d70-ac0674e5bf34)

vista actual del registro del parámetro 


![Image](https://github.com/user-attachments/assets/5c9c4a21-488b-42a0-bfc7-267dc471af70)

Se tuvo que cambiar el código de abreviación del parámetro por ende se realizan los respectivos cambios en el código


![Image](https://github.com/user-attachments/assets/bdb18127-593f-494f-971f-5fe7f90c8fcc)



![Image](https://github.com/user-attachments/assets/fdb01095-e493-493a-b94c-05122fc62c90)

ahora en academica.detalle se debe realizar actualización del detalle de anexos para que sea uno de los 3 detalles de anexos existente



![Image](https://github.com/user-attachments/assets/70135210-a330-4d51-952f-8964ce71de90)

vista actual del registro


![Image](https://github.com/user-attachments/assets/94419507-e4b3-46c1-bf65-e78f72ecc124)

se procede a hacer el insert del detalle anexo 2



![Image](https://github.com/user-attachments/assets/96d6f923-a851-4d01-8005-b1a980293e97)

se procede a hacer el insert del detalle anexo 3



![Image](https://github.com/user-attachments/assets/e3de679a-c77e-48bf-bbf6-18a4fa2f0689)

vista de los registros de los detalles de anexos creados 



![Image](https://github.com/user-attachments/assets/75e873d9-d1a2-42f5-9634-2e235973d9e0)

Debido a que se manejaba un sólo código de abreviación de detalle y se crearon dos más se tuvo que actualizar el existente de 'DAR' a 'DAR1' y en la creación de los otros 2 quedaron 'DAR2' y 'DAR3' respectivamente, por ende se tuvo que realizar un ajuste en la lógica del método cargarSolicitudes en el controlador crearSolicitud



![Image](https://github.com/user-attachments/assets/2666a625-87e5-4fbe-bf3e-20b02ce472b0)

Se realizan los insert para el detalle_tipo_solicitud que en este caso sería solicitud de revisión de proyecto de grado para modalidad de monografía con su respectivo número de orden, insert para anexo 2



![Image](https://github.com/user-attachments/assets/bec7d499-a671-4263-99bd-3e278084f4fd)

Insert para anexo 3



![Image](https://github.com/user-attachments/assets/e1efd060-774d-4fd1-8ab3-c3190e07035f)

Vista del registro de los 3 detalles de anexo



![Image](https://github.com/user-attachments/assets/973adc29-91c1-4cdb-a45d-dcdd46376727)

Se realiza la prueba de visualización de los 3 anexos en el formulario de solicitud de revisión 



![Image](https://github.com/user-attachments/assets/fe9e9f0d-2569-4257-b6fe-6baedeef3c5e)

Se realiza prueba enviando una solicitud sin anexos cargados, se genera exitosamente y se puede visualizar en la imagen el payload de tr_solicitud que lleva solo 3 detalles entre esos un sólo documento


![Image](https://github.com/user-attachments/assets/9bd91f9d-caf8-4630-9d86-8293f4517a99)

Desde docente director se revisa la visualización correcta de la solicitud con anexos vacíos


![Image](https://github.com/user-attachments/assets/87a3ab81-c6e1-4fea-b81b-1343c5d769e0)

Se realiza prueba cargando los 3 anexos cada uno con un archivo de formato diferente (word, excel y power point)

![Image](https://github.com/user-attachments/assets/f02dc9da-9815-4e4c-a5a6-08992e8d31e5)

Visualización del payload del anexo 1 en la carga de documentos a nuxeo



![Image](https://github.com/user-attachments/assets/11d18f18-5cdb-4f7c-b78f-172e0ef5e3cc)

 Visualización del payload del anexo 2 en la carga de documentos a nuxeo



![Image](https://github.com/user-attachments/assets/2459a166-0d21-4bb4-8d5e-fec927003408)



 Visualización del payload del anexo 3 en la carga de documentos a nuxeo


![Image](https://github.com/user-attachments/assets/01193fe6-d7d6-44aa-a880-ac3e7c62ac5f)

Visualización del payload de la solicitud donde se ven todos los detalles entre esos el del documento final y los 3 anexos



![Image](https://github.com/user-attachments/assets/aaa5d482-ba37-4124-aac1-701de7e1dac8)

Desde docente director se revisa la correcta visualización de la solicitud realizada


![Image](https://github.com/user-attachments/assets/46ab43ff-194d-4200-a250-938433adfc2b)

Se realiza prueba cargando sólo el anexo 3


![Image](https://github.com/user-attachments/assets/8ca895c2-e537-42f2-b9c4-715dc6cd9bc5)

Se visualiza el payload de la solicitud donde se ve llevando el documento final y el anexo 3



![Image](https://github.com/user-attachments/assets/4d534472-fbfd-4a8e-a2a3-527bb38d4206)

Desde docente director se revisa la correcta visualización respectivamente de la prueba 



![Image](https://github.com/user-attachments/assets/386788cd-f06b-458c-add5-7a59be704e3f)

**Comment by diagutierrezro** [comment]
Pendiente por aprobar PR para verificar funcionamiento correcto en pruebas.
