### ISSUE TITLE
Revisión de sincronización de bases de datos en producción

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#657]
Se requiere realizar la revisión de las bases de datos en ambiente de producción para prepararse para el despliegue de pasantías en producción para la realización del piloto

**Sub Tareas**

- [x] Revisar que los comentarios en el isuse #584 estén completos para realizar validación de datos.
- [x] Revisar y comparar junto con @diagutierrezro los datos en base de datos de pruebas y de producción.
- [x] Crear scripts para actualizar db de producción en casos que sea necesario.

**Criterios de aceptación**

- [x] Revisión de issue realizada.
- [x] Comaparación realizada.
- [x] Creación de scripts realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Revisando el issue de los cambios a la base de datos, se realizaron los siguientes scripts detallando los datos e ids que se deben tener en cuenta para la ejecución en la base de datos de producción:

Para la base de datos **_udistrital_core_**:

- Schema "documento":

En este script se hace el insert de varios nuevos tipos de documentos, por lo que se debe crear una dirección de workspace para cada uno de ellos. Adicional, verificar el id del dominio que corresponde a Polux:

```bash
INSERT INTO documento.tipo_documento
	(nombre,descripcion,codigo_abreviacion,activo,numero_orden,tamano,extension,workspace,tipo_documento_nuxeo,fecha_creacion,fecha_modificacion,dominio_tipo_documento) 
	VALUES 	('Actas de Seguimiento','Actas de Seguimiento de la modalidad de Pasantia','ASP_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
		('Contrato Pasantia','Acuerdo de Voluntad, Convenio o Contrato para la modalidad de Pasantia','AVCC_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
		('Carta Aval Pasantia','Carta de la Unidad Académica Responsable para la modalidad de Pasantia','CUA_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
		('Hoja de Vida Director Externo','Hoja de Vida del Director Externo de la pasantía','HVDE_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9);
```

- Schema "parametros":

En este script se hace el insert de 2 nuevos estados del trabajo de grado para la modalidad de pasantía. Se debe tener en cuenta si el ID 73 corresponde también al tipo de parámetro de 'Estado del trabajo de grado' y el ID 83 corresponde a Tipo Detalle
```bash
INSERT INTO parametros.parametro(
	nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion, tipo_parametro_id)
	VALUES  ('ARL Cargada, en espera de aprobación', 'El estudiante cargó el certificado de afiliación de ARL y es necesaria la aprobación por parte de la Oficina de Extención de Pasantías', 'ACEA_PLX', true, 0.00, NOW(),NOW(), 73),
		('ARL Rechazada', 'La Oficina de Extensión de Pasantía rechazó la ARL', 'ARC_PLX', true, 0.00, NOW(),NOW(), 73),
		('ArchivoComprimido', 'Detalle de tipo archivo comprimido', 'ACOM_PLX', true, 0.00, now(), now(), 83);
```

Este script se encarga de eliminar la modalidad de Pasantía Externa:
```bash
DELETE FROM parametros.parametro WHERE codigo_abreviacion = 'PASEX_PLX';
```

Este script se encarga de actualizar el código de abreviación de la modalidad de Pasantía

```bash
UPDATE parametros.parametro
	SET codigo_abreviacion='PAS_PLX'
	WHERE codigo_abreviacion='PASIN_PLX';
```

Para la base de datos **_udistrital_core_db_** Schema **academica**:

- El siguiente Script es para actualizar el formulario de la Solicitud cambio de Título de Pasantía, se deben verificar los siguientes id en la tabla detalles:
  - 27: Actual resumen de la propuesta
  - 29: Nuevo resumen de propuesta
  - 30: Propuesta actual
  - 32: Nueva propuesta
  - 33: Áreas de conocimiento actuales
  - 34: Nuevas áreas de conocimiento

```bash
UPDATE academica.detalle_tipo_solicitud
	SET activo = false
	WHERE detalle IN (27,29,30,32,33,34);
```

- Este Script se encarga de crear el formulario para la Solicitud de Prórroga para Pasantía. Se deben tener en cuenta los siguientes IDs:
  - En la tabla modalidad_tipo_solicitud: 89, correspondiente a Solicitud de Prórroga y Pasantía
  - En la tabla detalle: 20, Tipo de prórroga
  - En la tabla detalle: 13, Causa
  - En la tabla detalle: 52, Información de Prórroga

```bash
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (20, 89, true, true, 1),
		(13, 89, true, true, 2),
		(52, 89, true, true, 1);
```

- Scripts para agregar el nuevo detalle para agregar documentos anexos. Se debe tener en cuenta el ID del tipo de detalle "ArchivoComprimido" creado en el segundo Script

```bash
INSERT INTO academica.detalle(
	nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle)
	VALUES ('Documentos anexos para revisión', 'SELECCIONE_DOCUMENTOS_PARA_REVISION_PROYECTO', 'no_service;20000', 'DAR', true, 6686);
```

Una vez creado este detalle, se debe agregar a todas las solicitudes de revisión para cada una de las modalidades en la tabla detalle_tipo_solicitud
```bash
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES ([id_detalle_creado], [id_modalidad_tipo_solicitud], true, false, [no. orden]);
```

- Scripts para la modificación del formulario para la Solicitud Inicial de Pasantía. En este se debe tener en cuenta los siguientes IDs:
  - Tabla Detalle: 18, Hoja de vida del nuevo director externo
  - Tabla Modalidad_tipo_solicitud: 82, Solicitud Inicial y Pasantía

```bash
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES  (18, 82, true, true, 15);
```

Se modifica el orden de los siguientes detalles:

```bash
UPDATE academica.detalle_tipo_solicitud
	SET numero_orden = 16
	WHERE detalle = (SELECT id FROM academica.detalle WHERE codigo_abreviacion = 'CCUAA');

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden = 17
	WHERE detalle = (SELECT id FROM academica.detalle WHERE codigo_abreviacion = 'ACTERM');
```

**Comment by JuanDHernandezA** [comment]
Se revisan los IDs en la base de datos de producción mencionados anteriormente y se modifican los scripts:

- Para la base de datos udistrital_core en el Schema documento, se crean los nuevos tipos de documento ya con su respectivo workspace:

```bash
INSERT INTO documento.tipo_documento
	(nombre,descripcion,codigo_abreviacion,activo,numero_orden,tamano,extension,workspace,tipo_documento_nuxeo,fecha_creacion,fecha_modificacion,dominio_tipo_documento) 
	VALUES 	('Actas de Seguimiento','Actas de Seguimiento de la modalidad de Pasantia','ASP_PLX',true,1.00,5,'pdf','default-domain/workspaces/oas/oas_app/polux/actas_seguimiento','File',NOW(),NOW(),9),
		('Contrato Pasantia','Acuerdo de Voluntad, Convenio o Contrato para la modalidad de Pasantia','AVCC_PLX',true,1.00,5,'pdf','default-domain/workspaces/oas/oas_app/polux/contrato_pasantia','File',NOW(),NOW(),9),
		('Carta Aval Pasantia','Carta de la Unidad Académica Responsable para la modalidad de Pasantia','CUA_PLX',true,1.00,5,'pdf','default-domain/workspaces/oas/oas_app/polux/carta_aval','File',NOW(),NOW(),9),
		('Hoja de Vida Director Externo','Hoja de Vida del Director Externo de la pasantía','HVDE_PLX',true,1.00,5,'pdf','default-domain/workspaces/oas/oas_app/polux/hoja_vida_externo','File',NOW(),NOW(),9);
```

- Para la base de datos de udistrital_core Schema parametros, se crean los siguientes parámetros con sus respectivos IDs de tipo de parámetro:

```bash
INSERT INTO parametros.parametro(
	nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion, tipo_parametro_id)
	VALUES  ('ARL Cargada, en espera de aprobación', 'El estudiante cargó el certificado de afiliación de ARL y es necesaria la aprobación por parte de la Oficina de Extención de Pasantías', 'ACEA_PLX', true, 0.00, NOW(),NOW(), 86),
		('ARL Rechazada', 'La Oficina de Extensión de Pasantía rechazó la ARL', 'ARC_PLX', true, 0.00, NOW(),NOW(), 86),
		('ArchivoComprimido', 'Detalle de tipo archivo comprimido', 'ACOM_PLX', true, 0.00, now(), now(), 96);
```

- Se elimina la modalidad de Pasantía Externa, y se anota el ID para futuras consultas y eliminacioes:

```bash
#id PASEX_PLX= 4582
DELETE FROM parametros.parametro WHERE codigo_abreviacion = 'PASEX_PLX';
```

- Se modifica el código de abreviación de Pasantía y se anota el ID para futuras consultas:

```bash
#id PAS_PLX=4654
UPDATE parametros.parametro
	SET codigo_abreviacion='PAS_PLX'
	WHERE codigo_abreviacion='PASIN_PLX';
```

- Para la base de datos de udistrital_core_db se verificaron los siguientes Scripts
  - Se actualiza el formulario de Solicitud de Cambio de Título para la modalidad de Pasantía:

```bash
UPDATE academica.detalle_tipo_solicitud
	SET activo = false
	WHERE detalle IN (27,29,30,32,33,34);
```
   - Se crea el formulario de Solicitud de Prórroga para la modalidad de Pasantía:

```bash
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (20, 89, true, true, 1),
		(13, 89, true, true, 2),
		(52, 89, true, true, 1);
```

   - Se agrega el campo de Hoja de Vida de Director Externo para el formulario de la Solicitud Inicial de Pasantía

```bash
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES  (18, 82, true, true, 15);
```

   - Se modifica el orden en este último formulario de los siguiente detalles

```bash
UPDATE academica.detalle_tipo_solicitud
	SET numero_orden = 16
	WHERE detalle = (SELECT id FROM academica.detalle WHERE codigo_abreviacion = 'CCUAA');

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden = 17
	WHERE detalle = (SELECT id FROM academica.detalle WHERE codigo_abreviacion = 'ACTERM') AND modalidad_tipo_solicitud = 82;
```

  - Se elimina los registros asociados a la modalidad de Pasantía Externa:

```bash
DELETE FROM academica.modalidad_tipo_solicitud
	WHERE modalidad = 4582;
	
DELETE FROM academica.detalle_tipo_solicitud
	WHERE modalidad_tipo_solicitud IN (SELECT id FROM academica.modalidad_tipo_solicitud WHERE modalidad = 4582);
```

Queda pendiente modificar el orden de los detalles en la Solicitud de Revisión una vez creado el Tipo de Detalle de Archivo Comprimido

**Comment by diagutierrezro** [comment]
Solo queda pendiente por actualizar los scripts que se crean posterior al registro de nuevos detalles para actualizar los ids.

**Comment by JuanDHernandezA** [comment]
Se crean los siguientes Scripts para continuar con la sincronización en la base de datos de producción:

- Una vez creado el tipo de detalle Archivo Comprimido en la base de datos de parámetros, se crean los detalles en la base de datos de Polux. Adicional a esto, se crea el detalle del Pais de la Revista:

```bash
INSERT INTO academica.detalle( nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle) VALUES 
('Documento anexo 1', 'SELECCIONE_DOCUMENTOS_PARA_REVISION_PROYECTO', 'no_service;20000', 'DAR1', true, 4769),
('Documento anexo 2', 'SELECCIONE_DOCUMENTOS_PARA_REVISION_PROYECTO', 'no_service;20000', 'DAR2', true, 4769),
('Documento anexo 3', 'SELECCIONE_DOCUMENTOS_PARA_REVISION_PROYECTO', 'no_service;20000', 'DAR3', true, 4769),
('País de la revista', 'PAIS_REVISTA', 'no_service', 'PR', true, 4643);
```

- Se corrige el formulario de la Solicitud Inicial de Pasantía, en donde los detalles de Director Externo eran usados como Director Interno:

```bash
UPDATE academica.detalle_tipo_solicitud SET detalle=53 WHERE detalle = 70 AND modalidad_tipo_solicitud = 82;	
UPDATE academica.detalle_tipo_solicitud SET detalle=54 WHERE detalle = 71 AND modalidad_tipo_solicitud = 82;
```
