### ISSUE TITLE
Ajustar el metodo de descarga para que se pueda descargar cualquier tipo de documento

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#658]
Se requiere realizar un ajuste al metodo creado anteriormente el cual se llama GetZip, inicialmente se debe modificar dicho nombre ya que ahora se podrá descargar cualquier tipo de documento (de las extensiones permitidas) posterior a esto modificar la lógica para que no convierta los documentos a .zip sino que mantenga su extensión original.

**Sub Tareas**

- [x] Modificar el nombre y llamados de la función getZip.
- [x] Modificar la lógica del metodo para poder descargar cualquier tipo de documento.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Modificación del metodo creado anteriormente realizada.
- [x] Pruebas de funcionamiento realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza cambio de nombre al a getDocAnyFormat en el controlador aprobar_solicitud


![Image](https://github.com/user-attachments/assets/d3b1b307-c398-422a-a061-be637d3b5e6b)

se cambia el nombre del método en html 



![Image](https://github.com/user-attachments/assets/de702205-2057-40e4-8380-582d95104328)

Se realizan cambios en la lógica del metodo para poder descagar documentos con cualquier extensión



![Image](https://github.com/user-attachments/assets/b7a5eaeb-0d71-49cd-b154-8c525c6f5e38)

Se realiza prueba de descarga con archivo excel cargado en petición previamente hecha



![Image](https://github.com/user-attachments/assets/627d777f-0f02-4d38-895a-e135f34e654a)

la lógica desarrollada permite abrir la ventana de descarga del documento


![Image](https://github.com/user-attachments/assets/e2dd891b-74ad-48eb-8f9c-c3227661bd1b)

se ejecuta la descarga con el documento identificado con su respectivo formato 


![Image](https://github.com/user-attachments/assets/e0179428-adf3-43de-9126-9cb673ea03da)

se verifica en la data del response la extensión y nombre del archivo


![Image](https://github.com/user-attachments/assets/20bd3854-e0d0-4b89-a37c-390bb07f598d)

Se realiza prueba de descarga con archivo power point cargado en petición previamente hecha


![Image](https://github.com/user-attachments/assets/632656da-4cbc-4515-9166-8c8713c53514)

la lógica desarrollada permite abrir la ventana de descarga del documento donde se puede evidenciar la extensión o formato que trae el archivo


![Image](https://github.com/user-attachments/assets/9a53c03c-4273-408b-888b-e264bbb65d5a)


se ejecuta la descarga con el documento identificado con su respectivo formato

![Image](https://github.com/user-attachments/assets/352383a4-98bb-4b38-987f-395a859620e6)

Se realiza prueba de descarga con archivo word cargado en petición previamente hecha


![Image](https://github.com/user-attachments/assets/701d9c9a-51e8-4936-a272-873a2c69a276)

la lógica desarrollada permite abrir la ventana de descarga del documento donde se puede evidenciar la extensión o formato que trae el archivo


![Image](https://github.com/user-attachments/assets/9d33f979-4f05-4b46-8c50-80184a0ceaf8)

se ejecuta la descarga con el documento identificado con su respectivo formato


![Image](https://github.com/user-attachments/assets/354f6835-411f-42ad-931a-a842af9b2cc3)

Se realiza ajuste en translate para cambio en el label de descarga



![Image](https://github.com/user-attachments/assets/cd528129-1ae4-47fd-a719-47522e59b158)

se revisa cambio en interfaz



![Image](https://github.com/user-attachments/assets/9d0783c5-f010-49d3-9a65-bf2e8304e9ee)

**Comment by diagutierrezro** [comment]
Queda pendiente por aprobar PR, se comprueba el correcto funcionamiento en una reunión con Andres. Muy buen trabajo.
