### ISSUE TITLE
Corregir aspectos solicitados posterior a reunión con cliente

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#661]
Se requiere realizar las correcciones solicitadas por el usuario posteriores a la presentación realizada al usuario en #621 donde se requieren cambios de textosy adición de alertas.

**Sub Tareas**

- [x] Agregar aviso para aclararle al usuario que el campo de NIT y CIIU no son obligatorios.
- [x] Modificar textos en donde dice director interno y debe ir externo.
- [x] Modificar alerta para que especifique correctamente que la ARL se carga en el apartado de revisión de documentos.
- [x] Comprobar que los cambios se hicieron correctamente.

**Criterios de aceptación**

- [ ] Modificaciones realizadas.
- [ ] Comprobación de cambios realizados.
- [ ] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
**Para la subtarea no. 1:**
Se modifica la lógica del html de crear_solicitud, con el fin de mostrar una advertencia en los campos de NIT y CIIU de la pasantía, visualizándose de la siguiente manera:

![Image](https://github.com/user-attachments/assets/7132112f-8b8a-4521-9e29-77232c3f0ea8)

**Para la subtarea no. 2:**
Se revisa en la base de datos los detalles asociados a la solicitud inicial de la Pasantía. En este se puede observar que los detalles de "Nombre del director externo" y "Documento del director externo" no están asociados a este formulario, sino que están los detalles de "Nombre del director interno" y "Documento del director interno":

![Image](https://github.com/user-attachments/assets/443480cc-44dd-4327-bf94-818ef4235687)

![Image](https://github.com/user-attachments/assets/8a2862a9-9bdd-41cc-aefa-94b23c278da8)

Por lo que se ejecuta el siguiente script para cambiar los detalles que si corresponden al formulario

```bash
UPDATE academica.detalle_tipo_solicitud
	SET detalle=53
	WHERE detalle = 70 AND modalidad_tipo_solicitud = 82;
	
UPDATE academica.detalle_tipo_solicitud
	SET detalle=54
	WHERE detalle = 71 AND modalidad_tipo_solicitud = 82;
```

Con esto, el formulario se mostraría de la siguiente manera:
![Image](https://github.com/user-attachments/assets/9b6b2ebb-427c-4917-973b-dc8b8a4af712)

**Para la subtarea no. 3:**
Desde los textos del cliente se modifica la advertencia del cargue de la ARL para mayor claridad con respecto a la sección en donde debe realizar el cargue del documento:

![Image](https://github.com/user-attachments/assets/24904cd3-830a-456e-909d-db302e3222f5)
