### ISSUE TITLE
Modificar cargue de documentos hacia nuxeo para que se haga en cola

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#662]
Se requiere realizar la modificación del cargue de documentos de núxeo para que este se haga en cola y no se envíen todos los documentos al tiempo para evitar fallos en el gestor_documental, para esto se sugiere usar las funciones asincronas para esperar respuesta de una petición para iniciar la siguiente..

**Sub Tareas**

- [x] Ajuste a lógica realizado.
- [x] Probar funcionamiento correcto, especilamente para modalidad de pasantía.

**Criterios de aceptación**

- [x] Ajuste de lógica realizado.
- [x] Pruebas de funcionamento realizas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se adjunta el mensaje de informe del daily:
![Image](https://github.com/user-attachments/assets/3e3d41a7-1b11-4445-91d3-ad32f9391510)

**Comment by JuanDHernandezA** [comment]
Se investigaron los distintos métodos que existen para hacer que un conjunto de peticiones se ejecuten una a una, esperando que responda la anterior petición. Se probaron los siguientes métodos:

- Agregar la palabra await en la petición y async en la función donde se encuentra dicha petición
- Crear una función asincrónica encargada de realizar todas las peticiones. Esta función se llama antes de realizar el Map del arreglo de documentos
- Crear una función asincrónica encargada de realizar una única petición. Esta función es llamada dentro del Map para enviar todas las peticiones necesarias
- Crear una Promesa dentro de la función asíncrona para controlar la respuesta de la petición
- Transformar el map en un 'For ... of ...' para recorrer cada documento y enviarlo a la función asíncrona.

Ninguno de los anteriores métodos funcionó, todos ejecutaban la petición a la misma vez y no esperaban a la respuesta de la anterior. Se sigue investigando para encontrar algún otro método que solucione el error

**Comment by JuanDHernandezA** [comment]
Se hace uso de funciones recursivas para que el aplicativo envíe una a una las peticiones al gestor documental. Al momento en que una petición responda de forma correcta, la función recursiva se encarga de enviar el siguiente documento al gestor documental. Una vez no queden más documentos a subir, la función llama a la siguiente funcionalidad y completar el flujo de la solicitud inicial.

Se prueba el resultado y se verifica que las peticiones no se envían a la vez:
![cargue_documentos](https://github.com/user-attachments/assets/c16413d5-d6eb-4b0f-addd-49ea9d406aee)

Con esta nueva funcionalidad, el formulario de la solicitud inicial de la modalidad de pasantía  y el API del gestor documental no fallan al enviar los 4 documentos asociados a la modalidad.

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego, muchas gracias.
