### ISSUE TITLE
Gestionar la elaboración del manual de usuario para la modalidad de pasantía

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#663]
Se requiere realizar la actualización del manual manual de usuario para la modalidad de pasantía 

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento.
- [x] Levantar requerimientos de elaboración.
- [x] Generar el requerimiento de elaboración de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión con Viviana para el día 08/08/2024 a las  11:00 am 

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzNkMjhhZmUtZGE4Ni00Mjg2LWEyODktYzYwZmY5MDE0NDBk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se definio la entrega para el día miercoles  14/08/2024 junto con Viviana

**Comment by mantnicot** [comment]
Se ha presentado retrasos de parte de Viviana con respecto a la entrega del manual , se espera esta semana se haga entrega

**Comment by mantnicot** [comment]
Se han gestionado los manuales de parte de Viviana

[Manuales pasantías](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkVjiWNcmNlIsjVjcTc16-QBt65tzoA8sRdrmlCTEMMYHA?e=jdBsHr)

**Comment by jcmurilloa** [comment]
Muy buen trabajo, quedaron full los manuales.
