### ISSUE TITLE
Actualizar diagrama de flujo modalidad pasantía nuevo formato

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#666]
Se requiere realizar la actualización del diagrama de flujo de la modalidad pasantía con el formato actual

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones segúnformato actualizado
- [x] Presentar al equipos SoS diagramas actualizados
- [x] Refinar diagramas según revisión de equipo SoS

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
se ha actualizado el formato 




![Image](https://github.com/user-attachments/assets/604a71a2-429f-49ce-9126-712dd291611f)



[Carpeta flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eh_lhUcUHmxJg20-w-IoqAwBoXJzcsoFYT2cWyMcpOupqQ?e=KERLhO)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, pendiente definición de estados con @diagutierrezro
