### ISSUE TITLE
Presentación para realización de manuales para modalidad de pasantía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#669]
Se requiere realizar la presentación a Viviana para la realización de los manuales del sistema en la modalidad de pasantía.

**Sub Tareas**

- [x] Realizar presentación a Viviana para la creación de los manuales.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realizó la presentación del flujo de la modalidad de Pasantía para el desarrollo de los manuales. Durante la presentación, el aplicativo presentó un error con respecto al Director Externo en el que no se almacenaba la información del vinculado desde la solicitud inicial.

Se adjunta la grabación de la reunión:

[Link de la Grabación](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n%20de%20Polux%20-%20Muestra%20manual%20de%20pasant%C3%ADas-20240808_110852.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=b1qjIh)

**Comment by JuanDHernandezA** [comment]
Se revisa la causa del error de no guardar de forma correcta el Director Externo. El error se produce debido a los cambios realizados en el issue #661, en donde se modificaron los detalles del formulario de la solicitud inicial para la modalidad de monografía. 

Se realizaron los cambios para almacenar los datos del Director Externo y se probaron, resultando de forma exitosa:
![Captura de pantalla 2024-08-08 181951](https://github.com/user-attachments/assets/e206cd6e-dab0-4ca7-a19d-7ab811a3e966)

Adicional a esto, se probó la solicitud de cambio de director externo para verificar la funcionalidad, la cual respondió de forma correcta:
![Captura de pantalla 2024-08-08 183509](https://github.com/user-attachments/assets/35eb3d71-6c4b-4965-8739-03d8885e6eb2)
