### ISSUE TITLE
Apoyo en la creación del acta de entregables a producción

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#670]
Se requiere realizar el apoyo en la creación del acta de entregables que se encuentra en el siguiente [documento](https://udistritaleduco-my.sharepoint.com/:w:/r/personal/diagutierrezr_udistrital_edu_co/Documents/2024/POLUX/Aceptaci%C3%B3n%20de%20entregable%20-%20p%C3%B3lux.docx?d=wf6d5f35ba79d4cbaa5cb50b82cfbd789&csf=1&web=1&e=DPGj1e), se puede usar como guia el [acta de entregables](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EVKJPydjPxBOldUqvgxPwgMB_h192kV1G0WuXUhHCQ7jlw) realizada para firma electrónica. 

Se requiere llenar unicamente la información de la tabla dejando de lado las columnas de revisión y aprobación.

**Sub Tareas**

- [x] Documento de acta de entregables llenado.
- [x] Documentación de issue.

**Criterios de aceptación**

- [x] Documento finalizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza apoyo a la realización del acta de entregables, el documento se visualiza en el siguiente link:

https://udistritaleduco-my.sharepoint.com/:w:/r/personal/diagutierrezr_udistrital_edu_co/Documents/2024/POLUX/Aceptaci%C3%B3n%20de%20entregable%20-%20p%C3%B3lux.docx?d=wf6d5f35ba79d4cbaa5cb50b82cfbd789&csf=1&web=1&e=DPGj1e

**Comment by diagutierrezro** [comment]
Se continuará posteriormente con el documento, muchas gracias Andres.
