### ISSUE TITLE
Limpieza de solicitudes y trabajos de grado en ambiente de pruebas

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#673]
Se requiere realizar la limpieza de solicitudes y trabajo de grado en ambiente de pruebas para reducir la cantidad de trabajos de grado que se han creado durante el proceso de desarrollo, para esto se requiere analizar la información que debe ser modificada o eliminada en la base de datos con los diferentes usuarios de pruebas con los que se cuentan, una vez hecho este análisis se requiere hacer la respectiva modificación o eliminación de dichos datos.

**Sub Tareas**

- [x] Análisis de información a modificar o eliminar para hacer la limpieza de solicitudes y trabajos de grado.
- [x] Modificación y/o eliminación de información para realizar la limpieza.
- [x] Probar con los diferentes usuarios de prueba que la limpieza se realizó de manera efectiva.

**Criterios de aceptación**

- [x] Anánlisis de información realizada.
- [x] Modificación y/o eliminación de datos realizada.
- [x] Comprobación de datos modificados y/o eliminados realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Inicialmente se revisan las peticiones que se ejecutan al momento de listar las solicitudes. Se observa que la petición a la tabla usuario_solicitud contiene la relación entre el código del estudiante con el id de las solicitudes.

Se revisa desde el menú de Listar Solicitudes con el perfil de un estudiante si la cantidad de solicitudes corresponde al mismo número de registros asociados a dicho estudiante en la base de datos:

![Image](https://github.com/user-attachments/assets/af939f87-1eaf-47b7-be64-52766bcf9fec)

![Image](https://github.com/user-attachments/assets/a832e733-6213-4a02-93d0-2ea560f2e722)

Al ser el mismo número de solicitudes, se confirma que se deben eliminar estos registros para reducir el número de peticiones al momento de Crear o Listar las solicitudes.

Se elimina un solo registro en la base de datos, esto con el fin de verificar que no exista ningún conflicto con alguna otra tabla o alguna funcionalidad en el aplicativo de Polux. Se probó la funcionalidad y no generó ningún error, por lo que se procede a eliminar todas las solicitudes, a excepción de las últimas 10 por usuario.

Se borraron las solicitudes de los siguientes usuarios:
- pruebasoaspolux
- pruebasoaspolux2
- pruebasoaspolux3
- pruebasoaspolux4

Se revisó cada uno de los menús de Polux con cada usuario de estudiantes y no presenta ningún error.

Revisando los perfiles de los docentes, el menú de Listar Solicitudes no presenta inconveniente debido a que primero se hace un filtro para consultar las solicitudes activas.

Se encontró un error al momento de entrar al menú de Revisión Documentos Docente, debido a que hay trabajos de grado antiguos que generan conflicto con las nuevas funcionalidades de Polux:

![Image](https://github.com/user-attachments/assets/3c2691fd-64ad-4dea-b460-c398a5ea62ee)

De igual manera, en el menú de Registrar Nota, los trabajos de grados que se observan sin código de estudiante no encuentra información del trabajo de grado en la base de datos

![Image](https://github.com/user-attachments/assets/9b1295f5-35d8-44c8-a711-4179a9de7803)

También este error ocurre en el menú de Pasantía:


![Image](https://github.com/user-attachments/assets/6f6a8771-215d-402f-ba5d-3c4539080dee)

**Comment by JuanDHernandezA** [comment]
Se procede a eliminar los trabajos de grado que generan los errores mencionados previamente. Se buscan por el id del trabajo de grado y se eliminan todos los registros asociados. Las tablas modificadas fueron:

- areas_trabajo_grado
- asignatura_trabajo_grado
- detalle_pasantia
- documento_trabajo_grado
- vinculacion_trabajo_grado
- revision_trabajo_grado
- correccion
- comentario
- evaluacion_trabajo_grado

Con estas eliminaciones ya los menús de Revisión Documento Docente, Registrar Nota y Pasantía no presentan ningún error:

![Image](https://github.com/user-attachments/assets/cdc9e52c-a706-4d4d-a024-1459c1d9203b)

![Image](https://github.com/user-attachments/assets/ebc8f9e5-e61c-43dd-a520-5eaceba201bb)

![Image](https://github.com/user-attachments/assets/6a23a7c6-c18a-4c10-ad25-6ff52a1f5dd2)

**Comment by diagutierrezro** [comment]
Se valida que las solicitudes ya no aparecen en el sistema, buen trabajo Juan Diego
