### ISSUE TITLE
Revisión de manera en la que falla el mid de pólux

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#674]
Se requiere realizar la revisión sobre como falla el mid de pólux una vez se ha implementado X-Ray en este mid ya que las peticiones ahora se manejan un poco diferente y se debe revisar la manera en la que falla el Api para realizar los respectivos ajustes posteriormente.

**Sub Tareas**

- [x] Revisión de la manera en la que falla el mid.
- [x] Documentar el issue con las respectivas pruebas realizadas y evidencias de la forma en la que falla el Api

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se analiza en que parte de las transacciones de solicitud interviene el MID, se toma para realizar pruebas el endpoint tr_solicitud para solicitar el cambio de titulo de un proyecto de grado, se altera una url en el MID en el helper que interviene para el correcto funcionamiento:



![Image](https://github.com/user-attachments/assets/b4951e05-a523-4517-98cb-3efd3d3fd7aa)

se ejecuta prueba para revisar la respuesta del error



![Image](https://github.com/user-attachments/assets/57233e54-14bb-4d63-b8f0-8fe55ac3f501)

vista del Response en Network del inspector del navegador

![Image](https://github.com/user-attachments/assets/e4f457e8-de7d-404d-87df-3536bbf1940f)

vista del Preview en Network del inspector del navegador


![Image](https://github.com/user-attachments/assets/02283ef9-cab0-44ed-a8e7-bbd9f06b3912)

vista de los Headers en Network del inspector del navegador



![Image](https://github.com/user-attachments/assets/23a84242-45fc-4719-9d51-47045e4cfb7c)

vista de la respuesta en la consola del MID


![Image](https://github.com/user-attachments/assets/e8f7e2b7-11b5-4fce-9edc-175772edbee2)

Se realiza prueba desde el postman cargando el body correctamente 



![Image](https://github.com/user-attachments/assets/2e8eb9b7-5efa-4c73-bf5e-0b590ff74488)

Se corrige el cambio de la url en el código del MID para que quede correctamente y ahora se procede a realizar una prueba enviando el payload erroneo o incompleto



![Image](https://github.com/user-attachments/assets/07474541-6277-4563-8024-8dbd3f621665)

visualización de las respuestas en consola del postman


![Image](https://github.com/user-attachments/assets/5a042f29-98a5-4e74-bbb5-f2f187b53325)

visualización de la respuesta en la consola del MID


![Image](https://github.com/user-attachments/assets/9853e6e2-3df0-4dce-9d0a-dd6c59ea829d)

Ahora se genera un error alterando la url de una consulta que al salir erronea debe entrar a una de las funciones de rollback


![Image](https://github.com/user-attachments/assets/d6a8e06c-bd9f-470e-ba70-993a49db3e79)

se realiza prueba desde postman


![Image](https://github.com/user-attachments/assets/759bc8cd-8577-4513-bd89-3b1513f002f3)

visualización de la respuesta en consola del MID



![Image](https://github.com/user-attachments/assets/d2a20c7a-cf1f-46cb-9921-1697a3c9d7f3)

Ahora se realiza prueba desde el cliente con la alteración previamente mencionada en el MID



![Image](https://github.com/user-attachments/assets/758e1f97-477a-44f0-a651-ff9d12c5cc13)

vista del Preview en Network del inspector del navegador


![Image](https://github.com/user-attachments/assets/15a65cee-6492-43c2-aa19-5d8bdfa0ad01)


vista del Response en Network del inspector del navegador


![Image](https://github.com/user-attachments/assets/1697c2f2-00e1-4364-8d13-21dd70c24b06)

vista de la respuesta en consola del MID


![Image](https://github.com/user-attachments/assets/65e9b72d-5bd5-44cc-b43f-c6235eb647b1)

**Comment by Astaroth-Andres-Molano** [comment]
De acuerdo a pruebas realizadas se encuentra que hay que realizar modificación en las respuestas en el CRUD debido a que desde esa instancia no están llegando el formato de respuesta correctamente, procedimiento se realizará en el issue #675

**Comment by diagutierrezro** [comment]
Se iniciará modificando la respuesta del CRUD y posteriormente se iniciará modificaciones necesarias en el MID y cliente.
