### ISSUE TITLE
Realizar ajustes para hacer que el Api de polux_mid falle correctamente - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#675]
Se requiere realizar los ajustes al Api de polux_mid para que esta falle correctamente, los ajustes a realizar se deberán analizar según lo que se encontró en #674 para que se ajuste a los requerimientos de la oficina.

**Sub Tareas**

- [x] Realizar ajustes a la manera en la que falla el Api.
- [x] Realizar pruebas de que las modificaciones funcionan correctamente.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan los ajustes en polux_crud en 50 controladores para que responda con el formato adecuado (success, statuscode, message, data, etc) en los mensajes de transacción satisfactoria ó error según el caso (post, getone, getall, put, delete, getbyuser, etc)


![Image](https://github.com/user-attachments/assets/82ee6993-076f-4eb7-aa90-6736c8056cea)



![Image](https://github.com/user-attachments/assets/b7942001-387e-4bfb-aa54-0e674051870b)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan pruebas para una transacción Post, el CRUD arroja error y no de la forma esperada


![Image](https://github.com/user-attachments/assets/cf9100a3-6bb1-4cd9-9325-69ad878af4b5)

Se realiza un backup de la base de datos para hacer pruebas en entorno local con el CRUD



![Image](https://github.com/user-attachments/assets/808ae710-3c59-431a-a395-217fa0b3404a)

Se vuelve a intentar probar realizando un post y vuelve a arrojar error no de la forma esperada


![Image](https://github.com/user-attachments/assets/799f2abb-f1f0-48a3-894e-373c1dfef5ba)

Se realiza prueba haciendo una consulta GET, responde exitosamente según los cambios


![Image](https://github.com/user-attachments/assets/d4910fa1-f461-4401-8eb1-cf1491c8662b)

Se realiza prueba con una consulta PUT, responde exitosamente según los cambios


![Image](https://github.com/user-attachments/assets/4a954b73-c25f-4318-8d0a-85fc16fe5f5e)

Se realiza prueba realizando consulta PUT pero con datos erróneos para que responda con error, responde con el formato esperado, el mensaje es el mensaje predeterminado en el encabezado del swagger


![Image](https://github.com/user-attachments/assets/0f5ee98a-10e2-4c4f-b879-b0251f154273)
