### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de exploración con Facultad de artes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#676]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de exploración con Facultad de artes
**Sub Tareas**

- [ ] Concertar reunión con el cliente.
- [ ] Desarrollar la reunión con el cliente.
- [ ] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto.
- [ ] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [ ] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha enviado un correo a petición de reunión , pues no se ha podido comunicar por el número brindado.

Tambien se buscara ir el presencialmente en caso de obtener respuesta




![Image](https://github.com/user-attachments/assets/41624a4b-9e80-4e83-b519-087451766db3)

**Comment by mantnicot** [comment]
Se ha comentado gracias a la gestión del lider tecnico y funcionamiento , que se pueda realiza runa reunión con la decanatura de artes para poder dar un cliente y poder gestionar los procesos , se adjunta el correo enviado desde computo a petición de funcionamiento y la decanatura.




![Image](https://github.com/user-attachments/assets/09cdef43-2fd9-465d-998b-9697cda0e362)

Se quedara a espera de poder realziar la reunión

**Comment by mantnicot** [comment]
Se ha hablado con computo con respecto a la respuesta de correo y se ha confirmado que se envió de forma incorrecta el correo y se hizo el envio



![Image](https://github.com/user-attachments/assets/8b9e8453-ca56-4c9a-852a-e59b8bd97b61)

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/9ca81734-6aa3-4238-b1d0-3583b504a069)


Se ha dado un cliente de parte de artes 
Se espera poder comunicarse para cuadrar una reunión

**Comment by jcmurilloa** [comment]
Debemos concertar con este cliente definido un pronto encuentro, con el ánimo de lograr el objetivo de la issue.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/da9498d5-5d23-4e60-b73f-796c4d86f9d3)

Se envio comunicación e caso de no respuesta se escribira directamente al correo para respuesta más inmediata

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/ff45aa2a-4a56-472a-9378-a640ed1446ff)
Se ha enviado el correo para comunicarse de forma más rapida con la facultad de artes

**Comment by mantnicot** [comment]
Se ha recibido respuesta de parte de la facultad

![Image](https://github.com/user-attachments/assets/066c28a2-85b2-4959-a300-dc9e53ce0cb4)

**Comment by jcmurilloa** [comment]
Por favor concertar la reunión con el responsable lo más pronto posible @mantnicot.

**Comment by mantnicot** [comment]
Se ha intentado comunicar con la persona , pero no responde 
![Image](https://github.com/user-attachments/assets/54e93cfe-7dee-44be-94ff-8b5269a7cb20)

Se volvera a comunicar con la facultad por correo

**Comment by jcmurilloa** [comment]
Por favor enviemos documento con información de Pólux por medio de correo electrónico, en caso de que haya interés y respuesta en el sistema, retomaremos nuevamente el ejercicio por medio de issues.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/e99b0a78-c51f-49ce-a7c5-e68ea8edb246)

**Comment by jcmurilloa** [comment]
A la falta de respuesta en múltiples contactos con los interesados para desarrollar un encuentro sincrónico, se procedé a enviar la información vía correo electrónico. Se queda a la espera del interés por parte del potencial usuario para concertar reuniones y exponer de manera más detallada la información.
