### ISSUE TITLE
Concertar y desarrollar sesión de exploración con Facultad tecnológica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#677]
Se requiere realizar la concertación y desarrollo de sesión de exploración con Facultad tecnológica

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Ya se ha podido realizar el primer contacto , a espera de poder generar una reunión con la persona intermediaria

**Comment by mantnicot** [comment]
Se ha podido hablar directamente con una persona de la facultad que nos conto la siguientes aclaraciones :

* Se realiza una fase anteproyecto y después revisión de terminados y no terminados 
* Se asigna los evaluadores dependiendo de la afinidad que tenga el mismo o el proyecto curricular lo asigna después de terminado
* Hay carreras que no publican el cronograma a tiempo

Junto a esto se informa que la única documentación que se usa en la facultad es con respecto a pasantías 

[URL DOCUMENTACIÓN PASANTÍA](https://ftecnologica.udistrital.edu.co/uextension/index.php/practicas-y-pasantias/practicas/normatividad)


Y por ultimo en al revisión se nota que se rigen libremente bajo el acuerdo 012 2022



![Image](https://github.com/user-attachments/assets/98a9285b-df81-48ca-a736-c9218d274db1)

**Comment by jcmurilloa** [comment]
Como lo repasamos en el Daily, debemos procurar contactar a la decanatura de esta facultad.

**Comment by mantnicot** [comment]
Con base a lo que paso cn la facultad de artes , se hablara con funcionamiento para poder apoyar en el contacto con Decanatura de la facultad de tecnologia

**Comment by jcmurilloa** [comment]
Pendiente enviar comunicado desde cómputo, similar al enviado para la Facultad de Artes.

**Comment by mantnicot** [comment]
Se ha generado el comunicado desde computo a la facultad de tecnologia



![Image](https://github.com/user-attachments/assets/8f9c5ca0-8f9c-4caa-8f14-6b4d9e19aa6b)

**Comment by jcmurilloa** [comment]
Buen trabajo, esperemos que este contacto surja efecto.

**Comment by mantnicot** [comment]
Se ha dado respuesta de parte de la facultad , dando asignación aun docente 



![Image](https://github.com/user-attachments/assets/24411795-80c8-4b91-8a81-b404671a557a)

**Comment by jcmurilloa** [comment]
Con esta respuesta debemos entonces concertar una reunión con este docente lo más pronto posible.

**Comment by mantnicot** [comment]
Se ha intentado obtener información/documentación sobre la facultad para pdoer concertar la reunión pero por problemas de gestion y comunicación no se ha podido obtener esta misma.

![image](https://github.com/user-attachments/assets/5708cc4a-a0c5-4b02-914a-5ec196cb177b)

Se espera poder concertar esta semana esa reunión para así agilizar los procesos de recolección de información

**Comment by jcmurilloa** [comment]
Se traslada la issue para un sprint mas reciente, con el ánimo de continuar el seguimiento.

**Comment by mantnicot** [comment]
Se iba arealizar hoy la reunión con Hermes del al facultad , pero no ubo asistencia de sus parte ni comunicación

Se espera poder gestionar otro espacio

![Image](https://github.com/user-attachments/assets/b9b69c6b-713c-4d15-9a9f-38ed82f55c25)

**Comment by jcmurilloa** [comment]
De no exisitir una concertación y desarrollo de la reunión en el siguiente sprint, se dará por cerrada la issue y se documentará sobre la falta de interés de la facultad en el sistema.

**Comment by mantnicot** [comment]
Se adjunta el acta del la sesión sin firmas

[acta de la sesión](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EYNoAJO7PmhMiN7D8jpZDVoBXtwLUJQBny0_csswGvpfHQ?e=2JmhYw)

**Comment by jcmurilloa** [comment]
Que buen acercamiento @mantnicot, esperamos sea el inicio de un gran usuario para nuestros sistemas. A recoger firmas!

**Comment by mantnicot** [comment]
Se adjunta el acta con las firmas correspondientes
[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EdNJg3QHRXJFmLMWvSSqBLABdcMGtF1UdzyB_HLtLp3cxg?e=8pPu9K)
