### ISSUE TITLE
Gestionar la elaboración del boletín para la promoción de Pólux

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#678]
Se requiere realizar la gestión para la generación de un boletín relacionado con el uso del sistema Pólux 

**Sub Tareas**

- [x] Generar contacto con responsable de boletines.
- [x] Levantar requerimientos de elaboración.
- [x] Generar el requerimiento de elaboración de boletín
- [x] Revisión de boletín generado

**Criterios de aceptación**

- [x] Solicitud de creación de boletín con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Ya se esta gestionando de parte de decanatura todo el proceso de boletín y distribución , aun así también se hablara con viviana para ver si hay necesidad de crear otro 




![Image](https://github.com/user-attachments/assets/065e610e-b1cc-4fae-816d-68aa1800184a)

**Comment by mantnicot** [comment]
Se han presentado demoras en la comunicación de parte de Viviana con respecto a entrega de logos en formatos de IU , para la edición de los boletines.

**Comment by mantnicot** [comment]
Se ha generado el envio de los logos



![Image](https://github.com/user-attachments/assets/dbcecaf2-db76-4021-95d3-4c95b7cc0c46)

**Comment by mantnicot** [comment]
Se ha generado el primer boletin de borrador pero con base a recomendaciones del equipo se han pedido cambios 




![Image](https://github.com/user-attachments/assets/cc178645-4f6e-452c-ad1c-ea1ac5d555a6)

**Comment by mantnicot** [comment]
Se espera actaulización

**Comment by mantnicot** [comment]
Se ha creado el boletin con las actualizaciones



![Image](https://github.com/user-attachments/assets/eca3fef3-6f23-474e-8df8-57aa03ab8cac)





![Image](https://github.com/user-attachments/assets/ac67376e-eee1-497f-bb83-8e3742e41978)



![Image](https://github.com/user-attachments/assets/f1b2a271-852b-4cb9-b07f-25d5181db85f)



![Image](https://github.com/user-attachments/assets/57d84f2c-25f8-4a24-8c65-c3e83a776da3)

**Comment by jcmurilloa** [comment]
Quedo muy completo el diseño de los boletines, excelente trabajo @mantnicot. Ahora a difundir!
