### ISSUE TITLE
Gestionar la expedición de resolución por parte de vicerrectoría para la implementación del sistema Pólux para las diferentes modalidades de grado

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#679]
Se requiere realizar la gestión para la expedición de resolución por parte de vicerrectoría relacionada con la implementación del sistema Pólux para las diferentes modalidades de grado 

**Sub Tareas**

- [x] Generar contacto con responsable en vicerrectoría.
- [x] Levantar requerimientos de elaboración.
- [x] Generar el requerimiento de elaboración de resolución.
- [ ] Revisión de resolución elaborada.

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de resolución con responsable
- [ ] Resolución expedida

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se propone el siguiente comunicado para vicerrectoría de parte de decanatura , pero se van a realizar cambios con respecto a la darle prioridad a crear una resolución 

[](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EVBb9BSkNU5DkcwtCoPZj00BbKghtJMu0RIQudqCblcpug?e=UIbyAa)

**Comment by mantnicot** [comment]
Este es el documento que se esta trabajando junto con el cliente de Decanatura

[Borrador documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EVBb9BSkNU5DkcwtCoPZj00BbKghtJMu0RIQudqCblcpug?e=JBROiG)

**Comment by jcmurilloa** [comment]
En este sentido, se refleja un documento tipo circular, más no un acto administrativo vinculante que exhorte al uso de Pólux por parte de la comunidad universitaria. Lo comentaremos en el próximo Review SoS.

**Comment by jcmurilloa** [comment]
Por favor explorar la proyección de una circular por medio de la OATI, para ser expedida por medio de vicerrectoría.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/d79dac99-2e2c-439c-9239-894109462d04)
se ha realizado el envio a computo , se espera la evidencia

**Comment by jcmurilloa** [comment]
Estaremos atentos a la respuesta.

**Comment by jcmurilloa** [comment]
Deriva el desarrollo de la Issue en generar una entrega de cada una de las modalidades a funcionamiento, con el ánimo de gestionar un comunicado masivo por parte de la OATI.
