### ISSUE TITLE
Revisar las apis

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/polux_cliente#68]
Revisar el estado y respuesta de las apis y endpoints usados según sus entornos.

( marcar el check de cada api según su entorno si ya fue revisada, cualquier novedad ha de ser comanda en los comentarios del presente issue)

- **conf_pruebas**
    - [x] ACADEMICA_SERVICE
    - [x] POLUX_SERVICE
    - [x] POLUX_MID_SERVICE
    - [x] CONFIGURACION_SERVICE
    - [x] NUXEO_SERVICE
    - [x] CORE_SERVICE
    - [x] OIKOS_SERVICE
    - [x] SESIONES_SERVICE

- **cloud_preproduccion**
    - [x] ACADEMICA_SERVICE
    - [x] POLUX_SERVICE
    - [x] POLUX_MID_SERVICE
    - [x] SESIONES_SERVICE
    - [x] CONFIGURACION_SERVICE
    - [x] NUXEO_SERVICE
    - [x] CORE_SERVICE
    - [x] OIKOS_SERVICE

**Comment by BrayanB24** [comment]
Las API se revisaron en las instancias de Amazon, se confirma que hay varias apagadas, se espera volverlas a desplegar hasta que se tenga el desarrollo terminado

**Comment by BrayanB24** [comment]
conf Pruebas: 

Las apis de  Polux Service y Polux MID Service se despliegan en contenedores de manera local con el entorno de desarrollo obtenido. ACADEMICA_SERVICE presenta estado de error interno 500 que debe ser revisado. CONFIGURACION_SERVICE retorna "200 status ok" por lo que aparentemente se encuentra en funcionamiento. NUXEO_SERVICE funciona de manera correcta. CORE_SERVICE retorna "200 status ok" por lo que aparentemente se encuentra en funcionamiento. OIKOS_SERVICE debe ser revisada pues no esta retornando el estado por defecto del api "200 status ok". SESIONES_SERVICE devuelve un estado 404 de error lo cual indica que puede no estar configurada en WSO2 o directamente no está desplegada. 

conf cloud_preproduccion:

Las API de preproducción se encuentran deshabilitadas o no funcionales, se recomienda volver a desplegar completamente polux en ambiente de pruebas. Este proceso se realizará una vez funcione de manera correcta el cliente.
