### ISSUE TITLE
Realizar lectura de documento para implementación de notificaciones

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#681]
Se requiere realizar la lectura del [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/nfwalterosp_udistrital_edu_co/EZyICfTJdlBBugaJATZ5_pwBDZT0YG7KWCWWzbJijvSumQ?e=cBYviX) para la implementación de notificaciones por correo en el sistema de pólux, mientras se va realizando la lectura ir analizando como se haría dicha implementación en el sistema de pólux.

**Sub Tareas**

- [x] Lectura de documento sobre firma electrónica.
- [x] Documentación sobre como se podría ir implementando las notificaciones.

**Criterios de aceptación**

- [x] Lectura realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realiza la lectura de la documentación del API de Notificaciones, de la cual se destaca y propone las siguientes funcionalidades para implementar en el aplicativo de Polux:

- Se debe enviar la notificación al usuario en los siguientes escenarios:
  - Al recibir una solicitud o respuesta de solicitud
  - Al recibir una solicitud de revisión
  - Al recibir un nuevo comentario en la revisión
  - Al momento en que un estudiante de modalidad de Pasantía carga el documento de ARL
  - Al momento en que la Oficina de Extensión de Pasantía aprueba o rechaza la ARL
  - Al momento en que el Docente Director carga un Acta de Seguimiento
  - Al momento en que el Docente Evaluador o Docente Director suben la nota del trabajo de grado

- Se propone la creación de Plantillas de correo para cada uno de los tipos de notificaciones mencionados, aprovechando la funcionalidad de la API y generalizando los mensajes generados por el sistema Polux, cambiando únicamente los textos como Nombre del estudiante, modalidad, tipo de solicitud, etc... Adicional a esto, se debe tener en cuenta las recomendaciones mencionadas en la documentación con respecto a las notificaciones clasificadas como "correo no deseado o spam"
- Se analiza que se debe crear y enviar la notificación desde el Cliente, al momento en que la transacción del MID responda de forma correcta
- Se debe contar con usuarios de prueba con los cuales se tenga acceso al correo electrónico y se puedan verificar las notificaciones generadas desde Polux
- Se investiga la forma de obtener los correos del usuario al cual se desea notificar; por medio de WSo2 o la API de AutenticacionMid existe la funcionalidad de obtener el correo por medio del documento, actualmente ese endpoint se encuentra en la rama Develop y no se ha subido a la API Store
