### ISSUE TITLE
Realizar implementació inicial de firma.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#682]
Se requiere realizar una implementación inicial de las notificaciones, teniendo en cuenta lo leido en #681, inicialmente se realizará una prueba de implementación cuando el estudiante realice una solicitud inicial en la modalidad de monografía, temporalmente se quemará el correo de Juan Diego para realizar las pruebas de esta implementación

**Sub Tareas**

- [x] Prueba inicial de implementación de notificaciones.
- [x] Documentar los errores y exitos obtenidos.

**Criterios de aceptación**

- [x] Prueba inicial realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se implementa el Servicio de Notificaciones por Correo desde el Cliente de Polux, al momento en que un estudiante envía el formulario de la solicitud incial. Se usa el formato de Payload recomendado en la documentación de #681:

![image](https://github.com/user-attachments/assets/8a7c9130-b291-4fb3-9eb1-e252356f9acc)

Se envía la petición POST al endpoint email/enviar_email, el cual no necesita de una plantilla para el envío del correo:

![image](https://github.com/user-attachments/assets/9a63b3f3-748d-4d24-a946-d63481e992eb)

Inicialmente se presenta el siguiente error, en donde a API responde un Status 400

![Captura de pantalla 2024-08-16 111312](https://github.com/user-attachments/assets/c09356a9-266b-4485-a01f-9d4deff5c13e)

Junto con Néider Walteros y Diego Gutiérrez se revisan los posibles errores, en donde encontramos que la url de intranet de la API de Notificaciones tenía https en vez de http. Se solicitan los cambios para que la url de auth apunte a la url con https.

Una vez realizados los cambios, el correo de envía de forma correcta:

![image](https://github.com/user-attachments/assets/289388fe-efd9-441a-8f6b-de2129d93127)

Con las pruebas realizadas se pueden destacar los siguientes comentarios:

- Siempre se va a mostrar la información del campo Html, a pesar de que se envíe vacio o el campo Text tenga infomación. La infomación de este último campo nunca se va a mostrar, pero se deben enviar los 2 campos dentro del Payload, sino se envían los 2, sale un error 500:
![image](https://github.com/user-attachments/assets/e1e8d3d4-5d8e-44a1-8157-93d249e0e1f1)

Si se envía con el Data de Html vacío, no muestra ningún mensaje:
![image](https://github.com/user-attachments/assets/630d8f9e-01db-4655-a4c6-aaaf9f2870d8)

Se recomienda enviar el campo de Text-Data vacío:
![image](https://github.com/user-attachments/assets/0a273c1f-d988-4469-b2eb-05f9ef0707f5)


- No es necesario tener el campo de "Attachments" con información (este es el campo para adjuntar documentos), se puede omitir si no se desean enviar documentos
- El correo llega a la Bandeja de Entrada, pero con el mensaje _"Algunos contactos que recibieron este mensaje no suelen recibir correos electrónicos de notificacionespolux@udistrital.edu.co. [Por qué esto es importante](https://aka.ms/LearnAboutSenderIdentification)"_
