### ISSUE TITLE
Buscar información del coordinador de los proyectos

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#683]
Se requiere realizar la busqueda en la base de datos de oracle la información necesaria para obtener los datos del coordinador, una vez se encuentre dicha información @diagutierrezro debe solicitar a Jhon la creación de un nuevo endpoint en JBPM para ser consultado.

**Sub Tareas**

- [x] Busqueda de información realizada en las bases de datos de oracle.
- [x] Documentación de tablas necesarias para realizar el endpoint.

**Criterios de aceptación**

- [x] Busqueda realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1: Busqueda de información realizada en las bases de datos de oracle.

En la base de datos "SUDD", específicamente en el esquema "MNTAC" hay dos tablas que pueden ser de gran utilidad para crear los endpoints, estas son: "ACCRA" y "ACDOCENTE". En la primera tabla se encuentran todos los coordinadores de los diferentes proyectos curriculares y en la segunda se encuentran los datos principales como el Nombre y Apellido del coordinador.

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Documentación de tablas necesarias para realizar el endpoint.**

1. El código de la carrera será enviando a través del endpoint.
2. Se busca en la tabla "ACCRA" por el código de la carrera suministrado en el endpoint, en la columna 'CRA_COD' y esto retornará la columna que nos sirve llamada 'CRA_EMP_NRO_IDEN' la cuál almacena el usuario o identificación del coordinador.
3. Tomando en cuenta el dato de la columna 'CRA_EMP_NRO_IDEN' se realiza la consulta al endpoint que ya existe: http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/servicios_academicos/coordinador_usuario 
4. Este retorna los datos necesarios (nombre y apellido) del coordinador de la siguiente manera y con el cuál se podría finalizar el reporte de solicitudes:
URL: http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/servicios_academicos/coordinador_usuario/86052448
Resultado:
<img width="565" alt="image" src="https://github.com/user-attachments/assets/8b284c4a-7e5f-44e3-b9aa-b27c964c8665">
