### ISSUE TITLE
Crear script para creación de endpoint en JBPM

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#684]
Se requiere realizar la creación del script de la consulta que se debe hacer en JBPM, posterior a esto hablar con Jhon para la creación del endpoint que ejecute el script realizado.

**Sub Tareas**

- [x] Crear Script de consulta teniendo en cuenta las tablas ACCRA y PEEMP el cual debe tener en el WHERE el filtro por el código del proyecto (CRA_COD).
- [x] Documentar script creado.

**Criterios de aceptación**

- [x] Script creado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
```SQL
SELECT empleado.EMP_NOMBRE
FROM MNTAC.ACCRA coordinador
JOIN MNTPE.PEEMP empleado
ON coordinador.CRA_EMP_NRO_IDEN = empleado.EMP_NRO_IDEN
WHERE coordinador.CRA_COD = 20;
```

**Comment by diagutierrezro** [comment]
Ya se le hizo la solicitud a Jhon para la creación del endpoint, aún nos encontramos a la espera.
