### ISSUE TITLE
Proyectar comunicado lanzamiento, punto medio y final de piloto en producción para modalidad pasantía

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#686]
Se requiere realizar la proyección del comunicados de lanzamiento, punto medio y final de de piloto en producción para la modalidad de pasantía.

**Sub Tareas**

- [x] Proyección de los comunicados
- [x] Revisión por parte del líder del proyecto
- [x] Documentación de los comunicados

**Criterios de aceptación**

- [x] Comunicado de lanzamiento aprobado
- [x] Comunicado de punto proyectado
- [x] Comunicado final proyectado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada líder de proyecto.

**Comment by mantnicot** [comment]
Se ha generado el correo para computo 



![Image](https://github.com/user-attachments/assets/5893ee0e-4b8d-411a-ad59-9629fd8bdf06)

**Comment by mantnicot** [comment]
Se ha generado el correo de lanzamiento con los diferentes usuarios del piloto



![Image](https://github.com/user-attachments/assets/082f6267-54ac-495d-9677-5384a6fabb83)

**Comment by jcmurilloa** [comment]
Gracias @mantnicot, estaremos atentos a la proyección y envío de comunicados de punto medio y final del piloto en esta misma issue.

**Comment by mantnicot** [comment]
Se ha enviado el comunicado de inicio previamente revisado con el equipo



![Image](https://github.com/user-attachments/assets/0fac978c-4474-4870-8b15-9733ff4a1ab8)

**Comment by jcmurilloa** [comment]
Excelente mensaje @mantnicot, esperemos cumpla el objetivo e iniciemos Polux de la mejor manera!

**Comment by mantnicot** [comment]
Se ha enviado el correo a computo para su envio 

![Image](https://github.com/user-attachments/assets/48cf1ec0-cc49-4570-9d00-79b8a1935358)

**Comment by mantnicot** [comment]
Se ha realizado el envio a los usuarios del piloto



![Image](https://github.com/user-attachments/assets/b7c42ba3-6501-4070-b3a5-1ce2acc09200)

**Comment by jcmurilloa** [comment]
Excelente comunicación la realizada a lo largo del piloto @mantnicot.

**Comment by mantnicot** [comment]
Se ha realizado la petición de envio del correo para finalización del piloto 

![Image](https://github.com/user-attachments/assets/1dd7698c-ce36-449f-a86f-b9d0ccbe201c)

**Comment by mantnicot** [comment]
se ha enviado el ultimo comunidado de parte de computo


![Image](https://github.com/user-attachments/assets/34abbf79-f2d5-45e2-ae21-93350046501b)
