### ISSUE TITLE
Definir templates para notificaciones.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#689]
Se requiere realizar la definición de los templates que se van a usar para el envío de notificaciones, tener presente las diferentes modalidades y notificaciones que se deben realizar e ir creando los templates.

**Sub Tareas**

- [x] Definir templates a realizar.
- [x] Crear los templates que se van a usar en las notificaciones.
- [x] Documentar los templates creados indicando en que parte del flujo se usarían.

**Criterios de aceptación**

- [x] Templates definidos.
- [x] Templates creados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realizó una reunión con @mantnicot en donde se analizaron los distintos escenarios donde se deba realizar el envío de notificación. Se crearon y diseñaron las siguientes plantillas:

- Solicitud Estudiante
- Respuesta Solicitud
- Solicitud ARL
- Respuesta ARL
- Registro de Nota
- Revisión Documento (estudiante)
- Revisión Documento (docente)

[Link grabación de la reunión](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/polux%20-%20plantillas%20notificaciones-20240820_120332-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=YJ7iES&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

Adicional a esto, se realizan pruebas de la funcionalidad para crear y usar plantillas en el sistema de notificaciones, por lo que se crea una plantilla de prueba:

```bash
{
    "Template":{
        "HtmlPart":"<p>Esto es un texto de prueba {{variable}}</p><p>Probando mas cosas {{variable}}</p>",
        "SubjectPart":"Asunto del correo {{texto}}",
        "TemplateName":"POLUX_PLANTILLA_PRUEBA",
        "TextPart":""
    }
}
```

Se prueba la plantilla, cambiando los valores de las variables creadas:

```bash
{
    "Source": "notificacionPolux@udistrital.edu.co",
    "Template": "POLUX_PLANTILLA_PRUEBA",
    "Destinations": [
        {
            "Destination": {
                "ToAddresses": [
                    "ajuanh@udistrital.edu.co"
                ]
            },
            "ReplacementTemplateData": {
                "variable": "texto de la variable",
                "texto": "SI ES DINAMICO"
            }
        }
    ]
}
```

Dando como resultado el siguiente correo:

![Image](https://github.com/user-attachments/assets/71af8af2-3cd5-4398-9fe0-122c194b3468)

Con las pruebas realizadas podemos resaltar los siguientes aspectos:
- Tanto el contenido del correo como el asunto pueden ser dinámicos si se usan variables desde la creación de la plantilla
- Se puede usar una misma variable varias veces dentro de la plantilla
- El campo de DefaultTemplateData no es obligatorio

**Comment by mantnicot** [comment]
Se adjunta las plantillas de los correos 

[PLANTILLAS CORREOS](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcRCnyhXAcdNhKZXcAvj7t8Bp2qzHFUmaHhBhwm5xvWhKg?e=uf5Bac)

**Comment by JuanDHernandezA** [comment]
Se crearon las plantillas en el sistema de notificaciones y se probaron cada una enviando el correo por medio del API Store, dando como resultado los siguientes correos:

- Solicitud Estudiante
![image](https://github.com/user-attachments/assets/85064d44-a297-4dd0-8db4-e47ab4ebd04a)

- Respuesta Solicitud
![image](https://github.com/user-attachments/assets/d5958bda-bb08-4ce4-93e1-b4219280a1b7)

- Solicitud ARL
![image](https://github.com/user-attachments/assets/388b3963-e634-4d23-bff4-3dd971a8f900)

- Respuesta ARL
![image](https://github.com/user-attachments/assets/d37cda94-570c-4bd5-8994-cbd1359e4bcb)

- Registro de Nota
![image](https://github.com/user-attachments/assets/a4b06996-b4c4-490f-b3f9-c9d7539e0813)

- Revisión Documento (estudiante)
![image](https://github.com/user-attachments/assets/53848df7-3d1d-47ee-9589-242e5d263e20)

- Revisión Documento (docente)
![image](https://github.com/user-attachments/assets/7d857e78-a224-49fc-8b36-644b90d6a0fb)

Con lo cual ya se pueden usar las plantillas desde el sistema de Polux

**Comment by diagutierrezro** [comment]
Muy buen trabajo a los dos, las plantillas están muy bien realizadas, con esto se continúa implementación de notificaciones en el sistema. Gracias.
