### ISSUE TITLE
Mostrar flujo basico de pólux con imagenes en un celular

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#690]
Se requiere realizar una demostración del flujo basico de pólux haciendo el proceso desde un celular sacando los respectivos pantallazos, esto por solicitud del usuario para generar un boletín.

**Sub Tareas**

- [x] Flujo básico realizado desde un celular.
- [x] Cargar imagenes del flujo en la siguiente [carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuuQVfl2SkNMuvemu0ghUxMBbQ3CBeUswBuNJIlmABPziA?e=AVtQa1).

**Criterios de aceptación**

- [x] Flujo basico realziado.
- [x] Imagenes cargadas.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
SubTarea N°1:  Flujo básico realizado desde un celular.

1. Desafortunadamente el despliegue de las opciones en los formularios principales como el de crear solicitud, no funcionan desde el celular, adjunto evidencia:

![Imagen de WhatsApp 2024-08-23 a las 09 44 46_37045ea2](https://github.com/user-attachments/assets/29c7ea45-3f0c-4347-8b7c-5014b99b90cc)

Es por está razón que no se pudo continuar con todo el flujo.

**Comment by CrisEs2506** [comment]
SubTarea N°2: Cargar imagenes del flujo en la siguiente [carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuuQVfl2SkNMuvemu0ghUxMBbQ3CBeUswBuNJIlmABPziA?e=AVtQa1).

https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuuQVfl2SkNMuvemu0ghUxMBbQ3CBeUswBuNJIlmABPziA?e=AVtQa1
