### ISSUE TITLE
Realizar ajustes al sistema para piloto de pasantía en producción

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#693]
Se requiere realizar el 

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
Después de una revisión y análisis, se llegó a la conclusión que debido a que en la base de datos de Academica se guardan únicamente los ID's (llaves foraneas) que conectan con otras bases de datos como Parametros y JBPM, es inevitable el no usar consultas que quemen dichos ID's. Por tanto, se llegó a una posibilidad para hablar con los ingenieros DBA, para estudiar el caso en el que se implementen otras columnas para almacenar el Código de Abreviación y de este modo, que las consultas se realicen teniendo en cuenta este Código de Abreviación, con el fin de que independientemente de si se usa bases de datos de producción o pruebas, siempre encuentre la información asociada a este código y no con un ID que está sujeto a cambios.

**Comment by JuanDHernandezA** [comment]
Se presentó un error al momento de enviar la solicitud inicial. El mensaje de la consola fue el siguiente:

![Image](https://github.com/user-attachments/assets/4f3a2d09-9b9f-4752-844c-f5fa6d291754)

Revisando el error, se observa que el tipo de detalle "Archivo Anexo" no estaba actualizado en la base de datos:

![Image](https://github.com/user-attachments/assets/d62dda35-c2d3-44cf-b587-f2d8da4319a1)

Por lo que se sincroniza con el registro actual de la base de datos de desarrollo

![Image](https://github.com/user-attachments/assets/8bf8768f-ecf7-459f-a60c-9d08209bfbe2)

Se prueba nuevamente la Solicitud Inicial y funciona correctamente

**Comment by mantnicot** [comment]
Se ha revisado y se deja abierta hasta que se culmine el flujo con los usuarios

**Comment by diagutierrezro** [comment]
El piloto se finalizó satisfactoriamente.
