### ISSUE TITLE
Revisar scripts y endpoints utilizados para reportes.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#694]
Se requiere realizar una reunión en conjunto  con @diagutierrezro para revisar los scripts y endpoints utilizados en el reporte para definir si los metodos utilizados se van a mantener o se van a modificar.

**Sub Tareas**

- [x] Realizar reunión entre desarrollador y lider tecnico.

**Criterios de aceptación**

- [x] Reunión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
Después de una revisión y análisis, se llegó a la conclusión de que debido a que en la base de datos de Academica se guardan únicamente los ID's (llaves foraneas) que conectan con otras bases de datos como Parametros y JBPM, es inevitable el no usar consultas que quemen dichos ID's. Por tanto, se llegó a la posibilidad de hablar con los ingenieros DBA, para estudiar el caso en el que se implementen otras columnas para almacenar el Código de Abreviación y de este modo lanzar las consultas SQL, con el fin de que independientemente de si se usa bases de datos de producción o pruebas, siempre encuentre la información asociada a este código y no con un ID que está sujeto a cambios.
