### ISSUE TITLE
Ajustar scripts para creación de formularios de diferentes solicitudes

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#696]
Se requiere realizar el ajuste de los scripts para la creación de los formularios de las diferentes solicitudes del sistema. Se debe primero revisar el orden actual de las diferentes solicitudes en ambiente de pruebas y ajustar los scripts para enviarse a los DBA y ajustar los formularios en producción.

**Sub Tareas**

- [x] Revisar orden actual de formularios.
- [x] Ajustar scripts para modificar formularios en producción.
- [x] Documentar scripts enviados.

**Criterios de aceptación**

- [x] Revisión de formularios en ambiente de pruebas realizada.
- [x] Scripts ajustados.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se comparan los formularios de la solicitud de revisión de trabajo de grado para todas las modalidades y se realiza el siguiente script para la sincronización con la base de datos de producción. En los scripts se realiza la inserción del campo de "documentos anexos" a todos los formularios y se actualizan el orden de algunos detalles debido al nuevo detalle agregado. También se agrega el detalle de "país de la revista" para la modalidad de artículo académico y se agregan los campos faltantes al formulario de la solicitud inicial de Pasantía:

```bash
INSERT INTO academica.detalle_tipo_solicitud(
detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES  (76, 67, true, false, 4),
		(76, 68, true, false, 4),
		(76, 92, true, false, 3),
		(76, 65, true, false, 4),
		(76, 66, true, false, 4),
		(76, 69, true, false, 3),
		(77, 65, true, false, 5),
		(78, 65, true, false, 6),
		(79, 69, true, true, 5),
		(77, 92, true, false, 4),
		(78, 92, true, false, 5),
		(73, 82, true, false, 7),
		(74, 82, true, false, 8);

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=4
	WHERE id=298;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=6
	WHERE id=299;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=7
	WHERE id=300;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=6
	WHERE id=302;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=9
	WHERE id=264;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=10
	WHERE id=265;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=11
	WHERE id=266;
	
UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=12
	WHERE id=267;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=13
	WHERE id=268;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=14
	WHERE id=271;
```

Adicional a esto, se actualiza el nombre de la modalidad de grado de Pasantía, antes nombrada Pasantía Interna

```bash
UPDATE parametros.parametro
	SET nombre='Pasantía'
	WHERE codigo_abreviacion = 'PAS_PLX';
```

**Comment by diagutierrezro** [comment]
Los scripts ya se ejecutaron en ambiente de producción, buen trabajo Juan Diego
