### ISSUE TITLE
Concertar y desarrollar sesión de capacitación piloto pasantía con usuarios

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#697]
Se requiere realizar la concertación y desarrollo de sesión de capacitación piloto pasantía con usuarios

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.

**Criterios de aceptación**

- [x] Sesión grabada en Teams.
- [x] Documentación resultante de la sesión.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se crea un documento base para la sesión de capacitación
[Documento de base](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EUhmcg0WyPxOhdeYHl1PzwIBfhhxnf27JX28ggbRobE3Ew?e=qwauWv)

**Comment by jcmurilloa** [comment]
Es un documento que cuenta con los principales aspectos del sistema, es posible que podamos con base en este proyectar una presentación para este proceso de capacitación? Tenemos avance en la concertación de la primera sesión?

**Comment by mantnicot** [comment]
Se ha creado la reunión para el día 29/08/2024 y se adjunta material visual para un proceso rápido

[Presentación para la capacitación](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EWsZZ7cDj4ZBubovUqFYhQoBRgnG_RC0dPkMy6y1sFSqrQ?e=9mOUag)


[link reunion](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmEwYmVlZWItODk1Yi00YzRiLWEyM2UtMjgwYzczNjAzN2Y3%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha generado el acta de la sesión

[Acta de reunión](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWg1XpkvE-FOtc1QgLdXZ-QBCbyg8WAu2jSaRtVtyE-Odw?e=pnSXSL)

**Comment by jcmurilloa** [comment]
Estaremos atentos a la suscripción del acta por parte de los responsables para el respecto cierre de la issue.

**Comment by mantnicot** [comment]
Se ah recogido todas las firmas 

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Ecfqz_VKjGFOv8dxRC6B8FIBf2qg1zeY33H91BJEOa0Kbg?e=R7Jaru)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, el piloto avanza muy bien!
