### ISSUE TITLE
Generar la investigación relacionada con las notificaciones y sus posibles errores de implementación

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#698]
Se requiere realizar la investigación relacionada con las notificaciones y sus posibles errores de implementación

**Sub Tareas**

- [x] Generar contacto con el responsable.
- [x] Adelantar la investigación.
- [x] Alimentar la documentación relacionada.

**Criterios de aceptación**

- [x] Documento con información relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha enviado la siguiente información de parte de Brayan Sierra



![Image](https://github.com/user-attachments/assets/4a7f5d69-b4d3-4c43-b286-44f0a30a06de)



[Issue 1313](https://github.com/udistrital/planeacion_cliente/issues/1313)
[Issue 1332](https://github.com/udistrital/planeacion_cliente/issues/1332)
[Issue 1333](https://github.com/udistrital/planeacion_cliente/issues/1333)

**Comment by jcmurilloa** [comment]
Con base en estas issues, podemos ir estructurando el documento de investigación. Cuando Bryan comenta que la documentación es reducida, quiere decir que es nula? Esperamos más información de parte de él?

**Comment by mantnicot** [comment]
Se comenzó analizar los issues dados por Brayan.

De primera parte se puede analizar la información en el documento de notificaciones , y se puede ver que se hace un comentario sobre la posibilidad de envió pero no generar el correo 

![Image](https://github.com/user-attachments/assets/9b827ad9-0c68-4503-b60a-f65262c4faf3)

Tambien se puede ver como manejar los errores 

![Image](https://github.com/user-attachments/assets/ff205fc7-bd68-434e-8ea8-56f595ecf5f8)

Pero aun así se cuenta que la posible solución de subir a producción se genera el problema de envió 

![Image](https://github.com/user-attachments/assets/8000fa0e-b218-4f52-b059-ffec431dae6d)

Se ha buscado directamente en amazon y se encuentra la sigueinte información para solucionar o identificar : 

![Image](https://github.com/user-attachments/assets/10242315-158b-41b4-9d5a-048f75699e6c)

![Image](https://github.com/user-attachments/assets/3b4724d8-0150-4770-8bc2-d6d3ab85cb83)



No se nota documento el porque el error.

**Comment by mantnicot** [comment]
al investigar sobre amazon SES , se le pregunta a Jaime sobre esta información , y se espera repsuesta 



![Image](https://github.com/user-attachments/assets/683097a5-b0ac-4dd8-9b02-9268fa1c6e32)

**Comment by jcmurilloa** [comment]
Esperemos pronta respuesta por parte de Jaime para complementar la documentación resultante de la investigación.

**Comment by mantnicot** [comment]
Se ha podido charlar co el ingeniero Jaime y pidio que se informara por medio de tuleap , por lo cual se esta levantado la información del correo al cual se le asigno el amazon ses y así poder crear el KB



![Image](https://github.com/user-attachments/assets/5277a321-9d6a-478b-b651-6b86d19a4e68)

**Comment by jcmurilloa** [comment]
Pendiente entonces @mantnicot, de la creación del KB para documentar aquí en la issue.

**Comment by mantnicot** [comment]
Se ha generado una reunión con ele quipo de Brayan y Jaime , para el día 10/09/2024 a las 2 pm 

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDljOWI1ZWEtODBkMi00MTZiLWI2NjgtNjUxZWQ5ZGIzM2Y1%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by jcmurilloa** [comment]
Por favor reportar con el analista del equipo 1 de inversión, para entregar la respectiva documentación y que inicien con el desarrollo de las soluciones.
