### ISSUE TITLE
Ajustar cliente para adaptarlo a cambios en estructuras de respuesta desde el crud - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#699]
Se requiere realizar los respectivos ajustes en el cliente de pólux para adaptar el sistema a las respuestas obtenidas por el CRUD y que la lógica no se vea afectada. Para esto es importante tener en cuenta que según los cambios realizados en el CRUD este ahora responde con una estructura donde la información se encuentra en un campo llamado Data.

**Sub Tareas**

- [x] Ajustar cliente para que responda correctamente teniendo en cuenta la nueva estructura del CRUD.
- [x] Probar funcionamiento correcto del sistema.
- [x] Documentar pruebas realizadas con los respectivos resultados.

**Criterios de aceptación**

- [ ] Cliente ajustado.
- [ ] Pruebas realizadas.
- [ ] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza modificación en el formato de recepción de respuestas para capturar la Data en el cliente en todas las peticiones realizadas al CRUD


![Image](https://github.com/user-attachments/assets/f6d72201-a3fb-4cc0-aa3c-9dda9ca8d39a)

Se realiza el procedimiento en todos los controladores del cliente en cada petición realizada al CRUD


![Image](https://github.com/user-attachments/assets/19098359-a3ec-42a8-8f06-398636290d52)

Se configura el endpoint del CRUD en el cliente para trabajar con el CRUD con el nuevo formato en local


![Image](https://github.com/user-attachments/assets/e25cd9e9-5ed2-42ac-82df-188343766972)

Se corre el CRUD en local


![Image](https://github.com/user-attachments/assets/c4205fdf-fd20-4b21-9580-c7f410822ca0)

Se realizan pruebas de funcionamiento pero hay un error, se interrumpe el flujo del cliente en un punto y no carga los detalles y solicitudes


![Image](https://github.com/user-attachments/assets/ec79dea8-13ad-4c1a-9fd5-13a85a6da870)

Se realiza analisis de la falla, se hace un barrido por todo el cliente verificando que el procedimiento se haya realizado corrctamente y no haya errores en la captura de la Data en elguna petición, se imprimen varios objetos en algunas funciones para hacer seguimiento del flujo de la lógica del cliente, la falla se está presentando en el controlador crear_solicitud.js en la ejecución del método getProrroga, se sigue haciendo analisis para solucionar la falla.
