### ISSUE TITLE
Revisar el error en visualización de desplegables desde vista de dispositivo movil.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#700]
Se requiere realizar la revisión del error encontrado en #690 donde se encontró que desde la vista de un dispositivo móvil los desplegables no se muestran por lo que el flujo no se puede completar. Tener presente que en las pruebas que se hicieron desde el navegador cuando se pasa de vista normal a vista de dispositivo movil y los desplegables ya están cargado el desplegable si se muestra correctamente.

**Sub Tareas**

- [x] Realizar revisión de error de visualización en dispositivo movil.
- [x] Realizar ajustes necesarios para corregir el error.
- [x] Pruebas de correcto funcionamiento.

**Criterios de aceptación**

- [x] Revisión de error realizada.
- [x] Ajustes realizados.
- [x] Pruebas de correcto funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
Después de numerosos intentos por hacer funcionar los Selects de Polux, se ha hecho una comprobación creando un formulario común y corriente que funcionaría en cualquier dispositivo móvil, y al parecer, después de compilarse es que se dañan los selects, por lo que es una cuestión de tecnologías y herramientas que posiblemente se encuentran demasiado desactualizadas a los navegadores de los dispositivos móviles a día de hoy.
