### ISSUE TITLE
Ajustar descargar de documentos anexos en la sección de ver solicitudes

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#701]
Se requiere realizar el ajuste en la sección de visualizar solicitudes en el que las solicitudes de revisión no permiten descarga de los documentos anexos 

![Image](https://github.com/user-attachments/assets/2face8fa-4961-43e9-9c13-e5c759f835d3)

Guiarse de la lógica creada en aprobar_solicitud, función getDocAnyFormat, los documentos anexos deben descargarse.

**Sub Tareas**

- [x] Ajustar visualización de solicitudes de revisión para permitir descarga de documentos.
- [x] Probar funcionamiento correcto de la funcionalidad.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Ajustar visualización de solicitudes de revisión para permitir descarga de documentos.**

1. Se agrego los siguientes divs en el archivo "listar_solicitudes.html" de la carpeta "views/solicitudes/" y "views/directives/solicitudes" respectivamente:

``` HTML
<div ng-if="detalle.carrera===undefined">
                    <div ng-if="detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion!=='DOC_PLX' && detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion!=='LNUX_PLX' && detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion!=='DAN_PLX'">
                        <!-- <label class="col-sm-8 "> {{detalle.Descripcion}} </label> -->
                        <div ng-if="detalle.DetalleTipoSolicitud.Detalle.CodigoAbreviacion === 'LR'">
                            <a class="col-sm-8" ng-href="{{detalle.Descripcion}}" target="_blank">{{detalle.Descripcion}}</a>
                        </div>

                        <div ng-if="detalle.DetalleTipoSolicitud.Detalle.CodigoAbreviacion !== 'LR'">
                            <label class="col-sm-8">{{detalle.Descripcion}}</label>
                        </div>
                    </div>
                    <div ng-if="detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='DOC_PLX' || detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='LNUX_PLX'">
                        <label ng-click="listarSolicitudes.getDocumento(detalle.Descripcion)" class="col-sm-8 " style="color:blue; text-decoration: underline;"> {{ 'VER_DOCUMENTO' | translate}} </label>
                    </div>
                    
                    <div ng-if="detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='DAN_PLX'">
                        <label ng-click="listarSolicitudes.getDocAnyFormat(detalle.Descripcion)" class="col-sm-8 " style="color:blue; text-decoration: underline;"> {{ 'DESCARGAR_DOCUMENTOS' | translate}} </label>
                    </div>
                  </div>
```

``` HTML
<div ng-if="detalle.carrera===undefined">
                            <div ng-if="detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion!=='DOC_PLX' && detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion!=='LNUX_PLX' && detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion!=='DAN_PLX'">
                              <!-- <label class="col-sm-8 "> {{detalle.Descripcion}} </label> -->
                              <div ng-if="detalle.DetalleTipoSolicitud.Detalle.CodigoAbreviacion === 'LR'">
                                <a class="col-sm-8" ng-href="{{detalle.Descripcion}}" target="_blank">{{detalle.Descripcion}}</a>
                              </div>
                              
                              <div ng-if="detalle.DetalleTipoSolicitud.Detalle.CodigoAbreviacion !== 'LR'">
                                <label class="col-sm-8">{{detalle.Descripcion}}</label>
                              </div>
                          </div>
                          <div ng-if="detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='DOC_PLX' || detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='LNUX_PLX' || detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='DAN_PLX'">
                              <label ng-click="d_listarSolicitudes.getDocumento(detalle.Descripcion)" class="col-sm-8 " style="color:blue; text-decoration: underline;"> {{ 'VER_DOCUMENTO' | translate}} </label>
                          </div>

                          <div ng-if="detalle.DetalleTipoSolicitud.Detalle.TipoDetalleAux.CodigoAbreviacion==='DAN_PLX'">
                            <label ng-click="d_listarSolicitudes.getDocAnyFormat(detalle.Descripcion)" class="col-sm-8 " style="color:blue; text-decoration: underline;"> {{ 'DESCARGAR_DOCUMENTOS' | translate}} </label>
                          </div>
                        </div>
```

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Probar funcionamiento correcto de la funcionalidad.**

1. Listar Solicitud:

<img width="524" alt="image" src="https://github.com/user-attachments/assets/a7ca60a2-c2c5-47d4-b509-5e37a26ecbae">

2. Aprobar Solicitud:

<img width="530" alt="image" src="https://github.com/user-attachments/assets/73ed9728-bb19-48ea-aaea-b5f48fb0a498">

3. Consultar Trabajo Grado:

<img width="521" alt="image" src="https://github.com/user-attachments/assets/a4581bfe-561b-42d9-b56c-0d69c3293c0c">

**Comment by diagutierrezro** [comment]
Muy buen trabajo Cristian.
