### ISSUE TITLE
Realizar reunión con estudiantes usuarios de Pólux

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#702]
Se requiere realizar reunión con los estudiantes usuarios de pólux para explicarles el flujo del sistema en la modalidad de pasantía.

**Sub Tareas**

- [x] Realizar reunión con usuarios.
- [x] Realizar presentación del flujo.

**Criterios de aceptación**

- [x] Reunión realizada.
- [x] Presentación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realizó la reunión con los usuarios en donde se presentó y probó el funcionamiento del sistema Polux para la creación de la Solicitud Inicial para la modalidad de pasantía.

Durante la presentación se presentó un error en los campos de los formularios, el cual ya fue solucionado y documentado en el issue #693  

Se adjunta link de la reunión:

[Grabación de la reunión](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/P%C3%B3lux%20-%20Primer%20acercamiento%20rol%20estudiantes-20240829_171245-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=voMaCW)

**Comment by diagutierrezro** [comment]
El error fue solucionado y se encuentra documentado en el issue de #693 . Muchas gracias Juan Diego
