### ISSUE TITLE
Ajustar cliente para adaptarlo a cambios en estructuras de respuesta desde el crud - parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#704]
Se requiere realizar la finalización del ajuste del cliente para adaptarlo a las nuevas respuestas que se reciben desde el CRUD, se debe terminar de corregir los errores presentados en #699 para que el cliente funcione como lo hacía anteriormente.

**Sub Tareas**

- [x] Terminar ajuste de cliente para adpatción a nuevas solicitudes.
- [x] Pruebas de funcionamiento correcto en general de todo el flujo del sistema.

**Criterios de aceptación**

- [x] Ajustes finalizados.
- [x] Pruebas de funcionamiento correcto realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se continúa haciendo pruebas de funcionamiento al flujo, desde estudiante se sube actualización del documento


![Image](https://github.com/user-attachments/assets/961d7c2e-71d3-4832-bce5-bbaac0443cef)

Se solicita revisión de manera exitosa


![Image](https://github.com/user-attachments/assets/a1f04dd3-686a-414e-845f-e3a26ce100a8)



![Image](https://github.com/user-attachments/assets/31cbac33-6eb3-431a-b136-d138c7564e90)

Desde docente director se ingresa para revisar la nueva versión



![Image](https://github.com/user-attachments/assets/d790676a-b146-4113-9936-fbd08ded9816)

Se realiza comentario al documento y se registra exitosamente


![Image](https://github.com/user-attachments/assets/069c34d4-d9a4-4b9b-9392-43e757a7ac70)

Desde el estudiante se revisa la corrección o comentario por parte del docente director



![Image](https://github.com/user-attachments/assets/c1947c9e-3f73-4d00-b9be-f475343d6f30)



![Image](https://github.com/user-attachments/assets/853fa6e9-4af7-4438-8aff-cd9143a2fad8)

Se realiza solicitud de revisión final del proyecto de grado


![Image](https://github.com/user-attachments/assets/99342385-079b-4089-8d15-31c31c8e0f32)

Desde docente director se revisa la solicitud


![Image](https://github.com/user-attachments/assets/e74f3039-52f5-4fae-a184-df80cb046576)

Se realiza prueba de rechazo de la solicitud de manera exitosa


![Image](https://github.com/user-attachments/assets/88e45196-a3fe-46fb-be34-c15088d50d67)

Se modifica el Aviso en los detalles de documentos anexos



![Image](https://github.com/user-attachments/assets/c997298d-1931-4e35-984d-ddceee2bde80)

Se vuelve a realizar el procedimiento de solicitud de revisión final de proyecto de grado, desde docente director se aprueba y ahora se realiza el procedimiento desde coordinador



![Image](https://github.com/user-attachments/assets/b1447b7f-d100-4269-a2d2-f182c7b73eea)



![Image](https://github.com/user-attachments/assets/1826047e-7b9c-4423-8d82-85c07e30b959)

Aprobación exitosa



![Image](https://github.com/user-attachments/assets/07834805-d41b-457f-9b00-d233505ce069)

Se ingresa desde docente evaluador 



![Image](https://github.com/user-attachments/assets/3563ce76-beec-46ca-8cb2-14165c508162)

Se registra la calificación de manera exitosa



![Image](https://github.com/user-attachments/assets/4d57564f-2822-4716-a297-d7bd01b7b7ff)



![Image](https://github.com/user-attachments/assets/24bb4fa4-8ff8-4c74-8a2f-53a120772420)

Ahora desde docente director se realiza registro de la nota



![Image](https://github.com/user-attachments/assets/bded3325-ceea-4295-b277-860be72c6291)



![Image](https://github.com/user-attachments/assets/94b6eecc-5404-414d-9784-2a0c20d26def)

Registro de nota exitosamente



![Image](https://github.com/user-attachments/assets/d37800dc-1278-4e5b-98d1-09ff171b4da5)

Por último desde estudiante se visualiza las notas registradas



![Image](https://github.com/user-attachments/assets/f4aeb0a3-73b2-4770-96b0-36da9a8cf927)

**Comment by diagutierrezro** [comment]
Queda pendiente revisar manejo de errores una vez se termine de estabilizar el MID. Buen trabajo Andres
