### ISSUE TITLE
Concertar y desarrollar sesión de capacitación piloto pasantía con usuario oficina pasantías y coordinadores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#707]
Se requiere realizar la concertación y desarrollo de sesión de capacitación piloto pasantía con usuarios oficina pasantías y coordinadores

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.

**Criterios de aceptación**

- [x] Sesión grabada en Teams.
- [x] Documentación resultante de la sesión.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido concretar con la ofician de pasantías la reunión para el día 5/09/2024 a las 11:00 am

[Enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjRlMjU3ZjQtMWU2OS00MWQ5LTgxYjUtYmYyZWQyNDU5ZmM0%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by jcmurilloa** [comment]
Trata de no dejar pasar más de dos días entre el desarrollo de la reunión y el acta, es importante tener la información reciente para generar la narrativa de la reunión lo más cercana posible al encuentro desarrollado.

**Comment by mantnicot** [comment]
Se ha creado el acta correspondiente a al reunión

[acta de reunión](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdETjeIQvrNDtXo2Jduj61wBbo4p06KNwEXg_MrBUbu1hA?e=RdAC01)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, puedes recopilar las respectivas firmas.

**Comment by mantnicot** [comment]
Se ha recolectado todas las firmas 

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Edbw2dW_UaBBmOMd6A5O1vQBKEbqIGzB90R534RDUvM46Q?e=pAQNsr)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot !
