### ISSUE TITLE
Generar contacto con las Facultades ciencias de la salud, ciencias y eduación y ciencias, matemáticas y naturales para la promoción y uso de Pólux

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#708]
Se requiere realizar el Generar contacto con las Facultades ciencias de la salud, ciencias y eduación y ciencias, matemáticas y naturales para la promoción y uso de Pólux

**Sub Tareas**

- [x] Enviar correos electrónicos a Facultades
- [x] Contactar por medio telefónico a responsable desginados
- [ ] Concertar sesiones de exploración del uso de Pólux

**Criterios de aceptación**

- [x] Correo electrónico enviado
- [ ] Contacto efectivo con responsable de cada facultad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha enviado el comunicado de parte de computo para las facultades


![Image](https://github.com/user-attachments/assets/f1a1d284-c178-4184-913a-6fb6fbeb4089)



![Image](https://github.com/user-attachments/assets/de800e95-09ca-4e0c-a5ce-57c911b6f780)



se espera respuesta

**Comment by mantnicot** [comment]
Se ha podido obtener respuesta de la facultad de ciencias de la salud , pero en el primer contacto al paracer no tienen ningun tipo de documentación con respecto a trabajo de grado

**Comment by mantnicot** [comment]
Se ha generado una matriz con base a lo dicho por el Gerente para dar seguimiento a los avances en la diferentes facultades

[Matriz de facultades](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZQjW-s7PzREh9bnTrCLkfIBc6J0GIrioo4RLUB5pqPkhw?e=265KO0)

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/5d30615c-1484-4591-8da9-163fa0c9f520)

Se ha dado respuesta de parte de salud y no se tiene procesos ni estudiantes por el momento

**Comment by jcmurilloa** [comment]
Se dará por terminada la issue, y se programará una nueva al momento de generar el contacto efectivo con las facultades pendientes.
