### ISSUE TITLE
Presentar los reportes realizados al usuario.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#711]
Se requiere realizar la presentación al usuario para mostrarle los reportes generados y obtener retroalimentación.

**Sub Tareas**

- [x] Realizar presentación al usuario.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1:  Realizar presentación al usuario.**

https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/POLUX%20-%20Primera%20muestra%20reportes-20240905_100513-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=aUFQ1l&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Comment by diagutierrezro** [comment]
Se realiza la reunión para mostrarle al usuario, de allí surgen algunos comentarios de ajustes por hacer pero de manera general se aprueban los reportes, muy buen trabajo Cristian.
