### ISSUE TITLE
Ajustar vista de registro de nota para mostrar anexos cargados en solicitud de revisión

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#712]
Se requiere realizar el desarrollo para que en la vista de ver detalles como de registrar calificaciones en le módulo de registrar nota permita ver los anexos que se adjuntaron cuando se realizó la solicitud de revisión, estos anexos tambien deben poderse descargar.

**Sub Tareas**

- [x] Desarrollar la visualización y descarga de los anexos cargados en la solicitud de revisión.
- [x] Verificar que lo anterior se puede realizar tanto en "ver detalles" como en "registrar calificaciones".
- [x] Probar funcionamiento correcto del desarrollo.

**Criterios de aceptación**

- [x] Desarrollo para ver anexos realizado.
- [x] Verificación de desarrollo para las dos vistas realizada.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1:  Desarrollar la visualización y descarga de los anexos cargados en la solicitud de revisión.**

1. La vista a modificar se encuentra en el archivo "registrar_nota.html" especificamente en el div con el id "modalRegistrarNota", es en el siguiente apartado en donde se agregará la información restante para mostrar los anexos y se puedan descargar:

<img width="632" alt="image" src="https://github.com/user-attachments/assets/c3080d7b-a742-43ca-af15-6ad92fe58370">

**Comment by diagutierrezro** [comment]
Se iniciará corrección del guardado de anexos en otro issue.
