### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de presentación de reportes

### ISSUE THREAD

**Issue by mantnicot** [udistrital/polux_cliente#715]
Se requiere realizar el  la concertación, desarrollo y levantamiento del acta de presentación de reportes para el Cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x]  Acta revisada por el líder de proyecto.
- [ ]  Acta firmada por las partes con anexo de historias de usuario o mockup.
- [ ]   Acta y anexos documentados.
Requerimientos

No aplica

Definition of Ready - DoR

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.
Definition of Done - DoD - Análisis/Diseño

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ]Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado la sesión , se adjunta el acta correspondiente del 05/09/2024 a las 10:00 am , junto al equipo de desarrollo

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbPrsH-2shRNtNv_LuV3e1QBDjsazJNxjgGpkKR8wCitEg?e=rTpxoh)

**Comment by jcmurilloa** [comment]
Acta revisada, por favor recoger firmas.

**Comment by mantnicot** [comment]
Se ha recolectado la firmas


[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EYC1EPRiYUxKirBLhMuNQP4BxKOZIKuBGoEopconZoK8YA?e=ZuTIcf)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
