### ISSUE TITLE
Ajustar transacción al momento de aprobar solicitudes de revisión - Parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#716]
Se requiere realizar la finalización del ajuste de la transacción que se inició en #714 donde se debe corregir el error que se presenta al momento de ejecutar la transacción y realizar las pruebas del correcto funcionamiento de la transacción, incluido los rollback para evitar afectaciones a la misma.

**Sub Tareas**

- [x] Corregir error presentado en la issue anterior.
- [x] Probar funcionamiento correcto de la transacción incluyendo los rollback.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Corrección de transacción realizada.
- [x] Pruebas de funcionamiento realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1:  Corregir error presentado en la issue anterior.**

<img width="959" alt="image" src="https://github.com/user-attachments/assets/31f0f528-7df2-488f-9c47-133032812452">

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Probar funcionamiento correcto de la transacción incluyendo los rollback.**

- Se registra correctamente los documentos y anexos en la tabla "documento_trabajo_grado":
<img width="337" alt="image" src="https://github.com/user-attachments/assets/d246fc66-101e-4e84-bbc5-7b211fd01ab6">

- Se registra correctamente los enlaces de los documentos y anexos en la tabla "documento_escrito":
<img width="671" alt="image" src="https://github.com/user-attachments/assets/3211f3af-7a43-4a29-a460-a7c4cbeb493e">

**Comment by diagutierrezro** [comment]
Muy buen trabajo Cristian.
