### ISSUE TITLE
Ajustar vista para visualización de anexos en registro de nota

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#717]
Se requiere realizar el ajuste en cliente de pólux para que en el modulo del registro de nota se pueda descargar los anexos que se cargaron en la solicitud de revisión, para esto importante tener en cuenta el ajuste realizado en #716 para consultar las tablas en las que ahora se guarda estos documentos. Tener presente que los documentos anexos se deben mostrar tanto para la vista de unicamente visualización como la de registro de nota.

**Sub Tareas**

- [x] Agregar descargar de documentos anexos en modulo de registro de nota.
- [x] Verificar que los anexos aparecen en las dos vistas del modulo.
- [x] Probar funcionamiento correcto del desarrollo realizado.

**Criterios de aceptación**

- [x] Desarrollo para descarga de anexos realizado.
- [x] Verificación de descarga de documentos en las dos vistas realizada.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Agregar descargar de documentos anexos en modulo de registro de nota.**

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Verificar que los anexos aparecen en las dos vistas del modulo.**

**Comment by CrisEs2506** [comment]
**SubTarea N°3: Probar funcionamiento correcto del desarrollo realizado.**
