### ISSUE TITLE
Creación de vista para modulo de reportes - Parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#718]
Se requiere realizar la implementación del modulo de reportes teniendo en cuenta los mockups creados en #724  la cual debe permitir generar y descargar los reportes que se requieran.

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTareas**

1. Se debe crear los menús desde la base de datos que corresponde al llamado de la siguiente petición:

<img width="527" alt="image" src="https://github.com/user-attachments/assets/95b93bf1-fde7-45a5-9972-93f142a15c0d">

<img width="526" alt="image" src="https://github.com/user-attachments/assets/25de63f7-f7b6-4bdc-b237-9a383b402fa4">

2. Agregar los nuevos archivos HTML (template) y Javascript (controller) al archivo "app.js":

<img width="614" alt="image" src="https://github.com/user-attachments/assets/c72085b9-da77-44c0-8b17-443ef2200317">

**Comment by CrisEs2506** [comment]
**Nota:** Al parecer algunos servicios que son utilizados para generar los reportes se encuentran caídos por lo que no se pudo comprobar el funcionamiento adecuado del nuevo módulo creado (se adjunta evidencia):

<img width="752" alt="image" src="https://github.com/user-attachments/assets/c04ca138-3ab2-4863-a969-4e2a69b6981c">

**Comment by diagutierrezro** [comment]
Se continuará revisión de la vista del modulo de reportes en otra issue, buen trabajo Cristian.
