### ISSUE TITLE
Ajustar cliente para definir manejo de errores y respuestas del mid - parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#721]
Se requiere realizar el ajuste en el cliente para adaptarlo a la nueva respuesta del mid tanto en las peticiones exitosas como en los errores, primero se debe adaptar el cliente para que funcione correctamente con la nueva estructura de respuesta que da el MID, una vez se realice esto empezar a revisar el manejo de errores tanto para errores en el mid como en el crud.

**Sub Tareas**

- [x] Ajustar cliente a nueva estructura recibida en peticiones correctas hacia el MID.
- [x] Ajustar cliente a nueva estructura recibida en peticiones con errores tanto en CRUD como en MID.
- [x] Documentar pruebas realizadas tanto para casos correctos como errores.

**Criterios de aceptación**

- [x] Ajuste de peticiones correctas realizado.
- [x] Ajuste de peticiones con errores realizado.
- [x] Documentación de issue con pruebas ejecutadas realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se comienzan a realizar cambios en la captura de respuestas satisfactorias al MID dado que estas conultas ya están listas allí, se inicia en el controlador crear_solicitud.js
![Image](https://github.com/user-attachments/assets/c7467ad5-477d-45eb-8691-d4008ecdeace)
parece que en algunos puntos la lógica está diseñada con respecto a la forma de reponder anterior en un Post, devolvía un JSON  con la palabra "Success"
![Image](https://github.com/user-attachments/assets/75049b64-5e40-48b6-ae45-eecac1178e65)
Se procede a realizar cambio en la lógica para que funcione comprobando el booleano que llega en el atributo Success

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes para captura correcta de respuestas de las peticiones que apuntan a Polux_MID

![Image](https://github.com/user-attachments/assets/425bbc8c-0d38-4abb-b941-bea34a9bec55)
Se están realizando pruebas de funcionamiento, se realizará en el transurso del día ya que la Issue #728 se extendió y se terminó el viernes.

**Comment by Astaroth-Andres-Molano** [comment]
Debido a un error se perdió el avance de los ajustes de manejo de formato en el CRUD y MID, se tuvo que volver a realizar los procedimientos, se realizaron pruebas a las respuestas del CRUD, funciona exitosamente, se realiza prueba de funcionamiento de respuesta exitosa al MID pero responde error, se procede a buscar la falla.![Image](https://github.com/user-attachments/assets/b6272ffa-329b-491a-9ff0-81dc870e1b60)
