### ISSUE TITLE
Ajustar textos de terminos y condiciones.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#722]
Se requiere realizar el ajuste de los textos cuando se hacen las solicitudes, especialmente los textos de los terminos y condiciones que deben aceptar los estudiantes.

**Sub Tareas**

- [x] Ajustar textos de las solicitueds.
- [x] Pruebas de ajustes realizados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza cambio en los textos de términos y condiciones teniendo en cuenta algunas particularidades en las diferentes modalidades
![Image](https://github.com/user-attachments/assets/f54e0acd-16d7-4024-bbce-8101acb1fa4a)
![Image](https://github.com/user-attachments/assets/1c14ba0a-d92e-41a3-9ed8-76fc392b4e99)
