### ISSUE TITLE
Crear aviso de ARL en la creación de la solicitud inicial para modalidad de pasantía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#723]
Se requiere realizar la creación de una alerta en la que se le indique a los estudiante que es importante que tramiten la ARL aún si la solicitud no ha sido aprobada. (Pendiente por definir si se le mostrará a todos los estudiantes o solo externa mirando campos de NIT y CIIU)

**Sub Tareas**

- [x] Creación de alerta con texto definido.
- [x] Prueba de alerta creada.

**Criterios de aceptación**

- [x] Alerta creada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se espera poder ver avances y comentarios para poder dar seguimiento de trabajos , gracias

**Comment by jcmurilloa** [comment]
No se presentarios avances en todo el sprint para esta issue, según la no realización de comentarios.

**Comment by Astaroth-Andres-Molano** [comment]
Debido al aumento de actividades solicitadas en las obligaciones contratadas con PlanesTic esta actividad tuvo que ser postergada unos días.
Se hace analisis para encontrar en que controlador y método debe intervenir el Aviso de ARL, se realizan ajustes
![Image](https://github.com/user-attachments/assets/c65d49e7-8611-405d-b03d-0e127fbcce75)
Se realiza una prueba haciendo una petición inicial de pasantía
![Image](https://github.com/user-attachments/assets/d7b9312b-220c-4827-b378-49772c515a41)
De manera exitosa sale el aviso solicitandole al estudiante diligenciar su ARL
![Image](https://github.com/user-attachments/assets/88c14f24-25b8-4448-aa76-3cc57764f74f)
Cuando el estudiante lee el aviso y da click en ok, sale el aviso que informa que la solicitud se realizó de manera satisfactoria 
![Image](https://github.com/user-attachments/assets/b52af8bc-2fc9-408c-a672-c0cda4590123)
Se va al perfil de oficina de extensión de pasantías para rechazar la solicitud y poder realizar otras pruebas
![Image](https://github.com/user-attachments/assets/22a0ebd4-8793-462b-9899-9d7e8cbdf362)
Solicitud rechazada con éxito
![Image](https://github.com/user-attachments/assets/6254dd0b-8f24-47a9-b393-5e49ce0b9fec)
Ahora se realiza prueba haciendo solicitud a una modalidad diferente para ver que no salga el aviso de ARL
![Image](https://github.com/user-attachments/assets/16e9b672-edce-43b3-92b1-f3e326d892f2)
La solicitud se genera exitosamente y solo sale el aviso de éxito
![Image](https://github.com/user-attachments/assets/ff0b2bfb-c821-42a3-ae6d-5659fa9ff64e)
