### ISSUE TITLE
Diseñar mockup de vista del módulo reportes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#724]
Se requiere diseñar el mockup para el módulo de reportes. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado el primer diseño de modulo de reportes 
[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmB_5v1TSitCsOV_4nkc-J8BeEGmvP7ZFuupOV7-JQf46A?e=RBqEkJ)

![Image](https://github.com/user-attachments/assets/988e23c9-0dac-4f41-93de-6a500e5d2a88)
![Image](https://github.com/user-attachments/assets/62ca8b2d-a766-4c98-a3ed-62e2810fdf33)

**Comment by jcmurilloa** [comment]
Revisaremos al detalle en el review, se ve muy bien el diseño!

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, aprobado mockup para iniciar desarrollo.
