### ISSUE TITLE
Concertar y desarrollar sesión de capacitación piloto para coordinadores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#725]
Se requiere realizar la concertación y desarrollo de sesión de capacitación piloto pasantía con usuarios coordinadores

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [ ] Desarrollar la reunión con el cliente.
- [ ] Proyectar acta de sesión

**Criterios de aceptación**

- [ ] Sesión grabada en Teams.
- [ ] Acta revisada por líder del proyecto
- [ ] Acta firmada pr responsables.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Por temas de asignación de permisos a las credenciales de los coordinadores , se esta aplazando la reunión pues se de solucionar eso primero


Se genero asigno una reunión con el jefe , funcionamiento y el cliente para el 13/09/2024 a las 10 am

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NWU4N2QwMmItNzk0My00MzVkLTk2NDYtNDk5NjY2Mjc1ZmVl%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Después de lo charlado con el equipo , se determina que mientras se resuelve el inconveniente con los usuarios no se pueda hacer la capacitación.

**Comment by jcmurilloa** [comment]
Estaremos atentos a la colaboración por parte de los coordinadores para dar por cumplido el ciclo del flujo en la modalidad pasantías,en caso contrario se anotarán los resultados en el informe final del piloto.

**Comment by jcmurilloa** [comment]
Se traslada la issue, con el ánimo de concretar para el respectivo sprint, la capacitación hac´ía coordinadores y asistentes.

**Comment by mantnicot** [comment]
Se ha podido charlar con Kevin y se cuadro generar la reunión apenas se termine el proceso de los usuarios y se pueda gestionar la otra semana , con base al comunicado de parte del decano se dará prioridad a solucionar ese fallo.

[Incidencias en el funcionamiento de Pólux tras su implementación.pdf](https://github.com/user-attachments/files/17063917/Incidencias.en.el.funcionamiento.de.Polux.tras.su.implementacion.pdf)

**Comment by jcmurilloa** [comment]
Se cierra la issue, debido a que no hubo interés por parte de los coordinadores, en el entendido de que los asistentes usarán el sistema.
