### ISSUE TITLE
Definir templates para notificaciones de asignación de director y evaluador

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#726]
Se requiere realizar la definición de los templates que se van a usar para el envío de notificaciones de asignación de director y evaluador, tener presente las diferentes modalidades y notificaciones que se deben realizar e ir creando los templates.

**Sub Tareas**

- [x] Definir templates a realizar.
- [x] Crear los templates que se van a usar en las notificaciones.
- [x] Documentar los templates creados indicando en que parte del flujo se usarían.

**Criterios de aceptación**

- [x] Templates definidos.
- [x] Templates creados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha creado uno template para la notificación de correo de asignación para los roles

(Documento de plantilla)[https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfMKBCe35edAtN4-aGqeCyoBRPAuG07xOjo9yFoEaEiq4w?e=TLlMJC]

**Comment by jcmurilloa** [comment]
Excelente template!
