### ISSUE TITLE
Ajustar rollbacks en el mid

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#728]
Se requiere realizar el ajuste de los rollback en el mid de Pólux ya que debido a los cambios realizado en el CRUD se requiere modificar la lógica para el correcto funcionamiento de los rollback en las transacciones que se realizan.

**Sub Tareas**

- [x] Realizar ajustes a los rollback de transacciones.
- [x] Probar con errores controlados que los rollback si se estén ejecutando.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se crea método SendrequestNew2, el cual hace un llamado a el método extractData2 que permite retornar el status code para asegurar que en caso de error la consulta entre a los Rollbacks, y también en caso de error extractData2 no ejecuta ningún panic que interrumpe el flujo para pasar a los Rollbacks
![Image](https://github.com/user-attachments/assets/1af09f6a-a190-49db-b531-4e078bcc0c90)
![Image](https://github.com/user-attachments/assets/52a7f5da-556d-4616-8efe-00f8a5cceafe)
![Image](https://github.com/user-attachments/assets/91b4bbad-33fe-419d-92f8-ea190f3a244e)
Se realizan pruebas de errores para verificar que entra a los rollbacks y que responda correctamente

![Image](https://github.com/user-attachments/assets/91a88553-88ba-4634-b473-fcd7dc7275e1)
![Image](https://github.com/user-attachments/assets/d8e5f501-1698-4d61-8cd9-96712dda7ff6)

Se realiza prueba haciendo consulta correcta, respuesta satisfactoria correctamente
![Image](https://github.com/user-attachments/assets/c078db6b-57f6-4ee3-870c-0776dbd4ac5a)
