### ISSUE TITLE
Ajustar flujo general para usar rol de coordinador

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#732]
Se requiere realizar el ajuste al flujo general para que no se use el rol COORDINADOR_PREGRADO sino en su lugar unicamente COORDINADOR, por ahora solo se requiere hacer la modificación de estos dos roles y posteriormente se debe analizar la modificación de la lógica para distinguir entre un rol de coordinador de pregrado y posgrado.

Para esto es importante solicitar la adición del rol en WSO2 a algun usuario de coordinador, agregar el rol desde el cliente de configuración o editar el de COORDINADOR_PREGRADO.

Revisar el código donde se use el rol COORDINADOR_PREGRADO, hacer la modificación y pruebas de funcionamiento correcto.

**Sub Tareas**

- [x] Solicitar adición de rol en WSO2 (no borrar el anterior), para esto se debe definir primero cual  preguntar a Juan Camilo Martinez o a @mantnicot para solicitar ayudar con esa gestión.
- [x] Ajustar menú para funcionamiento con el nuevo rol.
- [x] Ajustar código donde sea necesario para uso con el nuevo rol y que el sistema siga funcionando correctamente.

**Criterios de aceptación**

- [x] Cambio de rol para prueba en WSO2 realizado.
- [x] Ajuste de menú realizado.
- [x] Ajustes de código realizados.
- [x] Pruebas de funcionamiento correcto realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**Nota:** Se cambio el nombre de 'COORDINADOR_PREGRADO' a solo 'COORDINADOR' en los siguientes archivos:
- notificaciones.js
- consultar_trabajo_grado.js
- reporte_general.js
- aprobar_solicitud.js
- listar_solicitudes.js
- notificacion.js
- consultar_trabajo_grado.html
- aprobar_solicitud.html
- listar_solicitudes.html

**Comment by CrisEs2506** [comment]
**SubTarea N°3: Ajustar menú para funcionamiento con el nuevo rol.**

1. Se requiere que la petición 'userRol' asigne a los coordinadores el nuevo rol creado previamente 'COORDINADOR', ya que actualmente sigue con el rol 'COORDINADOR_PREGRADO'. Con este cambio realizado ya se puede continuar con las pruebas

<img width="526" alt="image" src="https://github.com/user-attachments/assets/0a7eb6cc-b9ab-4a94-b165-c239fbe6ecac">

<img width="527" alt="image" src="https://github.com/user-attachments/assets/5922ab51-a98a-4850-b334-5b6c96c89727">

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Ajustar menú para funcionamiento con el nuevo rol.**

1. Aprobar Solicitud Trabajo Grado:
<img width="640" alt="image" src="https://github.com/user-attachments/assets/ee42f40f-50d8-4b5d-9c37-76cb6c8ebc08">

<img width="638" alt="image" src="https://github.com/user-attachments/assets/f802ca17-a53a-4027-8dc6-4a9be4f01dd4">

<img width="286" alt="image" src="https://github.com/user-attachments/assets/ac184a1c-0bd7-4a47-a5a8-400fccc0d583">

2. Consultar Trabajo Grado:
<img width="574" alt="image" src="https://github.com/user-attachments/assets/5e0522c6-566a-46a4-a1ae-001aaef6b834">

3. Solicitud de Prorroga:

<img width="254" alt="image" src="https://github.com/user-attachments/assets/34c21752-26bc-46ea-bc18-93373ec410d1">

4. Solicitud de Cambio de Título de Grado:
![image](https://github.com/user-attachments/assets/4b655813-2e3d-4eff-b4d0-38a2991c0d85)

<img width="251" alt="image" src="https://github.com/user-attachments/assets/4a7fc901-0b46-4852-929d-079090765611">

5. Solicitud de Cambio de Objetivos:
![image](https://github.com/user-attachments/assets/4a2ee8ca-46c3-4f09-baf7-7af62e744447)
<img width="253" alt="image" src="https://github.com/user-attachments/assets/8c8a6b5a-9820-4b77-bd40-acac8758bac5">

6. Solicitud de Revisión de Trabajo de Grado:

![image](https://github.com/user-attachments/assets/c2ac65e0-17ba-46ea-98d4-cdda16d21bbb)

<img width="250" alt="image" src="https://github.com/user-attachments/assets/46ec0eae-788f-47f0-8061-e1e37856c0b1">

7. Solicitud de Cancelación de Trabajo de Grado:

![image](https://github.com/user-attachments/assets/77805ea7-80c2-4e81-b0ab-74135d8eae81)
<img width="251" alt="image" src="https://github.com/user-attachments/assets/5bcd71b5-472f-4202-b2bb-46d7a819ac42">

Nota: La solicitud de cambio de director interno y de evaluador no es posible realizarse ya que en el momento para pruebas solo existen dos profesores disponibles, y se necesitaría al menos 3.
