### ISSUE TITLE
Realizar script para consulta de documento asociado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#733]
Se requiere realizar un script donde se suministre el código del proyecto curricular y con este se obtenga el documento del coordinador actual para posteriormente solicitar la creación de un endpoint por JBPM para obtener el correo donde se realizarán las notificaciones. Se recomienda revisar el script que se realiza en la petición de COORDINADOR/PREGRADO desde JBPM para poderlo usar como guía en la creación del otro, para obtener este script se le debe solicitar a Jhon Castellanos

**Dependencias**
- Se debe solicitar a los DBA acceso a la base de datos de Oracle donde se encuentra la información.

**Sub Tareas**

- [x] Realizar script para obtener coordinador de proyecto curricular.
- [x] Prueba de resultado obtenido con el script.

**Criterios de aceptación**

- [x] Script realizado.
- [x] Prueba realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se solicitó el script que se usa en el endpoint de JMBP coordinador_carrera/DOCUMENTO/NIVEL a Jhon Castellanos, el cual es el siguiente:
```bash
SELECT 
DISTINCT
CASE WHEN emp_nombre IS NULL THEN 'No registra.' ELSE emp_nombre END nombre_coordinador,
as_cra_cod codigo_proyecto_curricular,
as_cra_nom nombre_proyecto_curricular
FROM accra
INNER JOIN peemp ON cra_emp_nro_iden=emp_nro_iden
INNER JOIN accra_snies ON cra_cod=as_cra_cod
INNER JOIN actipcra ON CRA_TIP_CRA=TRA_COD
WHERE cra_emp_nro_iden=?
AND TRA_NIVEL=?
```

En donde se observa que el código de la carrera se obtiene de la columna as_cra_cod y el documento del coordinador se encuentra en la columna cra_emp_nro_iden. Con estos datos se puede empezar a realizar el script para recuperar el documento del coordinador a partir del código de la carrerra del estudiante.

Ahora, se realizó la solicitud por tuleap para obtener acceso a la base de datos: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=64832&group_id=177

Una vez respuesta la solicitud, se prueba el usuario y el script obtenido, el cual responde correctamente:
![Image](https://github.com/user-attachments/assets/32ba8d60-91e3-4fca-8151-4b4c25368072)

**Comment by JuanDHernandezA** [comment]
Se continua con el análisis al Script obtenido, con el fin de saber qué información contiene cada una de las tablas:

- MNTAC.ACCRA: Información completa de las carreras
- MNTPE.peemp: Información de empleados
- MNTAC.accra_snies: Información de las carreras resumido
- MNTAC.actipcra: Información de los tipos de carrera

Con esta información, se propone el siguiente script para recuperar la información del coordinador enviando el código de la carrera:

```bash
SELECT cra_emp_nro_iden documento_coordinador, emp_nombre nombre_coodinador, emp_email_ins correo_coordinador 
FROM MNTAC.ACCRA
INNER JOIN MNTPE.peemp ON cra_emp_nro_iden=emp_nro_iden
WHERE CRA_COD = ?
```

En este script se recupera el documento, el nombre y el correo institucional del coordinador.

Se prueba el script con los códigos de todos los proyectos curriculares registrados en la base de datos:

![Image](https://github.com/user-attachments/assets/bcd1ebd4-a807-4151-9099-44884a4fea6f)

Se puede observar que en algunos coordinadores no registra un correo institucional, por lo que otra propuesta sería recuperar únicamente el documento, y con este, buscar el correo desde el API de Autenticación_mid

**Comment by JuanDHernandezA** [comment]
Se presenta la propuesta a @diagutierrezro, junto a él se determina que el script no retorne el correo del coordinador, únicamente su documento y el nombre, y posterior se recupera el correo por medio del API de autenticacion_mid. Por lo tanto, el script a usar es:

```bash
SELECT cra_emp_nro_iden documento_coordinador, emp_nombre nombre_coodinador 
FROM MNTAC.ACCRA
INNER JOIN MNTPE.peemp ON cra_emp_nro_iden=emp_nro_iden
WHERE CRA_COD = ?
```

Se prueba el script con el código de carrera de ingeniería de sistemas:
![Image](https://github.com/user-attachments/assets/ceaa3d97-8d76-47b8-b5ae-0b393bbdb14b)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego, queda pendiente por mi parte solicitar la creación de los endpoints para continuar con el desarrollo.
