### ISSUE TITLE
Actualizar documento de hallazgos piloto Pasantía

### ISSUE THREAD

**Issue by mantnicot** [udistrital/polux_cliente#735]
Se requiere realizar la actualización del [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbAlDu5nx25Liu97QfLC1uUBwgY57LV6G-UroBmgkuyHaA?e=g0Vftg) de hallazgos del piloto realizado para la modalidad de pasantía.

Se deben agregar todas las situaciones que indicaron los usuarios en el grupo que se había definido, esto con el fin de llevar un mejor registro de lo realizado en dicho piloto.

Sub Tareas
- [x] Documento de hallazgos actualizado.

Criterios de aceptación

- [x] Documento actualizado.
- [x] Documentación de issue realizada.

Requerimientos

No aplica

Definition of Ready - DoR

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

Definition of Done - DoD - Desarrollo

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se actualiza el documento de hallazgos con los comentarios y situaciones presentadas durante el piloto a través de reuniones y el grupo del WhatsApp

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego
