### ISSUE TITLE
Ajustar cliente para definir manejo de errores y respuestas del mid - parte 2

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#736]
Se requiere realizar la finalización del ajuste de manejo de errores en el cliente teniendo en cuenta lo iniciado en #721, falta finalizar el manejo de errores de las peticiones provenientes desde el mid, se debe probar el funcionamiento correcto del sistema.

**Sub Tareas**

- [x] Realizar cambios para manejo de errores desde el mid.
- [x] Pruebas de funcionamiento correcto del sistema.

**Criterios de aceptación**

- [x] Cambios realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
No se presentarios avances en todo el sprint para esta issue, según la no realización de comentarios.

**Comment by Astaroth-Andres-Molano** [comment]
Debido a pruebas desde Postman en issues anteriores el usuario estudiante queda bloqueado, por lo que se procede a hacer limpieza de la Base de datos, se revisan las peticiones realizadas por el usuario, se observa que la petición a la tabla usuario_solicitud contiene la relación entre el código del estudiante con el id de las solicitudes.

![Image](https://github.com/user-attachments/assets/dca4c9cc-8c59-4241-b9c0-6fef716c5c9e)
![Image](https://github.com/user-attachments/assets/4936a994-5b99-43d7-bb2a-f46b45ffb42b)
Se elimina un solo registro en la base de datos, esto con el fin de verificar que no exista ningún conflicto con alguna otra tabla o alguna funcionalidad en el aplicativo de Polux. 
![Image](https://github.com/user-attachments/assets/61ea6b27-1205-4ff5-8701-cbfa4bd96556)

Se procede a eliminar los trabajos de grado y peticiones que generan los errores mencionados previamente. Se buscan por el id del trabajo de grado y se eliminan todos los registros asociados. Las tablas modificadas fueron:

areas_trabajo_grado
asignatura_trabajo_grado
detalle_pasantia
documento_trabajo_grado
vinculacion_trabajo_grado
revision_trabajo_grado
correccion
comentario
evaluacion_trabajo_grado
![Image](https://github.com/user-attachments/assets/df46a0b6-5dbb-4d01-b63f-9939f972b93b)
![Image](https://github.com/user-attachments/assets/ec9c6dc2-5a13-4730-a2ee-d0b9be8f984e)

Con estas eliminaciones ya los menús de Revisión Documento Docente, Registrar Nota y Pasantía no presentan ningún error, y se procede a hacer pruebas haciendo un ciclo de modalidad de monografía:

![Image](https://github.com/user-attachments/assets/97796be1-400d-4201-9903-9728005a9bbd)
Se observa que el formato de respuesta de un Post realizado apuntando a Pólux MID sea el correcto

![Image](https://github.com/user-attachments/assets/b8365bee-e479-491d-9ea2-e295808a4da9)
Respuesta exitosa
![Image](https://github.com/user-attachments/assets/0ce0b4df-f76d-45af-b3ee-48ac408878ff)
![Image](https://github.com/user-attachments/assets/098199ba-4438-4d8a-82f5-25a542d7501f)
![Image](https://github.com/user-attachments/assets/8fdbad46-2ab5-4ab7-a4d5-f162a8475d7d)
Ahora desde docente director se revisa la petición hecha desde estudiante
![Image](https://github.com/user-attachments/assets/41f5cfdd-fe47-4a05-86c7-52824ac941eb)
Se aprueba la solicitud por parte del docente director
![Image](https://github.com/user-attachments/assets/b18debab-f4ce-4f7b-ad79-ecfe134c4481)
Había una API sin servicio en el momento de la prueba se obtiene error de CORS
![Image](https://github.com/user-attachments/assets/de6b8c6b-14fe-4cd6-b393-df6966377fd9)
![Image](https://github.com/user-attachments/assets/ad8b4dbe-02ee-4758-a87a-a3d6faf4dcd3)
Se debe esperar el restablecimiento correcto del servicio. Al transcurrir unas horas se reanudan las pruebas, se realiza nuevamente la aprobación desde docente director y coordinador a la solicitud inicial
![Image](https://github.com/user-attachments/assets/da039e77-5b70-4f35-88b4-61134b28f6fd)
![Image](https://github.com/user-attachments/assets/a7ca63b2-c9cd-4f98-ad29-9241dbcefb76)
Ahora se inicia con el ciclo de revisión de documentos o avances del proyecto de grado por parte del estudiante
![Image](https://github.com/user-attachments/assets/dcdb7d0a-1795-4e42-8821-183d15f79501)
Error en la actualización del documento
![Image](https://github.com/user-attachments/assets/14fb4c43-85cc-4567-9d3a-d2e4c770839f)
![Image](https://github.com/user-attachments/assets/c55e8e9d-e018-4966-a45b-64a156638614)
Se procede a realizar el analisis al error 
![Image](https://github.com/user-attachments/assets/8e0439d9-15e2-4b47-8ec6-0957cf92d2c7)
Se encuentra que para una consulta a la API de parametros ya el formato de respuesta cambió y en esa lñinea de código aún se recibe la respuesta con el formato antiguo, se procede a realizar el ajuste
![Image](https://github.com/user-attachments/assets/33cb0e03-5c0e-43a2-b7a1-18cf8bf5773c)

Se continúa con el flujo, actualización exitosa
![Image](https://github.com/user-attachments/assets/4e95a209-2a27-4fab-9975-e905386c14c8)
Se hace solicitud de revisión documento
![Image](https://github.com/user-attachments/assets/ce829391-bb77-4895-8326-60d05a6e88c7)
solicitud exitosa
![Image](https://github.com/user-attachments/assets/c52058fa-c9a1-4321-9c2d-3440adfeea1c)
Ahora desde docente director se realiza revisión al documento
![Image](https://github.com/user-attachments/assets/54b89667-4d76-490f-aa04-35cff6401984)
![Image](https://github.com/user-attachments/assets/242a0a57-9aa7-4abd-9111-6f7d62688d57)
Se realiza comentario docente director
![Image](https://github.com/user-attachments/assets/c038bd3d-e0f0-48b9-8c18-2999b7f4bc97)
![Image](https://github.com/user-attachments/assets/b2fa788c-8efb-4eca-8450-144e5b786ee6)
Regisro exitoso
![Image](https://github.com/user-attachments/assets/e7ac0fe8-e2bc-44af-b40f-79bb39e97c40)
Ahora se realiza prueba con solicitud de cambio de titulo
![Image](https://github.com/user-attachments/assets/78ddf1f4-bc1c-43c9-a347-348778163cb9)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/33d01e96-0432-469f-a316-903647703148)
Arpobación docente director
![Image](https://github.com/user-attachments/assets/9de342ac-9cdc-450f-a6e3-c5148044ca7e)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/bd0b8ff2-31aa-4dc0-943c-8d5ff14cfb78)
Aprobación por parte del coordinador
![Image](https://github.com/user-attachments/assets/61aa1eac-3f6a-4931-b4ce-838ed3250f91)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/7a8993d2-dd88-4d29-a151-0bc76f291d59)
Se realiza prueba de solicitud de cambio de objetivos
![Image](https://github.com/user-attachments/assets/28533015-d5b8-4ce0-8f51-d442710d4e40)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/f6c9e52b-d35b-4f9b-b7e9-21d25590953c)
Aprobación docente director
![Image](https://github.com/user-attachments/assets/8c0dd9f9-c6e1-493b-b6d6-680237b6e1c3)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/e05f4767-b398-48ee-ab11-360068330fa1)
Aprobación desde coordinador
![Image](https://github.com/user-attachments/assets/b2974747-04d6-4075-acba-df8de1b55a19)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/e8273716-bc09-446a-b1e4-5bfb12f18af1)
Solicitud de prorroga exitosa desde estudiante
![Image](https://github.com/user-attachments/assets/16021317-f389-4e68-8b8f-d54b0ef354b9)
Aprobación docente director
![Image](https://github.com/user-attachments/assets/a95f6166-c636-4437-b618-2328722af1cf)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/8af0b1ec-ea72-473a-b7f3-1e309adbd670)
Aprobación exitosa por parte deo coordinador
![Image](https://github.com/user-attachments/assets/986cd933-fc2a-4dc1-816a-557449544adb)
Se realiza ahora la prueba de solicitud de cancelación de modalidad
![Image](https://github.com/user-attachments/assets/56f9e92c-e64c-4c2f-be2f-709d7950d8e7)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/5dd03182-ad1a-45b6-84e1-caec489dc4d4)
Aprobación por parte de docente director
![Image](https://github.com/user-attachments/assets/13ec51d9-c923-477c-a87b-584b7125bcaf)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/96b7804b-f368-4bfa-bf0a-8280633f13c9)
Aprobación desde coordinador
![Image](https://github.com/user-attachments/assets/4a8636de-470b-4f70-8836-e18474c4c293)
Ahora se rechaza la solicitud, así probando exitosamente el rechazo de una solicitud y para no romper el flujo de la prueba
![Image](https://github.com/user-attachments/assets/7ad8c8df-de09-43d1-997e-6ce9e59a9fd0)
Ahora se realiza prueba de solicitud de revisión de trabajo de grado
![Image](https://github.com/user-attachments/assets/104835a1-a1ad-4a94-be04-e8fc6b68844f)
Carga de documentos del estudiante
![Image](https://github.com/user-attachments/assets/6a5e2a5b-c71f-4994-8de9-e348fd51dc65)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/a92c010d-9323-43ee-bf1f-f823bde25fed)
Aprobación docente director
![Image](https://github.com/user-attachments/assets/3ffe6939-0cf9-4902-8cbc-c6a005ffe8b6)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/0ba8a427-4ccd-4a91-845e-e71121017653)
Aprobación exitosa por parte del coordinador
![Image](https://github.com/user-attachments/assets/82821315-6ff5-4b20-b800-073955ea840f)

Ahora se va a registrar la nota por parte del docente evaluador
![Image](https://github.com/user-attachments/assets/860287ba-0ca6-4475-b6b5-cd6912012d4e)
Error registrando nota
![Image](https://github.com/user-attachments/assets/db630317-eaf6-48ed-ae97-c8c6f2c33d89)

Se procede a analizar el error en la respuesta del MID
![Image](https://github.com/user-attachments/assets/60745b8f-f7ba-4553-9cbf-f0957ed3b9a4)
Se revisa el formato de respuesta, se ve correcto
![Image](https://github.com/user-attachments/assets/cc645cf3-5ca2-4a90-87b6-e432a13dc164)
Se encuentra error en la conexión a la base de datos en el CRUD
![Image](https://github.com/user-attachments/assets/81c1a9bb-40ab-456a-9340-0ede06a8d7ec)
Despues de unas horas se procede nuevamente a conectar el servicio del CRUD y aún hay error en la conexión, se revisa conexión desde PgAdmin, el error continúa
![Image](https://github.com/user-attachments/assets/94715f8c-1f38-4879-a654-83d89378c330)
Se constata que hay conexión a VPN
![Image](https://github.com/user-attachments/assets/abf75699-879b-4355-a024-daa335b29b5f)

**Comment by Astaroth-Andres-Molano** [comment]
Cuando se restablece la conexión se continúa con el procedimiento, al realizar el registro de nota por parte del docente evaluador, ocurre un error
![Image](https://github.com/user-attachments/assets/85a3f431-bc1a-4ecf-9941-255e6272f2e7)
se realiza analisis de la falla, se encuetra que en la consulta al obtener un objeto vacío la condicional if nota[0].Id !=0 arroja error, por ende se antepone una comprobación de longitud del mismo para saltar el paso y siga el ciclo del for en estos casos

![Image](https://github.com/user-attachments/assets/5faba178-fc01-406e-b0d0-9a28d98485d9)
se realiza nuevamente el registro de nota por parte del docente evaluador de manera exitosa
![Image](https://github.com/user-attachments/assets/822f2f0e-9413-4ed3-9767-8458574ea543)
se realiza registro de nota por parte del docente director
![Image](https://github.com/user-attachments/assets/6c737164-b138-4819-8c4f-204324a4bcbb)
Registro exitoso
![Image](https://github.com/user-attachments/assets/75cc8b29-9713-473b-8d98-a0d31a74744f)
Ahora se visualiza las notas desde estudiante
![Image](https://github.com/user-attachments/assets/1d8c3104-0f95-4ccb-a37e-815d69a6d062)

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza prueba de funcionamiento con la modalidad de pasantía
![Image](https://github.com/user-attachments/assets/3c9b5cb7-b4b4-46cf-ae24-55a74e38be9e)
Se registra exitosamente la solicitud inicial
![Image](https://github.com/user-attachments/assets/d39e728f-64fc-4f00-b06d-2feabdf12518)
Siguiendo el flujo de pasantía se visualiza el formato de aprobación desde rol de oficina de pasantías
![Image](https://github.com/user-attachments/assets/aedc2cc9-5842-4597-8698-5eb1a6af7b1f)
Aprobación exitosa por parte de oficina de extensión de pasantías
![Image](https://github.com/user-attachments/assets/681acdcc-8061-48a5-87f6-97ba0ecfdf98)
Aprobación de pasantías rol coordinador
![Image](https://github.com/user-attachments/assets/29b15051-632e-4efc-a079-e3d26a9ae5ea)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/ae18442e-79cc-4566-a107-6bc117746746)
Ya una vez aprobado el proyecto de pasantía se comienzan a realiza las diferentes solicitudes posibles, se inicia con solicitud de cambio de título
![Image](https://github.com/user-attachments/assets/ba66b705-0ca2-492e-b457-bbaaf40f3053)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/37222cb2-2519-49bf-8de7-2555b1777593)
Aprobación desde rol Director Interno
![Image](https://github.com/user-attachments/assets/fafc273b-c102-4924-ac2d-b6aa35afa618)
Respuesta de aprobación exitosa
![Image](https://github.com/user-attachments/assets/429e6985-4e96-4677-a671-25687350518b)
Formato de aprobación rol de Coordinador
![Image](https://github.com/user-attachments/assets/b83a52ad-2c4a-414a-8258-f25da5138d1b)
Aprobación a soliciutd exitosa
![Image](https://github.com/user-attachments/assets/573cd427-5822-4ec0-b69a-6b037ad6a1ab)
Prueba solicitud Cambio de Objetivos
![Image](https://github.com/user-attachments/assets/f0e74b64-b728-403d-afb4-b42e87a49fce)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/bc6df30c-8c6a-47cc-836a-37f15f554529)
Formato aprobación rol Director Interno
![Image](https://github.com/user-attachments/assets/bb543b8b-e598-4379-948c-c67ee9c70e65)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/3954ece3-f93f-4435-ab2f-7fe29a672005)
Desde rol Coordinador se realiza la aprobación de manera exitosa
![Image](https://github.com/user-attachments/assets/035ebeb3-7523-491f-9c17-a68495a4435a)
![Image](https://github.com/user-attachments/assets/b93adc33-cbfa-4fb2-a5f9-066c7f4a309e)
Prueba solicitud de Prorroga
![Image](https://github.com/user-attachments/assets/f225e2d4-d2be-4e01-a1ef-846d5e2c2484)
Error en la solicitud
![Image](https://github.com/user-attachments/assets/c1a6bf31-5cd0-4ce4-84ba-30b9edc91786)
Al revisar el error se encuentra que hay problemas en la conexión a la base de datos, servicio caído
![Image](https://github.com/user-attachments/assets/75a6989f-4454-4ac4-8c43-2f22c50f8ba5)
Se debe esperar un rato para reanudar la actividad.
Al restablecerse el servicio se continúa con la solicitud de prorroga de manera exitosa
![Image](https://github.com/user-attachments/assets/4c51a57a-01f7-4535-839c-b6f0ecf0cdce)
Aprobación por parte del director interno
![Image](https://github.com/user-attachments/assets/a93864e3-853f-4b1a-8313-64372e1ef749)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/22e2e09b-5284-4863-a12c-2d326e366c6b)
Aprobación rol Coordinador
![Image](https://github.com/user-attachments/assets/901a99ad-7ba9-4858-9e5c-8e7d9cd629b8)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/1b471ed4-c92f-4381-8b28-aa02ad5718f3)
Ahora se procede a realizar pruebas en la sección de revisión de documentos en pasantías
![Image](https://github.com/user-attachments/assets/e1936706-42e1-4d12-80dd-55b005f7f10d)
Se realiza el procedimiento de subir ARL desde estudiante
![Image](https://github.com/user-attachments/assets/51ebb350-b2b7-4643-8ac2-2a5dfd6f44df)
Envío exitoso
![Image](https://github.com/user-attachments/assets/821a9809-1ce0-40db-80cb-00daf16fd4c5)
Revisión de ARL por parte de oficina de extensión de pasantías
![Image](https://github.com/user-attachments/assets/3ec9cd68-d61a-4c47-8e5e-f021fdcaeb5b)
Registro exitoso
![Image](https://github.com/user-attachments/assets/8ea6ad74-d1cf-4a13-918e-8e8218047c9c)
Ahora desde estudiante se genera nueva versión de documento del proyecto 
![Image](https://github.com/user-attachments/assets/1d4f563d-c7be-4ff9-a435-66dda44a4bbf)
Y solicita revisión del documento exitosamente
![Image](https://github.com/user-attachments/assets/fc40fd1b-337b-40e0-b15e-9b3f97bfa97a)
![Image](https://github.com/user-attachments/assets/57698f2e-090e-4fb6-b9c6-fbbc3cf74e6f)
Revisión de documentos por parte del director interno
![Image](https://github.com/user-attachments/assets/ea230e97-6725-4dec-b720-4c9025d0c20c)
Registro de revisión exitoso
![Image](https://github.com/user-attachments/assets/57804ee5-961d-4e45-9fe5-8e81cce1babf)
Visualización de la corrección o comentarios desde el estudiante
![Image](https://github.com/user-attachments/assets/83390682-cfa1-43f3-b0bd-5520a85c5684)
Ahora se realizará una prieba de cancelación que será aprobada por director interno y rechazada por coordinador para no perder el flujo  del proyecto que se lleva en este punto
![Image](https://github.com/user-attachments/assets/9a1a3fd4-1f92-4791-b7e2-ae72ce5cedd9)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/aaff6500-1da4-40f9-93a1-0050ba070a0f)
Aprobación por parte del director interno
![Image](https://github.com/user-attachments/assets/8c1906df-7f97-42dd-9aae-69441c2a33b2)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/e0c90fef-8791-4491-b9ca-4955740d2da0)
Ahora desde Coordinador se realiza el rechazo de la solicitud exitosamente
![Image](https://github.com/user-attachments/assets/708656d6-38fa-4087-b6f9-071341831caa)
Prueba de revisión de trabajo de grado
![Image](https://github.com/user-attachments/assets/be57ec11-152e-4b0c-945f-548542bae3f8)
Carga de documentos por parte del estudiante
![Image](https://github.com/user-attachments/assets/896e8f15-e435-4e84-a776-d23191f7ae55)
Solicitud exitosa
![Image](https://github.com/user-attachments/assets/e0f3c264-d2de-4e2a-9f3a-177e1e03aeca)
Aprobación exitosa director interno
![Image](https://github.com/user-attachments/assets/729c2f84-331a-4203-98a5-d3ea91d0eb7b)
Aprobación oficina de extensión de pasantías
![Image](https://github.com/user-attachments/assets/25b388fe-5066-42c1-892d-42c1e2828acb)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/32e73e08-aafd-4843-98e1-3101ab94eecc)

Aprobación por parte del coordinador
![Image](https://github.com/user-attachments/assets/7063fb9a-4acd-491e-9e0b-9e9e42271601)
Aprobación exitosa
![Image](https://github.com/user-attachments/assets/9c89d24d-0de6-4d85-9ef7-33a2dde79c6e)
Calificación registrada por director interno exitosamente
![Image](https://github.com/user-attachments/assets/0441097c-0dc1-4722-8aa2-6d619c762b10)
Visualización de la calificación desde rol de estudiante
![Image](https://github.com/user-attachments/assets/36feb831-5796-4f08-9d36-b23f52d6448a)

**Comment by Astaroth-Andres-Molano** [comment]
Despues de reralizadas las pruebas de funcionamiento se realizan los PR para hacer Merge a entorno de pruebas.
