### ISSUE TITLE
Revisar script para consulta de asistente de coordinador.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#737]
Se requiere realizar la revisión del script suministrado y analizar el funcionamiento, en dado caso de que requiera cambios realizarlos, una vez se ajuste el script enviarselo a @diagutierrezro para solicitar la creación del endpoint desde JBPM para su posterior uso en el sistema.

**Sub Tareas**

- [x] Realizar revisión de script suministrado.
- [x] Ajustar script en caso de ser necesario.
- [x] Subir evidencia del funcionamiento del script.

**Criterios de aceptación**

- [x] Revisión realizada.
- [x] Ajuste realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se prueba el siguiente script proporcionado por @diagutierrezro:

```bash
SELECT DISTINCT cra_cod PROYECTO,
cra_abrev NOMBRE,
ctp_pen_nro PLAN,
tra_nivel NIVEL,
NVL(tra_cod_nivel,0) CODIGONIVEL,
ctp_ind_cred CREDITOS
FROM ACCRA
INNER JOIN V_CRA_TIP_PEN ON CTP_CRA_COD=CRA_COD
INNER JOIN ACTIPCRA ON CRA_TIP_CRA=TRA_COD
INNER JOIN GEUSUWEB  ON CRA_COD = USUWEB_CODIGO_DEP
WHERE USUWEB_CODIGO=?
AND ((usuweb_fecha_fin >= sysdate AND usuweb_tipo_vinculacion=9) or usuweb_tipo_vinculacion=10) 
AND USUWEB_ESTADO = 'A'
ORDER BY CODIGONIVEL, PROYECTO, PLAN
```

Se prueba el script ingresando el documento de la secretaria del proyecto curricular de Ingeniería de Sistemas, dando como resultado:
![Image](https://github.com/user-attachments/assets/b58e7390-ec65-46b1-bebb-c12939992b94)

Se observa que retorna a los vinculados cuya vinculación a un departamento sea "administrativo planta" o "contratista OPS" y que aún esté activo; esta información se obtiene de la tabla "GEUSUWEB". Las demás tablas del script son para consultar la información del proyecto curricular.

Se busca si existe alguna forma de recuperar el tipo de vinculación o el tipo de usuario que tiene la persona del documento ingresado, se encuentra una columna llamada "USUWEB_TIPO" el cual contiene el ID de los siguientes roles:
![Image](https://github.com/user-attachments/assets/6ac57b44-954d-4e7c-837e-d66f840ae284)

Por lo que se agrega a la consulta y se filtra la búsqueda por el tipo de usuario "Asistente proyecto". Además, se eliminan las consultas que no son necesarias en la consulta, por lo que se obtiene el siguiente script:

```bash
SELECT DISTINCT cra_cod PROYECTO,
cra_abrev NOMBRE,
usutipo_tipo TIPO_USUARIO
FROM MNTAC.ACCRA
INNER JOIN MNTGE.GEUSUWEB  ON CRA_COD = USUWEB_CODIGO_DEP
INNER JOIN MNTGE.GEUSUTIPO ON USUTIPO_COD = USUWEB_TIPO
WHERE USUWEB_CODIGO = ? 
AND ((usuweb_fecha_fin >= sysdate AND usuweb_tipo_vinculacion=9) or usuweb_tipo_vinculacion=10) 
AND USUWEB_ESTADO = 'A'
AND USUTIPO_COD = 110
ORDER BY PROYECTO
```

Se prueba nuevamente con el documento de la secretaria del proyecto curricular de ingeniería de sistemas:
![Image](https://github.com/user-attachments/assets/c4a67cf5-60fb-46f0-ba26-a5f2c421b165)

En donde se observa que se retorna el código y nombre del proyecto curricular, así como el tipo de usuario. Con lo cual ya se tiene un script base para consultar a qué proyecto curricular pertenece un asistente de proyecto

**Comment by diagutierrezro** [comment]
Queda pendiente por mi parte solicitar la creación del endpoint para continuar con el desarrollo.

**Comment by diagutierrezro** [comment]
Se realiza pequeña modificación al script para no tener ids quemados ya que no se puede garantizar que estos ids sean los mismos en producción.

```bash
SELECT DISTINCT cra_cod PROYECTO,
cra_abrev NOMBRE,
usutipo_tipo TIPO_USUARIO
FROM MNTAC.ACCRA
INNER JOIN MNTGE.GEUSUWEB  ON CRA_COD = USUWEB_CODIGO_DEP
INNER JOIN MNTGE.GEUSUTIPO ON USUTIPO_COD = USUWEB_TIPO
INNER JOIN MNTGE.GETIPOVINCULACION ON USUWEB_TIPO_VINCULACION = TVIN_COD
WHERE USUWEB_CODIGO = ?
AND ((usuweb_fecha_fin >= sysdate AND TVIN_NOMBRE ='CONTRATISTA OPS') or TVIN_NOMBRE='ADMINISTRATIVO PLANTA') AND USUWEB_ESTADO = 'A'AND USUTIPO_TIPO = 'ASISTENTE PROYECTO' ORDER BY PROYECTO
```
