### ISSUE TITLE
Realizar desarrollo para acceso de asistentes al sistema

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#738]
Se requiere realizar el desarrollo y ajustes pertinentes para que los usuarios con rol CONTRATISTA pero que sean asistentes de coordinadores tengan acceso al sistema y tengan la posibilidad de realizar las mismas acciones que puede realizar el coordinador actualmente.

**Sub Tareas**

- [x] Por ahora se requiere ajustar menús para que los roles CONTRATISTA tengan acceso al mismo menú que los coordinadores (mientras se define si se asignaran nuevos roles a los asistentes).
- [x] Realizar desarrollo para que el rol CONTRATISTA tenga acceso a las mismas funcionalidades que el coordinador.
- [x] Utilizando el endpoint creado en #737 se debe definir que el asistente solo pueda ver las solicitudes asociadas al proyecto del cual es asistente de coordinación.
- [x] Documentar issue con pruebas realizadas.

**Criterios de aceptación**

- [x] Ajuste de menú realizado.
- [x] Desarrollo realizado.
- [x] Revisión de solicitudes realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se revisan los roles actuales del sistema Polux en Configuración para el ambiente de pruebas:
![image](https://github.com/user-attachments/assets/2663794c-6af4-471a-91dd-fc9273b87e89)

Se crea el nuevo rol de contratistas:
![image](https://github.com/user-attachments/assets/8d5a2be3-8c43-4706-9b3d-4fb6ce0ece62)

Se revisan los menús a los que tiene acceso el Coordinador, para posterior agregarlos al nuevo rol de Contratista, el cual quedaría con los siguientes accesos:
![image](https://github.com/user-attachments/assets/c8421c72-d654-4470-8c48-95c0810fa75a)

**Comment by JuanDHernandezA** [comment]
Se comienza con el desarrollo y ajustes en los menús y vistas donde el rol de CONTRATISTA tiene acceso

Inicialmente se trabaja en la vista "Listar Solicitudes", en donde se desarrolla la lógica para recuperar los proyectos asociados al asistente y mostrarlos en el combo box de la vista:

![Image](https://github.com/user-attachments/assets/e3c324a8-7c88-4270-b914-ced29d9bc04f)

Ahora, se verifica que se puedan listar las solicitudes de sus proyectos curriculares. Por lo que se realiza una solicitud con un estudiante de ingeniería de sistemas y otro de artes, con el fin de verificar que solo muestre los asociados a sus proyectos. Inicialmente no mostraba ninguna solicitud debido a que en el nuevo endpoint, para conseguir las carreras asociadas al asistente, responde de forma distinta al endpoint del coordinador.

Una vez realizados los cambios el asistente únicamente puede ver las solicitudes asociadas a sus proyectos:
![Image](https://github.com/user-attachments/assets/8b8cfe41-975e-4a7e-9637-46f379ea44fb)

Se prueban los botones de "ver detalles" y "responder solicitud":

Para el primer botón no se realizaron ajustes:
![Image](https://github.com/user-attachments/assets/477df960-3299-47a3-96be-6272021711ad)

Para la segunda acción, nuevamente se realizaron ajustes para que funcione con el nuevo endpoint:
![Image](https://github.com/user-attachments/assets/587d28c9-3e26-439f-8dec-0e6a5daed2e0)

Al seleccionar el Acta del Consejo, no aparecen las actas del proyecto curricular asociado, se realizan los ajustes:
![Image](https://github.com/user-attachments/assets/66e12823-a8fa-4000-a9de-483d9da66d20)

Se aprueba la solicitud y funciona de forma correcta:
![Image](https://github.com/user-attachments/assets/a454a1e2-a5da-45c0-a9ea-cf96047eb6cc)

De igual forma, se prueba en rechazar la solicitud, también funciona de forma correcta:
![Image](https://github.com/user-attachments/assets/30c4df78-f9b3-4184-9e63-6babb22975bf)

Se ajusta la vista para cuando no se tienen solicitudes, se muestre el mensaje:
![Image](https://github.com/user-attachments/assets/3bea1255-63cd-4150-9667-63f03ab8eded)

Se prueba la funcionalidad de cargar nuevas actas, se ajusta el combobox para seleccionar el proyecto del cual pertenece el acta:
![Image](https://github.com/user-attachments/assets/2a57ac63-9992-40d3-818d-6e9e67b271bc)

Se ajusta la lógica para enviar de forma correcta el código del proyecto y se envía el acta de forma correcta:
![Image](https://github.com/user-attachments/assets/2b89a7bb-a6bc-4102-b4db-018fbd519105)

**Comment by JuanDHernandezA** [comment]
Se continua el desarrollo con la vista "Trabajo de Grado: Consultar". Se revisa el código y se observa que se debe agregar el nuevo rol para mostrar el menú de consulta, se agrega el rol CONTRATISTA y se obtienen los siguientes resultados:
![Image](https://github.com/user-attachments/assets/8f329614-80b5-4f68-b812-147c1c2c3eab)

Se prueba con el código del estudiante de sistemas:
![Image](https://github.com/user-attachments/assets/28d7331b-2ed8-4935-97bd-3d12263f4c9c)

Con respecto a la vista "Reportes", se corrige porque desde Configuración Pruebas se seleccionó la vista incorrecta:
![Image](https://github.com/user-attachments/assets/9ff06af6-416f-4e92-91f1-771a90b4d2fb)

Con estos cambios, el asistente de proyecto tiene los mimos permisos y acciones que el usuario del coordinador.

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego
