### ISSUE TITLE
Implementar endpoint creado para correo de coordinadores.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#739]
Se requiere realizar la implementación del endpoint que surge del query creado en #733 para obtener el documento del coordinador, posterior a esto se usa el endpoint de autenticación para obtener el correo y enviar la notificación.

**Sub Tareas**

- [x] Implementar endpoint para obtener documento.
- [x] Obtener correo del coordinador.
- [x] Enviar notificación al correo del coordinador obtenido.
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Endpoint de obtención de documento implementado.
- [x] Correo de coordinador obtenido.
- [x] Notificación enviada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se implementa el nuevo endpoint desarrado, el cual se obtiene del siguiente link, en donde se debe indicar el código del poyecto curricular: https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v1/consulta_carrera_condor/

Se realiza el desarrollo para notificar al coordinador cuando el Docente Director aprueba la Solicitud Inicial, el listado de destinatarios es el siguiente, donde se puede observar el correo del estudiante y el del coordinador:
![Image](https://github.com/user-attachments/assets/d3703521-cce3-4cc2-a58e-935f5327faf1)

![Image](https://github.com/user-attachments/assets/1df1a394-dfaf-4d67-b77d-332981ef14aa)

**Comment by JuanDHernandezA** [comment]
Continuando con el desarrollo de recuperar el correo del coordinador, se prueban todos los tipos de solicitudes y al momento de aprobarlas por el Docente Director, se verifica que se envíe la notificación al Coordinador. Las solicitudes probadas fueron:
- Solicitud de prórroga
- Solicitud de cambio de director interno
- Solicitud de cambio de título de trabajo de grado
- Solicitud de cambio de evaluador(es)
- Solicitud de cambio de objetivos
- Solicitud de cancelación de Modalidad
- Solicitud de cambio de codirector
- Solicitud de revisión de trabajo de grado

![Image](https://github.com/user-attachments/assets/72832ce8-158b-485e-b7a0-0c728c991de1)

Adicional a esto, se probaron el flujo con la modalidad de Pasantía:
- Solicitud de cambio de director externo
- Solicitud de revisión de trabajo de grado

Para la Solicitud de revisión de trabajo de grado, se verificó que al momento que el Docente Director cargara la nota, se notificara a la Coordinación. Se probó en ambas modalidades y funciona correctamente

**Comment by diagutierrezro** [comment]
Se debe analizar si es necesario crear las notificaciones hacia los asistentes según el desarrollo realizado.
