### ISSUE TITLE
Implementar vista de acta de respuesta por parte del coordinador.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#740]
Se requiere realizar la implementación en el que se pueda ver de alguna manera (consecutivo y/o documento) el acta de respuesta de las solicitudes que son respondidas por el coordinador, esto se realizará en la sección de consultar trabajo de grado. Tambien se requiere agregar este menú al rol de EXTENSION_PASANTIAS.

**Sub Tareas**

- [x] Agregar menú de consulta de trabajos de grado para rol EXTENSION_PASANTIAS.
- [x] Realizar desarrollo que permita mostrar información del acta de respuesta en las solicitudes.

**Criterios de aceptación**

- [x] Menú agregado.
- [x] Desarrollo realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Agregar menú de consulta de trabajos de grado para rol EXTENSION_PASANTIAS.**

Se agrego el nuevo menú de Consultar al rol EXTENSION_PASANTIAS:
<img width="698" alt="image" src="https://github.com/user-attachments/assets/32705d21-efae-4508-ba2d-0c90178ebc78">

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Realizar desarrollo que permita mostrar información del acta de respuesta en las solicitudes.**

Toda la lógica de consultar_trabajo_grado se encontraba bien, por lo que la única modificación que se realizó fue en el HTML del mismo, en la siguiente parte:

```HTML
           <form ng-if="consultarTrabajoGrado.userRole.includes('COORDINADOR_PREGRADO') || consultarTrabajoGrado.userRole.includes('EXTENSION_PASANTIAS')" name="formCodigoEstudiante" ng-submit="consultarTrabajoGrado.consultarTrabajoGrado()">
                <div class="col-sm-3">
                    <label class="control-label"> {{'INPUT.CODIGO_ESTUDIANTE' | translate}} </label>
                </div>
                <div class="col-sm-6">
                    <input type="text" class="form-control col-sm-12" ng-model="consultarTrabajoGrado.codigoEstudiante" required>
                </div>
                <div class="col-sm-3">
                        <input type="submit" ng-disabled="consultarTrabajoGrado.codigoEstudiante.length != 11" value="{{'INPUT.CONSULTAR' | translate}}"  class="col-sm-12 btn btn-success" type="submit">
                </div>
            </form>
```

**Comment by diagutierrezro** [comment]
Muy buen trabajo Cristian.
