### ISSUE TITLE
Construir documentación para usuarios de Pólux

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#743]
Se requiere realizar la construcción de la documentación informativa soporte para usuarios ed pólux. 

**Sub Tareas**

- [x] Proyectar documento a modo de soporte sobre los formatos que no se utilizarán en el flujo del sistema
- [x] Proyectar documento con generalidades del sistema para la promoción en las diferentes facultades
- [x] Enviar documentos revisados por SoS a interesados

**Criterios de aceptación**

- [x] Documento soporte con formatos sin uso en el sistema
- [x] Documento para promoción Pólux facultades
- [x] Correos enviados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha generado el documento para las facultades y así mismo , se espera de parte del cliente una información de flujos procedimentales para la documentación

[documetno facultades](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcQfFYq5ExtOgHCtg10_d-cBgcQp8SgDH4yIr7X2J9ThGg?e=PgdK5g)

**Comment by jcmurilloa** [comment]
Revisaremos al detalle el documento en el review @mantnicot.

**Comment by jcmurilloa** [comment]
Pendiente registrar los dicumentos procedimentales según la información por parte del cliente.

**Comment by mantnicot** [comment]
De parte del cliente se ha definido que los documento de cambios serían de parte autónoma de la facultades u oficinas.

Por lo cual los cambios serían en el procedimiento en la facultad de ingeniera con respecto a pasantía , son : 

- certificado de notas
- historico de pagos
- Carta de aprobación de proyecto de grado

Por esto  no se agrega a la documentación general pues solo aplica para la oficina de extensión de la faucltad de ingenieria, se envia la documentación base para las facultades reiterando la petición de usuarios y que se lea la información 

![Image](https://github.com/user-attachments/assets/4b65c8de-8dcc-4afe-ba72-816c4863b5d7)

**Comment by jcmurilloa** [comment]
Teniendo en cuenta los comentarios del cliente, y el trabajo realizado por parte del analista, se procede a cerra la issue.
