### ISSUE TITLE
Analizar como se puede agregar información adicional para ARL

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#744]
Se requiere realizar el análisis sobre como se podría implementar que el estudiante que realiza una solicitud inicial de pasantía pueda enviar información adicional que únicamente es visible por parte de la oficina de pasantía como el nombre del estudiante, correo personal, teléfono, etc.

**Sub Tareas**

- [x] Realizar documento donde se defina que cambios (a nivel tecnico) se deberían realizar según las propuestas realizadas (tener en cuenta los cambios a hacer en cliente y Apis).
- [x] Documentar issue.

**Criterios de aceptación**

- [x] Documento realizado.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza analisis para implementar la captura de datos personales del estudiante para tramitar la ARL en los casos de que vaya a realizar pasantía al interior de la universidad, se crea documento con el analisis.[Carga de Datos Personales ARL.docx](https://github.com/user-attachments/files/17189528/Carga.de.Datos.Personales.ARL.docx)
