### ISSUE TITLE
Realizar pruebas de funcionamiento del sistema.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#745]
Se requiere realizar pruebas funcionales del sistema debido a que se han realizado multiples cambios y se requiere comprobar la estabilidad del mismo, para esto se requiere llenar el formato que se ha venido manejando para este tipo de pruebas.

**Dependencias**
Para realizar estas pruebas se requiere que el ambiente de pruebas tenga los ultimos cambios incluido los de los issues #723 y #736 

**Sub Tareas**

- [x] Realizar pruebas funcionales del sistema en su totalidad que incluye multiples modalidades de grado, diferentes tipos de solicitudes en su flujo general, generación de reportes, etc.
- [x] Realizar documento con las pruebas funcionales.
- [x] Documentar errores encontrados para ser solucionados.

**Criterios de aceptación**

- [x] Pruebas funcionales realizadas.
- [x] Documento realizado.
- [x] Documentación de errores encontrados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Realizar pruebas funcionales del sistema en su totalidad que incluye multiples modalidades de grado, diferentes tipos de solicitudes en su flujo general, generación de reportes, etc.**

1. Al momento de listar las solicitudes por parte de cualquier estudiante desde la rama develop, el mensaje que aparece es el siguiente:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/3f54f858-b0ed-471c-8b56-c0175f577de1">

Desafortunadamente todas las solicitudes tienen como código de status 200, entrando más a fondo se ve que el código ejecutado es desde el crud, pero nuevamente todos los códigos de status son 200 (es decir, no hay ningún panic o error que se esté arrojando).

2. Al momento de crear solicitud por parte de cualquier estudiante vuelve a ocurrir lo mismo:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/54f9db44-3c55-4824-90d9-215c8235d84f">
