### ISSUE TITLE
Realizar corrección de errores de las pruebas - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#750]
Se requiere realizar el la corrección de los errores encontrados en las pruebas funcionales que se realizan al sistema para estabilizarlo despues de los ajustes realizados al mid y al crud

**Sub Tareas**

- [x] Revisar y ajustar errores encontrados en el sistema.
- [x] Documentar errores encontrados y solucionados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Revisar y ajustar errores encontrados en el sistema.**

Se tendrá en cuenta la Issue #745 para seguirla trabajando paralelamente juntando las pruebas provenientes de los errores corregidos en esta issue:
https://github.com/udistrital/polux_cliente/issues/745

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Documentar errores encontrados y solucionados.**

1. Aprobar Solicitud Inicial por parte del Coordinador:
![image](https://github.com/user-attachments/assets/a8bbe435-4866-4b91-9044-ba0dbafcd879)

**Comment by CrisEs2506** [comment]
Se da continuidad a la corrección de los errores en esta ISSUE:

https://github.com/udistrital/polux_cliente/issues/761
