### ISSUE TITLE
Crear script para obtener asistente asociado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#752]
Se requiere realizar el script para obtener el documento del asistente similar a lo realizado en #733, una vez se realice este script avisar a @diagutierrezro para solicitar la creación del endpoint.

**Sub Tareas**

- [x] Crear script para obtener el documento del asistente según el proyecto  curricular.

**Criterios de aceptación**

- [x] Script creado.
- [x] Documenación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se revisan los script desarrollados en los issues #733 y #737 para tomar como base y crear el script para recuperar el documento del asistente de proyecto ingresando el código de la carrera.

Se desarrolla el siguiente script:

```bash
SELECT DISTINCT USUWEB_CODIGO documento_asistente, emp_nombre nombre_asistente
FROM MNTAC.ACCRA
INNER JOIN MNTGE.GEUSUWEB  ON CRA_COD = USUWEB_CODIGO_DEP
INNER JOIN MNTGE.GEUSUTIPO ON USUTIPO_COD = USUWEB_TIPO
INNER JOIN MNTGE.GETIPOVINCULACION ON USUWEB_TIPO_VINCULACION = TVIN_COD
INNER JOIN MNTPE.peemp ON EMP_NRO_IDEN = USUWEB_CODIGO
WHERE cra_cod = ?
AND ((usuweb_fecha_fin >= sysdate AND TVIN_NOMBRE = 'CONTRATISTA OPS') or TVIN_NOMBRE = 'ADMINISTRATIVO PLANTA') AND USUWEB_ESTADO = 'A' AND USUTIPO_TIPO = 'ASISTENTE PROYECTO'
```
dando como resultado la siguiente consulta usando el código de Ingeniería de Sistemas:
![image](https://github.com/user-attachments/assets/9caed3fc-ba53-417a-99ae-edabfbfc183c)

**Comment by JuanDHernandezA** [comment]
Se solicita la creación del endpoint con el script creado. El link para acceder a los datos del Asistente del Proyecto es:

https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v2/obtener_asistente/{codigo_proyecto}

**Comment by diagutierrezro** [comment]
Se solicita a Jhon la creación del endpoint con el script creado.
