### ISSUE TITLE
Implementar envío de información personal para ARL - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#753]
Se requiere realizar la implementación inicial para que el estudiante envíe la información personal para que desde la oficina de pasantía se haga la gestión de la ARL cuando la pasantía es interna, es importante tener en cuenta que dicha información solo es visible por la oficina de pasantía.

Para definir el alcance de este issue se iniciará agregando el campo donde el estudiante selecciona si es pasantía interna o externa y dependiendo de su selección se habilitan los campos para envíar la información solicitada. 

Ajustar vista con usuario de modalidad de pasantía para poder visualizar esta información cuando el usuario que se encuentra logueado tiene el rol de OFICINA_PASANTIA.

**Sub Tareas**

- [x] Crear script para realizar cambios en la DB en caso de ser necesario, si esto se realiza documentar la issue #584 para tener los cambios presentes al desplegar a producción.
- [x] Ajustar formulario de solicitud inicial para solicitar información personal requerida para ARL en caso de ser una pasantía interna (si no es interna no mostrar estos campos).
- [x] Ajustar logica para que unicamente desde la oficina de pasantía se pueda ver la información suministrada por el estudiante para iniciar tramites de ARL.

**Criterios de aceptación**

- [x] Script creado.
- [x] Ajustes de solicitud inicial realizados.
- [x] Ajustes de visualización de información realizados.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Inicialmente se realiza el cambio en la BD local, para realizar pruebas de funcionamiento primero y luego si realizar el cambio en la BD de pruebas en la tabla academica.detalle_pasantia
![Image](https://github.com/user-attachments/assets/c1f55295-d1ae-42a8-b4a5-72acb23e55fc)
![Image](https://github.com/user-attachments/assets/dd1bdf53-cd47-40d5-84af-7f767a112c76)

Se realiza modificación en el API POLUX_CRUD en el modelo detalle_pasantia creando el campo datos_personales
![Image](https://github.com/user-attachments/assets/c417c5a8-a846-4e5c-ab1f-4aa80578fe7c)
Se realiza una prueba desde Postman realizando un GET, responde correctamente un registro que trae el nuevo campo con valor Null

![Image](https://github.com/user-attachments/assets/df78fda6-f3c1-48d1-a385-1e863d655f74)
Se realiza prueba realizando una inserción con el nuevo campo, responde error
![Image](https://github.com/user-attachments/assets/ea16273e-0ac1-4030-8f16-ddaf393e5d64)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan correcciones en el JSON de prueba en el POST pero se seguía obteniendo error, se revisó documentación de Beego, inicialmente se prueba utilizando el tipo JSONField con los ajustes respectivos en controlador y modelo, arrojó error 
![Image](https://github.com/user-attachments/assets/9a73988d-9821-4711-a009-a5331ff2438e)
Luego con el tipo [] byte con los ajustes respectivos en controlador y modelo, arrojó error
![Image](https://github.com/user-attachments/assets/c99fb7b1-ebc1-4c4b-ae77-156cb324b2ed)
Se probó con tipo RawMessage con los ajustes respectivos y también arrojó error
![Image](https://github.com/user-attachments/assets/48151e62-370e-4870-9d6a-bee40d650c1f)
Tambíen se probo declarando el campo como tipo map[string]interface{} y también arrojó error
![Image](https://github.com/user-attachments/assets/ad8d2e96-aa11-4240-a361-efe436066e34)
También se probó declarando el campo tipo string, los errores salían por error en el Unmarshal o por que el tipo de dato en el modelo no era soportado por el ORM a pesar de que en la documentación salen sugeridos.
Se sigue verificando y se piensa una forma que sería serializar el campo y convertiendolo de manera automatica a string

![Image](https://github.com/user-attachments/assets/01d1b454-6300-4d3b-a99a-8c7abf3d71e5)
se realizan ajustes en las funciones que hacen insert, update, getone y getall, se realiza prueba y funciona pero de acuerdo a cambios para que pueda tratar los datos trae otro campo en la consulta, por ende lo necesario es realizar el tratamiento del campo en el API MID y en el CRUD solo mantener el cambio añadiendo el campo en el modelo
![Image](https://github.com/user-attachments/assets/06d77880-2935-47f7-bbdd-393d7ce238fe)
![Image](https://github.com/user-attachments/assets/e8adca85-ea26-4313-a48d-d22358fd8508)
