### ISSUE TITLE
Actualizar Mockups modalidades espacios académicos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#755]
Se requiere realizar la actualización de los mockups relacionados con las modalidades espacios académicos. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado el mockups de la modalidad de creación de solicitud 

[Carpeta de mockup](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EogEQdSTGIBMpKs2bx6VTJQBcUK0s9oekNDQR3R0jFUy-A?e=xdR7rz)

![Image](https://github.com/user-attachments/assets/d9b5a1d6-dc00-4017-bd2c-7e1d0efaf47f)

**Comment by mantnicot** [comment]
Ha sido aprobado por el líder técnico

**Comment by jcmurilloa** [comment]
Muy buenos diseños @mantnicot.
