### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de requerimientos con el cliente Biblioteca

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#756]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos con el cliente Biblioteca

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha generado la reunión , se coloca el enlace de la misma y se construye el acta posterior

[Enlace Reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTcyOTBhM2ItYWFjNy00ZGUwLWE2ZjMtOTFiZDY4MDQwZjZh%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha levantado el acta de la reunión
[acta reunión](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Eeg8zQde3-JNnfZiS8rRWOEBp38WwOmZ81e4aKv65M5qxQ?e=gHEisT)

**Comment by jcmurilloa** [comment]
Acta revisada y con VoBo para recolección de firmas.

**Comment by mantnicot** [comment]
Se adjunta el acta con las firmas correspondientes
[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ET-M5CbX4_9FiH6xBS8wlioB7DBQdpPBiK5XzE8oK46KtQ?e=lYnhJQ)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
