### ISSUE TITLE
Implementar envío de información personal para ARL - parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#760]
Se requiere realizar la continuación de la implementación para el envío de información personal para finalizar lo desarrollado en #753, se debe tener presente que la visualización de dicha información solo la puede ver el usuario con rol de oficina de pasantía.

- Se debe crear la columna en la tabla solicitud_trabajo_grado que si bien se manejará como un json a nivel de db es string.

- Revisar manejo de modales para generar formulario desde esta vista y que el estudiante envíe los datos personales solicitados desde allí, importante verificar como almacenar la información una vez el modal sea cerrado.

**Sub Tareas**

- [x] Crear columna en solicitud_trabajo_grado y ajustar CRUD.
- [x] Revisar manejo de modal en el cliente para envío de información.
- [x] Probar envío de información hacia la tabla modificada.

**Criterios de aceptación**

- [x] Columna de tabla y CRUD modificados.
- [x] Revisión de manejo de modales realizada.
- [x] Pruebas de envío de información realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Debido a que ocultar detalles de acuerdo a si la pasantía es interna o externa no fue practico para el manejo del formulario, se toma como alternativa trabajar la captura de estos datos con un modal, inicialmente se estudió si se podía implementar con angular material, pero por la versión antigua del Angular de este cliente podían generarse problemas de versiones y compatibilidad, luego de esto se estuvo estudiando para esta versión como puede funcionar un modal para capturar datos, se revisó como un ejemplo el modal de revisión de arl, aunque este es de muestra de datos, y se procede a crear un elemento HTML condicionado para que solo haga aparición en caso de que el estudiante seleccione modalidad de pasantía:

![Image](https://github.com/user-attachments/assets/8a7d116d-f6a2-493d-a8e8-48b794e6f56a)

![Image](https://github.com/user-attachments/assets/4750a5c6-77c2-4988-8327-3a9d4c9d7661)

Se realizan ajustes de estilos clases CSS
![Image](https://github.com/user-attachments/assets/aa9946ad-fad2-4fe7-9a83-312d959b5634)
Se crea la plantilla HTML para el modal
![Image](https://github.com/user-attachments/assets/f8e67e23-5e2a-4eed-9b19-eebdf08370bf)
Pero esta al ser un archivo separado no respondió al ejecutar la función para abrir la ventana del modal, entonces se procedió a añadir la plantilla en el HTML de la vista de crear solicitud y de esta forma funcionó
![Image](https://github.com/user-attachments/assets/c04dcc54-9298-4adb-8912-9fbea2685ec6)
Se crea función para captura de datos ingresados al modal para que a su vez estos sean adjuntados al objeto que se envía en la solicitud inicial

![Image](https://github.com/user-attachments/assets/7ed87b4f-a585-49e9-899b-bd5c53da01d4)
Inicialmente la función tiene unos print en consola para realizar pruebas de captura de datos, se realiza prueba exitosa
![Image](https://github.com/user-attachments/assets/24c260f8-9b95-42df-982c-6decf0f8ae0a)

**Comment by Astaroth-Andres-Molano** [comment]
Se habían creado los detalles necesarios para la carga de los datos personales, pero debido a que se van a renderizar de forma diferente se procede a revertir los cambios realizados a las tablas academica.detalle, academica.detalle_tipo_solicitud y academica.detalle_solicitud:
DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=339;

DELETE FROM academica.detalle_tipo_solicitud
	WHERE id=339;

DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=345;

DELETE FROM academica.detalle_tipo_solicitud
	WHERE id=345;

DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=344;

DELETE FROM academica.detalle_tipo_solicitud
	WHERE id=344;

DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=343;

DELETE FROM academica.detalle_tipo_solicitud
	WHERE id=343;

DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=342;

DELETE FROM academica.detalle_tipo_solicitud
	WHERE id=342;

DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=341;

DELETE FROM academica.detalle_tipo_solicitud
	WHERE id=341;

DELETE FROM academica.detalle_solicitud
	WHERE detalle_tipo_solicitud=340;

DELETE FROM academica.detalle
	WHERE id=92;

DELETE FROM academica.detalle
	WHERE id=91;

DELETE FROM academica.detalle
	WHERE id=90;

DELETE FROM academica.detalle
	WHERE id=89;

DELETE FROM academica.detalle
	WHERE id=88;

DELETE FROM academica.detalle
	WHERE id=87;

DELETE FROM academica.detalle
	WHERE id=86;

Se vuelve a ajustar el orden de los detalles en la modalidad de pasantía:

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=10
	WHERE id=264;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=11
	WHERE id=265;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=12
	WHERE id=266;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=13
	WHERE id=267;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=14
	WHERE id=268;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=15
	WHERE id=271;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=16
	WHERE id=329;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=17
	WHERE id=270;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=18
	WHERE id=307;

![Image](https://github.com/user-attachments/assets/f291505e-2d2a-4aa2-804c-dfde41565c31)

Estos registros de detalles previamente realizados y estos cambios de reversión en la base de datos no se registraron en la Issue #584 ya que primero se sometió a pruebas el desarrollo de esta forma y no funcionó así y se optó por otra solución.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes para el tratamiento del JSON DatosPersonalesArl que hace parte del modelo SolicitudTrabajoGrado que hace referencia a la nueva columna creada en la tabla academica.solicitud_trabajo_grado para persistir los datos personales del estudiante en caso de pasantía interna, en el API MID en el controlador tr_solicitud.go se realizan dichos cambios
![Image](https://github.com/user-attachments/assets/beb09e64-0dcb-41de-978e-100c72eaed16)
Se modifica el modelo en el API MID SolicitudTrabajoGrado
![Image](https://github.com/user-attachments/assets/ed66d319-d663-4ee3-82d4-ab716227680c)
En el API CRUD se realiza la respectiva modificación al modelo SolicitudTrabajoGrado para persistir los datos
![Image](https://github.com/user-attachments/assets/d505d0d2-3e72-48df-b77b-3081f713c053)
Se realiza prueba haciendo la solicitud y llenando los campos de la modalidad de pasantía y los datos del modal realizado respectivamente, la prueba es exitosa
![Image](https://github.com/user-attachments/assets/20229fa1-1a36-402c-b646-cb89734f68b8)
verificación del registro en la base de datos
![Image](https://github.com/user-attachments/assets/a12b8740-b2d3-4619-982a-62b8798961f6)

**Comment by Astaroth-Andres-Molano** [comment]
Se concluye la tarea de envío de información de datos personales para trámite de ARL para la modalidad de pasantía interna, se realiza adelanto para el desarrollo de recuperar u obtener los datos se revisa la petición que realiza el cliente observando que la hace directamente al CRUD con un GET a la ruta solicitudTrabajoGrado, por ende se inicia la labor de realizar el tratamiento del campo datosPersonalesARL para hacer la conversión de String a JSON nuevamente, se realiza de varias formas en el model en el operador que trae la data pero no se logró conseguir que hiciera la conversión
![Image](https://github.com/user-attachments/assets/8e632bca-2902-4e99-be46-75dca8032619)
![Image](https://github.com/user-attachments/assets/06b268cd-6aeb-4851-93a9-9c29e8c03fd2)
Se plantea modificar la petición del cliente para que ahora la haga al MID, y desde allí procesar la respuesta para que retorne los datos en formato JSON.
