### ISSUE TITLE
Iniciar ajuste para vista de solicitud inicial en modalidad de materias de posgrado - parte 1.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#762]
Se requiere realizar el ajuste inicial de la vista de la solicitud inicial para las modalidad de materias de posgrado teniendo en cuenta los [mockups](https://github.com/udistrital/polux_cliente/issues/755) creados, tener presente que ahora no se cargaran las materias previamente por parte del coordinador de posgrado sino que unicamente se pondran los proyectos curriculares hacia los que va dirigida la solicitud.

**Sub Tareas**

- [x] Ajustar interfaz de la solicitud inicial teniendo en cuenta los mockups.
- [x] Probar funcionamiento de la interfaz modificada.
- [x] Documentar issue con ajustes realizados.

**Criterios de aceptación**

- [x] AJuste realizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
https://github.com/udistrital/polux_cliente/issues/647

**Comment by CrisEs2506** [comment]
Daily 11/10/2024
Se ha logrado desarrollar el espacio para confirmar el acuerdo de solicitud, el espacio de selección única para la prioridad de la opción, el listado de las áreas de conocimiento y el último espacio para confirmar acuerdos de solicitud.
Actualmente, me encuentro en el desarrollo del cargue de documentos y la selección de proyectos curriculares no solo a nivel visual si no a nivel lógico.

**Comment by CrisEs2506** [comment]
**Script para Cargue de Documentos - Materias Posgrado**

```SQL
INSERT INTO academica.detalle(nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle)
VALUES ('Solicitud Escrita de las Materias', 'SOLICITUD_MATERIAS', 'no_service', 'SEM', true, 4665);

INSERT INTO academica.detalle(nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle)
VALUES ('Justificación', 'JUSTIFICACION', 'no_service', 'JUST', true, 4665);

INSERT INTO academica.detalle(nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle)
VALUES ('Carta de Aceptación de Inscripción', 'CARTA_ACEPTACION_INSCRIPCION', 'no_service', 'CAI', true, 4665);

INSERT INTO academica.detalle(nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle)
VALUES ('Sábana de Notas', 'SABANA_NOTAS', 'no_service', 'SN', true, 4665);
```

**Comment by CrisEs2506** [comment]
**Resultado Final de la Vista**

<img width="479" alt="image" src="https://github.com/user-attachments/assets/012fc5ce-c590-4ca1-ae8a-87666f7d212c">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/c420e7fc-6bf3-4450-ac8a-fe806d03c703">

<img width="472" alt="image" src="https://github.com/user-attachments/assets/4b485b8e-a5ac-4f9c-a683-95d67246975c">
