### ISSUE TITLE
Realizar ajustes solicitados en pruebas de carga y seguridad.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#763]
Se requiere realizar los ajustes solicitados producto del desarrollo de pruebas de carga y seguridad que se solicitaron en el [tuleap](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=63212).

**Sub Tareas**

- [x] Eliminar servicio de nuxeo y credenciales quemandas, despues de esto garantizar que el sistema continúe funcionando con el gestor documental.
- [ ] Agregar uso de sonarqube en el drone.yml en el crud y mid de pólux.
- [x] Realizar flujo de solicitud inicial e ir revisando en base de datos el registro correcto de la hora ya que según las pruebas la hora no está quedando correcta.

**Criterios de aceptación**

- [x] Servicio de nuxeo eliminado.
- [ ] Sonarqube agregados.
- [x] Revisión de campos de fecha creación y modificación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se eliminó los servicios de nuxeo, nuxeo_cliente y nuxeo_mid, junto con esto se borraron todas las peticiones, funciones y lógicas que utilizaban estos servicios. Dando con un total de 43 archivos modificados, se prueba el sistema enfocándose principalmente en las funcionalidades donde se requiera el cargue y visualización de documentos. Se realizan las pruebas con la modalidad de monografía y se prueban las siguiente funcionalidades:

- Solicitud inicial
- Revisión de documento Estudiante
- Subir una nueva versión del documento de tg
- Revisión de documento Docente
- Adjuntar documento a la revisión del docente
- Solicitud de revisión de trabajo de grado
- Subir Acta de Socialización
- Visualización del documento y descarga de los archivos anexos

A lo largo de las pruebas se eliminaron otros servicios y archivos que hacían uso de Nuxeo para su correcto funcionamiento. Todas las pruebas con respecto al gestor documental respondieron de forma correcta.

Pero durante las pruebas se presentaron fallos con respecto a las peticiones que se realizan para recuperar los datos que se adjuntarán en el correo de la notificación. Estos errores se presentan debido a que el desarrollo de las notificaciones no está actualizado con los cambios realizados al API MID y a la nueva forma de respuesta que se desarrolló. Se corrigieron las siguientes consultas para continuar con las pruebas:

- revision_documento.js
![Captura de pantalla 2024-10-09 151556](https://github.com/user-attachments/assets/d8465fa4-3f30-4846-8cc3-d73233a9875b)
![Captura de pantalla 2024-10-09 151603](https://github.com/user-attachments/assets/82bf2999-fba7-4902-aaf6-2589155c04e1)
- registrar_nota.js
![image](https://github.com/user-attachments/assets/ca3dd47d-28d0-4609-bbf5-a725d34ecb3d)

Se deben tener en cuenta estos cambios para hacer las correcciones en el ambiente de pruebas.

**Comment by JuanDHernandezA** [comment]
Para el error de la fecha en la base de datos, se buscaron las tablas de Polux en donde se almacene la fecha y hora actual. Se encontraron las siguientes tablas:

- asignatura_trabajo_grado
- comentario
- detalle_trabajo_grado
- revision_trabajo_grado
- solicitud_trabajo_grado
- vinculacion_trabajo_grado

Se prueba las fechas que se ingresan en las tablas para verificar en cuál se presenta el error de hora incorrecta:

- asignatura_trabajo_grado: Hora correcta
![Image](https://github.com/user-attachments/assets/16ccca9a-1764-46f3-8391-de28a6fa981f)

- comentario: Hora correcta
![Image](https://github.com/user-attachments/assets/a0712c49-ea7f-4a78-9f7d-7454f98f0611)

- detalle_trabajo_grado: Hora correcta
![Image](https://github.com/user-attachments/assets/cea1f1ed-b62b-4d86-9d19-14baf838d47f)

- revision_trabajo_grado: Hora incorrecta en primera columna
![Image](https://github.com/user-attachments/assets/f29ce083-12ed-4c41-943a-5b6607612db0)

- solicitud_trabajo_grado: Hora correcta
![Image](https://github.com/user-attachments/assets/167ba19d-bb31-41c3-b95f-b5331fca52ec)

- vinculacion_trabajo_grado: Hora incorrecta
![Image](https://github.com/user-attachments/assets/19dc778d-c528-4520-a5f6-adc2d44156e8)

Para corregir las fechas de la tabla vinculacion_trabajo_grado se realizaron los siguientes cambios:

- En el cliente ya no se envía la fecha actual, sino un string vacío:
![Image](https://github.com/user-attachments/assets/0a8b39f1-d861-47d5-b503-21653d0a5dba)

- En el mid se cambia el modelo, en donde las variables de fecha no serán de tipo time, sino de tipo string y ambos se establecen como No requeridos:
![Image](https://github.com/user-attachments/assets/953b2e0f-8144-4ff5-8e2c-8ab1b1991f7a)

- En el CRUD también se cambia el modelo:
![Image](https://github.com/user-attachments/assets/a554ab9a-3c26-4c04-92e8-c20e380d7ee8)

- En el controlador del CRUD se agrega la fecha actual por medio del utils y se deja en nulo la fecha final:
![Image](https://github.com/user-attachments/assets/bc4e7d21-7ca6-4c0c-ae87-7887d3d4520a)

Se prueban los cambios y se observa que funciona correctamente
![Image](https://github.com/user-attachments/assets/c971fd77-e748-4f3a-83ac-6bd9cbcd3ac1)

Ahora, para la tabla revision_trabajo_grado se observa que al momento en que un estudiante crea la solicitud, la fecha de la columna "fecha_recepcion" es correcta:
![Image](https://github.com/user-attachments/assets/b9b7b139-45e0-46b9-b452-afd0ced42813)

Pero al momento en que el docente responde la revisión la fecha cambia, restándole 5 horas:
![Image](https://github.com/user-attachments/assets/a6788568-a932-4bdd-b74f-819b9a1ef478)

Se cambian los modelos del CRUD y MID para poder usar el utils de la universidad:
![Image](https://github.com/user-attachments/assets/bb5cc081-fe6c-4182-be76-ddabedfde4ef)

Se observa que hay un error al momento de recuperar la fecha de la columna "fecha_recepcion" en donde retorna una doble zona horaria (+0000 + 0000):
![Image](https://github.com/user-attachments/assets/c1421096-7fbd-49e5-8ad4-d536774d880c)

Se consulta y la única forma es eliminar esos caracteres del string:
![Image](https://github.com/user-attachments/assets/f29ff77c-681b-4860-a88b-eb0d289db587)

Se prueban los cambios y se observa que la hora de la columna "fecha_recepcion" se conserva y la fecha de la columna "fecha_revision" es correcta:
![Image](https://github.com/user-attachments/assets/6c7f8694-5c9f-48de-8168-88f53a267e53)

**Comment by JuanDHernandezA** [comment]
Para realizar las pruebas de Sonarqube, se comienza en el API MID. 

Se observa que ya existe el archivo "sonar-project.properties" pero es distinto al usado en el API MID de resoluciones:

![Image](https://github.com/user-attachments/assets/ab44da7a-c475-4fb5-957e-df85536b3894)

Se copia el documento de resoluciones_mid y se ajusta para polux_mid:
![Image](https://github.com/user-attachments/assets/6c79926b-53dc-4300-b55c-51952cbf1c65)

Se agrega en el archivo de drone.yml el step del sonarqube:
![Image](https://github.com/user-attachments/assets/d441f6a7-7478-49a0-a055-04203cf2a7f3)

De igual forma, en el CRUD ya existía el archivo "sonar-project.properties", por lo que se modifica y se agrega el step en el documento drone.yml:
![Image](https://github.com/user-attachments/assets/a76be434-1c83-4aeb-8487-dcd1e0606d90)
![Image](https://github.com/user-attachments/assets/bf789d85-0487-4889-bbf6-cf001a8c64b6)

Se observa el resultado en el drone y aparece un error en el que mencionan que la respuesta del servidor de Sonar está vacía:
![Image](https://github.com/user-attachments/assets/57fad391-1c51-47d8-9a26-41a130231567)

Se especula que hace falta una variable de entorno que apunte a dicho servidor. Por lo cual no se pueden continuar con las pruebas

**Comment by diagutierrezro** [comment]
Queda pendiente por parte mía solicitar que se agreguen las respectivas variables desde infraestructura, buen trabajo Juan Diego
