### ISSUE TITLE
Ajustar código según ajustes de SonarQube

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#764]
Se requiere realizar ajustes de código en las Apis según lo que surja de la ejecución del sonar qube que se agregó en las Apis.

**Sub Tareas**

- [x] Ajustes de código realizado.
- [x] Documentación de ajustes realizados.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se analizan y solucionan los siguientes errores:

- Se agrega el atributo de lenguaje a la etiqueta:
![Image](https://github.com/user-attachments/assets/82851c72-b0f1-45ec-b648-c52defc908b6)
![Image](https://github.com/user-attachments/assets/b840b9cb-5512-4980-a63d-5e29e9c04d82)

- Se elimina parámetro repetido:
![Image](https://github.com/user-attachments/assets/0ed6c0ff-fe1c-484d-9404-22c7692de08e)
![Image](https://github.com/user-attachments/assets/db9570da-baba-4d84-b079-1499369b4ba2)

- Se inicializan las variables:
![Image](https://github.com/user-attachments/assets/b77af0d3-3619-4dd1-a383-3bc4f909724e)
![Image](https://github.com/user-attachments/assets/5efdc60b-4adf-4b3f-9104-3f8049ee6061)

- Se borra el llamado a _console_
![Image](https://github.com/user-attachments/assets/1a3b3b50-76a0-4b61-8a0c-a5d5ce6407b3)

- Se elimina variable repetida:
![Image](https://github.com/user-attachments/assets/92148ba4-2c98-4398-8acd-c4ae95ef9288)
![Image](https://github.com/user-attachments/assets/b1b783da-88a2-4884-acf9-babc449a80c4)

- Se elimina variable de entorno duplicada:
![Image](https://github.com/user-attachments/assets/62811503-c4fb-4d3a-abd3-27ca0056a3ad)

- Se comenta estructura condicional sin uso:
![Image](https://github.com/user-attachments/assets/d08ced3e-8088-4ea8-bbab-e65e3d167717)
![Image](https://github.com/user-attachments/assets/bcda1c60-0e5a-4015-85b6-1b571e676daf)

- Se elimina atributos repetidos:
![Image](https://github.com/user-attachments/assets/ad0288ee-f4af-4e03-8a28-9a9d117b357c)

- Se agrega título en etiqueta:
![Image](https://github.com/user-attachments/assets/0c239ed1-490d-42ed-8e79-522da6002dbf)
![Image](https://github.com/user-attachments/assets/3054f02c-20de-48be-811a-c2233e49cda2)

- Se eliminan varias etiquetas _center_ ignoradas:
![Image](https://github.com/user-attachments/assets/0522e1cc-a6d4-47e9-9ec1-acbe868023d1)
![Image](https://github.com/user-attachments/assets/c1c59413-b330-4d9e-8bf0-6a9e352eaefd)

- Se reemplazan varias etiquetas <i> por <em>
![Image](https://github.com/user-attachments/assets/043b129b-63b6-44d9-9681-e149e2101339)

- Se reemplazan las etiquetas <b> por <strong>
![Image](https://github.com/user-attachments/assets/e003d489-88d3-4790-8107-14eea80d4745)

**Comment by JuanDHernandezA** [comment]
Se continua con la solución de errores en el Cliente:

- Se agrega el atributo rel para las etiquetas link:
![Image](https://github.com/user-attachments/assets/7fd6d299-6f68-42b1-a144-3eab6325fe30)

- Se elimina código comentado sin usar:
![Image](https://github.com/user-attachments/assets/38afb77b-672b-4e11-8ec1-8ecee2aa9ba6)

- Se eliminan variables que no se usan:
![Image](https://github.com/user-attachments/assets/748352c0-315a-4dd3-9941-09f9c23c4565)

- Se corrigen declaración de variables duplicadas:
![Image](https://github.com/user-attachments/assets/b975c9ed-5ab6-4f6a-9f2a-8bf2109dae18)

- Se eliminan bloques condicionales vacíos:
![Image](https://github.com/user-attachments/assets/33407eff-fa29-45bb-9215-d693adf37626)

- Se cambia el nombre de algunas variables para evitar errores:
![Image](https://github.com/user-attachments/assets/cc14a0ed-1f26-45d5-9e1b-70612b9d4f29)

Debido a que el servicio de JBPM ya funciona, se revisan los cambios que se han realizado.

Se puede observar que al eliminar la etiqueta _center_ ya los contenidos no están centrados:
![Image](https://github.com/user-attachments/assets/ffa00848-be3a-4a29-b442-ca36a600827d)

Al crear una solicitud, no se muestra el formulario, queda en blanco la página. Al revertir los cambios en el documentos _crear_solicitud.js_ vuelve a la normalidad el flujo.

De igual forma, al momento de consultar el trabajo de grado, el menú se queda cargando y no muestra los detalles:
![Image](https://github.com/user-attachments/assets/f5f84235-6e62-4172-96c1-f584ea07b65b)

En este caso, al revisar el documento de _consultar_trabajo_grado.js_ los únicos cambios realizados fueron con respecto a la variable "defer":
![Image](https://github.com/user-attachments/assets/743b5967-7c3f-4fb2-be13-8029e0847e11)

Al revertir los cambios, el menú funciona correctamente:
![Image](https://github.com/user-attachments/assets/f1f53d20-46bb-4aca-a6f6-247753c58d19)

Por lo que se propone que los cambios asociados a las variables "defer", no modificarlas.

Al responder una solicitud por parte de la coordinación, no se muestran las actas anteriores:
![Image](https://github.com/user-attachments/assets/8d664045-a67a-484e-8514-6de91732c8d6)

Se encuentra el cambio realizado y se corrige el error:
![Image](https://github.com/user-attachments/assets/35c81b7e-f981-4547-8293-507b4dfda112)

Se prueba responder una Solicitud Inicial, pero al momento de que el coordinador la aprueba sale error:
![Image](https://github.com/user-attachments/assets/9979ea71-e37b-429f-b312-291983022b76)

Se revierten los cambios realizados en el documento _aprobar_solicitud.js_ pero sigue saliendo el mismo error. 

Se debe evaluar si empezar las correcciones desde el principio y realizar las pruebas en el sistema, o buscar en dónde está fallando la solicitud y demás errores que se presenten.

**Comment by JuanDHernandezA** [comment]
Se revisa el error que se produce desde el API MID y se observa que es con respecto al formato de las fechas. Se piensa que el error es porque no se ha actualizado la rama release con los cambios realizados en el issue #763. Se solicita a @diagutierrezro la actualización en el MID y CRUD, y al aprobar la solicitud inicial por parte del coordinador, se observa que funciona de forma correcta:
![image](https://github.com/user-attachments/assets/66d90bd4-4441-4e0a-ad5c-615c1a41b7ff)

Se observa que el documento _estudiante/revision_documento.js_ fue modificado, por lo que se prueban todas las funcionalidades de esta vista para verificar que los cambios realizados no afecten el correcto flujo. Las funcionalidades probadas fueron:

- Subir una nueva versión del documento
- Solicitar nueva revisión
- Ver el documento adjunto a la revisión
- Agregar comentarios a la revisión

Todas estas funcionalidades no fueron afectadas por los cambios realizados; pero al probar la última funcionalidad se observa que presenta un error asociado a la actualización de la respuesta de las APIs, se corrige y funciona correctamente:
![image](https://github.com/user-attachments/assets/73fb3ed2-7fb6-426b-be0c-fb89ea6d875c)

Durante las pruebas se encontró con un error al momento de aprobar una solicitud de cancelación, en donde la tabla _vinculacion_trabajo_grado_ presentaba un error de formato en las fechas que se ingresaban. Se analiza el error y se observa que las fechas que se recuperan desde la base de datos se deben "reparar" al volver a enviarlas en un UPDATE con la función del utils oas time_bogota.TiempoCorreccionFormato(v.FechaInicio). Pero si es la primera vez que se ingresa la fecha, entonces se debe usar la función time_bogota.TiempoBogotaFormato(). Al hacer estas correcciones, la solicitud de la cancelación funciona correctamente.

Continuando con las pruebas, se observa que otros documentos modificados son asociados a la modalidad: _actas_seguimiento.js_ y _revisión_arl.js_, por lo que se crea un trabajo de grado con la modalidad de pasantía y se verifica su correcta funcionalidad:

- Para la revisión del documento todo funcionó correctamente
- Para la vista de actas de seguimiento no cargaba la vista, pero como se mencionó en el comentario anterior, todos los cambios asociados a la variable del defer se deben mantener igual, por lo que se revierten los cambios realizados en esta vista y ya funciona correctamente

**Comment by JuanDHernandezA** [comment]
Se realiza la última prueba en la funcionalidad de registrar nota para verificar que los cambios realizados no afectan el flujo correcto de la vista. Se presenta un error al momento de solicitar una corrección, pero al revisar las peticiones, todas respondieron de forma correcta. Se revisa el código y se observa que hay un error debido al cruce de desarrollos de notificaciones y actualización de respuesta de las APIs MID y CRUD, por lo que había peticiones que no se accedía correctamente a su respuesta. Se corrige el error y la corrección se registra de forma correcta:
![Image](https://github.com/user-attachments/assets/fe43e9be-a0b7-413f-b37c-75263550c987)

Se prueba subir la calificación con los usuarios de Docente Evaluador y Docente Director, en ambos casos el flujo es correcto:
![Image](https://github.com/user-attachments/assets/815bd017-78dc-46fd-bb06-7f8bb879227b)

Con todas las pruebas realizadas, se continua con la soluciones de errores del sonarqube pero ahora se realizan pruebas al mismo tiempo que se realizan cambios y siguiendo las recomendaciones analizadas a lo largo del issue para evitar errores.

Se realizan los cambios en el documento _crear_solicitud.js_ en donde la mayoría de errores reportados son de nombre de variables duplicadas, por lo que se realiza el cambio donde el sonarqube reporta los fallos. Se realizaron las pruebas con todos los tipos de solicitudes, en donde la única que presentó un error fue la Solicitud de Revisión de Trabajo de Grado, se revierte el cambio donde presenta el error y todas las solicitudes responden de manera correcta.

Ahora, se continua con la solución de errores del archivo _listar_solicitudes.js_. Se corrigen los errores reportados en sonarqube y se prueba la funcionalidad de listar las solicitudes con todos los roles, en donde ninguno presentó ningún tipo de error.

Se realiza Push de los cambios y se visualiza una gran reducción en los bugs y code smell a comparación del inicio:
- Antes:
![Image](https://github.com/user-attachments/assets/cbb4cb21-4cb6-4fb4-8179-5bb6d5b3c479)

- Ahora:
![Image](https://github.com/user-attachments/assets/46367c93-9f53-4503-b353-131235736a6c)

En donde la mayoría de los errores de Code Smell son asociados a la variable defer que no se puede modificar y al código comentado del servicio de notificaciones.

Queda pendiente corregir los últimos errores reportados en el cliente y empezar la corrección en las APIs MID y CRUD de Polux

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego, continuarmeos los errores faltantes en otra issue.
