### ISSUE TITLE
Concertar reunión de refinamiento de requerimiento con facultad tecnologica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#766]
Se requiere realizar una reunión con la facultad tecnológica donde se les socialice el funcionamiento de pólux y levantar requerimientos y analizar la manera de integrar esta facultad con el sistema.

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
se agedno la reunión el 08/10/2024 a las 10:00

[Enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OGU1NzY5MWUtZDhkMS00ZWY4LTg3MjEtZGEzOTQ5NzAwNzli%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by jcmurilloa** [comment]
Revisar el ajuste recomendado e iniciar recolección de fimas.

**Comment by mantnicot** [comment]
Se adjunta el acta firmada
[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EYP5GpyTYEFHhiKDEgFQ1JsBORqDBD-8JL2T4dpryB98Ng?e=CjJkdA)

**Comment by jcmurilloa** [comment]
Muy buen trabajo!
