### ISSUE TITLE
Visualización de datos personales en solicitud inicial únicamente con rol pasantía.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#779]
Se requiere realizar el desarrollo para tener la visualización de los datos de ARL según lo desarrollado en #760  con el fin de que solo los usuarios con el rol de EXTENSION_PASANTIA pueda visualizar estos datos en un modal cuando está aprobando la solicitud inicial, le debe aparecer un botón en el listado de la información el cual muestre la información enviada por el estudiante.

**Sub Tareas**

- [x] Desarrollar modal que permita visualización de dicha información.
- [x] Agregar botón que es visible únicamente cuando el rol del usuario incluye EXTENSION_PASANTIA.
- [x] Comprobar que el botón anterior solo es visible con el rol indicado.
- [x] Realizar pruebas de funcionamiento.

**Criterios de aceptación**

- [x] Modal desarrollado.
- [x] Botón agregado.
- [x] Comprobación de visualización realizada.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes para hacer el tratamiento del objeto que se recupera de solicitud_trabajo_grado y convertirlo en JSON
![Image](https://github.com/user-attachments/assets/af07f479-6df1-4576-b2b1-b3862ff8d465)
al realizar pruebas se encuentra un error en la carga de datos, una consulta que va a academica JBPM devuelve error 500 y esto atasca las pruebas
![Image](https://github.com/user-attachments/assets/e87c8ddb-0a0c-410c-84a2-a1f10b6a8d62)
![Image](https://github.com/user-attachments/assets/7ee921d2-2c25-466f-8b01-900ce2bb7e54)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan pruebas y se obtiene la información personal en formato JSON
![Image](https://github.com/user-attachments/assets/a38c6e70-c903-4166-9dc8-8a1dc3163f28)

**Comment by Astaroth-Andres-Molano** [comment]
Se desarrolla la función para mostrar el modal
![Image](https://github.com/user-attachments/assets/6f71bfd1-3f50-4f54-9188-075c2de15d93)
Se desarrolla la plantilla HTML del modal
![Image](https://github.com/user-attachments/assets/d99d0448-412f-4da8-9d44-dbdfb4f2be96)
Se desarrolla la sección que le indicará al funcionario que la pasantía es de caracter interno, esta aparecerá solo para el rol de extensión de pasantía y cuando la pasantía sea interna
![Image](https://github.com/user-attachments/assets/014fd11a-1ef9-4056-bc91-d62e4f71d4c3)
Vista de la sección con el label y botón para abrir modal con la información
![Image](https://github.com/user-attachments/assets/2cd9f4d7-8568-4d7a-89eb-ecc72cedffa3)
Vista del modal con la información
![Image](https://github.com/user-attachments/assets/29ae0d5c-40c7-414a-aa70-b399962a6de5)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres.
