### ISSUE TITLE
Visualización de datos personales para ARL en revisión de documentos (solicitud inicial).

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#780]
Se requiere realizar un desarrollo similar al realizado en #779 en el que aparezca un modal con la información personal del estudiante enviada para tramite de la ARL, este nuevo desarrollo debe ser visible en la sección de "Trabajo de grado - consultar", especificamente en la sección donde se listan las solicitudes realizadas en un trabajo de grado, para la solicitud inicial tambien debe aparecer un botón el cual al darle clic despliegue un modal donde se muestre la información personal que el estudiante había enviado en la solicitud inicial, este botón solo debe ser visible con el rol EXTENSION_PASANTIA.

**Sub Tareas**

- [x] Desarrollar modal para visualizar información.
- [x] Agregar botón en la solicitud inicial que se muestre solamente con el rol EXTENSION_PASANTIA y la solicitud sea una solicitud inicial.
- [x] Realizar pruebas del funcionamiento correcto.

**Criterios de aceptación**

- [x] Modal desarrollado.
- [x] Botón agregado.
- [x] Pruebas realizadas.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza corrección en el modelo del CRUD, al intentar realizar nuevamente la prueba ocurre error al cargar docentes evaluadores
![Image](https://github.com/user-attachments/assets/d620a216-1042-4f53-a6a7-66224e3078c3)
![Image](https://github.com/user-attachments/assets/0b7a2247-7fe9-4700-8976-21670a0396cc)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan correcciones y vuelve a registrar los datos correspondientes en base de datos
![Image](https://github.com/user-attachments/assets/3b12778a-d365-4587-be38-c526bc788b33)
