### ISSUE TITLE
Iniciar ajuste para vista de solicitud inicial en modalidad de materias de posgrado - parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#781]
Se requiere realizar la continuación en la visualización de la solicitud inicial para finalizar dicho formulario y una vez se finalice este formulario se debe revisar el flujo de aprobación el cual debe ser coordinación pregrado - coordinación posgrado 1 - coordinación posgrado 2.

**Sub Tareas**

- [x] Finalizar formulario de solicitud inicial.
- [x] Iniciar revisión y ajustes de flujo de aprobación.

**Criterios de aceptación**

- [x] Formulario de solicitud inicial finalizado.
- [x] Revisión y ajustes de flujo de aprobación realizados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Finalizar formulario de solicitud inicial.**

Resultado Final:

![image](https://github.com/user-attachments/assets/47cb3b86-5fd1-4344-b79f-e0175efc847c)

![image](https://github.com/user-attachments/assets/46befc52-b43f-48ac-a843-a75210265ef8)

![image](https://github.com/user-attachments/assets/00226bc5-93e3-45ac-ac78-d302e1da3651)

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Iniciar revisión y ajustes de flujo de aprobación.**

En el archivo 'solicitar_asignaturas.js' de Polux Cliente se modifico lo siguiente para darle completa funcionalidad al formulario:

<img width="631" alt="image" src="https://github.com/user-attachments/assets/2c1f19cf-b9f0-4510-b1fe-248f139ee093">

<img width="677" alt="image" src="https://github.com/user-attachments/assets/fe3d00ef-2355-4d02-b4b4-0ef7cfd00b09">

<img width="692" alt="image" src="https://github.com/user-attachments/assets/fcb2dcf9-81e4-4ca1-866b-9025143c570e">

<img width="452" alt="image" src="https://github.com/user-attachments/assets/ebfc7e5f-c204-42e5-826f-a3108e82fbe5">

<img width="695" alt="image" src="https://github.com/user-attachments/assets/5b31420f-8334-485b-b381-2fbca82bb108">

Además se agregaron los translates tanto en idioma español como en inglés:

<img width="445" alt="image" src="https://github.com/user-attachments/assets/4912a385-97d6-43ec-97a5-496906303cc1">

<img width="422" alt="image" src="https://github.com/user-attachments/assets/ad502797-ad3f-4251-9bdb-02ee30fb9e30">

**Comment by CrisEs2506** [comment]
**Nota:** Desafortunadamente desde el día martes se cayó la base de datos de JBPM hasta el miércoles después de medio día, por lo que retraso en gran medida el desarrollo de la ISSUE planteada y el día de ayer actualizaron los datos del periodo académico de los estudiantes, por lo que al hacer la búsqueda de las materias de posgrado para un periodo del futuro no es posible y por tanto no se puede continuar con el flujo de la modalidad, adjunto pruebas:

![Imagen de WhatsApp 2024-10-17 a las 19 09 58_e687f8f0](https://github.com/user-attachments/assets/26bc2782-653d-47ae-82f4-134f7afa7fdc)

![Imagen de WhatsApp 2024-10-17 a las 19 09 31_400581af](https://github.com/user-attachments/assets/7f16228c-758d-43cb-8f9b-9c0b642c5efd)

**Comment by CrisEs2506** [comment]
**La solicitud inicial ya es enviada correctamente:**

<img width="254" alt="image" src="https://github.com/user-attachments/assets/bb3da806-21b9-421c-af4f-a235d0048c56">

**Comment by diagutierrezro** [comment]
Muy buen trabajo Cristian.
