### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con facultad tecnológica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#782]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente facultad tecnológica

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido agendar para el día 22/10/2024 10 am

[Enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTk2M2QxOTYtODg1Zi00NjZmLTkyNTUtNWJlNWM3MGQyYzQ1%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha levantado el acta de la sesión
[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbMjyopZtPJMuElAAFllpaoBFb8igblE9P2hWpqSjIjFtw?e=njofLk)

**Comment by jcmurilloa** [comment]
Acta revisada y con VoBo para recolección de firmas.

**Comment by mantnicot** [comment]
Se ha recolectado las firmas del acta 

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ESS-ZOEtDMNDpFN0mxw30BUBqT37vEztCQwJXTAdAaiiSg?e=6G2IbC)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot!
