### ISSUE TITLE
Concertar, desarrollar y levantar sesión de refinamiento con el cliente Facultad Ciencias y Educación

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#783]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente Facultad Ciencias y Educación

**Sub Tareas**

- [ ] Concertar reunión con el cliente.
- [ ] Desarrollar la reunión con el cliente.
- [ ] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [ ] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto.
- [ ] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [ ] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha intentado comunicar con la facultad pero hasta la fecha no ha dado respuesta

**Comment by jcmurilloa** [comment]
@mantnicot, por favor comentar con evidencias los hasta ahora fallidos intentos con este posible cliente/usuario e insistir.

**Comment by mantnicot** [comment]
Se ha dado respuesta de parte de la facultad pero por cuestiones de paro , no se han permitido la obtención y agendamiento de reuniones , por lo cual se queda a espera de poder agendar de aprte de ellos 

![Image](https://github.com/user-attachments/assets/ab7cf22f-7136-4e0b-bd6b-f50d7d696693)

**Comment by mantnicot** [comment]
Hasta la fecha no se ha podido contactar con la persona responsable

**Comment by jcmurilloa** [comment]
Se cierra la issue tras varios sprints sin lograr la concertación de una reunión para concretar la exposición del sistema al portencial usuario.
