### ISSUE TITLE
Agregar campo activo para visualización de anexos en solicitud de revisión.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#785]
Se requiere realizar ajustes para que no se muestren los anexos de las solicitudes de revisión que han sido previamente rechazadas, por lo que se plantea utilizar campo activo en la base de datos.

**Dependencias** 
Por parte del lider @diagutierrezro se debe solicitar la creación del campo activo ya que es una modificación de la estructura.

**Sub Tareas**

- [x] Verificar la tabla a la que se le debe agregar el campo activo.
- [x] Ajustar modelo del CRUD para que se ajuste a los cambios realizados en la DB.
- [x] Ajustar consulta para que traiga los documentos activos.
- [x] Ajustar transacción en la cual se valide si hay documentos de tipo Anexo y volverlos false en caso de envia una nueva solicitud de revisión.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Tabla verificada.
- [x] Ajuste de CRUD realizado.
- [x] Consulta modificada.
- [x] Transacción ajustada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se solicita a los DBA la creación de las columnas que se piden por lineamientos.

```
ALTER TABLE academica.documento_trabajo_grado
ADD COLUMN activo bool, ADD COLUMN fecha_creacion timestamp, ADD COLUMN fecha_modificacion timestamp;
```

**Comment by Astaroth-Andres-Molano** [comment]
Se realiza modificación al modelo documento_trabajo_grado en el API CRUD
![Image](https://github.com/user-attachments/assets/e1b4567e-270d-4961-b5e6-e338987fabc9)
Se realiza ajustes en el cliente en el controlador registrar_nota.js 
Modificación en la consulta para que traiga los documentos activos y se elimina el parametro limit de esta
![Image](https://github.com/user-attachments/assets/c9ac81fa-c52c-46b6-a1a4-9809dc2c4432)
Se crea variable array para guardar los ID de los documentos de grado y anexos y se modifica la consulta de documento final de grado para agregar el id al mismo
![Image](https://github.com/user-attachments/assets/da32158f-3c9b-4695-8492-c62ce97390b5)
Modificación de función de documentos anexos para incluirlos en el array de documentos
![Image](https://github.com/user-attachments/assets/115cd548-65cc-4884-b37f-5e700148df24)
Se desarrolla consulta PUT para la desactivación de los documentos en la tabla academica.documento_proyecto_grado en la función registrarCorrecciones.js
![Image](https://github.com/user-attachments/assets/22af61fe-1316-4734-ac9b-af8fc238fa1b)
Se procede a realizar pruebas de funcionamiento, se realiza solicitud de trabajo de grado incluyendo 2 anexos
![Image](https://github.com/user-attachments/assets/d6cfc6d8-eedb-41b1-89d4-a854da7d7b30)
![Image](https://github.com/user-attachments/assets/80e9150d-b22b-4390-b0a1-1c93c00c2b3d)

Se realiza todo el ciclo de aprobación de la solicitud por parte de los roles de docente director y coordinador, ahora en rol de docente evaluador se procede a solicitar correciones, se visualiza que tiene documento final de proyecto de grado y 2 anexos
![Image](https://github.com/user-attachments/assets/daf5d9fd-eb16-46a3-8101-87ece8c1edcf)
![Image](https://github.com/user-attachments/assets/82570ba3-11c2-4a3b-a4f3-409d7399a8ea)
Se genera la solicitud de correciones y se visualiza las consultas PUT desactivando los documentos exitosamente
![Image](https://github.com/user-attachments/assets/8409e37e-e907-48d2-b539-ab14938841aa)
Se procede a iniciar nuevo ciclo de solicitud de revisión de proyecto de grado, en esta solicitud se agrega un sólo anexo
![Image](https://github.com/user-attachments/assets/21b67aa8-5d32-44a2-bc53-3dbb57b30777)
![Image](https://github.com/user-attachments/assets/d8a4c129-452a-4278-8162-a30dd8fa961a)
Se realiza nuevamente todo el ciclo de parobación por parte de los roles de docente director y coordinador, se llega al rol de docente evaluador y se procede a solicitar correciones, se visualiza que efectivamente muestra un sólo anexo y desactivó los documentos de la solicitud anterior
![Image](https://github.com/user-attachments/assets/31b239d0-7e87-426a-b944-0481476b45ca)
![Image](https://github.com/user-attachments/assets/bd0641fd-717d-4ef3-a44e-433e8586efa2)
Se ejecuta la solicitud de correcciones de manera exitosa
![Image](https://github.com/user-attachments/assets/0bc25d12-1898-4f59-8a62-8a08bd76221a)
Se visualiza las consultas PUT de manera exitosa desactivando los documentos 
![Image](https://github.com/user-attachments/assets/cd20e10b-f877-47c1-be47-55ba46ad6b58)
Se visualiza en la base de datos en academica.documento_trabajo_grado que los registros de los documentos quedan desactivados
![Image](https://github.com/user-attachments/assets/ad837d8e-811c-407e-aa88-8d21effaf93a)

**Comment by diagutierrezro** [comment]
El cambio del campo activo en False, se debe realizar en la transacción del MID al momento en el que se aprueba la nueva solicitud de revisión, se debe realizar este ajuste. Por lo demás está muy bien, buen trabajo Andres.
