### ISSUE TITLE
Ajustar código según ajustes de SonarQube - Parte 2.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#790]
Se requiere realizar la continuación de los ajustes que sean posibles en el reporte del SonarQube que se inició en #764, como alcance para este sprint se requiere terminar los ajustes que sean posible en el cliente.

**Sub Tareas**

- [x] Realizar ajustes del Sonar en el cliente.
- [x] Documentar ajustes realizados.

**Criterios de aceptación**

- [x] Ajustes de sonar realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se continua con la limpieza y corrección de errores registrados en el Sonarqube para el repo del Cliente.

Actualmente se cuenta con el siguiente número de errores:
![Image](https://github.com/user-attachments/assets/4ecf0a42-f340-435d-9671-5117c641e25b)

Se corrigen los errores faltantes, los cuales en su mayoría son relacionados a variables ya declaradas, evitar el shadowing (variables con el mismo nombre), variables sin usar y código comentado. Esto sin contar los errores que no se pueden evitar como son: la declaración de la variable asociada al defer; las variables reportadas como "sin usar" asociadas al sistema de notificaciones, esto debido a que la petición que ejecuta la notificación y hace uso de estas variables está comentada; defición de ids y legends en varios labels y tablas de las vistas, entre otros errores que no se pueden eliminar.

Luego de realizar la corrección, se realizan las pruebas a todo el flujo para la modalidad de Monografía, en donde se presentó un error al momento de hacer la solicitud de cambio de evaluador. Se analiza y se encuentra que el error es en el MID; este error está asociado a la nueva forma en que responden las APIs. Se soluciona, se prueba y el sistema responde correctamente a este y las demás correcciones realizadas.

Una vez verificada la funcionalidad del sistema, se suben los cambios y se observa que el número de errores ha sido reducido en gran cantidad:
![Image](https://github.com/user-attachments/assets/b5c2a46c-ea54-4ad3-b812-b4f33d893e0d)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Juan Diego, muchas gracias.
