### ISSUE TITLE
Ajustar código según ajustes requeridos por SonarQube en el API Mid.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#791]
Se requiere realizar los ajustes necesarios (que sean posibles) en el API Mid de Pólux con el objetivo de reducir los errores generados en el reporte de SonarQube.

**Sub Tareas**

- [x] Realizar ajustes según reporte del sonar que no afecten el funcionamiento normal del mid.
- [x] Documentar modificaciones realizadas.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se comienza con la solución de errores del API MID reportados en el Sonarqube:
![Image](https://github.com/user-attachments/assets/4b1f69f7-5a87-4cf9-8cd5-23d5e50f9272)

Revisando los _bugs_, todos están en los archivos autogenerados por el Swagger, por lo que no pueden solucionar o cambiar:
![Image](https://github.com/user-attachments/assets/4225052a-9d1a-434d-aba3-8014c0387b5a)

Se comienza la revisión y corrección de _Code Smell_:

- Se elimina función con misma lógica que otra función en el mismo archivo de _verificarRequisitos_:
![Image](https://github.com/user-attachments/assets/775c3c3a-723e-40c9-a173-9663908074ea)

Se prueba su funcionalidad y responde correctamente:
![Image](https://github.com/user-attachments/assets/cdd0c2c7-1bc5-4839-a65e-15b913950ad5)

- Se corrigen varias variables que no cumplían con las reglas de definición de variables:
![Image](https://github.com/user-attachments/assets/37f4598e-a10b-4dd4-9980-218ac124ffaf)
![Image](https://github.com/user-attachments/assets/f48152ac-8c53-4aa9-b378-d0b9f4626e98)
![Image](https://github.com/user-attachments/assets/0ac18aed-9f62-4aa8-bbee-b68e8fbfb9a2)

- Se encuentra que la mayoría de errores reportados tiene que ver con reducir el número de 'if's' dentro de una función, pero este error no se puede corregir debido a que todas las peticiones que se realizan al API CRUD empiezan con un condicional:
![Image](https://github.com/user-attachments/assets/b38d14fb-768c-4cb8-9d97-bf08a363b0c1)

- Otro error que se presenta con frecuencia es la redefinición de la variable "url", pero no se puede eliminar este error debido a que esta variable se usa cada vez que se envía una petición al API CRUD:
![Image](https://github.com/user-attachments/assets/0aa91d0d-8989-468f-a697-29ea2f57a8a1)

- Se corrige condicional vacío:
![Image](https://github.com/user-attachments/assets/f2fac9cc-332a-4545-82b3-d76cd0787759)

- Se observa que en la sección de _Code Smell_ tambien contiene errores en los archivos del swagger. Se seleccionan estos archivos para obtener el número de errores que contienen y se observa que es la gran mayoría:
![Image](https://github.com/user-attachments/assets/076c9adb-5d4d-438f-8e68-372f8872ecd2)

**Comment by JuanDHernandezA** [comment]
Después de corregir los errores con los nombres de las variables, se verifica la funcionalidad de los siguientes transacciones modificadas:
- verificarRequisitos
- tr_respuesta_solicitud
- tr_vinculacion_registrar_nota

Por lo que se prueba el flujo completo de las solicitudes y la funcionalidad de registrar las notas.

Se realizaron las pruebas al flujo completo para la modalidad de Monografía, en donde no se presentó ninguna novedad, todos los cambios realizados funcionan de forma correcta.

Se vuelve a correr las pruebas del Sonarqube y se observa la reducción de número de errores:
![Image](https://github.com/user-attachments/assets/a62933f4-f0c9-4a46-bcfd-e64a070d888e)

Si seleccionamos los archivos no relacionados con el swagger se observa la reducción de errores (55 inicialmente) y también que los errores que se reportan son aquellos que no se pueden corregir (reducción de número de if's y declaración múltiple de la misma variable):
![Image](https://github.com/user-attachments/assets/777176b1-8855-4c5d-8af1-16e1d93e0f47)

Con lo cual las correcciones en el API MID se han finalizado.

**Comment by diagutierrezro** [comment]
La mayor cantidad de errores que se generan son del swagger el cual es autogenerado, se hablará con Mafe para explicarle por que no se pueden solucionar. Gracias Juan Diego.
