### ISSUE TITLE
Realizar ajustes para discriminar entre COORDINADOR de PREGRADO y POSGRADO.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#792]
Se requiere realizar los ajustes necesario teniendo en cuenta que ahora los roles son unicamente COORDINADOR, por lo que se hace necesario diferenciar entre los proyectos de PREGRADO y POSGRADO realizando las peticiones hacia JBPM. Para esto es necesario analizar las bases de datos y generar un script en el que con el documento del coordinador se obtenga tanto el proyecto curricular del cual es coordinador como el nivel de dicho proyecto, es decir si es un proyecto de PREGRADO o de POSGRADO, una vez se obtengan el endpoint utilizarlo para hacer las respectivas validaciones sobre el nivel del proyecto curricular.

**Sub Tareas**

- [x] Realizar script para obtener proyectos curriculares del coordinador junto con el nivel de dicho proyecto.
- [x] Implementar endpoint creado para realizar validaciones sobre el nivel del proyecto curricular del coordinador.
- [x] Realizar pruebas de funcionamiento correcto para verificar que no se han afectado las modalidades ya estables (monografía, pasantía, etc).

**Criterios de aceptación**

- [x] Script realizado.
- [x] Endpoint implementado.
- [x] Pruebas a modalidades anteriores realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1:  Realizar script para obtener proyectos curriculares del coordinador junto con el nivel de dicho proyecto.**

```SQL
SELECT  
    snies.AS_CRA_NOM, 
    actipcra.TRA_NIVEL
FROM 
    MNTAC.ACCRA accra
JOIN 
    MNTAC.ACCRA_SNIES snies 
    ON accra.CRA_COD = snies.AS_CRA_COD
JOIN 
    MNTAC.ACTIPCRA actipcra 
    ON accra.CRA_TIP_CRA = actipcra.TRA_COD
WHERE 
    accra.CRA_EMP_NRO_IDEN = ?;
```

Ejemplo de la ejecución de la consulta SQL con el CRA_EMP_NRO_IDEN = 23495318:

<img width="370" alt="image" src="https://github.com/user-attachments/assets/8996f535-ef84-47d2-9aba-8f3d5dba2801">

**Comment by CrisEs2506** [comment]
**SubTarea N°2: Implementar endpoint creado para realizar validaciones sobre el nivel del proyecto curricular del coordinador.**

<img width="463" alt="image" src="https://github.com/user-attachments/assets/645e7d19-2b43-4c77-8713-cab40729afc2">

<img width="463" alt="image" src="https://github.com/user-attachments/assets/d9e25bf3-badd-4274-82c0-840ab4ddb588">

**Comment by diagutierrezro** [comment]
Muy buen trabajo Cristian, gracias.
