### ISSUE TITLE
Finalizar creación de modal en consultar trabajos de grado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#799]
Se requiere realizar la finalización de la creación del modal al momento de consultar trabajo de grado que se inició en #780 se requiere renderizar correctamente el modal, importante validar los roles del usuario que está consultando y el tipo de trabajo de grado.

**Sub Tareas**

- [x] Mostrar modal con información personal del estudiante cuando el que consultar es el rol de EXTENSION_PASANTIAS.
- [x] Validar que solo puedan ver la información la oficina de pasantias.
- [x] Realizar pruebas de funcionamiento.

**Criterios de aceptación**

- [x] Modal desarrollado.
- [x] Validaciones realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se desarrolla el botón en la directiva listar_solicitudes
![Image](https://github.com/user-attachments/assets/08d2597c-d1d1-40a9-bcfe-5620cc0d6c58)
Se crea función para mostrar el modal en la directiva listar_solicitudes
![Image](https://github.com/user-attachments/assets/3ca93d23-cafa-4236-a0e0-e4f74e1940bf)
En el HTML de directiva listar_solicitudes se crea la plantilla
![Image](https://github.com/user-attachments/assets/d20c08bb-2b02-49b6-a59e-d410fe1ab8fc)
Se realizan ajustes para capturar los datos personales para ARL
![Image](https://github.com/user-attachments/assets/46cd9757-4b44-49ff-848a-714e4c76b65e)
Se realizan ajustes para capturar el rol y así condicionar a que solo se vea por parte de rol de pasantías
![Image](https://github.com/user-attachments/assets/8f80ff49-3aff-4a6b-a1cf-45aded6b99fd)
Se realiza visualización del botón en la tabla listar solicitudes
![Image](https://github.com/user-attachments/assets/1ee840d2-3446-4fc9-8456-99f632d37533)
Se prueba funcinalidad del botón y se visualiza el modal con los datos para ARL
![Image](https://github.com/user-attachments/assets/8bd33964-acf5-4748-91b1-dbf04a084020)

**Comment by diagutierrezro** [comment]
Muy buen trabajo Andres, gracias.
