### ISSUE TITLE
Ajustar código según ajustes requeridos por SonarQube en el API CRUD.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#806]
Se requiere realizar los ajustes necesarios (que sean posibles) en el API CRUD de pólux con el fin de solucionar los problemas que se generan en el reporte de [sonar](https://sonarqube.portaloas.udistrital.edu.co/project/issues?id=udistrital%3Apolux_crud&resolved=false&types=CODE_SMELL). Documentar los errores que no sean posibles resolver

**Sub Tareas**

- [x] Realizar ajustes al código para solucionar la mayor cantidad de errores posibles.
- [x] Documentar ajustes realizados y cambios que no sea posible realizar.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se comienza la corrección de los errores en el API CRUD reportados en el Sonarqube:
![Image](https://github.com/user-attachments/assets/b314fad0-1d88-4fa5-adbb-7db2dcdb1d09)

Se revisan todos los errores reportados para analizar cuales se pueden solucionar y cuales no se pueden modificar; se encuentran los siguientes errores:

- Refactorizar la lógica utilizada en ciertas funciones para reducir el número de estructuras condicionales y ciclos. Este error no se puede reducir debido a que la lógica implementada así lo requiere
- Varios usos de la misma cadena String en un mismo archivo. Se propone crear una variable global con el valor del string y hacer uso de dicha variable donde se requiera. Se debe tener en cuenta que estos Strings son textos de errores ("REGISTRAR_NOTA.ERROR.REGISTRANDO_NOTA") y URLS ("github.com/udistrital/polux_crud/controllers:AreaConocimientoController")
- Corregir estructura condicional debido a que se repite la lógica:
![Image](https://github.com/user-attachments/assets/c165237e-e409-451d-8ded-4f8e9ca87ac7)

Se modifica la lógica y se elimina la estructura, ejecutando así siempre la lógica que contenía el if y else:
![Image](https://github.com/user-attachments/assets/6c59468c-2144-4ca4-be99-c9dfddf23b28)

Este error se encontraba en 2 archivos, reporte_solicitud y reporte_general. Por lo que se corrige en ambos documentos:
![Image](https://github.com/user-attachments/assets/2f6f15dc-b933-42ba-bf77-3f68b964c99a)

- Agregar un _title_ a una etiqueta html:
![Image](https://github.com/user-attachments/assets/3fb8746e-509e-4c9e-b81b-80ab7bde1381)

Debido a que este documento hace parte del directorio del swagger y es un documento generado de forma automática, no se puede eliminar el error.

**Comment by JuanDHernandezA** [comment]
Se prueban los cambios realizados en los archivos _reporte_solicitud.go_ y _reporte_general.go_. Desde la vista de "generar reportes", ambos reportes se solicitan y generan de forma correcta, con lo cual los cambios para solucionar el error no afectaron a la funcionalidad del sistema.

Con las pruebas realizadas, se vuelve a ejecutar el Sonar para verificar la reducción en el número de Bugs en el CRUD:
![Image](https://github.com/user-attachments/assets/72f2b1a0-b96a-439c-8605-1c3da0be4df8)

En donde los errores de Code Smell que quedan son los relacionados a la reducción de complejidad y declaración múltiple del mismo valor de variable en los archivos autogenerados, por lo que la solución de los errores en el CRUD queda finalizada.

Adicional a esto, @diagutierrezro modificó el archivo de .gitignore del MID y CRUD para que el Sonarqube no tuviera en cuenta los errores dentro de los archivos autogenerados del Swagger. Con lo cual, el número de errores en el MID se reduce en gran cantidad:
![Image](https://github.com/user-attachments/assets/c290e4ab-7b0c-4227-82fe-9ac996de66d8)
