### ISSUE TITLE
Apoyar en actualización de documentación técnica que se presenta a funcionamiento.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#807]
Se requiere realizar el apoyo en la revisión y ajuste de la [documentación tecnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbJ-FyQnHu1IqMFJJg_1SpsBVO193db6c_rNPMBPD-tWkQ) que se presenta a funcionamiento con el fin de actualizar estos documentos con el funcionamiento actual del sistema ya que se han agregado diferentes funcionalidades como las notificaciones o ajustes en pasantias que deben quedar documentados.

Adicional a esto se deben crear dos diagrfamas, modular y procedimental los cuales fueron solicitados por funcionamiento, para esto se debe hablar con funcionamiento para recibir guía sobre como realizar estos diagramas.

**Sub Tareas**

- [x] Apoyar en la actualización de la documentación técnica.
- [x] Crear diagramas módular y procedimental.
- [x] Documentar ajustes realizados.

**Criterios de aceptación**

- [x] Apoyo en documentación tecnica realizado.
- [x] Diagramas creados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se inicia la actualización del documento técnico del sistema Polux. Se comienza con la actualización de los endpoints utilizados en el sistema, los cambios realizados fueron:

MID:
agregados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_mid/v1/tr_registrar_acta_seguimiento (post) 
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_mid/v1/tr_solicitud (post)

CRUD:
agregados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/estudiante_vinculacion_trabajo_grado (get)

eliminados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/tr_solicitud (post)
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/tr_registrar_acta_seguimiento (post) 

modificados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/tr_formato (-get-.post) 
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/trabajo_grado (get, post, _put_)
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/documento_tg (get, _post_)
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/areas_trabajo_grado (get, _post_)
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/documento_escrito (get, post, _put_)
https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/comentario (_get_, post) 

ACADEMICA:
se cambia a v2 todas las URLs

agregados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v2/consulta_carrera_condor/{codigo_carrera} (get) 
https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v2/obtener_asistente/{codigo_carrera} (get) 
https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v2/asistente_proyecto/{documento}  (get) 

GESTOR DOCUMENTAL:

agregados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/gestor_documental_mid/v1/document/uploadAnyFormat (post) 

NUXEO:
Se elimina del documento debido a que se eliminó su uso en el sistema de Polux

NOTIFICACIONES:

agregados:
https://autenticacion.portaloas.udistrital.edu.co/apioas/notificacion_mid/v1/email/enviar_templated_email (post)

**Comment by JuanDHernandezA** [comment]
Se actualizan las siguientes secciones del documento:
- Errores conocidos:
![Image](https://github.com/user-attachments/assets/e0a7e6e2-f3ad-4b0c-8389-5abdf46c7cb3)

- Roles:
![Image](https://github.com/user-attachments/assets/870945a7-4c48-4cf5-b964-33a80167af4c)

- Limitaciones (funcionalidades no contempladas en el MVP) :
![Image](https://github.com/user-attachments/assets/845b883b-3e83-4f71-9815-c08658429f9e)

**Comment by JuanDHernandezA** [comment]
Se coontinua con la actualización y realizan las correcciones y ajustes reportados por @diagutierrezro:

- En la sección de roles se agregan las vistas para el rol de EXTENSION_PASANTIA y se eliminan las vistas de Materias de Posgrado y Materias de Profundización:
![Image](https://github.com/user-attachments/assets/a6d71b2d-b3e9-4950-9806-7892b10213b4)

- Se agregan los siguientes endpoints utilizados en el MID y se indica cuales endpoints se usan en el Cliente y en el MID:

  - CRUD: 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/areas_trabajo_grado (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/asignatura_trabajo_grado (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/comentario (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/correccion (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/detalle_pasantia (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/detalle_solicitud (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/detalle_trabajo_grado (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/documento_escrito (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/documento_solicitud (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/documento_trabajo_grado (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/espacio_academico_inscrito (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/estudiante_trabajo_grado (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/evaluacion_trabajo_grado (get, post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/reporte_general (get) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/reporte_solicitud (get) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/respuesta_solicitud (post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/revision_trabajo_grado (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/solicitud_trabajo_grado (post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/trabajo_grado (get, post, put, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/usuario_solicitud (post, delete) 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/vinculacion_trabajo_grado (get, post, put, delete) 

   - PARAMETROS 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro (get) 

   - DOCUMENTOS 
     - https://autenticacion.portaloas.udistrital.edu.co/apioas/documento_crud/v2/tipo_documento (get) 

- Se agrega la limitación de que para realizar una modalidad de grado con otro estudiante, deben ser del mismo proyecto curricular

Con esto queda pendiente la revisión y posible corrección de los cambios realizados al documento técnico y la elaboración de los diagramas modular y procedimental
