### ISSUE TITLE
Ajustar transacción para modificar campo activo.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#808]
Se requiere realizar el ajuste en la transacción de aprobación de solicitudes para que cuando sea una solicitud de revisión se revise si ya existen anexos sobre ese trabajo de grado y dejarlos en false.

**Sub Tareas**

- [x] Ajustar transacción para modificar campos de activo.
- [x] Documentar issue con cambios realizados.

**Criterios de aceptación**

- [x] Ajuste de transacción realizado.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
El día 28/1072024, no se realizó avance debido a que tuve que realizar unas pruebas e informe de accesibilidad para la página de Obticud para PlanesTIC

**Comment by Astaroth-Andres-Molano** [comment]
Se modifica el modelo de documentoTrabajoGrado en API MID
![Image](https://github.com/user-attachments/assets/01f92f2a-f92a-4671-be1f-601012ccb9df)
Se crea consulta para que por medio de la tabla tipo_documento por código de abreviación se referencie el ID de los documentos anexos que a su vez son la referencia en la tabla documento_escrito

![Image](https://github.com/user-attachments/assets/45296f26-404d-42fa-becd-61160522cdfe)
Se crea consulta para obtener los anexos a desactivar
![Image](https://github.com/user-attachments/assets/816033f0-c7b7-4727-89dd-546129fddc7d)
Se desarrolla la consulta para actualizar el registro en documento_trabajo_grado y desactivar los anexos previos
![Image](https://github.com/user-attachments/assets/893dfb63-3dbb-413e-bd29-267f4154e73a)

**Comment by Astaroth-Andres-Molano** [comment]
Se procede a realizar pruebas, se inicia solicitud de revisión de proyecto de grado por parte del estudiante enviando 2 anexos
![Image](https://github.com/user-attachments/assets/6e7f790a-6232-468e-b965-ea57cb1381a6)
![Image](https://github.com/user-attachments/assets/1ac1f5b3-9a68-418e-bbb1-300c04a0ffc8)
Se realiza aprobación por parte del Docente Director
![Image](https://github.com/user-attachments/assets/9a990fd7-a438-4d2f-96e4-db32f1783707)
Aprobación por parte del coordinador que es el paso donde ahora queda funcionando la actualización a la tabla documento_trabajo_grado
![Image](https://github.com/user-attachments/assets/2349ede4-3dd0-49bd-a3cb-5cbca90f147f)
Se visualiza el registro en documento_trabajo_grado en base de datos
![Image](https://github.com/user-attachments/assets/719f20c8-943c-45f9-b67c-81ce0816c7b1)
Se realiza solicitud de correcciones por parte del Docente Evaluador donde se visualizan los 2 anexos
![Image](https://github.com/user-attachments/assets/6d8d91c0-285e-4c64-8bff-f8dabdef7892)
![Image](https://github.com/user-attachments/assets/cf4a5554-2edb-4337-abf3-096cc5a1b1ba)
Se vuelve a iniciar el cilo de solicitud de solicitd de trabajo de grado con 1 solo anexo, se visualiza la aprobación por el Coordinador
![Image](https://github.com/user-attachments/assets/159e77f6-afbe-4eed-bad6-e2871f7d2a99)
Se visualiza ahora el registro en documento_trabajo_grado donde se visualiza que los anteriores anexos fueron desactivados y queda registrado el nuevo
![Image](https://github.com/user-attachments/assets/7749e711-a41c-40a6-85fc-d6050e17b3f2)
Visualización de corrección por parte del Docente Evaluador donde se evidencia que llega 1 solo anexo, quedando así realizada la Issue
![Image](https://github.com/user-attachments/assets/03db5a1c-e850-4a9e-b82b-eda59be03768)
