### ISSUE TITLE
Creación de historias de usuario para espacios academico de profundización

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#811]
Se requiere realizar la Creación de formatos de historias de usuario para espacios academico de profundización

**Sub Tareas**

- [x] Creación del formato historias de usuario 
- [x] Socialización del formatos historias de usuario 
- [x] Aprobación del formato de historias de usuario

**Criterios de aceptación**

- [x] Formatos historias de usuario aprobados
- [x] Documentación de formatos historias de usuario para módulo reportes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han creado las historias de usuario , se compartían con el usuario
[Historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET0JZZqwj99PjlESZTKuGUEBkQ4Etn-n0gkTEk-nGsllUw?e=0jXwzf)

**Comment by jcmurilloa** [comment]
Muy buen trabajo, pendiente aprobaciín por parte del usuario.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/07dc703d-bc9a-4317-befc-f21704e36909)
 se ha agendado una sesión con el cliente atravez de computo y se enfatizo en poder dar permisos o saltar la cola 

![Image](https://github.com/user-attachments/assets/edce21cb-8848-41e9-a9f6-09a198f03207)
 pero aun así no se ha podido y la sesión se atraso por eso 

se han aprobado las historias de usuario , se hablara con el equipo sobre los cambios propuestos

![Image](https://github.com/user-attachments/assets/db79e380-1053-4959-b80a-12e72545d331)

**Comment by jcmurilloa** [comment]
Seguiremos insistiendo en esa necesidad @mantnicot sobre las sesiones, lo importantes es que se logró aprobar las HU con el cliente, buen trabajo. Pendiente acta.
