### ISSUE TITLE
Documentar el requerimiento según el analisis para la integración de Pólux con el RIUD

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#812]
Se requiere realizar la investigación relacionada con las notificaciones y sus posibles errores de implementación

**Sub Tareas**

- [x] Generar contacto con el responsable.
- [x] Adelantar la investigación.
- [x] Alimentar la documentación relacionada.

**Criterios de aceptación**

- [x] Documento con información relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se adjunta el documento para al definición del requerimiento de interoperabilidad de polux y riud 

[documento requerimiento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EVqGwHnOs1RCoDeYvcaxP8gBZluRHwF-AugCh4Cx8z94Zg?e=ZKH83p)

**Comment by jcmurilloa** [comment]
Documentación acorde a lo solicitado @mantnicot, buen trabajo!
