### ISSUE TITLE
Construir acta de entregable para las diferentes modalidades de Pólux

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#813]
Se requiere realizar la proyección del acta de entregables para las diferentes modalidades de Pólux

**Sub Tareas**

- [x] Recopilar la información técnica de cada modalidad
- [x] Construir el acta de entregables del sistema
- [x] Exponer acta de entregables a funcionamiento

**Criterios de aceptación**

- [x] Acta de entregables documentada
- [x] Acta de entregables aprobada por funcionamiento

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha creado una base para el acta de entregable
[acta de entregable](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/caescorciab_udistrital_edu_co/ERuMIvNqwOhDplApSKodijUBnS1owh_IzlMFXugjUZ_0SA?e=JyAWjQ)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, revisaremos el acta en el próximo review.
