### ISSUE TITLE
Generar el despliegue de los diferentes ajustes realizados del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#814]
Se requiere realizar el despliegue a producción de diferentes actualizaciones realizadas en el sistema con base a los diferentes requerimientos realizados

**Sub Tareas**

- [x] Revisar las actualizaciones pendientes por desplegar
- [x] Revisar las BD y solicitar ajustes necesarios
- [x] Solicitar creación de End Points en producción
- [x] Generar los despliegues de cada actualización

**Criterios de aceptación**

- [x] EndPontis creados
- [x] Actualización de ajustes en producción

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Está refinada y estimada en puntos de historia por el equipo.
- [X] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] Las dependencias están identificadas y resueltas.
- [X] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Al momento de solicitar los cambios en DB para desplegar en producción se pidió por parte de los DBA una reunión para socializar los cambios hacia producción y aprobar los mismos, la reunión se pudo realizar el dia viernes 15 de noviembre, se aprobaron los cambios.
