### ISSUE TITLE
Iniciar ajustes de solicitud inicial para materias de profundización.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#815]
Se requiere realizar el ajuste para la vista de la solicitud inicial que realiza el estudiante basandose en los mockups que se encuentran en el issue #755 se puede usar como guia el issue #793 donde se realiza el ajuste inicial a la solicitud inicial para materias de posgrado ya que al vista es practicamente la misma. Tener presente que se deben realizar cambios en los detalles en la base de datos. Importante ir documentando los cambios realizados en el issue #584 

**Dependencias** 
Por parte de @diagutierrezro se debe solicitar modificación del usuario pruebasoaspolux3 para que ahora sea un estudiante de un programa académico de la facultad tecnológica.

**Sub Tareas**

- [x] Ajustar formulario de solicitud inicial.
- [x] Documentar cambios realizados en la base de datos en el issue indicado.
- [x] Realizar pruebas de funcionamiento.
- [x] Documentar issue con ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Formulario ajustado.
- [x] Documentación de cambios en db realizada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se analiza que la modalidad de Espacios Académicos  de Profundización es la 4603 y que el tipo de solicitud es 4634, se deduce que la modalidad_tipo_solicitud es el 16, llego a la tabla academica.detalle_tipo_solicitud para solicitud inicial de modalidad de Espacios Académicos  de Profundización y se actualiza el orden de añgunos detalles, utilizando los comandos:

UPDATE academica.detalle_tipo_solicitud
	SET activo=false, numero_orden=11
	WHERE id=176;

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=1
	WHERE id=45;
UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=6
	WHERE id=44;
Se realiza el insert de los siguientes registros para agregar detalles:
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (93, 16, true, true, 2);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (94, 16, true, true, 3);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (95, 16, true, true, 4);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (96, 16, true, true, 5);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (80, 16, true, true, 7);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (81, 16, true, true, 8);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (8, 16, true, true, 9);

INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (75, 16, true, true, 10);

![Image](https://github.com/user-attachments/assets/dcf12365-94e2-4402-8f2d-d1310ce45e3d)

A continuación se visualiza el formulario de solicitud inicial de Espacios Académicos  de Profundización:

![Image](https://github.com/user-attachments/assets/6a3910de-44f7-4ff7-a20b-fb9e9171abaf)
![Image](https://github.com/user-attachments/assets/05840ead-bd88-48d3-97b5-5c5585aeebd1)

Se encuentra que no traduce el texto de Aceptar Términos y Condiciones
![Image](https://github.com/user-attachments/assets/aed797ea-0ae8-4cb7-b38c-45956093247a)

Se realizan ajustes en crear_solicitud.js y text_translate.js

![Image](https://github.com/user-attachments/assets/5a47b6b9-b89d-4a66-960e-d23d0dd408e8)
![Image](https://github.com/user-attachments/assets/d6655c3c-33e8-4cb3-a6bb-bbfd8ef895e8)

Se visualiza el formulario con la corrección
![Image](https://github.com/user-attachments/assets/f0ff1568-7879-4780-85da-73803c99c512)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes para que funcione correctamente el envío de esta solicitud inicial:
![Image](https://github.com/user-attachments/assets/5fc3af69-4c1e-4a3e-a118-629dabaf9a3e)
Solicitud realizada con éxito:
![Image](https://github.com/user-attachments/assets/1db08295-cee6-42df-a220-6f51e643da22)

**Comment by diagutierrezro** [comment]
@Astaroth-Andres-Molano Por favor documeta los cambios hechos en bases de datos en el issue de #584
