### ISSUE TITLE
Brindar apoyo en despliegue a producción de nuevas funcionalidades desarrolladas.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#817]
Se requiere realizar diferentes tareas con el fin de brindar apoyo a @diagutierrezro en el despliegue a producción de las nuevas funcionalidades que se han desarrollado y que aún no se encuentran en producción como son las notificaciones, cargue de anexos, envío de información personal para ARL. Este apoyo puede incluir principalmente revisión de bases de datos y scripts realizados para minimizar al máximo la cantidad de errores que se puedan presentar durante el despliegue de estas funcionalidades.

**Sub Tareas**

- [x] Servir de apoyo en el despliegue a producción de nuevas funcionalidades.
- [x] Revisar despliegues realizados.
- [x] Revisar cambios en bases de datos.
- [x] Documentar issue con las diferentes tareas que se requieran.

**Criterios de aceptación**

- [x] Apoyo realizado.
- [x] Revisiones realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realiza el análisis y revisión del PR del Cliente para subir a producción, en donde se encontraron los siguientes cambios a realizar:

- Se deben actualizar las siguientes vistas y roles en la página de Configuración:
  - Se debe crear el rol de COORDINADOR y agregar sus respectivas vistas
  - Se debe crear el menú de "Reportes" y agregar esta vista a los roles de COORDINADOR Y CONTRATISTA
  - Desde el Rol de EXTENSION_PASANTIAS se debe agregar la vista de "Trabajo de Grado > Consultar"
- Se debe verificar si el endpoint en el API Autenticacion_mid _token/documentoToken_ se encuentra en producción
- Se debe verificar si el endpoint en el API de Notificaciones_mid _email/enviar_templated_email_ se encuentra en producción, así mismo todas las plantillas creadas de las notificaciones
- Al verificar el código de tipo de documento "ANX_PLX" se observa que no tiene un workspace propio creado y asociado en la base de datos
- Se verificaron los siguientes endpoints de JBPM y en qué servicios se encuentran disponibles: 
  - **consulta_carrera_condor**: academica_pruebas, servicios_academicos, servicios_academicos_produccion
  - **obtener_asistente**: academica_pruebas
  - **asistente_proyecto**: hay similares en academica_pruebas y servicios_academicos_produccion

**Comment by JuanDHernandezA** [comment]
Se realizaron los siguientes scipts para la sincrinización con la base de datos de producción:

alter table's:
- documento_trabajo_grado:
```bash
ALTER TABLE academica.documento_trabajo_grado 
ADD COLUMN activo boolean,
ADD COLUMN fecha_creacion timestamp.
ADD COLUMN fecha_modificacion timestamp
```

- solicitud_trabajo_grado:
```bash
ALTER TABLE academica.solicitud_trabajo_grado
ADD COLUMN datos_personales_arl json
```

inserts:

- academica - Detalle:
```bash
INSERT INTO academica.detalle(nombre, enunciado, descripcion, codigo_abreviacion, activo, tipo_detalle)
VALUES ("Sábana de Notas","SABANA_NOTAS","no_service","SN",true,4645),
("Carta de Aceptación de Inscripción","CARTA_ACEPTACION_INSCRIPCION","no_service","CAI",true,4645),
("Justificación","JUSTIFICACION","no_service","JUST",true,4645),
("Solicitud Escrita de las Materias","SOLICITUD_MATERIAS","no_service","SEM",true,4645),
("Prioridad Espacio Academico","PRIORIDAD_ESPACIOS_ACADEMICOS","prioridad-espacios-academicos","PEAP",true,4648),
("Espacios academicos 2","SELECCIONE_ESPACIOS_ACADEMICOS_2","solicitar-asignaturas-2","ESPELE2",true,4649);
```
- academica - Detalle tipo solicitud:
```bash
INSERT INTO academica.detalle_tipo_solicitud(
	detalle, modalidad_tipo_solicitud, activo, requerido, numero_orden)
	VALUES (77, 66, true, true, 5),
	(78, 66, true, true, 6),
	(77, 67, true, true, 5),
	(78, 67, true, true, 6),
	(77, 68, true, true, 5),
	(78, 68, true, true, 6),
	(77, 69, true, true, 9),
	(78, 69, true, true, 10);

UPDATE academica.detalle_tipo_solicitud
	SET numero_orden=8
	WHERE id =338;
```

- documento - tipo documento:
```bash
INSERT INTO documento.tipo_documento(
	nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, workspace, tipo_documento_nuxeo, fecha_creacion, fecha_modificacion, dominio_tipo_documento)
	VALUES ("Anexos", "Anexos asociados a las revisiones de trabajo de grado", "ANX_PLX", true, 1.00, 5, "pdf", /default-domain/workspaces/oas/oas_app/polux/documento_revision, "file", NOW(), NOW(), 9);
```
