### ISSUE TITLE
Realizar ajustes para producción

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#819]
Se requiere realizar revisión de casos de soporte que surjan en ambiente de producción. A la fecha de la creación del issue se tiene un error en el que el asistente de Ing industrital no puede visualizar las solicitudes, tambien se mencionó que el docente no pudo visualizar y aprobar la solicitud por varios intentos.

**Sub Tareas**

- [x] Analizar casos de soporte.
- [x] Realizar ajustes si es necesario para solucionar los errores.
- [x] Documentar problemas encontrados y ajustes realizados.

**Criterios de aceptación**

- [x] Análisis de casos realizado.
- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realiza el análisis del fallo al momento de listar las solicitudes por parte del Asistente de Coordinación del proyecto de Ingeniería Industrial.

Se hace la consulta para verificar que el usuario sea el Asistente del proyecto curricular de Ing Industrial usando su documento en el endpoint de JBPM _asistente_proyecto_. La consulta retorna que el usuario si corresponde al cargo mencionado:
![Image](https://github.com/user-attachments/assets/becd5c15-afd8-43d3-916d-79cd6af0efd0)

Revisando el mensaje de advertencia que se muestra al momento en que el usuario ingresa al menú de Listar Solicitudes, se observa que muestra 2 mensajes: Error porque el estudiante no ha realizado una solicitud; y error porque el coordinador no tiene solicitudes pendientes. También, se observa que el Asistente tiene acceso al menú Revisión de Documentos, lo cual para el rol de Coordinador y Constratista no debería ocurrir:
![Image](https://github.com/user-attachments/assets/f12f7766-106d-4669-8904-50e62bba0625)

Por estos errores, se realiza una consulta al endpoint de Autenticación _userRol_ para verificar los roles que tiene el usuario. Se observa que adicional al rol de CONTRATISTA, el usuario tiene el rol de ESTUDIANTE:
![Image](https://github.com/user-attachments/assets/22d0d0b1-8e25-467b-ae35-67c6a5b10a8b)

Se solicita que se realice el cambio/eliminación de los roles del usuario para poder acceder al sistema.

**Comment by diagutierrezro** [comment]
Se da respuesta a la [tarea ](https://iris.portaloas.udistrital.edu.co/scp/tasks.php?id=14560), se ajusta el cliente para que ahora realice validación si es un estudiante activo al momento de realizar el listado de solicitudes. Este error ocurrió porque era un contratista que previamente fue estudiante.

**Comment by diagutierrezro** [comment]
Sobre la [tarea](https://iris.portaloas.udistrital.edu.co/scp/tasks.php?id=14619) aparentemente es un error de la estudiante quien está intentando agregarse nuevamente a la lista de estudiante que van a participar del trabajo de grado. Se dió respuesta a la solicitud indicando esto, sin embargo, se debe realizar validación con la estudiante para asegurarse de que esto si es así.
