### ISSUE TITLE
Realizar presentación de modalidades faltantes, reportes y notificaciones a funcionamiento

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#828]
Se requiere realizar una presentación a funcionamiento donde se muestren las modalidades faltantes por presentar, estas son monografía, artículo académico, investigación y emprendimiento, adicional se deben mostrar los desarrollos de reportes y notificaciones.

**Sub Tareas**

- [x] Realizar presentación a funcionamiento.
- [x] Documentar issue con link de grabación.

**Criterios de aceptación**

- [x] Presentación realizada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se realizó la presentación a Funcionamiento en donde se mostró el desarrollo y funcionalidad de las modalidades de: Monografía, Investigación, Emprendimiento y Artículo Académico; así como la funcionalidad de Notificaciones y Reportes.

Se adjunta el link de la grabación de la reunión:

[Link grabación](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/computo_udistrital_edu_co/Documents/Grabaciones/Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n%20de%20Polux%20-%20Muestra%20modalidades%20funcionamiento-20241112_100738.mp4?csf=1&web=1&e=CNbbjB&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
