### ISSUE TITLE
Realizar aprobación por parte de coordinadores de POSGRADO

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#830]
Se requiere realizar la aprobación por parte de los coordinadores de POSGRADO, es importante tener en cuenta que cuando se da respuesta la solicitud queda en dos estados diferentes según el número de opción que sea y tambien se debe tener en cuenta si la respuesta es aprobado o rechazado ya que según estos estados es que se maneja la transacción mas adelante.

Comparar la transacción actual del mid con la que se tenía antes en el crud para verificar que ya ha sido migrada correctamente o si aún falta por hacer ajustes ya que esta funcionalidad no se probó cuando se estuvo haciendo dicha migración.

**Sub Tareas**

- [x] Revisar transacción tr_aprobar_solicitud para comprobar que se encuentra migrada desde el CRUD de manera correcta.
- [x] Realizar ajustes necesario para estabilizar la funcionalidad de aprobar solicitudes por parte del coordinador de posgrado.
- [x] Validar que una vez dan respuesta los dos la petición retorna correctamente al estudiante dando la respuesta oportuna.

**Criterios de aceptación**

- [x] Transacción revisada y ajustada.
- [x] Ajustes realizados.
- [x] Validación de respuesta realizada y/o ajustada.
- [x] Documentación de issue realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Error coordinador
![Image](https://github.com/user-attachments/assets/0726ea53-a077-43ae-83a8-cf5cecbd5de6)
![Image](https://github.com/user-attachments/assets/67beb454-cd7a-4ff2-bff8-d3eeb32f9c26)
![Image](https://github.com/user-attachments/assets/98c273ff-fc84-41b0-8e5b-fea3992de885)

Encontramos el error por consulta de solicitud_trabajo_grado id 1979
![Image](https://github.com/user-attachments/assets/d829a747-d8be-42d2-b3a4-01c0445fae29)
No trae usuario, se eliminó registro de db

Errordetalle duplicado

![Image](https://github.com/user-attachments/assets/d21b8b2f-7c2c-4346-987e-0d0bcbf635d2)
Corrección

![Image](https://github.com/user-attachments/assets/06a4b9c4-0791-46fe-a473-c88af44cf7ce)
vista detalle duplicado corregido
![Image](https://github.com/user-attachments/assets/13b051ef-9541-4871-95a9-79d7ac7dbb0d)

**Comment by CrisEs2506** [comment]
Adicionalmente surgieron otros errores:

1. Al rechazar la solicitud por parte del coordinador de posgrado, se está asignando de manera incorrecta el parametro, ya que se está colocando en estado solicitud el código 4611 que es "Rechazado por Consejo de Carrera" y debe ser 4655 "Rechazada Coordinador Posgrado Opción 1".

**Comment by CrisEs2506** [comment]
```JSON
{
    {
    "RespuestaAnterior": {
        "Id": 3931,
        "Fecha": "2024-11-11T07:24:00.348-05:00",
        "Justificacion": "Aprobación Posgrado",
        "EnteResponsable": 0,
        "Usuario": 79702248,
        "EstadoSolicitud": 4631,
        "SolicitudTrabajoGrado": {
            "Id": 2006,
            "Fecha": "2024-11-14T05:22:50.945-05:00",
            "ModalidadTipoSolicitud": {
                "Id": 13,
                "TipoSolicitud": 4634,
                "Modalidad": 4602
            },
            "TrabajoGrado": {
                "Id": 0
            },
            "PeriodoAcademico": "2024-3",
            "DatosPersonalesArl": "{\"ciudadNacimiento\":\"\",\"correoPersonal\":\"\",\"direccionResidencia\":\"\",\"eps\":\"\",\"fechaNacimiento\":\"\",\"pasantiaInterna\":false,\"telefono\":\"\"}"
        },
        "Activo": false
    },
    "RespuestaNueva": {
        "Id": null,
        "Fecha": "2024-11-15T17:53:54.716Z",
        "Justificacion": "Aprobado.",
        "EnteResponsable": 0,
        "Usuario": 52204982,
        "Activo": true,
        "EstadoSolicitud": 4654,
        "SolicitudTrabajoGrado": {
            "Id": 2006
        }
    },
    "DocumentoSolicitud": {
        "DocumentoEscrito": {
            "Id": 458
        },
        "SolicitudTrabajoGrado": {
            "Id": 2006
        }
    },
    "TipoSolicitud": {
        "Id": 4634
    },
    "Vinculaciones": null,
    "EstudianteTrabajoGrado": null,
    "VinculacionesCancelacion": null,
    "TrTrabajoGrado": {
        "TrabajoGrado": {
            "Titulo": "Espacios Académicos de Posgrado",
            "Modalidad": 4602,
            "EstadoTrabajoGrado": 4570,
            "DistincionTrabajoGrado": null,
            "PeriodoAcademico": "2024-3"
        },
        "EstudianteTrabajoGrado": [
            {
                "TrabajoGrado": {
                    "Id": 0
                },
                "EstadoEstudianteTrabajoGrado": 4648
            }
        ],
        "DocumentoEscrito": null,
        "DocumentoTrabajoGrado": null,
        "AreasTrabajoGrado": null,
        "VinculacionTrabajoGrado": [
            {
                "Usuario": 52204982,
                "Activo": true,
                "FechaInicio": "",
                "FechaFin": "",
                "RolTrabajoGrado": 4597,
                "TrabajoGrado": {
                    "Id": 0
                }
            }
        ],
        "AsignaturasTrabajoGrado": [
            {
                "CodigoAsignatura": 1,
                "Periodo": 3,
                "Anio": 2024,
                "Calificacion": 0,
                "TrabajoGrado": {
                    "Id": 0
                },
                "EstadoAsignaturaTrabajoGrado": 4658
            },
            {
                "CodigoAsignatura": 2,
                "Periodo": 3,
                "Anio": 2024,
                "Calificacion": 0,
                "TrabajoGrado": {
                    "Id": 0
                },
                "EstadoAsignaturaTrabajoGrado": 4658
            }
        ]
    },
    "ModalidadTipoSolicitud": {
        "Id": 13,
        "TipoSolicitud": 4634,
        "Modalidad": 4602
    },
    "TrabajoGrado": null,
    "SolicitudTrabajoGrado": {
        "Id": 2006,
        "Fecha": "2024-11-14T05:22:50.945-05:00",
        "ModalidadTipoSolicitud": {
            "Id": 13,
            "TipoSolicitud": 4634,
            "Modalidad": 4602
        },
        "TrabajoGrado": {
            "Id": 0
        },
        "PeriodoAcademico": "2024-3",
        "DatosPersonalesArl": "{\"ciudadNacimiento\":\"\",\"correoPersonal\":\"\",\"direccionResidencia\":\"\",\"eps\":\"\",\"fechaNacimiento\":\"\",\"pasantiaInterna\":false,\"telefono\":\"\"}"
    },
    "EspaciosAcademicos": null,
    "DetallesPasantia": null,
    "TrRevision": null,
    "EspaciosAcademicosInscritos": []
}
```

![image](https://github.com/user-attachments/assets/013550c2-ada0-48b2-ab14-3f7cd59d6283)
