### ISSUE TITLE
Construir diagrama modular y de procesos del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#832]
Se requiere realizar la construcción de los diagramas modulares y de procesis del sistema como complemento de la documentación técnica.

**Sub Tareas**

- [x] Revisar la inmersión del requerimiento según los siguientes enlaces: https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/ES7a6FEo7gFIvQXkuLrLJp8BwC2OkgrCL7OTdsrHmTVPfQ?e=lpuvxv, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/Ef8JZ-s9FXJBkRFKbsLcR2EBWG2yk5hAQ_qt7x0dcUo_sA?e=q9rxnW
- [x] Articular con líder técnico la información necesaria.
- [x] Proyectar los diagramas modulares y de procesos para equipo SoS.

**Criterios de aceptación**

- [x] Diagramas aprobados por equipo SoS
- [x] Diagramas referenciados en carpeta Documentación técnica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado un primer diseño del diagrama

![Image](https://github.com/user-attachments/assets/559a2d5e-8dca-4ce5-af67-adc30c1bcf5d)

[carpeta de diagrama](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoNWIxmTUBdKlcdHHmjHeukBrF_tnQ61Wfi2ZDhrd3cttQ?e=bThe3u)

**Comment by jcmurilloa** [comment]
Muy buen avance @mantnicot, queda pendiente diagrama de procesos.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/77178b18-f11e-4aec-868b-707284c3e1ae)

[Carpeta de diagrama procesos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvlENc6gro9HhdSV6O6DNQgBmrjwoQ4x-sTCj73RjDVOqw?e=VW6cZY)

**Comment by jcmurilloa** [comment]
Buenos diagramas @mantnicot, incluiremos estos diseños en la respectiva documentación, con el ánimo de su respectiva revisión y aprobación por parte de funcionamiento.
