### ISSUE TITLE
Definir la implementación de Pólux para la facultad tecnológica

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#833]
Se requiere realizar la investigación para la definición de la implementación de Pólux para ka facultad tecnológica.

**Sub Tareas**

- [x] Concertar con el cliente requerimientos para el uso de pólux. 
- [x] Definir la ruta para la implementación del sistema.
- [x] Exponer los resultados al equipo SoS.

**Criterios de aceptación**

- [x] Ruta definida para el uso de Pólux por parte de la facultad tecnológica.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/b582e4bf-2596-41a0-aeb1-d6ba8ebd6244)


La deifnición de ruta se hara de la siguiente manera : 

* Prueba del sistema en ambiente de pruebas con una asistente de la facultad
* En caso de haber comentarios , realizar las mejores
* Aprobación y entrega de Polux en la facultad 
* Divulgación y soporte

**Comment by jcmurilloa** [comment]
Por favor documentar la ruta de implementación en nuestros lineamientos.
