### ISSUE TITLE
Revisar opciones para generar diagrama E/R

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#838]
Se requiere realizar la revisión de opciones para generar el diagrama E/R con las modificaciones que se le han hecho a la base de datos con el fin de que desde el equipo de DBA se permita la modificación de la misma en ambiente de producción.

**Sub Tareas**

- [x] Revisar opciones para la generación de diagramas.
- [x] Generar diagrama E/R de la base de datos de Pólux en ambiente de pruebas.

**Criterios de aceptación**

- [x] Revisión de opciones realizada.
- [x] Diagrama E/R generado.
- [x] Issue documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se revisa el manual de instalación de pgmodeler en el repositorio de lineamientos de la OAS, pero se presentaron varios errores durante la instalación que no fue posible usar esta aplicación.

Se revisa y desde pgAdmin de PostgreSQL se puede generar el diagrama Entidad-Relación de la base de datos del esquema de académica. Se genera el diagrama:
![Image](https://github.com/user-attachments/assets/7e17fce6-5b89-421f-97ba-56691c3a4a36)

Pero contiene tablas que no se utilizan, por lo que se realizan modificaciones al diagrama:

- Se eliminan las tablas paramétricas y/o sin relación del diagrama y se analizan las tablas que no se usan o contienen información antigua:

- Estas tablas están relacionadas con otras tablas que si se utilizan:
  - areas_conocimiento (se usa en areas_docente y areas_trabajo_grado pero no está asociado en la BD)
  - areas_docente
  - distincion_trabajo_grado (se usa en trabajo_grado)
  - socializacion(se usa en evaluacion_trabajo_grado)

- Las siguientes tablas no tienen relación con ninguna tabla importante, por lo que se eliminan del diagrama generado:
  - documento_entidad
  - estructura_investigacion_trabajo_grado
  - formato
  - formato_evaluacion_carrera
  - pregunta_formato
  - pregunta
  - tipo_pregunta
  - respuesta
  - respuesta_evaluacion
  - respuesta_formato
  - modalidad
  - solicitud_soporte_plan_trabajo
  - estado_soporte_plan_trabajo

- Las siguientes tablas están asociadas a las modalidades de Materias de Posgrado y Materias de Profundización, por lo que se debe investigar si se utilizarán o no:
  - carrera_elegible
  - espacio_academico_inscrito
  - espacios_academicos_elegibles

Dando como resultado el siguiente diagrama:
![Image](https://github.com/user-attachments/assets/8eaf3348-af58-42da-a078-42dd68e53d94)

Aún queda pendiente revisar y realizar los cambios mencionados.

**Comment by JuanDHernandezA** [comment]
Se consulta sobre las siguientes tablas si se pueden eliminar o se conservan en el diagrama ER y se indica que se deben eliminar del diagrama:

- areas_conocimiento
- areas_docente
- distincion_trabajo_grado
- socializacion
- carrera_elegible
- espacio_academico_inscrito
- espacios_academicos_elegibles

Por lo que el diagrama resultante es:
![Image](https://github.com/user-attachments/assets/ebf2cb37-b68a-4b31-9f54-474dd9538ccb)

Adicional se adjunta el archivo .pgerd para modificaciones desde pgAdmin junto con la imagen .png:

[Diagrama ER Polux](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/ajuanh_udistrital_edu_co/Ek4saHgT9pBOk3PsEyASH3sB11DtGR5Qphg5TVH9eo6JOQ?e=zyGMTR)
