### ISSUE TITLE
Despliegue del sistema en ambiente de pruebas

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/polux_cliente#84]
Realizar los ajustes necesarios para el despliegue del sistema en pruebas.

**Comment by ddguerra90** [comment]
Junto a @JuanCamiloMartinezLopez  se realiza un cambio en la libreria uglify que impedia construir la aplicación al ejecutar el comando grunt build

![image](https://user-images.githubusercontent.com/31446845/104744259-a8576c80-571a-11eb-95ff-d5242b2193e6.png)

**Comment by JuanCamiloMartinezLopez** [comment]
Se crea la carpeta environment en **app/scripts/environment**, donde se crean los archivos **envirionment.js**, **environment_test.js**,  **environment_prod.js**. Necesarios para el manejo de las variables en los diferentes entornos.
https://github.com/udistrital/polux_cliente/commit/419d089076d2fe1d3d0cbe26a60700fc0a97dca7

**Comment by ddguerra90** [comment]
El sistema de encuentra actualmente desplegado en preproducción en el siguiente enlace 
http://pruebaspolux.portaloas.udistrital.edu.co/
