### ISSUE TITLE
Realizar ajustes en envío de JSON al realizar el flujo de aprobación.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#840]
Se requiere realizar el ajuste al JSON que se envía al momento de aprobar la solicitud según los comentarios realizadon en issues anteriores, revisar información de areas de conocimiento, documentos agregados en la solicitud, revisar estado del trabajo de grado y realizar pruebas y ajustes con diferentes coordinadores.

**Sub Tareas**

- [x] Revisar información enviada en el JSON para manejo correcto de información.
- [x] Realizar ajustes necesarios para estabilizar el envío y aprobación de solicitudes.
- [x] Documentar ajustes realizados.

**Criterios de aceptación**

- [x] Información revisada.
- [x] Ajustes realizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Revisar información enviada en el JSON para manejo correcto de información.**

1. Se ha logrado que se envié el documento del estudiante que realizó la solicitud al momento de aprobar por parte del coordinador tanto de pregrado como de posgrado:

<img width="480" alt="image" src="https://github.com/user-attachments/assets/96007cdb-0c4d-408a-8589-4fa043be1164">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/6bf73442-9736-429f-ad42-a1c29c8fe92b">

**Comment by CrisEs2506** [comment]
Flujo de Materias de Posgrado desde el Cliente y la Base de Datos:

**Solicitud Inicial**

Se crea la solicitud inicial por parte del estudiante:



1. Los detalles_solicitud al crear un estudiante la solicitud inicial son los siguientes:

![image](https://github.com/user-attachments/assets/ac9e78f1-1ce3-481a-80e2-52481d9c4a69)

2. En la tabla solicitud_trabajo_grado se crea un nuevo registro con la modalidad_tipo_solicitud con Id 13, que corresponde a una Solicitud Inicial de la modalidad Materias de Posgrado:

![image](https://github.com/user-attachments/assets/96f8a3c2-8642-4cd8-9f83-e926281e6733)

3. Se crea un nuevo registro en la tabla usuario_solicitud asociando el código del estudiante con la solicitud_trabajo_grado:

![image](https://github.com/user-attachments/assets/a39d01c6-64e8-4ba2-b68e-e095dd0b8cb1)

4. En respuesta_solicitud se crea un nuevo registro asociando la solicitud_trabajo_grado con el Id de estado_solicitud en 4610 que significa que la solicitud fue radicada y queda pendiente por aprobación del consejo de carrera (Coordinador de Pregrado):

![image](https://github.com/user-attachments/assets/558cec03-d98c-43cb-a974-a09b3fc5b3d6)

--- 

La solicitud inicial creada por el estudiante llega a la Coordinación de Pregrado y es aprobada correctamente:

![image](https://github.com/user-attachments/assets/fe7abadb-e6bb-4b1e-8310-dc8641c53e18)

![image](https://github.com/user-attachments/assets/dcaa07ca-7adc-4da5-828d-5e052a79bdb9)

![image](https://github.com/user-attachments/assets/56e0390c-166b-496a-9d24-bfb5961e3781)
![image](https://github.com/user-attachments/assets/8b9dd99d-f9eb-45fd-bd14-75cad93ad0d4)

<img width="254" alt="image" src="https://github.com/user-attachments/assets/6e7bfbaf-723d-4733-806c-d3ea7cb85a38">

5.

**Comment by CrisEs2506** [comment]
**Bug's:**

1. Cuando no se escoge un segundo proyecto curricular se está enviando un JSON vacío y esto está haciendo que el sistema detecte como si en verdad hubiera uno segundo, por lo que hay que arreglar este inconveniente desde el JSON que se envía en la solicitud inicial:

<img width="461" alt="image" src="https://github.com/user-attachments/assets/1ebeeed6-263d-4fa9-8a75-3c7b6cc3f189">

**Comment by Astaroth-Andres-Molano** [comment]
En el controlador crear_solicitud.js se genera un nuevo atributo en el campo descripción de los detalles que recogen los datos de las opciones de posgrado que elige el estudiante, este atributo "opcion" puede tener 2 valores (1 o 2) para ser usados como herramienta para la lógica que resolverá la función de aprobar solicitud por parte de los coordinadores de posgrado.

Ajustes en controlador crear_solicitud.js
![Image](https://github.com/user-attachments/assets/94c91c9c-cff6-480b-a76c-0e66add7a154)
Se realiza solicitud de modalidad de espacios academicos de posgrado para revisar que esté registrando el nuevo atributo
![Image](https://github.com/user-attachments/assets/801467ea-28c1-4001-9392-f6b2b9201756)
Visualización del Payload donde el JSON está parseado a String y se ve el dato "opcion"
![Image](https://github.com/user-attachments/assets/897f9132-95b7-4ce7-9d7b-89bfb94366c8)
Visualización del registro de los detalles en mención en la base de datos
![Image](https://github.com/user-attachments/assets/8c64d864-106c-458c-b25d-d36d21f0d4a3)
