### ISSUE TITLE
Agregar código de abreviación al crear registro en tabla vinculacion_trabajo_grado

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#841]
Se requiere realizar los ajustes necesarios para que se agregue el código de abreviación al momento de crear registros nuevos en la tabla vinculacion_trabajo_grado para que dicho código coincida con el id que se obtiene de parametros, esto es para los reportes generados por el sistema.

**Sub Tareas**

- [x] Realizar ajustes al momento de realizar registros nuevos en vinculacion_trabajo_grado.
- [x] Realizar pruebas de funcionamiento correcto de los cambios realizados.
- [x] Documentar issue con ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Inicialmente, se busca las solicitudes y/o funcionalidades en donde se requiera insertar en dato de código de abreviación en la tabla vinculado_trabajo_grado. Se observa que se usa en las solicitudes de Solicitud Inicial, Solicitud cambio de Director, Evaluador y Codirector.

Se verifica si al momento del aprobar una Solicitud Inicial desde la coordinación en el Payload se envía algún dato asociado al código de abreviación de los vinculados, se observa que no se envía ningún dato, ni siquiera en nulo asociado al código de abreviación:
![Image](https://github.com/user-attachments/assets/a970535d-a077-49f4-8f8e-f812a9d168d9)

Se modifica la información que se envía en la solicitud inicial, adjuntando el código de abreviación del vinculado:
![Image](https://github.com/user-attachments/assets/d6c1ab82-a3c6-487a-bba9-c7f0d88f432e)

Adicional a esto, se modifican los Modelos en las APIs MID y CRUD para que no genere conflicto al momento de recibir esta nueva "columna":
- MID:
![Image](https://github.com/user-attachments/assets/8032fa0a-60ac-49b6-90f1-69e2a3ecc9f6)

- CRUD:
![Image](https://github.com/user-attachments/assets/730a00ce-36e4-464e-84e8-5a75c5264d3d)

Se verifica que el código de abreviación haya quedado registrado en la base de datos, lo cual es correcto:
![Image](https://github.com/user-attachments/assets/41e220e6-6033-4c07-8f61-b334425c0ea0)

Los cambios realizados en el cliente únicamente sirven para los roles de Docente Director, Evaluador y Codirector para las modalidades de Pasantía, Monografía, Proyecto de emprendimiento, Creación e Interpretación, Producción académica.

Se realizan los mismos cambios durante la aprobación de la Solicitud Inicial para el rol de Director Externo en la modalidad de Pasantía y para el rol de Coordinador Posgrado en la modalidad de Materias de Posgrado

**Comment by JuanDHernandezA** [comment]
Se prueba que los cambios realizados funcionen también al momento de solicitar cambio de Docente Director, Codirector y Evaluador y se almacene el código de abreviación correspondiente, lo cual es correcto:
![Image](https://github.com/user-attachments/assets/c57d3321-2885-4f68-9a59-3ce960b74485)

Ahora, se prueba la funcionalidad para la modalidad de Pasantía. Primero se prueba que al momento en que la coordinación aprueba la Solicitud Inicial, se almacene al vinculado con su código de abreviación asociado:
![Image](https://github.com/user-attachments/assets/f169c6c1-e82e-42b7-8f59-f238096ae0b3)

Ahora, se prueba que se registre el código al momento de aprobar el cambio de Director Externo. Este arroja un error asociado al momento de actualizar el registro en la tabla documento_trabajo_grado, en donde los datos de Fecha_inicio están vacios al momento de recuperarlos:
![Image](https://github.com/user-attachments/assets/f0353c50-23ec-49fa-9b1a-9a9ab4367a68)

Esto se debe a los cambios realizados en la tabla documento_trabajo_grado en donde se agregaron los campos paramétricos, pero la lógica para subir y actualizar la Hoja de Vida del Director Externo aún no tenía estos cambios. Se actualiza dicha lógica:
![Image](https://github.com/user-attachments/assets/a6619d23-9cf2-4e07-8f0c-fed76191f58f)

Con esto, al momento en que el Coordinador aprueba la Solicitud de Cambio de Director Externo, se actualiza correctamente la tabla de vinculado_trabajo_grado con su respectivo Código de Abreviación:
![Image](https://github.com/user-attachments/assets/6b01061f-8243-4233-b5e8-b7940ecb8ca9)

Con esto, ya queda actualizada la funcionalidad para almacenar el código de abreviación de los vinculados a los trabajos de grado.
