### ISSUE TITLE
Revisar solicitudes durante un trabajo de grado activo.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#843]
Se requiere realizar la revisión para ajustar las solicitudes que se puedan realizar cuando una modalidad de materias de posgrado se encuentra en proceso, tentativamente son solicitud de cambio de materias y solicitud de cancelación pero se queda a la espera de la respuesta del analista.

**Dependencias**
Se queda a la espera de la respuesta que le den al analista sobre las solicitudes que se puedan realizar en dichas modalidades.

**Sub Tareas**

- [x] Ajustar solicitudes que se puedan realizar en modalidad de materias de posgrado.
- [ ] Documentar ajustes realizados.

**Criterios de aceptación**

- [ ] Ajustes realizados.
- [ ] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
Las solicitudes que tiene el estudiante para materias de posgrado son las siguientes:

![image](https://github.com/user-attachments/assets/13bfd7e8-1c7d-4396-a7d8-aaac33c43a31)

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Ajustar solicitudes que se puedan realizar en modalidad de materias de posgrado.**

1, Se solucionó el siguiente error que se presentaba al momento de crear la solicitud para el cambio de materias de posgrado:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/067ad912-e726-4c82-b569-a619e1b57956">

**Comment by CrisEs2506** [comment]
**Nota:** El formulario de cancelación de la modalidad de materias de posgrado quedó a cargo de @Astaroth-Andres-Molano, así que cuando quede listo, será documentado en esta issue.

**Comment by Astaroth-Andres-Molano** [comment]
Se inicia el flujo de solicitudes con trabajo de grado en curso
![Image](https://github.com/user-attachments/assets/fab4d6cf-20ae-4a98-8498-0ccb524d73c2)
El formulario de cancelación de modalidad es el siguiente para esta modalidad, sigue el mismo lineamiento de los demás solicitando solamente la justificación
![Image](https://github.com/user-attachments/assets/e072c4d3-2830-4927-bc51-87305004ae38)
