### ISSUE TITLE
Investigar sobre la estimación del uso de pólux según desarrollo de las diferentes modalidades y facultades en la Universidad

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#844]
Se requiere realizar la investigación relacionada con la estimación del uso de pólux según desarrollo de las diferentes modalidades y facultades en la Universidad

**Sub Tareas**

- [x] Generar contacto con el responsable.
- [x] Adelantar la investigación.
- [x] Alimentar la documentación relacionada.

**Criterios de aceptación**

- [x] Documento con información relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido crear el documento de estimación con base a la información suministrada de parte del cliente
[documento de estimación](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/caescorciab_udistrital_edu_co/EQZRazObT2xKliaB8TCz91UBvw8dS3VKaXhRXqxJ4V5DNg?e=KyXi9e)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!

**Comment by mantnicot** [comment]
Se ha actualizado la tabla de solicitudes
