### ISSUE TITLE
Levantar los requerimientos relacionados con las solicitudes materias de posgrado y reportes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#845]
Se requiere realizar la investigación relacionada con las solicitudes materias de posgrado y reportes con el cliente

**Sub Tareas**

- [x] Generar contacto y con el cliente.
- [x] Adelantar la consulta sobre los requerimientos.
- [x] Exponer la información al equipos SoS.

**Criterios de aceptación**

- [x] Issue documentada con los requerimientos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Las materias de posgrado no requieren ningún otro tipo de solicitud más haya de la inicial

Con respecto a los reportes el cliente dará respuesta por mediod el correo.
