### ISSUE TITLE
Actualizar Mockups del módulo Reportes con los filtros sugeridos por el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#846]
Se requiere realizar la actualización de los mockups relacionados con el módulo Reportes con los filtros sugeridos por el cliente

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
se han creado los filtros para el modulo de reportes

[carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsL2GcDgtF1MnIHwid9e15gB_9jhqaSkZkDHwdsZHKg-eQ?e=rHDjrZ)


![Image](https://github.com/user-attachments/assets/75faf827-c765-4dca-9598-fc8b6b47e7ca)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, pendiente revisar filtros para poder generar un reporte general de todos los proyectos curriculares de Pólux.
