### ISSUE TITLE
Agregar filtros en creación de reportes - Parte 3.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#850]
Se requiere realizar los ajustes necesarios en el API Mid con el fin de finalizar implementación de filtros en módulo de reportes, se debe usar el endpoint que se solicitará a Jhon para consultar los proyectos curriculares de una facultad (aún pendiente por aclarar si se puede usar una vista) y realizar ajustes necesarios para implementación de dichos filtros con información proveniente de otras Apis.

Revisar la opción de manejar los proyectos curriculares y facultades como dependencias en Oikos.

**Dependencias**
Se debe preguntar y solicitar a Jhon la creación de nuevos endpoints para consultas de facultad, tanto para obtener la facultad actual del coordinador como el listado de proyectos curriculares de una facultad.

**Sub Tareas**

- [ ] Realizar ajustes en el mid para consumir y adaptar cambios en endpoints nuevos.
- [ ] Modificar lógica en el MID con el fin de realizar ajustes necesarios a reportes.
- [ ] Realizar pruebas de funcionaimento correcto.
- [ ] Documentar issue con ajustes y pruebas realizadas.

**Criterios de aceptación**

- [ ] Ajustes para consumo de endpoints realizados.
- [ ] Modificaciones de lógica realizadas.
- [ ] Pruebas realizadas.
- [ ] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se continua el desarrollo de los filtros en la API MID. Se comienza con la optimización al momento de aplicar el filtro de proyecto curricular para disminuir los tiempos de respuesta de la consulta.

Para el issue #842 se desarrolló el filtro usando un ciclo For clásico para recorrer el slice de los registros del reporte y se agregó un condicional que evaluaba si el registro actual pertenecía al proyecto curricular seleccionado. Si era verdadero, continuaba su flujo normal; pero si era falso, se debía eliminar el registro del arreglo, pero debido a que en Go no existe una función para eliminar elementos de un arreglo, se debe re-crear el arreglo sin el registro encontrado. Esta funcionalidad hace que la API responda en tiempos muy altos al momento de generar los reportes.

Se consulta y se encuentra otra forma de filtrar los arreglos, esto se realiza por medio de un For Each de Go y, en vez de evaluar qué elementos eliminar y re-crear el slice del reporte, se almacenan los registros que si pasan la evaluación en un nuevo arreglo. Se implementa esta nueva funcionalidad y se realizan las siguientes pruebas, en donde se observa la reducción en los tiempos de consulta:

- Reporte General:
  - Con filtro antiguo: 9.58s
![Image](https://github.com/user-attachments/assets/a4d78a52-9e28-4322-a63a-88628b130173)

  - Con nuevo filtro: 1.82
![Image](https://github.com/user-attachments/assets/ad9e3ccc-17f0-4132-8f1c-5c2edc601442)

- Reporte de Solicitudes:
  - Con filtro antiguo: 52.68s
![Image](https://github.com/user-attachments/assets/6ad557c4-c794-4fe5-945c-6a72acf2be3b)

  - Con nuevo filtro: 3.34s
![Image](https://github.com/user-attachments/assets/1387c77f-6381-44d6-bf5e-417464c1e300)

Adicional a esto, se recibió respuesta de JBPM en donde indicaron que no es posible utilizar vistas en las consultas de la API, por lo que el script creado en el issue #842 no sirve.

Se analiza otras opciones y se encuentra con una tabla que contiene la información de las facultades. Se desarrolla el siguiente script, en donde ingresando el código de un proyecto curricular, retorna las carreras de su misma facultad y su mismo nivel:

```bash
SELECT CRA_COD codigo_proyecto_curricular, 
CRA_NOMBRE nombre_proyecto_curricular
FROM MNTAC.ACCRA
WHERE (CRA_DEP_COD, CRA_TIP_CRA) = (
	SELECT CRA_DEP_COD, CRA_TIP_CRA 
	FROM MNTAC.ACCRA 
	WHERE CRA_COD = ?)
	AND CRA_ESTADO = 'A'

```

Se prueba el script con el código 20 del proyecto de ingeniería de sistemas. El resultado es correcto debido a que retorna los proyectos de Pregrado de la facultad de Ingeniería:
![Image](https://github.com/user-attachments/assets/d4f1eedc-b385-4bc4-90c1-3d962ad53e32)

**Comment by JuanDHernandezA** [comment]
Se realizan cambios en los scripts de JBPM debido a que el endpoint solicitado no fue aprobado:

- En el endpoint de coordinador_carrera se agrega el dato de codigo_facultad el cual indica el código de la facultad a la cual pertenece el proyecto curricular asociado al coordinador ingresado:

```bash
SELECT 
DISTINCT
CASE WHEN emp_nombre IS NULL THEN 'No registra.' ELSE emp_nombre END nombre_coordinador,
as_cra_cod codigo_proyecto_curricular,
as_cra_nom nombre_proyecto_curricular,
CRA_DEP_COD codigo_facultad
FROM MNTAC.ACCRA
INNER JOIN MNTPE.peemp ON cra_emp_nro_iden=emp_nro_iden
INNER JOIN MNTAC.accra_snies ON cra_cod=as_cra_cod
INNER JOIN MNTAC.actipcra ON CRA_TIP_CRA=TRA_COD
WHERE cra_emp_nro_iden=?
AND TRA_NIVEL=?
```
Se prueba con los datos del coordinador de Ingeniería de Sistemas:
![Image](https://github.com/user-attachments/assets/9cf0a36b-9c43-4eac-9d05-f01b765225ba)

- Se modifica el script presentado en el comentario anterior. Ahora, como ya tenemos el código de la facultad, se envía este id junto con el nivel que se quiera obtener de los proyectos curriculares:
```bash
SELECT CRA_COD codigo_proyecto_curricular, 
CRA_NOMBRE nombre_proyecto_curricular
FROM MNTAC.ACCRA
INNER JOIN MNTAC.actipcra ON CRA_TIP_CRA=TRA_COD
WHERE CRA_ESTADO = 'A'
	AND CRA_DEP_COD = ?
	AND TRA_NIVEL=?
```

Se prueba con el ID 33, correspondiente a la facultad de ingeniería, dando como resultado la siguiente consulta, la cual contiene los proyectos de pregrado de la facultad de ingeniería:
![Image](https://github.com/user-attachments/assets/99dd2571-30a8-4549-a874-e8b9b08f6613)

Se prueba que los cambios realizados en el endpoint _coordinador_carrera_ hayan quedado y funcionen correctamente, lo cual es correcto:
![Image](https://github.com/user-attachments/assets/8e222a22-8901-4293-a1c1-0ead66d63575)

Con esto, quedamos a la espera de la generación del nuevo endpoint para realizar la implementación el los filtros de los reportes.

Adicional a esto, se realizaron los ajustes necesarios para que al momento en que no existan registros para los filtros ingresados, el API MID retorne un error y a partir de este notificar al usuario de que no hay trabajos de grado o solicitudes dentro de los parámetros ingresados:
![Image](https://github.com/user-attachments/assets/857c5241-4ff8-4740-88bc-d9f19efce7c5)

**Comment by diagutierrezro** [comment]
El issue no se pudo finalizar ya que aún se encuentra pendiente la creación del endpoint
