### ISSUE TITLE
Revisar listado de solicitudes cuando el coordinador para dos proyectos curriculares de una solicitud es la misma persona.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#855]
Se requiere realizar el análisis y ajustes en el listado de solicitudes al momento en el que los coordinadores van a revisar un proyecto curricular y la solicitud tiene dos proyectos curriculares en los cuales el coordinador es la misma persona. Se propone utilizar el mismo campo agregado en los detalles del proyecto curricular.

**Sub Tareas**

- [x] Análisis de listado de solicitudes realizado.
- [ ] Realizar ajustes en dicha vista para diferenciar la solicitud de la opción de grado 1 o 2.
- [ ] Realizar pruebas del funcionamiento una vez se hagan los ajustes.

**Criterios de aceptación**

- [ ] Analisis realizado.
- [ ] Ajustes realizados.
- [ ] Pruebas realizadas.
- [ ] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes para eliminar el JSON- de la cadena string que contiene los datos de la carrera y opción
![Image](https://github.com/user-attachments/assets/ee148ec4-13c4-4e87-bb88-c6e032646612)
Visualización de los datos parseados a JSON
![Image](https://github.com/user-attachments/assets/9d886398-e0ef-4e95-b5fe-87c3cd7fd92f)

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Análisis de listado de solicitudes realizado.**

Existe la posibilidad de indicarle al Coordinador de Posgrado mediante un mensaje, que la primera opción que él elija para aprobar la solicitud será aquella de la Opción No Prioritaria (Esto lo sabrá dando click en "Ver detalles" y comparar el número de la opción con el proyecto curricular)

<img width="466" alt="image" src="https://github.com/user-attachments/assets/f155711a-d6ef-42db-a91f-f2d2a4ab585a">

Como se observa en la imagen la opción no prioritaria sería la que está encerrado de verde para este caso.
