### ISSUE TITLE
Levantar información respecto a integración de notas con SGA

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#857]
Se requiere realizar una levantamiento de información para abordar la integración de notas con respecto a SGA, importante tener en cuenta los cambios que sugirió la facultad tecnologica y los cambios en registro de notas que se realiza desde esa facultad.

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias están identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha intentado comunicarse con responsables pero no se ha dado respuesta de parte de Milton

**Comment by mantnicot** [comment]
Se ha creado un documento de analisis con base a lo proporcionado por Braian por la falta de respuesta de parte de Milton


[documento de analisis](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Eez2Or6iXVFOusv996tWTScBDEijYL6zGtyFZqV6zRM-lw?e=xxGRjO)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, pendiente requerimientos de la segunda versión de SGA, con el fin de tomar la decisión de con cual se integrará Pólux.
