### ISSUE TITLE
Analizar y levantar información varia de Pólux

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#858]
Se requiere realizar el levantamiento de multiple información que ha surgido en reuniones con los usuarios:

**Sub Tareas**

- [x] Revisar diferencia de registro de notas entre facultad ing y tecnológica.
- [x] Analizar cargue de oficios que se realiza desde facultad tecnológica.

**Criterios de aceptación**

- [x] Investigación documentada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido definir junto con el usuario dé tecnológica soluciones para la nota y confirmación de la misma 

Se establecio cambios con los siguientes mockups : 

- Agregar comentario de identificar las notas 
- Agregar un recuadro de confirmación para subir al nota

![Image](https://github.com/user-attachments/assets/02701cc0-c11d-43d2-be64-990ece0dd13d)
![Image](https://github.com/user-attachments/assets/8b960936-08bc-4d1b-9be3-64c072c5b4c7)

[carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuhM1iUE7xRLvf736BjsruwBC2EWv7KkyZfhDBRS90KqIQ?e=xBWaLs)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot, infornación necesaria para avanzar en Pólux
