### ISSUE TITLE
Concertar, desarrollar y levantar del acta de sesión de muestra de polux asistente tecnologica

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#859]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de muestra de polux asistente tecnologica.

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se agrega la segunda acta de la sesión , realizada el día 05/12/2024
[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZTK84FotS5Nn0LhBrchj78BTPkIFX8x1zA5YDOM8JRSJw?e=XgaanI)

**Comment by jcmurilloa** [comment]
Actas revisadas y con VoBo para recolección de firmas.

**Comment by mantnicot** [comment]
Se adjunta el acta firmada


[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQ9s20DJJdJHpHWbNSp7vLIBjgWFajq8gQg4UewphMisPw?e=duHubo)
