### ISSUE TITLE
Finalizar adición de filtros en módulo de reportes.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#860]
Se requiere realizar la finalización en la adición de filtros para el módulo de reportes, se tiene pendiente por parte de Jhon Castellanos la creación del endpoint que retorna la información de los proyectos curriculares de una facultad, una vez creado el issue se requiere realizar filtros al JSON obtenido desde el CRUD para mostrar únicamente los registros de un proyecto curricular.

Terminar ajustes pendientes en el cliente para definir campos requeridos e inhabilitar botón de creación de reportes mientras no se hayan llenado todos los campos obligatorios.

**Sub Tareas**

- [x] Implementar endpoint creado.
- [x] Crear nuevo arreglo para agregar filtro por proyectos curriculares.
- [x] Realizar ajustes finales al cliente.
- [x] Realizar diferentes pruebas de filtros generando el excel final.

**Criterios de aceptación**

- [x] Implementación de endpoint realizado.
- [x] Nuevo arreglo obtenido.
- [x] Ajustes al cliente realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se crean los mensajes emergentes cuando el reporte se genera o no, los mensajes utilizados son los siguientes:

- Se encontraron registros:
![Image](https://github.com/user-attachments/assets/1c832a3c-5d98-418c-ae0d-0d72f37504f3)

- No se encontraron registros:
![Image](https://github.com/user-attachments/assets/fb222ee6-6436-4989-8013-2a3686311785)

Se realizaron cambios a la vista, quedando de la siguiente manera:
![Image](https://github.com/user-attachments/assets/566de2c2-d8e3-4fc2-a402-53537cf40d2f)

En donde también se agregó la funcionalidad para que los todos los campos sean requeridos y hasta que el usuario no ingrese todos los datos, no se habilitarán los botones de descarga de los reportes:
![Image](https://github.com/user-attachments/assets/15c74d88-8919-4f02-9184-121a574afc4b)
