### ISSUE TITLE
Iniciar planeación de piloto de modalidad de materias de posgrado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#862]
Se requiere realizar la documentación para la construcción del piloto en producción para la modalidad de posgrado.

**Sub Tareas**

- [x] Generar contacto con cliente
- [x] Levantar requerimientos de programación
- [x] Proyectar el plan piloto en producción
- [x] Presentar el plan piloto a equipos SoS

**Criterios de aceptación**

- [x] Plan piloto aprobado equipos SoS y cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha comenzado con el desarrollo de los documentos para el pilto de posgrado , se toman como referencia los de pasantia
[Carpeta piloto espacios academicos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Egy6qgSiU39Joa5Db7Xe5mgBpsazVuiW5ZKJ0A1JTNdFJA?e=kRLXYO)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, pendiente la actualización de fechas para el inicio, al momento de establecerlas con el cliente.
