### ISSUE TITLE
Iniciar revisión de registro de notas por parte del coordinador de posgrado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#863]
Se requiere realizar el desarrollo inicial para habilitar el registro de notas por parte de la coordinación de posgrado, la idea es utilizar la misma vista de registro de nota que utilizan los docente, revisar las solicitudes que se hacen para iniciar busqueda y listar estudiantes que tengan un trabajo de grado activo en la modalidad de espacios academicos de posgrado.

**Sub Tareas**

- [x] Ajustar vista de registro de nota modificando consultas realizadas cuando el que ingresa es un coordinador.
- [x] Realizar pruebas de que se lista correctamente los trabajos de grado en curso en modalidad de materias de posgrado.

**Criterios de aceptación**

- [x] Ajuste de vistas realizado.
- [x] Pruebas de listado realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Para que el Coordinador pueda acceder a la vista de Registrar Nota se modifica los permisos desde la página de configuración y se agrega el acceso a esta vista al rol COORDINADOR:

![Image](https://github.com/user-attachments/assets/a1b60c87-c74c-4e8a-b81b-0926b8ddfc80)

Se accede a la vista desde el usuario de la Coordinación de la Especialización en Ingeniería de Software y se observa que muestra todos los trabajos de grado asociados a dicho posgrado:
![Image](https://github.com/user-attachments/assets/98abce6a-3fb0-4cc2-b6f0-bb46f4d1bf9c)

Esta es la información que se muestra en el modal de "Ver Detalles":
![Image](https://github.com/user-attachments/assets/596df2eb-1c27-466b-9c38-c856be3becf6)

Inicialmente, se modifica para que únicamente muestre los trabajos de grado con estado "En Curso" y se habilita el botón de "Registrar Calificaciones":
![Image](https://github.com/user-attachments/assets/6f384db2-ecdc-496b-84c2-caac66b8f17c)

Esta es la vista al dar click en la opción "Registrar Calificación":
![Image](https://github.com/user-attachments/assets/6dc24df3-4bd9-4df6-a530-9e9ad789ff6a)

Al querer visualizar el documento de revisión y el documento anexo genera un error porque no existe una solicitud de revisión y sus documentos anexos. Debido a esto, se decide ocultar estas opciones cuando el usuario tiene rol de COORDINADOR:
![Image](https://github.com/user-attachments/assets/756f6a25-c3f9-488e-a11a-f124eb376ead)

**Comment by JuanDHernandezA** [comment]
Se agrega en el cliente el rol de COR_POSGRADO_PLX a la funcionalidad para enviar los datos ingresados a la transacción del MID tr_vinculado_registrar_nota.

En el MID se modifica la lógica para registrar la nota del vinculado con el rol COR_POSGRADO_PLX. Actualmente las notas se registran dependiendo el número de vinculados asociados a un trabajo de grado. En este caso, solo existe 1 vinculado al trabajo de grado, por lo que se hace uso de la funcionalidad de registrar la nota por parte de solo 1 vinculado.

Se registra la siguiente nota:
![Image](https://github.com/user-attachments/assets/8bf22a09-070a-41da-a3de-0caa4e3c01af)

Dando como resultado los siguientes registros en la base de datos:

- POST en la tabla evaluacion_trabajo_grado:
![Image](https://github.com/user-attachments/assets/61c2bfdd-2cc4-4a5e-a220-8a8ab7863943)

- PUT en los 2 registros de las asignaturas en la tabla asignaturas_trabajo_grado:
![Image](https://github.com/user-attachments/assets/e26eacfc-d418-4a65-960a-4f7795d2ce83)

- PUT en el registro del trabajo_grado, actualizando el estado a "Notificado a coordinación con calificación"
![Image](https://github.com/user-attachments/assets/f56a0278-3cd1-4910-9943-f63655dc8317)

Adicional, se configura la vista para cuando no hay trabajos de grado asociados en estado En Curso, muestre el mensaje siguiente mensaje:
![Image](https://github.com/user-attachments/assets/66e1786c-6d73-4e9d-9773-f1b5905c4f36)

Con esto, queda finalizada la funcionalidad de registrar la nota para la modalidad de materias de posgrado
