### ISSUE TITLE
Ajustar solicitud inicial cuando coordinador es el mismo para dos proyectos curriculares.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#867]
Se requiere realizar el ajuste de la solicitud inicial cuando el coordinador de posgrado es el mismo para los dos proyectos de una solicitud, en este caso se hará la modificación según lo acordado en el que primero se dará respuesta de la solicitud prioritaria y despues a la solicitud no prioritaria en caso de que la primera se haya rechazado. Si la solicitud prioritaria se aprueba de primeras el trabajo de grado se pondrá en curso y no será necesario dar respuesta a la siguiente solicitud, importante que según sea el proyecto que se vaya a responder se debe eliminar de la solicitud (únicamente de manera visual) la información del otro proyecto curricular.

**Sub Tareas**

- [x] Realizar ajustes para aprobación de solicitud inicial de la opción prioritaria y despues de la no prioritaria (si es necesario).
- [x] Realizar pruebas del correcto funcionamiento del sistema comprobando el punto anterior.
- [x] Documentar ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Aprobación inicial ajustada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
<img width="472" alt="image" src="https://github.com/user-attachments/assets/d69fba51-f0cc-45ff-b3d6-717760843fb6">

<img width="473" alt="image" src="https://github.com/user-attachments/assets/ec0cb521-5b16-4ba8-9b22-9416227d27be">

<img width="473" alt="image" src="https://github.com/user-attachments/assets/51292b78-c8e7-4c4e-98b2-113fca874f9d">

**Comment by CrisEs2506** [comment]
**Nota:** El gestor documental al parecer se cayó y no pude adelantar mucho :(.

```JSON
{
    "Status": "500",
    "Error": "HTTPError(503), error: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>503 Service Unavailable</title>\\n</head><body>\\n<h1>Service Unavailable</h1>\\n<p>The server is temporarily unable to service your\\nrequest due to maintenance downtime or capacity\\nproblems. Please try again later.</p>\\n<hr>\\n<address>Apache/2.4.7 (Ubuntu) Server at documental.portaloas.udistrital.edu.co Port 80</address>\\n</body></html>\\n', server trace: None"
}
```

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar pruebas del correcto funcionamiento del sistema comprobando el punto anterior.**

1. Se decidió rechazar con el proyecto curricular de la opción NO prioritaria (Especialización en teleinformática) y afortunadamente el estado quedó en 'RCPO2' como se observa en la siguiente imagen:

<img width="472" alt="image" src="https://github.com/user-attachments/assets/fc0102d2-eeaa-4cc3-b489-049b34a0573b">

2. Rechazar con el proyecto curricular de la opción prioritaria (Especialización en telecomunicaciones móviles) y el estado quedó en 'RCC' de forma correcta:

F valió por temas de Angular.forEach en 'aprobar_solicitud.js'.

**Comment by CrisEs2506** [comment]
![image](https://github.com/user-attachments/assets/83c99452-d1e9-4482-b585-0bb55a6c7d31)

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar pruebas del correcto funcionamiento del sistema comprobando el punto anterior.**

1. Se decidió rechazar con el proyecto curricular de la opción NO prioritaria (Especialización en teleinformática) y afortunadamente el estado quedó en 'RCPO2' como se observa en la siguiente imagen:



2. Rechazar con el proyecto curricular de la opción prioritaria (Especialización en telecomunicaciones móviles) y el estado quedó en 'RCC' de forma correcta:

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar pruebas del correcto funcionamiento del sistema comprobando el punto anterior.**

1. Se decidió rechazar con el proyecto curricular de la opción NO prioritaria (Especialización en teleinformática) y afortunadamente el estado quedó en 'RCPO2' como se observa en la siguiente imagen:



2. Rechazar con el proyecto curricular de la opción prioritaria (Especialización en telecomunicaciones móviles) y el estado quedó en 'RCC' de forma correcta:

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar pruebas del correcto funcionamiento del sistema comprobando el punto anterior.**

1. Aprobar con el proyecto curricular de la opción NO prioritaria (Especialización en teleinformática) y afortunadamente el estado quedó en 'ACPO2' como se observa en la siguiente imagen:

<img width="472" alt="image" src="https://github.com/user-attachments/assets/ace23746-968c-4035-9e0f-e877a4e06951" />

2. Aprobar con el proyecto curricular de la opción prioritaria (Especialización en telecomunicaciones móviles) y el trabajo de grado se creó satisfactoriamente:

<img width="832" alt="image" src="https://github.com/user-attachments/assets/6013ea38-0e30-4070-bc98-b0a86d22695a" />

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar pruebas del correcto funcionamiento del sistema comprobando el punto anterior.**

1. Rechazar con el proyecto curricular de la opción NO prioritaria (Especialización en teleinformática) y afortunadamente el estado quedó en 'RCPO2' como se observa en la siguiente imagen:

<img width="472" alt="image" src="https://github.com/user-attachments/assets/a5fba9b2-ba05-48aa-8047-dd4dcc7b4f2a" />

2. Aprobar con el proyecto curricular de la opción prioritaria (Especialización en telecomunicaciones móviles) y el trabajo de grado se creó satisfactoriamente:

<img width="832" alt="image" src="https://github.com/user-attachments/assets/979211da-a071-46fa-b08a-219c47f3f3df" />

**Comment by diagutierrezro** [comment]
Se le realizó una presentación al usuario Kevin para mostrar el flujo de solicitud inicial y todo salió muy bien, buen trabajo Cristian.
