### ISSUE TITLE
Ajustar vista de consulta de trabajo de grado para modalidad de posgrado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#868]
Se requiere realizar el ajuste en la vista de consulta de trabajo de grado para una modalidad de espacios académicos de posgrado, actualmente dicha vista falla para esta modalidad ya que debe hacer multiples consultas que se hacian anteriormente donde se consultaba información del proyecto curricular y las materias que tenía inscritas. Para este ajuste se debe tener presente que dicha información ya no existe, únicamente se debería mostrar la documentación cargada en un inicio y realizar una consulta para obtener el proyecto curricular en el que se está realizando la modalidad.

**NOTA**: Es importante tener presente que este cambio es únicamente para la modalidad de espacios académicos de posgrado y que no se debe ver afectado el funcionamiento normal con otras modalidades.

**Sub Tareas**

- [x] Eliminar consultas e información que ya no es necesaria (tabla de materias de posgrado).
- [x] Agregar consulta para obtener información del proyecto curricular de posgrado.
- [x] Ajustar vista e información mostrada en dicha vista cuando la modalidad es de posgrado.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Consultas e información eliminada.
- [x] Consulta para obtener información agregada.
- [x] Vista ajustada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se ingresa a la vista de Consultar Trabajo Grado al momento en que la coordinación de posgrado aprueba la Solicitud Inicial, se obtiene una vista con el error de no encontrar alguna información en las consultas:

![Image](https://github.com/user-attachments/assets/9149ca40-d5e8-4121-a323-5ecd08d648fb)

Se revisa las consultas que se realizan en el Cliente al momento de ingresar a la vista, en donde se encuentra que se realiza una consulta a la tabla espacio_academico_inscrito y asignatura_pensum. Debido a que actualmente no se usan estas tablas, se eliminan sus consultas del flujo. Al realizar este cambio se obtiene la siguiente vista:

![Image](https://github.com/user-attachments/assets/81e7e321-a649-4728-814f-0f6fef5f554e)

En donde se tienen las siguientes observaciones:

- Las asignaturas aparecen con el estado "Reprobado" en vez de "Sin Calificación"
- No se recuperan los documentos ingresados en la solicitud inicial
- No se pueden ver los detalles de la solicitud inicial y esta aparece sin su estado

Se corrige el error que muestra el mensaje de "Reprobado" en las asignaturas. Revisando el código, se observa que este mensaje se genera calculando si la nota registrada es mayor igual a 3.5. Debido a que desde un principio se registra las notas con 0, se muestra el mensaje de reprobado. Se agrega una condición para verificar que el trabajo esté en el estado de "Notificado a Coordinación con calificación" para realizar esta operación; de lo contrario mostrará el mensaje "Sin calificación":
- Trabajo de grado En Curso:
![Image](https://github.com/user-attachments/assets/d5e97f45-a88d-4caa-8aa0-a800aeaf56fb)
- Trabajo de grado Calificado:
![Image](https://github.com/user-attachments/assets/3deee0b9-7bb7-4c22-8241-61cb7871efc2)

Para corregir el error al visualizar los documentos del trabajo de grado, se observa que no se almacena ningún registro en la tabla documento_trabajo_grado asociado al trabajo de grado. Se verifica en el Payload al momento de aprobar la solicitud por parte de posgrado y se observa que no se envía ningún documento:
![Image](https://github.com/user-attachments/assets/59203cb5-81c0-4616-9785-8f75bd1a8901)

Para poder almacenar los documentos, se debe crear los nuevos tipos de documentos en la base de datos de parámetros. Para ello, se desarrolló el siguiente script:

```bash
INSERT INTO documento.tipo_documento
	(nombre,descripcion,codigo_abreviacion,activo,numero_orden,tamano,extension,workspace,tipo_documento_nuxeo,fecha_creacion,fecha_modificacion,dominio_tipo_documento) 
	VALUES 	('Solicitud escrita de las materias','Solicitud escrita de las materias seleccionadas','SEM_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
			('Justificación','Justificación selección materias','JMP_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
			('Carta de aceptación de inscripción','Carta de aceptación de inscripción','CAI_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9),
			('Sábana de notas','Sábana de notas del estudiante','SN_PLX',true,1.00,5,'pdf','/desarrollo/workspaces/polux/documentos_grado','File',NOW(),NOW(),9);

```

Dando como resultado la inserción de los nuevos tipos de documento:
![Image](https://github.com/user-attachments/assets/5425b9e1-2cfe-47e8-b7b8-49c691a90f2d)

Se comienza el desarrollo para almacenar los documentos con sus respectivos tipos.

**Comment by JuanDHernandezA** [comment]
Para almacenar los documentos de la solicitud inicial se creó un nuevo modelo en el MID para almacenar cada documentos escrito con su documento trabajo grado:
![Captura de pantalla 2024-12-11 125718](https://github.com/user-attachments/assets/e284d353-924e-4adf-80b9-e40a3424e0cc)

Y se crea un nuevo campo en el modelo TrTrabajoGrado:
![Captura de pantalla 2024-12-11 125631](https://github.com/user-attachments/assets/0f4eba01-81bd-4f00-9cdb-27b64e3922bd)

Se desarrolla la lógica necesaria en el cliente y en el MID para almacenar y asociar estos documentos con el trabajo de grado, dando como resultado los siguientes registros:
- documento_escrito:
![Captura de pantalla 2024-12-11 130329](https://github.com/user-attachments/assets/d3be0a05-4538-44cd-b29a-c1007ee0d3b6)

- documento_trabajo_grado:
![Captura de pantalla 2024-12-11 130413](https://github.com/user-attachments/assets/9d19729b-6864-488d-8246-863933cb11d4)

Ahora, se desarrolla la funcionalidad para recuperar y mostrar estos nuevos tipos de documentos en la vista de Consulta Trabajo Grado:
![Captura de pantalla 2024-12-11 132203](https://github.com/user-attachments/assets/cfd8bc25-fbd7-4a1e-839a-3e4bd590162c)

Adicional a esto, se agregó la funcionalidad para almacenar el código de abreviación del rol de los vinculados en el trabajo de grado para la modalidad de Materias de Posgrado:
![image](https://github.com/user-attachments/assets/88b42998-0172-47c2-9dda-7ed822e17957)

**Comment by diagutierrezro** [comment]
No se pudo finalizar la vista ya que por parte de los DBA no se hizo la modificación solicitada debido a que mencionaron que se debe realizar una reunión para explicarles el cambio pero aún no me dan agenda. La issue se bajará a 5 puntos y cuando se realice el cambio en la db se creará una nueva para finalizar.
