### ISSUE TITLE
Realizar ajustes necesarios para adaptación hacia los asistentes - Parte 1

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#870]
Se requiere realizar el ajuste de modalidad de materias de posgrado hacia el usuario de asistente de coordinación para que pueda realizar los flujos de aprobación y registro de nota que puede realizar el coordinador. Para la solicitud inicial revisar primero cuando los asistentes son diferentes.

**Sub Tareas**

- [x] Realizar ajustes necesarios para que con el rol de asistente se puedan realizar las mismas tareas que puede realizar el coordinador (aprobación de solicitudes inicial, cambios de materias y cancelación).
- [x] Realizar pruebas de funcionamiento tanto para aprobación de solicitudes en general como el registro de nota.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**Nota:** Un día de esta Issue fue usada para que al listar los detalles de la solicitud desde 'aprobar_solicitud' se quitara el detalle de aquel proyecto curricular del cuál no se seleccionó:

En la siguiente imagen la carrera seleccionada fue 'Esp. Ingeniería del Software', por tanto no aparece en los detalles 'Especialización en Proyectos Informáticos':

<img width="472" alt="image" src="https://github.com/user-attachments/assets/7cce6cf8-5dd5-4b47-9d09-9b1908cc2a68" />

Ahora realizando todo lo contrario:

<img width="473" alt="image" src="https://github.com/user-attachments/assets/af340ce5-eb07-4bca-8d58-844606e6cc04" />

El código realizado fue el siguiente:

```Javascript
let deleteDetalle;

            //Recorrer los detalles con Codigo de Abreviación ESPELE y ESPELE2
            for (let i = 0; i < ctrl.detallesSolicitud.length; i++) {
              if (ctrl.detallesSolicitud[i].DetalleTipoSolicitud.Detalle.CodigoAbreviacion == "ESPELE" || ctrl.detallesSolicitud[i].DetalleTipoSolicitud.Detalle.CodigoAbreviacion == "ESPELE2") {                    
                //Quitar el primer fragmento del string 'JSON-'
                var detalleString = ctrl.detallesSolicitud[i].Descripcion.replace("JSON-", "");
                
                if (ctrl.detallesSolicitud[i].DetalleTipoSolicitud.Detalle.CodigoAbreviacion == "ESPELE") {
                  console.log("Entre a ESPELE");

                  //Convertir el JSON en objeto si es ESPELE (Proyecto Curricular 1)
                  var infoESPELE = JSON.parse(detalleString);

                  if(infoESPELE.Codigo == $rootScope.codigoProyectoCurricularPosgrado) {
                    deleteDetalle = "ESPELE2";
                    break;
                  }
                }
                else {
                  console.log("Entre a ESPELE2");
                  //Convertir el JSON en objeto si es ESPELE2 (Proyecto Curricular 2)
                  var infoESPELE2 = JSON.parse(detalleString);

                  if(infoESPELE2.Codigo == $rootScope.codigoProyectoCurricularPosgrado) {
                    deleteDetalle = "ESPELE";
                    break;
                  }
                }
              }
            }
            console.log("deleteDetalle", deleteDetalle);

            //Eliminar el detalle del proyecto curricular del cuál actualmente no se tiene seleccionado
            ctrl.detallesSolicitud = ctrl.detallesSolicitud.filter(detalle => {
              const codigoAbreviacion = detalle.DetalleTipoSolicitud.Detalle.CodigoAbreviacion;
              return codigoAbreviacion !== deleteDetalle;
            })
```

**Comment by CrisEs2506** [comment]
**SubTarea N°1: Realizar ajustes necesarios para que con el rol de asistente se puedan realizar las mismas tareas que puede realizar el coordinador (aprobación de solicitudes inicial, cambios de materias y cancelación).**

1. En 'listar_solicitudes' se debe agregar el código pertinente para traer todas las solicitudes pertenecientes a la modalidad de Materias de Posgrado y teniendo en cuenta los estados, junto a que el tipo de solicitud sea Solicitud Inicial, Cambio de Materias de Posgrado o Cancelación de Modalidad:

<img width="838" alt="image" src="https://github.com/user-attachments/assets/7d259129-0f00-4c2c-bcbe-f28123324e5c" />

Adicionalmente se debe agregar toda la lógica para cuando en los detalles sea ESPELE o ESPELE2 que lo podemos encontrar en el if anterior el cuál es cuando el rol es Coordinador de Posgrado.

2. En el archivo de 'aprobar_solicitud' en las siguientes líneas se debería agregar un OR para cuando incluya el rol de CONTRATISTA y de igual forma ejecute la función aprobarPosgrado():

<img width="434" alt="image" src="https://github.com/user-attachments/assets/c9ee5f45-71b3-423f-949f-1c2ccd2a35d0" />
