### ISSUE TITLE
Realizar ajustes necesarios para presentación a facultad tecnológica.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#871]
Se requiere realizar ajustes necesarios solicitados por la facultad tecnológica, los cambios a realizar se encuentran en #858, estos cambios incluyen agregar una confirmación en el registro de nota de los docentes y un aviso en la vista de notas.

En el popup de la confirmación de nota agregar en el texto la nota que puso el docente, el texto quedará de la siguiente manera "¿Confirma que la nota que va a ingresar es #?"

**NOTA:** Realizar estos ajustes en una rama hotfix que inicie en rama master para enviar dichos cambios directamente a producción.

**Sub Tareas**

- [x] Realizar ajustes indicados.
- [x] Probar funcionamiento correcto.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se crea el Popup de confirmación al momento en que el usuario va a ingresar la nota:

![Image](https://github.com/user-attachments/assets/6cf842d1-c685-4e9d-b55d-72fedb058e91)

En caso de darle a "Aceptar", se continua el flujo normal:
![Image](https://github.com/user-attachments/assets/606febd5-57f6-41c2-a044-e43da8102bf8)

En caso de darle a "Cancelar", se recarga la página y se puede volver a subir la nota.

Con respecto al mensaje en la vista de Consultar, se agrega a la vista si el trabajo de grado tiene el estado "Notificado a coordinación con calificación":
![Image](https://github.com/user-attachments/assets/1b919086-2e0b-4887-bf62-429c2a1a81aa)

En caso de que tenga otro estado, no se muestra:
![Image](https://github.com/user-attachments/assets/33bce181-09c6-496e-a6fe-52b6becde2a2)
