### ISSUE TITLE
Construcción de manuales de usuario para las modalidades espacios acadénmicos posgrado y profundización.

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/polux_cliente#873]
Se requiere realizar los manuales de usuario para las modalidades espacios acadénmicos posgrado y profundización.

**Sub Tareas**

- [x] Levantar requerimientos de creación
- [x] Generar la construcción de Manuales
- [x] Exponer los manuales al equipo SoS

**Criterios de aceptación**

- [x] Manuales e instructivos refinados
- [x] Manuales e instructivos documentados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha actualizado en los manuales previo la información de espacios de posgrado y profundización

![Image](https://github.com/user-attachments/assets/f87dcab1-f805-4f0c-a15f-188cf2b5ceac)

En caso del coordinador se agrega la parte de registro de notas

![Image](https://github.com/user-attachments/assets/48fa2858-35ef-43e9-9b6a-3fa2ed50daf8)
![Image](https://github.com/user-attachments/assets/399eea6a-7d63-4997-adbd-80c54f70aec6)

Se adjunta la carpeta de los manuales actualizados
[carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EgViHpMrfqZFln3AKWhOvCEBmgYmp2o1ANdA6xBth2Uc4A?e=AmBClZ)

**Comment by diagutierrezro** [comment]
Se da visto bueno a las mofificacioens realizadas a los manuales para adaptarlos a materias de posgrado y profundización.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, manuales con VoBo del equipo SoS para continuar con el trámite.
