### ISSUE TITLE
Ajustar solicitud inicial cuando se envía unicamente una opción de proyecto curricular.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#874]
Se requiere realizar los ajustes necesarios en una solicitud inicial cuando un estudiante quiere enviar solo una opción de proyecto curricular. Como solución se plantea no enviar el detalle de ESPELE2 cuando la segunda opción de proyecto curricular no sea elegida, para esto se debe revisar la tabla de detalles para asegurarse que no sea obligatoria y despues de esto verificar que el detalle no se envíe. Posterior a esto revisar el flujo de aprobación para asegurarse de que el sistema sigue funcionando igual.

**Sub Tareas**

- [x] Revisar detalle de ESPELE2 en la base de datos y dejarlo no obligatorio.
- [x] Ajustar la creación de la solicitud inicial para asegurarse de que funciona correctamente.
- [x] Realizar pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Detalle en db revisado y ajustado.
- [x] Lógica de creación de solicitud inicial ajustada.
- [x] Pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se verifica si el detalle ESPELE2 es requerido en la Solicitud Inicial de la modalidad de Materias de Posgrado. El campo es requerido por lo que se cambia su valor a _false_ con el siguiente script:

```bash
UPDATE academica.detalle_tipo_solicitud
	SET requerido = false
	WHERE detalle = 80 AND modalidad_tipo_solicitud = 13;
```
Reflejando el cambio al momento de hacer la consulta en la tabla detalle_tipo_solicitud:
![image](https://github.com/user-attachments/assets/ca4c6068-4696-47c0-89f0-a98fb7743e29)

Se modifica la lógica que almacena la respuesta del detalle para que no se almacene ni se envíe en la transacción cuando el estudiante solo seleccionó un proyecto curricular. Dando como resultado que no se guarde el detalle:
- Sin la modificación el detalle se almacenaba con el campo vacío:
![image](https://github.com/user-attachments/assets/7a8696a1-645b-41e4-83af-db8ee403efd3)

- Con la modificación, ya no se almacena el detalle ESPELE2 (316):
![image](https://github.com/user-attachments/assets/e0667e61-0d8f-4b1b-90c8-a425bd180ba9)

Se ingresa a la solicitud con el usuario del coordinación de pregrado para verificar que no se visualiza el detalle, lo cual es correcto:
![image](https://github.com/user-attachments/assets/bcdbd9c0-3196-4f24-a22d-d0d642b45e7a)

De igual forma, el detalle de ESPELE2 tampoco sale en la vista de Aprobar Solicitud por parte del Coordinador de Posgrado:
![image](https://github.com/user-attachments/assets/e3b3e8d8-d53a-464d-b729-42c2cc9b1246)


Se prueba el flujo completo para verificar que estos cambios no afecten a la lógica principal para aprobar la solicitud inicial. Todo sale correcto y el coordinador de posgrado puede aprobar correctamente la modalidad y el trabajo de grado queda En Curso.

Con lo cual el estudiante ya puede seleccionar solo un proyecto curricular para su modalidad de Materias de Posgrado.
