### ISSUE TITLE
Finalizar flujo de aprobación de solicitudes de cambio de materias y cancelación.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#875]
Se requiere realizar el flujo de aprobación de las solicitudes de cambio de materias y cancelación en la modalidad de materias de posgrado, el flujo de aprobación para estas solicitudes es el COORDINADOR de pregrado y despues el COORDINADOR de posgrado. Se puede usar como guía en el cambio del flujo la solicitud inicial de modalidad de pasantía o la de materias de posgrado.

**Sub Tareas**

- [x] Ajuste del flujo de aprobación de las solicitudes de cambio de materias y cancelación.
- [x] Probar funcionamiento correcto de los ajustes realizados. Importante tener presente no afectar las otras modalidades.

**Criterios de aceptación**

- [x] Ajuste de flujo finalizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se encuentra error en la lectura del dato "Usuario" que corresponde a ente responsable 
![Image](https://github.com/user-attachments/assets/c621436e-7ba8-4fed-9eca-0c21fbbca681)
Se hace revisión en las consultas iniciales del controlador para saber si trae el dato Rol Trabajo Grado
![Image](https://github.com/user-attachments/assets/75304d02-d5cc-411b-a65c-bd27a2c5a430)
Se observa que en los objetos que se arman para Payload no incluyen al rol Coordinador Posgrado, se realiza ajuste para incluirlo en la transacción
![Image](https://github.com/user-attachments/assets/0599cf5c-d2cf-4845-823f-91569ec53d5b)
![Image](https://github.com/user-attachments/assets/b929abaf-77f2-40cd-99f1-9b15fd515abf)
Se realiza prueba y realiza la petición aparentemente exitosa
![Image](https://github.com/user-attachments/assets/4f21a922-3c3e-4859-9539-d59aeff89af0)

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes en el controlador del cliente "aprobar_solicitud"
![Image](https://github.com/user-attachments/assets/73d4bdc4-81eb-4315-915c-74c8023ff321)
se realiza nuevamente todo el ciclo de solicitud inicial para modalidad de espacios académicos de posgrado, se genera proyecto y se procede nuevamente con el flujo de cancelación, se realiza prueba de aprobación de solicitud por parte de3 coordinador pregrado
![Image](https://github.com/user-attachments/assets/6a81c3a0-86b3-4007-a6c4-4fdba339ca49)
se observa que payload envía
```JSON
{
    "RespuestaAnterior": {
        "Id": 4237,
        "Fecha": "2024-12-13T03:58:41.217Z",
        "Justificacion": "Su solicitud esta pendiente a la revision del docente",
        "EnteResponsable": 0,
        "Usuario": 0,
        "EstadoSolicitud": 4610,
        "SolicitudTrabajoGrado": {
            "Id": 2112,
            "Fecha": "2024-12-13T03:58:41.217Z",
            "ModalidadTipoSolicitud": {
                "Id": 14,
                "TipoSolicitud": 4635,
                "Modalidad": 4602
            },
            "TrabajoGrado": {
                "Id": 647,
                "Titulo": "Espacios Académicos de Posgrado",
                "Modalidad": 4602,
                "EstadoTrabajoGrado": 4582,
                "DistincionTrabajoGrado": null,
                "PeriodoAcademico": "2024-3",
                "Objetivo": ""
            },
            "PeriodoAcademico": "2024-3",
            "DatosPersonalesArl": ""
        },
        "Activo": false
    },
    "RespuestaNueva": {
        "Id": null,
        "Fecha": "2024-12-13T13:22:03.992Z",
        "Justificacion": "Test Cancel",
        "EnteResponsable": 0,
        "Usuario": 79702248,
        "Activo": true,
        "EstadoSolicitud": 4631,
        "SolicitudTrabajoGrado": {
            "Id": 2112
        }
    },
    "DocumentoSolicitud": {
        "DocumentoEscrito": {
            "Id": 813
        },
        "SolicitudTrabajoGrado": {
            "Id": 2112
        }
    },
    "TipoSolicitud": {
        "Id": 4635
    },
    "Vinculaciones": null,
    "EstudianteTrabajoGrado": {
        "Estudiante": "20192020102",
        "TrabajoGrado": {
            "Id": 647,
            "Titulo": "Espacios Académicos de Posgrado",
            "Modalidad": 4602,
            "EstadoTrabajoGrado": 4582,
            "DistincionTrabajoGrado": null,
            "PeriodoAcademico": "2024-3",
            "Objetivo": ""
        },
        "EstadoEstudianteTrabajoGrado": 4648
    },
    "VinculacionesCancelacion": [
        {
            "Id": 1192,
            "Usuario": 52204982,
            "Activo": true,
            "FechaInicio": "2024-12-12 22:57:44.346792 +0000 +0000",
            "FechaFin": "2024-12-13T13:22:03.992Z",
            "RolTrabajoGrado": 4597,
            "TrabajoGrado": {
                "Id": 647,
                "Titulo": "Espacios Académicos de Posgrado",
                "Modalidad": 4602,
                "EstadoTrabajoGrado": 4582,
                "DistincionTrabajoGrado": null,
                "PeriodoAcademico": "2024-3",
                "Objetivo": ""
            },
            "CodigoAbreviacion": ""
        }
    ],
    "TrTrabajoGrado": null,
    "ModalidadTipoSolicitud": {
        "Id": 14,
        "TipoSolicitud": 4635,
        "Modalidad": 4602
    },
    "TrabajoGrado": null,
    "SolicitudTrabajoGrado": null,
    "EspaciosAcademicos": null,
    "DetallesPasantia": null,
    "TrRevision": null,
    "EspaciosAcademicosInscritos": null,
    "MateriasProPos": false
}
```
Se verifica que el estudiante aún tenga una petición en curso
![Image](https://github.com/user-attachments/assets/34f62dd6-076d-44dc-9e7a-1118bb838911)


Se revisa desde el respectivo coordinador de posgrado y efectivamente le llega la solicitud de cancelación

![Image](https://github.com/user-attachments/assets/6a38776f-41a3-4b94-a7e1-60aaf5a2041e)
Vista de la solicitud
![Image](https://github.com/user-attachments/assets/8f2a29a0-79b5-493c-8a6d-be8a69601479)

![Image](https://github.com/user-attachments/assets/e5cb30c5-1b42-4a35-846c-3614439daab0)
Se verifica el Payload enviado
```JSON
{
    "RespuestaAnterior": {
        "Id": 4238,
        "Fecha": "2024-12-13T13:25:45.935Z",
        "Justificacion": "Test Cancel",
        "EnteResponsable": 0,
        "Usuario": 79702248,
        "EstadoSolicitud": 4631,
        "SolicitudTrabajoGrado": {
            "Id": 2112,
            "Fecha": "2024-12-13T03:58:41.217Z",
            "ModalidadTipoSolicitud": {
                "Id": 14,
                "TipoSolicitud": 4635,
                "Modalidad": 4602
            },
            "TrabajoGrado": {
                "Id": 647,
                "Titulo": "Espacios Académicos de Posgrado",
                "Modalidad": 4602,
                "EstadoTrabajoGrado": 4582,
                "DistincionTrabajoGrado": null,
                "PeriodoAcademico": "2024-3",
                "Objetivo": ""
            },
            "PeriodoAcademico": "2024-3",
            "DatosPersonalesArl": ""
        },
        "Activo": false
    },
    "RespuestaNueva": {
        "Id": null,
        "Fecha": "2024-12-13T13:41:05.617Z",
        "Justificacion": "Test Cancel",
        "EnteResponsable": 0,
        "Usuario": 52204982,
        "Activo": true,
        "EstadoSolicitud": 4612,
        "SolicitudTrabajoGrado": {
            "Id": 2112
        }
    },
    "DocumentoSolicitud": {
        "DocumentoEscrito": {
            "Id": 458
        },
        "SolicitudTrabajoGrado": {
            "Id": 2112
        }
    },
    "TipoSolicitud": {
        "Id": 4635
    },
    "Vinculaciones": null,
    "EstudianteTrabajoGrado": {
        "Estudiante": "20192020102",
        "TrabajoGrado": {
            "Id": 647,
            "Titulo": "Espacios Académicos de Posgrado",
            "Modalidad": 4602,
            "EstadoTrabajoGrado": 4582,
            "DistincionTrabajoGrado": null,
            "PeriodoAcademico": "2024-3",
            "Objetivo": ""
        },
        "EstadoEstudianteTrabajoGrado": 4649
    },
    "VinculacionesCancelacion": [
        {
            "Id": 1192,
            "Usuario": 52204982,
            "Activo": true,
            "FechaInicio": "2024-12-12 22:57:44.346792 +0000 +0000",
            "FechaFin": "2024-12-13T13:41:05.617Z",
            "RolTrabajoGrado": 4597,
            "TrabajoGrado": {
                "Id": 647,
                "Titulo": "Espacios Académicos de Posgrado",
                "Modalidad": 4602,
                "EstadoTrabajoGrado": 4582,
                "DistincionTrabajoGrado": null,
                "PeriodoAcademico": "2024-3",
                "Objetivo": ""
            },
            "CodigoAbreviacion": ""
        }
    ],
    "TrTrabajoGrado": null,
    "ModalidadTipoSolicitud": {
        "Id": 14,
        "TipoSolicitud": 4635,
        "Modalidad": 4602
    },
    "TrabajoGrado": null,
    "SolicitudTrabajoGrado": null,
    "EspaciosAcademicos": null,
    "DetallesPasantia": null,
    "TrRevision": null,
    "EspaciosAcademicosInscritos": null,
    "MateriasProPos": false
}

```
Nuevamente se verifica que el estudiante ahora quede en estado inicial para hacer una solicitud inicial nuevamente

![Image](https://github.com/user-attachments/assets/c3a1d631-977e-46c9-9b1e-2d757c70d124)

**Comment by Astaroth-Andres-Molano** [comment]
Para la solicitud de cambio de materias se cambia la lógica de la misma en el controlador "aprobar_solicitudes" del cliente, se elimina el tratamiento del espacio académico actual y espacios académicos elegibles, se implementa una lógica para llevar el flujo de carácter informativo llegando primero la solicitud a coordinador de pregrado
![Image](https://github.com/user-attachments/assets/abd4508c-f3ca-4895-8305-27397f2a0e64)
visualización de solicitud desde el estudiante
![Image](https://github.com/user-attachments/assets/1001eb80-96e5-451a-9286-502b04d31de6)
aprobación exitosa coordinador de pregrado
![Image](https://github.com/user-attachments/assets/3ec9e91c-3680-49ee-b0ed-6425cd5dfb21)
la solicitud pasa de coordinador de pregrado a coordinador de posgrado
![Image](https://github.com/user-attachments/assets/d1e3f8e5-c2d7-44d5-a627-fa5b028269b2)
Visualización de los detalles de la solicitud, donde el coordinador puede ver el nuevo documento
![Image](https://github.com/user-attachments/assets/08f3361c-fdac-456d-aebc-fe54ee8351db)
desde el rol de estudiante se revisa que en este punto tenga la restricción de solicitud en curso
![Image](https://github.com/user-attachments/assets/3c7d9450-b1bc-4527-a66a-4cc309347549)
ahora desde el rol de coordinador de posgrado se realiza la aprobación exitosa de la solicitud
![Image](https://github.com/user-attachments/assets/c87accaf-04d6-4dc8-ac30-e1c108cf0493)
Ahora se puede visualizar al Payload enviado del Coordinador de Posgrado
```JSON
{
    "RespuestaAnterior": {
        "Id": 4262,
        "Fecha": "2024-12-13T16:41:18.586Z",
        "Justificacion": "Test Cambio Materias",
        "EnteResponsable": 0,
        "Usuario": 79702248,
        "EstadoSolicitud": 4631,
        "SolicitudTrabajoGrado": {
            "Id": 2116,
            "Fecha": "2024-12-13T14:29:04.248Z",
            "ModalidadTipoSolicitud": {
                "Id": 15,
                "TipoSolicitud": 4641,
                "Modalidad": 4602
            },
            "TrabajoGrado": {
                "Id": 649,
                "Titulo": "Espacios Académicos de Posgrado",
                "Modalidad": 4602,
                "EstadoTrabajoGrado": 4582,
                "DistincionTrabajoGrado": null,
                "PeriodoAcademico": "2024-3",
                "Objetivo": ""
            },
            "PeriodoAcademico": "2024-3",
            "DatosPersonalesArl": ""
        },
        "Activo": false
    },
    "RespuestaNueva": {
        "Id": null,
        "Fecha": "2024-12-13T16:49:43.899Z",
        "Justificacion": "Test Cambio Materias",
        "EnteResponsable": 0,
        "Usuario": 52204982,
        "Activo": true,
        "EstadoSolicitud": 4612,
        "SolicitudTrabajoGrado": {
            "Id": 2116
        }
    },
    "DocumentoSolicitud": {
        "DocumentoEscrito": {
            "Id": 458
        },
        "SolicitudTrabajoGrado": {
            "Id": 2116
        }
    },
    "TipoSolicitud": {
        "Id": 4641
    },
    "Vinculaciones": null,
    "EstudianteTrabajoGrado": null,
    "VinculacionesCancelacion": null,
    "TrTrabajoGrado": null,
    "ModalidadTipoSolicitud": {
        "Id": 15,
        "TipoSolicitud": 4641,
        "Modalidad": 4602
    },
    "TrabajoGrado": null,
    "SolicitudTrabajoGrado": null,
    "EspaciosAcademicos": null,
    "DetallesPasantia": null,
    "TrRevision": null,
    "EspaciosAcademicosInscritos": null,
    "MateriasProPos": false
}

``` 
Se revisa que el estudiante se le hayan liberado nuevamente las solicitudes de proyecto en curso
![Image](https://github.com/user-attachments/assets/0fb831cc-2636-45fb-86d7-fffdd98f914a)
