### ISSUE TITLE
Terminar ajuste de visualización de trabajo de grado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#883]
Se requiere finalizar el ajuste en la vista de consulta de trabajo de grado para agregar teniendo presente que ya se realizó la modificación solicitada en la base de datos, lo que se encuentra pendiente es mostrar la información del proyecto curricular en el cual se está ejecutando el trabajo de grado en la modalidad de espacios académicos de posgrado.

**Sub Tareas**

- [x] Agregar información necesaria a la tabla espacio_academico_inscrito para poder implementar el cambio requerido.
- [x] Realizar ajuste en la vista de consulta del trabajo de grado para que allí se muestre la información del proyecto curricular.
- [x] Realizar pruebas de funcionamiento correcto de los ajustes realizados.

**Criterios de aceptación**

- [x] Información de la base de datos agreada.
- [x] Ajuste de la vista de consulta de grado realizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se inserta un nuevo registro en la tabla espacio_academico_inscrito asociando el trabajo de grado creado con el código de la Especialización en Ing. Software:
![Image](https://github.com/user-attachments/assets/9e3d0d70-603d-4038-921a-d17e607de11f)

Desde el cliente, se ajusta la función encargada de recuperar los datos de esta tabla ahora con las nuevas columnas. Se presenta un error en esta consulta desde el CRUD. Esto se debe a los cambios realizados a la tabla, por lo que se actualiza el modelo de la tabla espacio_academico_inscrito  en el CRUD:
![Image](https://github.com/user-attachments/assets/391121a2-c5cc-49b6-a8d4-e74e21457e2b)

Se prueba nuevamente la funcionalidad y se obtiene los datos de la tabla correctamente:
![Image](https://github.com/user-attachments/assets/f4ffdf8c-d6ed-479c-901a-1f87f211cbdb)

Se agrega la consulta a Académica para recuperar el nombre del proyecto curricular con el código recuperado:
![Image](https://github.com/user-attachments/assets/a51a9498-cb31-459b-9724-936d9f8be8d5)

Desde la vista, se agrega el campo donde se mostrará el nombre del proyecto recuperado encerrado en un condicional donde se evalua la modalidad:
![Image](https://github.com/user-attachments/assets/8e343f98-56f0-4c35-aae6-8e6d373579fd)

Dando como resultado la siguiente vista, donde se muestra el nombre del proyecto curricular de posgrado:
![Image](https://github.com/user-attachments/assets/b26404b8-ef1c-4944-a217-37a254110b7b)
