### ISSUE TITLE
Modificación de creación de trabajo de grado para info de proyecto curricular.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#886]
Se requiere realizar modificación de la solicitud inicial para agregar información a la tabla espacio_academico_inscrito cuando se apruebe la solicitud inicial del trabajo de grado, en esta tabla se debe poner el id del trabajo de grado creado y el código del proyecto curricular en el que se realizará la modalidad de grado.

**Sub Tareas**

- [x] Ajustar transacción en el mid para hacer un POST a la tabla.
- [x] Analizar adición de rollback y agregarlo si es posible.
- [x] Revisar el JSON que se envía desde el cliente, verificar si en ese JSON se puede obtener la información del proyecto curricular.
- [x] Realizar pruebas de funcionamiento correcto del desarrollo realizado.

**Criterios de aceptación**

- [x] Transacción ajustada.
- [x] Rollback analizado y agregado (si es posible).
- [x] JSON del cliente revisado y ajustado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se prepara la información para enviar al MID agregando el campo de espacio académico inscrito:
![Image](https://github.com/user-attachments/assets/7395aea7-100c-4857-a4e7-28a003407058)

En el MID se actualiza el modelo de espacio académico inscrito cambiando los datos de las columnas:
![Image](https://github.com/user-attachments/assets/13b044e6-cf3a-4141-a930-095b01606775)

En el MID ya se encontraba la funcionalidad para almacenar la información en la tabla espacio académico inscrito, pero su lógica era aplicada para almacenar las distintas materias seleccionadas por el estudiante.. Se corrige y ajusta la funcionalidad para almacenar un único registro el cual almacenará el id del proyecto curricular:
![Image](https://github.com/user-attachments/assets/e2a384e1-3654-4355-a061-a1fcb5c51f9f)

Se realizan los ajustes necesarios debido a que ya anteriormente se recibía un arreglo de los espacios académicos en el MID y se prueba la funcionalidad. Se observa que se almacena de forma correcta el registro en la tabla de espacio académico inscrito con el ID del proyecto curricular de posgrado y el ID del trabajo de grado:
![Image](https://github.com/user-attachments/assets/6d10cc27-f928-497c-8699-b750bd4b0b3f)

De igual forma se ingresa a la vista de consultar trabajo grado para verificar que se recupera de forma correcta el nombre del proyecto curricular de posgrado:
![Image](https://github.com/user-attachments/assets/86e833db-00e4-403c-9653-b5978ed0d3ca)

Queda pendiente verificar los rollback, pero se aprovechará la funcionalidad encontrada en la cual aplicaban los rollback a la función de trabajo de grado. Se agregará también los rollback a los documentos asociados a la solicitud inicial, el cual llamará a la función del rollback de espacio académico inscrito.

**Comment by JuanDHernandezA** [comment]
Se prueba utilizar la función rollback de DocumentoEscrito para cuando alguna de las peticiones de los documentos de la solicitud inicial falla.

Se presentaron varios inconvenientes que se solucionaron de la siguiente manera:
- Si la primera petición de los documentos falla, no llama a los siguientes rollbacks debido a que el llamado está dentro de un condicional que únicamente se entra si el trabajo de grado tiene documentos registrados. Se realiza el llamado fuera de este condicional y con esto se soluciona el inconveniente encontrado
- Si alguna de las peticiones de los documentos falla, este realiza todos los rollback de forma correcta. Pero, debido a que los otras peticiones no se encuentran dentro del if que verifica si la petición anterior se realizó de forma correcta o no los registros se ingresan a pesar de que ya se realizaron los Rollbacks. La solución que se propuso fue anidar cada uno de los IFs de las peticiones a las tablas de documento_escrito, documento_trabajo_grado y espacio_academico_escrito, con el fin de que si alguna de estas falla, no se realice el post de la siguiente petición, en cambio si realice los rollback y termine la petición en ese punto.

Con esto, todos los ajustes a la solicitud inicial para almacenar el nombre del proyecto curricular de posgrado y sus rollbacks queda finalizado.
