### ISSUE TITLE
Ajustes visuales a solicitud inicial de modalidad de posgrados.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#899]
Se requiere realizar ajustes visuales solicitados por el analista en la solicitud, ya se encuentran los [mockups ](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20POLUX%2F2024%2FEJECUCION%2FAnalista%20de%20requerimientos%2FMockups%2FMaterias%20de%20posgrado%2Fv2%2Fvista%20de%20creaci%C3%B3n%20de%20soliciutd%20modalidad%20de%20materias%20%2Edrawio%2Epng&parent=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20POLUX%2F2024%2FEJECUCION%2FAnalista%20de%20requerimientos%2FMockups%2FMaterias%20de%20posgrado%2Fv2) para esto, los ajustes son netamente visuales y son los siguientes:
- Modificación de textos para diferenciar mejor la primera o segunda opción de proyecto curricular.
- Una vez se confirme los proyecto curriculares seleccionados mostrar pop up donde se le indique al usuario la confirmación exitosa de los proyectos.
 
Adicional a estos ajustes iniciar el analisis y revisión cuando los coordinadores están revisando las solicitudes iniciales ya que la información llega bastante desordenada, por lo que es importante revisar si se puede mostrar dicha información de una manera mas ordenada sin afectar la lógica actual.

**Sub Tareas**

- [x] Ajustes visuales realizados.
- [x] Analizar y revisar opción de modificar orden de detalles al revisar solicitudes iniciales con coordinadores de pregrado o posgrado.
- [x] Documentar todo lo realizado en el issue.

**Criterios de aceptación**

- [x] Ajustes visuales realizados.
- [x] Análisis y revisión realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan ajustes visuales a la solicitud inicial de modalidad de espacios academicos de posgrado, se realizan ajustes en el HTML de crear solicitud
![image](https://github.com/user-attachments/assets/5f0d75f5-253f-453b-b3da-530d90990f76)
Se realizan ajustes al archivo "text_translate.js"
![image](https://github.com/user-attachments/assets/17a8851e-74f4-4075-a58f-ac818bb4ce9a)
Se realizan ajustes al archivo HTML de directivas "solicituar_asignaturas.html"
![image](https://github.com/user-attachments/assets/3b8976f8-5278-4798-85bf-6d67f15c6bf6)
Se obtienen los ajustes visuales solicitados
![image](https://github.com/user-attachments/assets/c5d94084-f893-4f30-8d1b-23847fba4c23)

**Comment by Astaroth-Andres-Molano** [comment]
Subtarea #2: Se revisa el estado de la vista de aprobación por parte de coordinadores para la modalidad de Espacios Académicos de Posgrado
![Image](https://github.com/user-attachments/assets/767ea436-eafc-4c8b-ae34-361e0f2cc0ab)
Para poder ordenar la información y que sea legible de manera ordenada se cambiaría el orden de los detalles agrupando primero los detalles que tienen la información de los espacios académicos inscritos o solicitados que en la imagen están subrayados en azul, y hacer lo mismo con los detalles que traen la información de la documentación requerida en la solicitud, en la imagen están subrayados en rojo, se puede utilizar un panel para separarlos, también se puede en el caso de los coordinadores de posgrado que los detalles de los espacios académicos que no sean de su competencia sean omitidos en la vista:
![Image](https://github.com/user-attachments/assets/34f8381b-7626-4b46-a1e1-cb50e82763df)
