### ISSUE TITLE
Ajustar tabla en listado de solicitudes

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#903]
Se requiere realizar el ajuste de la tabla cuando se listan solicitudes y la solicitud es de cambio de materias o cancelación en la modalidad de espacios academicos de posgrado ya que actualmente en dichas solicitudes no aparece la información del proyecto curricular del trabajo de grado por lo que se requiere realizar los ajustes necesarios para que aparezca el nombre del proyecto.

**Sub Tareas**

- [x] Utilizar el código registrado en la tabla espacio_academico_inscrito.
- [x] Consultar el nombre del proyecto curricular hacia el endpoint de JBPM utilizando el código anterior.
- [x] Ajustar la lógica para que en dichas solicitudes aparezca el proyecto curricular.
- [x] Realizar pruebas del correcto funcionamiento.
- [x] Documentar ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Código del proyecto curricular utilizado en el endpoint.
- [x] Lógica modificada.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**Cambio de Materias de Posgrado y Cancelación de Modalidad por parte del Coordinador de Posgrado**

<img width="472" alt="image" src="https://github.com/user-attachments/assets/aab287c8-00af-4a73-914b-13dc59dfa8fd" />

<img width="252" alt="image" src="https://github.com/user-attachments/assets/b75a87dd-4976-47ea-ab9a-e8ac6c18b117" />

---

<img width="472" alt="image" src="https://github.com/user-attachments/assets/4e647c5c-c344-42c8-97cd-2d7e1da4782a" />

<img width="251" alt="image" src="https://github.com/user-attachments/assets/127318c5-55f2-42a8-bd21-956c3eeb5598" />
