### ISSUE TITLE
Realizar ajustes solicitados por funcionamiento

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#907]
Se requiere realizar multiples ajustes que han sido solicitados por funcionamiento en la reunión realizada en #902, estos ajustes son:
- Revisar listado de solicitudes en consulta de trabajo de grado.
- Implementar notificaciones a modalidad de materias de posgrado.

Para las demás solicitudes realizadas por funcionamiento primero se debe evaluar su viabilidad.

**Sub Tareas**
- [x] Revisar listado de solicitudes en vista de consulta de trabajo de grado.
- [x] Implementar notificaciones al flujo de la modalidad.
- [x] Documentar modificaciones realizadas.

**Criterios de aceptación**

- [x] Revisión realizada.
- [ ] Notificaciones implementadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanDHernandezA** [comment]
Se comienza con la corrección al error de listar las solicitudes desde el menú de Consultar Trabajo Grado, esto debido a que al momento de querer visualizar los detalles de las solicitudes al tener un trabajo de grado con modalidad Materias de Posgrado sale el siguiente error:
![image](https://github.com/user-attachments/assets/5e3248be-c7fa-4e11-b24b-898a70e31dfc)

Además de no mostrar el estado de la solicitud:
![image](https://github.com/user-attachments/assets/f392ce38-5bcb-49ce-b073-2878aca85172)

Primero, se verifica si este error también se presenta en las demás modalidades, por lo que se crea un trabajo de grado con modalidad de Monografía y se accede a la vista. Se observa que se en esta modalidad si está el estado de la solicitud y se pueden visualizar de forma correcta los detalles:
![image](https://github.com/user-attachments/assets/eb5a5afe-aa28-4a23-81c4-29c950ea1db9)
![image](https://github.com/user-attachments/assets/a6972b5e-3f35-4b6f-9fe6-ead51061d53d)

Se revisan el archivo _directives/solicitudes/listar_solicitudes.js_ encargado de mostrar las solicitudes en esta vista y se revisa todo el flujo que se realiza.

Se encuentra que al visualizar los detalles se genera un error al acceder a la variable _solicitud.data.Respuesta.EstadoSolicitud_. Esta variable almacena la información asociada a la solicitud de la tabla _respuesta_solicitud_, pero la consulta que se realiza filtra la búsqueda para los registros cuyo estado sea ACTIVO, pero las respuestas a las solicitudes están quedando en FALSE:
![image](https://github.com/user-attachments/assets/77ccb14b-6431-4d29-b24c-668654559b1c)

Se prueba cambiando la última respuesta a TRUE para observar el comportamiento de la vista. Se observa que se visualiza correctamente el estado de la solicitud y los detalles de la solicitud:
![image](https://github.com/user-attachments/assets/90ef0b0e-a418-4ea6-81d7-841a30db9827)
![image](https://github.com/user-attachments/assets/70129021-6341-4072-9c27-13e48022a0f0)

Por lo que se debe agregar la funcionalidad de dejar en ACTIVO la solicitud aprobada por la coordinación de Posgrado, además de corregir la vista de los detalles.

**Comment by JuanDHernandezA** [comment]
Se modifica la lógica utilizada para almacenar el estado de la respuesta de la solicitud; ahora si almacenará el valor ACTIVO cuando se crea el trabajo de grado.

Se prueban los flujos de respuesta de solicitud para verificar si los cambios realizados permitian visualizar las solicitudes desde la vista de Consultar Trabajo Grado. Se observa que para los flujos cuya última respuesta es la que creará el trabajo de grado funciona correctamente:
- Aprueba la opción prioritaria de primeras 
- Aprueban las 2 coordinaciones, respondiendo primero la opción no prioritaria 
- Aprueba opción no prioritaria luego de rechazar opción prioritaria 

Pero al probar el flujo donde la coordinación de la opción no prioritaria aprueba y luego se rechaza la solicitud por parte de la coordinación de la opción prioritaria, en el listado de solicitudes muestra la solicitud rechazada por la última coordinación:
![Image](https://github.com/user-attachments/assets/7ddfe8d5-f12b-4988-aa5b-b097fa662f9a)

Para hacer que la solicitud que se visualiza sea la opción aceptada, se debe poner en ACTIVO la respuesta que aprueba el trabajo de grado, sea o no prioritaria. Con esto, cuando responda la prioritaria, si acepta la solicitud esta nueva respuesta será ACTIVA y pasará a FALSE si la anterior fue aceptada. Al realizar estos cambios se soluciona el error de la solicitud a mostrar:
![Image](https://github.com/user-attachments/assets/7497aa84-c48e-4f03-b6b3-f5fec66fc08f)

Pero esto genera un nuevo error al crear una nueva solicitud:
![Image](https://github.com/user-attachments/assets/8d2be71a-e864-4c35-b6d8-2abc2e439893)

Se infiere a que el sistema detecta una solicitud ACTIVA que no es la última respuesta, por lo que no permite crear nuevas solicitudes:
![Image](https://github.com/user-attachments/assets/f94d2561-4c93-474f-9a76-94c914a30bfe)

Adicional a esto, se encuentra otro error en el menú de Consultar Trabajo Grado, en donde se está almacenando el nombre del proyecto curricular que dio la última respuesta, haya aceptado o no. En la siguiente imagen se observa que el proyecto curricular inscrito es ESPECIALIZACION EN TELECOMUNICACIONES MOVILES, pero se había rechazado la solicitud con esta carrera, pero al ser la última coordinación que responde, su nombre queda almacenado en la tabla de espacio_academico_inscrito:
![Image](https://github.com/user-attachments/assets/c458b2e6-56dd-483f-a303-8631bd3f29e2)

**Comment by JuanDHernandezA** [comment]
Se revisa la lógica que guarda el estado de la solicitud al momento en que aprueba o rechaza la opción prioritaria. Se observa que se almacenan los estados correspondientes de ACC y RCC al momento coordinador de la prioridad responde la solicitud. Pero se observa que debajo de esta funcionalidad se encuentra la lógica que inserta el estado de solicitud de rechazado por coordinación 1, lo que conlleva que al momento en que la coordinación prioritaria rechaza la solicitud nunca queda en RCC o ACC las solicitudes.

Se encierra en un else esta última lógica y se vuelve a desarrollar la funcionalidad que establece en ACTIVO la última respuesta recibida por las coordinaciones.

Se realiza la prueba con el flujo de aprobar primero por coordinación no prioritaria y luego rechazar por coordinación prioritaria, con el fin de verificar que en el menú de consultar trabajo grado el estado de solicitud que se muestra sea aprobado por Consejo de carrera y el estudiante pueda crear nuevas solicitudes, lo cual es correcto:
![Image](https://github.com/user-attachments/assets/76136836-97e1-4597-a0f9-efcc45375bc5)
![Image](https://github.com/user-attachments/assets/f9b590b6-bb00-40c3-a499-692806f2e9d2)

Se realizan las pruebas con todos los demás flujos para verificar que la lógica aplicada no afectó a su funcionamiento. Todo funciona correctamente con cada flujo de aprobación.

Queda pendiente corregir la vista que muestra los detalles de las solicitudes y verificar el funcionamiento de las notificaciones para esa modalidad.
