### ISSUE TITLE
Implementar flujo con dos asistentes

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#908]
Se requiere realizar la implementación del flujo de materis de posgrado con dos asistentes para realizar las diferentes tareas.

**NOTA:** Queda pendiente por parte de @diagutierrezro el usuario de asistente faltante.

**Sub Tareas**

- [x] Realizar ajustes necesarios para poder implementar el flujo básico con multiples asistentes.
- [x] Realizar diferentes pruebas para comprobar funcionamiento correcto.
- [x] Documentar issue con ajustes y pruebas realizadas.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar ajustes necesarios para poder implementar el flujo básico con multiples asistentes.**

Daily 23/12/2024

1. El primer inconveniente que se encontró es que los contratistas estaban listando todas las solicitudes de Posgrado sin tener en cuenta los proyectos curriculares que tenían a cargo, por lo que se le dió solución a este problema.

**Comment by CrisEs2506** [comment]
**SubTarea N°2:  Realizar diferentes pruebas para comprobar funcionamiento correcto.**

Daily 24/12/2024

<img width="473" alt="image" src="https://github.com/user-attachments/assets/bb119665-73b0-43f4-b9ab-d652c9e05ac9" />
<img width="474" alt="image" src="https://github.com/user-attachments/assets/6111689a-80c0-4fea-a37f-f1af7d3edbab" />
<img width="472" alt="image" src="https://github.com/user-attachments/assets/b7416a7d-7ef5-459e-8a35-d0a4922e79e4" />

---

<img width="472" alt="image" src="https://github.com/user-attachments/assets/4814fdb1-116c-48f1-ba7b-f1ec830a4464" />
<img width="471" alt="image" src="https://github.com/user-attachments/assets/bd4f1cb0-1227-4d2b-b235-bc1422e9dfd7" />

---

1. Aprobar con proyecto curricular de la opción no prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

2. Rechazar con proyecto curricular de la opción prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

- Resultado Final:

<img width="721" alt="image" src="https://github.com/user-attachments/assets/12a9af6b-ab12-4295-8909-1d00c9a6da59" />

---

1. Rechazar con proyecto curricular de la opción no prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

2. Aprobar con proyecto curricular de la opción prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

- Resultado Final:

<img width="715" alt="image" src="https://github.com/user-attachments/assets/df677b3f-cfea-4b58-b01e-b301dfab8e48" />

---

1. Aprobar con proyecto curricular de la opción no prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

2. Aprobar con proyecto curricular de la opción prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

- Resultado Final:

<img width="740" alt="image" src="https://github.com/user-attachments/assets/12df2144-b8fc-433e-85e1-5799720a5338" />

---

1. Rechazar con proyecto curricular de la opción prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

2. Rechazar con proyecto curricular de la opción no prioritaria:

<img width="252" alt="image" src="https://github.com/user-attachments/assets/848a8991-b298-45ac-94e6-c98529add438" />

- Resultado Final:

<img width="739" alt="image" src="https://github.com/user-attachments/assets/40ea804c-ac5f-4e28-8973-30663aca3a4e" />

**Comment by CrisEs2506** [comment]
**SubTarea N°3: Agregar el menú de Registrar Nota al rol de Contratista**

Daily 26/12/2024

1. Se añadió la opción de Registrar Nota desde pruebas configuración:

<img width="723" alt="image" src="https://github.com/user-attachments/assets/5fab1f96-0495-4bff-8dd9-69b9bbb94c07" />
