### ISSUE TITLE
Realizar investigación sobre reinicio de sistemas con diferentes usuarios

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#911]
Se requiere realizar una investigación sobre el porque puede pasar el reinicio del sistema sin razón alguna averiguando si pasa o ha pasado en otros sistemas.

**Sub Tareas**

- [x] Generar contacto con responsable
- [x] Definir comentarios frente a lo investigado

**Criterios de aceptación**

- [x] Investigación realizada
- [x] Exposición de conclusiones

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha investigado con el arquitecto y se ha identificado problemas posibles de node , se espera poder saber más de parte de funcionamiento e identificar el problemas

![Image](https://github.com/user-attachments/assets/b82b4f76-f23f-4040-aa23-fa3ed6377e72)

**Comment by mantnicot** [comment]
Se ha hablado con funcionamiento y con Maria Fernanda y se ha podido identificar dos cosas:

- Polux es el único sistema con este problema de reinicio
- Hay por ahora dos posibilidades para el problema :  

     1-) Version del node o Angular js
     2-) No se esta generando fecha de expirancion del cliente


![tmp_7a7dc4ab-4772-47c7-a16c-4c84d4611c28.png](https://github.com/user-attachments/assets/85383add-b382-4d19-b701-4813d69f2d7a)

**Comment by jcmurilloa** [comment]
Muy buen insumo para direccionar el equipo de desarrollo para darle solución a este reinicio.
