### ISSUE TITLE
Modificar registro de nota con coordinadores de posgrado.

### ISSUE THREAD

**Issue by diagutierrezro** [udistrital/polux_cliente#912]
Se requiere realizar la modificación en el registro de la nota por parte del coordinador para esto se necesita agregar un checkbox el cual en caso de ser marcado debe generar otro campo de registro de nota (revisar si se necesita cambios en bases de datos), tener presente el mockup modificado en #888 .

Muy importante realizar pruebas de registro de nota en otras modalidades para garantizar que no se afecte el funcionamiento normal posterior al cambio realizado.

**Sub Tareas**

- [x] Ajustar registro de nota por parte del coordinador de posgrado.
- [x] Realizar pruebas de registro de nota en otras modalidades para garantizar correcto funcionamiento.

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Pruebas realizadas.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Astaroth-Andres-Molano** [comment]
Se realizan los ajustes para la parte visual en la vista general/registrar_nota.html y en el controlador general/registrar_nota.js

![Image](https://github.com/user-attachments/assets/072bdf5c-c072-44d6-86ca-c8592175c031)

A continuación se visualiza el formulario con el checkbox sin seleccionar
![Image](https://github.com/user-attachments/assets/01f78f07-b3f7-4864-a344-1a7fcc3c128a)
Ahora la visualización con el checkbox seleccionado
![Image](https://github.com/user-attachments/assets/e3f2a98a-5780-464a-922d-8cf45dcbbc5e)
